// Deep, per-module audit content for the Advanced Audit track. Keyed by module id
// (e.g. "iam-03"). Each record gives the REAL specifics an auditor needs — the
// concrete artifact (the actual file/export/list), the concrete test with PASS
// criteria and what an exception looks like, the real source systems, the real
// tools/commands/APIs to pull the evidence, the typical finding, and references.
//
// The generator (gen-audit-track.mjs) weaves these into each module's briefing,
// auditMeta, CTF, quiz, and the runnable MCP server. Modules without a record here
// fall back to a generic (clearly weaker) template — author them here to deepen.
//
// Fields per record:
//   artifacts: string[]   the concrete evidence objects (a user access list, a
//                         config file, an export) — surfaced as auditMeta.artifacts
//   test:      string     the procedure + PASS criteria + what an exception is
//   systems:   string[]   the real systems of record the evidence comes from
//   owners:    string[]   the role/function that owns each source
//   tools:     string[]   real commands / API calls / queries to gather it
//   finding:   string     what a typical, real finding looks like
//   refs:      [t,url][]   module-specific standards/guidance (optional)

export const MODULES = {
  // ── Identity & Access Management (IAM) ──────────────────────────────────────
  "iam-01": {
    artifacts: [
      "The IdP user export — every account with status, creation date, last-login, and licence/role assignments",
      "The HR worker feed — active workers with hire and termination dates (the authoritative 'who should exist')",
      "The access-request approval tickets that authorised each account at creation",
      "Deprovisioning evidence — disable/delete timestamps to compare against termination dates",
    ],
    test: "Reconcile every IdP account to an active worker in the HR system of record. PASS: each enabled account maps to an active worker; every new account had an approved access request before creation; every terminated worker's accounts were disabled within SLA (e.g. ≤24h privileged, ≤7d standard) and de-licensed. Exceptions: orphaned accounts with no matching active worker, terminated workers still enabled, and accounts created with no approval ticket.",
    systems: ["Okta / Microsoft Entra ID (the identity provider)", "Workday / SAP SuccessFactors (HR system of record)", "ServiceNow (access-request + approval workflow)"],
    owners: ["Identity & Access Management — runs provisioning operations", "HR — owns authoritative worker status and dates", "Line managers — approve the access requests"],
    tools: [
      "Okta:   GET /api/v1/users?limit=200  (status, created, lastLogin, then paginate the Link header)",
      "Entra:  Get-MgUser -All -Property displayName,accountEnabled,createdDateTime,signInActivity",
      "HR:     Workday/SuccessFactors 'active workers + termination date' report (CSV/SOAP)",
      "Trail:  ServiceNow table API /api/now/table/sysapproval_approver?sysparm_query=... for the approval record",
    ],
    finding: "Orphaned accounts with no active worker, and terminated employees whose accounts stayed enabled for days or weeks past their termination date — each named with account id, worker id, and the gap in days.",
    refs: [["NIST SP 800-53 AC-2 Account Management", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"], ["NIST SP 800-63 Digital Identity", "https://pages.nist.gov/800-63-3/"]],
  },
  "iam-02": {
    artifacts: [
      "The joiner-mover-leaver (JML) event log from HR — hires, role/department changes, and terminations in the period",
      "Before/after entitlement snapshots for each worker who changed role",
      "The birthright-role mapping (job code → the access automatically granted)",
      "Leaver deprovisioning timestamps vs the HR termination date",
    ],
    test: "For every MOVER (role/department change) in the period, diff the worker's entitlements before and after. PASS: birthright access updated to the NEW role AND prior-role entitlements removed (no accumulation); joiners got only their role's birthright access; leavers were fully deprovisioned within SLA. Exceptions: 'privilege creep' — movers who kept old-role access on top of new; leavers with residual access; joiners over-provisioned beyond their role.",
    systems: ["HR / HRIS (the JML event source)", "IGA platform — SailPoint / Saviynt / Microsoft Entra ID Governance (entitlements)", "The role / birthright catalogue"],
    owners: ["IAM / Identity Governance — owns the JML automation", "HR — owns the lifecycle events", "Role owners — define each role's birthright access"],
    tools: [
      "IGA:   SailPoint identity-cube entitlement history, or Saviynt 'identity entitlement' export, before vs after the move date",
      "Entra: Get-MgUserMemberOf for each mover at two points in time, then diff the group sets",
      "Okta:  group-membership snapshots (/api/v1/users/{id}/groups) diffed across the move",
      "HR:    JML event extract (effective-dated hires / transfers / terminations)",
    ],
    finding: "Movers who accumulated entitlements across two or three past roles (named, with the stale entitlements listed), and a handful of leavers whose access was removed late.",
    refs: [["NIST SP 800-53 AC-2 / AC-6", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"], ["Gartner — Identity Governance & Administration", "https://www.gartner.com/en/information-technology/glossary/identity-governance-and-administration-iga"]],
  },
  "iam-03": {
    artifacts: [
      "A CSV of every active user joined to their enrolled authentication factors (factor type + enrolment date)",
      "The per-application authentication-policy export showing which apps require MFA and which factor types are allowed",
      "The list of sensitive/regulated applications that the MFA requirement must cover",
      "Sign-in / system logs showing factor usage (to catch policy that exists but isn't enforced)",
    ],
    test: "Reconcile the active-user roster against factor enrolment and the per-app auth policies. PASS: every active human account has at least one phishing-resistant factor (FIDO2/WebAuthn or platform passkey); every application handling confidential/regulated data REQUIRES MFA (not 'optional'); no account relies on SMS or voice as its only factor. Exceptions: active accounts with zero factors or SMS-only, and sensitive apps where MFA is optional or disabled.",
    systems: ["Okta (Universal Directory + Authentication Policies)", "Microsoft Entra ID (Conditional Access)", "The HR system of record for 'active worker'"],
    owners: ["IAM — owns the IdP and the authentication policies", "Application owners — set each app's auth-policy requirement", "HR — the authoritative active-worker list"],
    tools: [
      "Okta:  GET /api/v1/users?filter=status eq \"ACTIVE\"  then  GET /api/v1/users/{id}/factors",
      "Okta:  GET /api/v1/policies?type=ACCESS_POLICY  for the per-application MFA rules",
      "Entra: Get-MgUserAuthenticationMethod -UserId <id>  ;  export Conditional Access policies",
      "Entra: AuthenticationMethods registration & usage report (CSV)",
    ],
    finding: "Typically 3–8% of active accounts have no MFA or are SMS-only, and one or two sensitive apps have MFA set to 'optional' — each named with the user or app id.",
    refs: [["NIST SP 800-63B Authenticator Assurance Levels", "https://pages.nist.gov/800-63-3/sp800-63b.html"], ["CISA — Implementing Phishing-Resistant MFA", "https://www.cisa.gov/resources-tools/resources/implementing-phishing-resistant-mfa"]],
  },
  "iam-04": {
    artifacts: [
      "The privileged-principal inventory — Domain/Enterprise Admins, cloud admin roles, root, local admins, and application super-users",
      "The PAM vault inventory — which privileged credentials are vaulted, rotated, and checkout-controlled",
      "Session checkout / recording logs for privileged access",
      "The standing-vs-just-in-time (JIT) grant list, and break-glass account usage records",
    ],
    test: "Enumerate every privileged principal across directory, cloud, and hosts, then reconcile against the PAM vault. PASS: each is vaulted with automatic rotation, requires MFA + approval/checkout, prefers JIT over standing access, and sessions are logged/recorded; break-glass accounts are sealed and alert on use. Exceptions: privileged accounts NOT in the vault ('discovered, not managed'), unjustified standing admin, shared admin credentials, and break-glass used without a corresponding incident.",
    systems: ["CyberArk / Delinea / BeyondTrust (PAM)", "Active Directory (privileged groups)", "Microsoft Entra PIM + AWS/Azure/GCP IAM (cloud admin roles)"],
    owners: ["Privileged Access Management team — owns the vault and policy", "Platform / infrastructure owners — own the admin accounts", "Security operations — monitor privileged sessions"],
    tools: [
      "AD:      Get-ADGroupMember 'Domain Admins','Enterprise Admins','Schema Admins','Administrators' -Recursive",
      "Entra:   Get-MgRoleManagementDirectoryRoleAssignment  +  PIM eligible vs active assignments",
      "AWS:     aws iam list-entities-for-policy --policy-arn arn:aws:iam::aws:policy/AdministratorAccess  + Access Analyzer",
      "CyberArk: 'accounts discovered (DNA/Discovery) vs onboarded' reconciliation export",
    ],
    finding: "Privileged accounts discovered on hosts and in cloud that are not vaulted, plus standing Domain Admin members beyond the approved break-glass set — each named.",
    refs: [["NIST SP 800-53 AC-6(5) Privileged Accounts", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"], ["CISA — Privileged Access Management guidance", "https://www.cisa.gov/"]],
  },
  "iam-05": {
    artifacts: [
      "The IdP session/token policy export — idle timeout, absolute lifetime, refresh-token lifetime + rotation, reauthentication rules",
      "Per-application session configuration — cookie flags (HttpOnly/Secure/SameSite) and idle/absolute timeouts",
      "Conditional-access / sign-in-frequency policies (step-up reauth, device binding)",
      "Evidence that tokens/sessions are revoked on logout and on deprovisioning",
    ],
    test: "Review session controls across the IdP and the sensitive applications. PASS: idle and absolute session limits are set in proportion to sensitivity (e.g. ≤15-min idle for admin consoles); refresh-token lifetime is bounded and rotated; step-up reauthentication is required for high-risk actions; sessions are revoked on logout and termination; cookies are HttpOnly/Secure/SameSite. Exceptions: unbounded or over-long sessions on sensitive apps, no step-up, refresh tokens never rotated, sessions not revoked on deprovision.",
    systems: ["Okta / Microsoft Entra ID (session + token policies)", "The applications' own session configuration", "API gateway / reverse proxy (token validation)"],
    owners: ["IAM — owns IdP session policy", "Application owners — own app-level session config", "AppSec — reviews cookie/token handling"],
    tools: [
      "Okta:  GET /api/v1/policies?type=ACCESS_POLICY  (session rules) and the global session policy export",
      "Entra: Conditional Access 'Sign-in frequency' + 'Persistent browser session' policy export",
      "App:   inspect Set-Cookie flags + documented idle/absolute timeouts for each sensitive app",
      "Token: confirm refresh-token rotation + revocation-on-logout in the OAuth/OIDC config",
    ],
    finding: "An admin application with a 12-hour idle session and refresh tokens that never rotate, so a stolen token stays valid far beyond the user's presence.",
    refs: [["OWASP Session Management Cheat Sheet", "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html"], ["NIST SP 800-63B — Reauthentication", "https://pages.nist.gov/800-63-3/sp800-63b.html"]],
  },
  "iam-06": {
    artifacts: [
      "The access-certification campaign records — reviewer, items reviewed, approve/revoke decisions, and timestamps",
      "The entitlement catalogue under review (especially high-risk/privileged entitlements)",
      "Revocation evidence for every 'revoke' decision, with the time-to-revoke",
      "Rubber-stamp metrics — approve-all rate and time-per-decision per reviewer",
    ],
    test: "Examine the most recent recertification campaign for in-scope high-risk entitlements. PASS: every high-risk entitlement was reviewed by an accountable owner within the cycle (e.g. quarterly for privileged, annually for standard); 'revoke' decisions were actually executed within SLA; and no reviewer certified their own access. Exceptions: entitlements never included in any campaign, revokes decided but not executed, a reviewer approving 100% of items in minutes (rubber-stamping), or reviewer = grantee.",
    systems: ["SailPoint / Saviynt / Microsoft Entra ID Access Reviews (the IGA campaign engine)", "The IGA entitlement catalogue", "ITSM (to correlate revoke decisions with actual removals)"],
    owners: ["IAM / Identity Governance — runs the campaigns", "Entitlement / business owners — perform the reviews", "Internal audit — independent assurance"],
    tools: [
      "SailPoint: certification campaign export (item-level decisions + decision timestamps)",
      "Entra:    GET /identityGovernance/accessReviews/definitions/{id}/instances/{id}/decisions",
      "Correlate: each 'revoke' decision → the deprovisioning ticket/event that executed it",
      "Analytics: per-reviewer approve-rate and median seconds-per-decision (rubber-stamp signal)",
    ],
    finding: "A privileged group that appears in no certification campaign, and 'revoke' decisions with no corresponding removal 60+ days later — the review happened on paper but changed nothing.",
    refs: [["NIST SP 800-53 AC-2(j) Account Reviews", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"], ["SOX ITGC — periodic access reviews", "https://pcaobus.org/"]],
  },
  "iam-07": {
    artifacts: [
      "The non-human / service-account inventory — each account with a named human owner and documented purpose",
      "The local-administrator inventory per host, and whether each is LAPS-managed (unique per host)",
      "The generic/shared-account list and whether each permits interactive logon",
      "Password age / rotation and vaulting status for every service account",
    ],
    test: "Inventory every service, generic, and local account. PASS: each has a named human owner and documented purpose; service accounts are non-interactive, least-privileged, and vaulted + rotated (or gMSA); local-admin passwords are unique per host (Windows LAPS); no shared interactive generic accounts exist. Exceptions: ownerless service accounts, service accounts in privileged groups, shared interactive logins, identical local-admin passwords reused across hosts, and passwords years old.",
    systems: ["Active Directory (service accounts, gMSA, adminCount)", "Windows LAPS (local-admin password management)", "PAM vault (service-account custody)", "Host/endpoint inventory"],
    owners: ["IAM — owns the account standard", "Server / application owners — own their service accounts", "Platform security — owns LAPS + vaulting"],
    tools: [
      "AD:   Get-ADUser -Filter {ServicePrincipalName -like '*'} -Properties PasswordLastSet,adminCount,MemberOf",
      "AD:   find service accounts where PasswordLastSet is years old, or with adminCount=1 (privileged)",
      "LAPS: report ms-Mcs-AdmPwd / Windows-LAPS attribute coverage across the host estate",
      "Risk: list Kerberoastable SPNs (service accounts with weak/old passwords exposed to offline cracking)",
    ],
    finding: "A service account with a 5-year-old password sitting in Domain Admins, and a single local-admin password reused across 400 workstations (one cracked hash = lateral movement everywhere).",
    refs: [["Microsoft — Windows LAPS", "https://learn.microsoft.com/windows-server/identity/laps/laps-overview"], ["NIST SP 800-53 IA-5 Authenticator Management", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"]],
  },
  "iam-08": {
    artifacts: [
      "The entitlement-to-user assignment export (who holds what, across apps and cloud)",
      "The Segregation-of-Duties (SoD) ruleset — the toxic combinations (e.g. create-vendor + approve-payment)",
      "The SoD violations report — users currently holding conflicting entitlements",
      "Mitigating-control evidence for any conflict that was risk-accepted",
    ],
    test: "Run the SoD ruleset against current assignments and assess least privilege. PASS: no user holds a toxic combination without an approved, real mitigating control; entitlements trend toward least privilege (unused/over-broad access is removed). Exceptions: active SoD conflicts (e.g. a user who can both create and approve payments), over-entitled accounts with access far beyond their role, and conflicts 'accepted' with no genuine compensating control.",
    systems: ["ERP GRC — SAP GRC Access Control / Oracle Risk Management (financial SoD)", "IGA platform (cross-app entitlements)", "Cloud IAM (AWS/Azure/GCP policies)"],
    owners: ["IAM / GRC — owns the ruleset", "Business process owners — own the SoD policy for their process", "Internal audit / Finance — for financially-significant SoD"],
    tools: [
      "SAP GRC: Access Risk Analysis (ARA) report — user-level risk violations against the ruleset",
      "IGA:     export entitlement assignments and join against the toxic-combination ruleset",
      "AWS:     IAM Access Analyzer 'unused access' + Access Advisor last-accessed (least-privilege evidence)",
      "Cloud:   flag policies granting wildcard '*' actions or '*' resources",
    ],
    finding: "A dozen users who can both create and approve vendor payments with no compensating control, and cloud roles granting wildcard '*' actions far beyond what the workload uses.",
    refs: [["NIST SP 800-53 AC-5 (SoD) / AC-6 (least privilege)", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"], ["ISACA — Segregation of Duties", "https://www.isaca.org/"]],
  },
  "iam-09": {
    artifacts: [
      "The certificate inventory — CN/SAN, issuer, key type/size, signature algorithm, expiry, and where each cert is deployed",
      "The CA hierarchy and issuance policy (what may be issued, to whom, with what constraints)",
      "Renewal evidence — which certs auto-renew (ACME) vs are renewed manually",
      "Private-key protection evidence — HSM vs filesystem, and who can read the key",
    ],
    test: "Inventory all TLS, client, and code-signing certificates. PASS: every certificate is inventoried and owned, uses approved algorithms and key sizes (RSA-2048+/ECDSA-P256+, SHA-256+), is not expired or expiring-without-an-owner, auto-renews where possible, and has its private key HSM-protected with least-privilege access; no self-signed certs in production and no unmanaged wildcard sprawl. Exceptions: unknown or expired certs serving production, weak keys (RSA-1024/SHA-1), private keys world-readable on disk, and certs expiring with no renewal owner.",
    systems: ["Venafi / Keyfactor / AWS Certificate Manager / internal PKI (AD CS)", "The issuing CA(s)", "Load balancers, web servers, and service meshes where certs terminate"],
    owners: ["PKI / Cryptography team — owns the CA and policy", "Platform / application owners — own the endpoints where certs are deployed"],
    tools: [
      "Inventory: Venafi/ACM export (CN, issuer, key, expiry, deployment)",
      "Discovery: query Certificate Transparency logs (crt.sh) for all certs issued for the org's domains",
      "Endpoint: nmap --script ssl-cert / openssl s_client -connect host:443 (algorithm + expiry of what's actually served)",
      "AD CS:    the issued-certificates database (templates, key archival, weak-key issuance)",
    ],
    finding: "Three expired certificates still serving production, several RSA-1024/SHA-1 certificates, and a wildcard certificate whose private key sits unprotected in a web root.",
    refs: [["NIST SP 800-57 Key Management", "https://csrc.nist.gov/projects/key-management"], ["CA/Browser Forum Baseline Requirements", "https://cabforum.org/baseline-requirements-documents/"]],
  },
  "iam-10": {
    artifacts: [
      "The access-policy matrix — for each sensitive resource, what identity + device posture + context is required",
      "The device-trust / posture signals that feed access decisions (compliant, managed, healthy)",
      "Segmentation evidence showing no implicit trust is granted by network location alone",
      "Continuous-evaluation / session-revocation logs (access pulled when risk rises mid-session)",
    ],
    test: "Sample sensitive resources and verify access requires a verified identity AND device posture AND context on every request — not network location. PASS: policies enforce least privilege per session, require MFA + a compliant/managed device, and continuously evaluate risk to revoke access; there is no 'on the corporate LAN = trusted'. Exceptions: resources reachable on the LAN with no auth/posture check, a VPN that grants flat subnet access, and policies keyed only to source IP.",
    systems: ["Microsoft Entra Conditional Access / Okta + device trust (Intune / Jamf)", "ZTNA — Zscaler / Cloudflare Access / Netskope", "Network microsegmentation (Illumio / NSX / cloud security groups)"],
    owners: ["IAM — owns identity-based access policy", "Network security — owns segmentation/ZTNA", "Endpoint — owns device posture", "Security architecture — owns the zero-trust target state"],
    tools: [
      "Entra:  export Conditional Access policies + confirm Continuous Access Evaluation (CAE) is enabled",
      "Posture: Intune device-compliance state feeding device-based Conditional Access",
      "ZTNA:   export the per-application access policy (identity + posture + context conditions)",
      "Test:   attempt to reach a sensitive resource from an untrusted segment / non-compliant device and confirm it is denied",
    ],
    finding: "An administrative console reachable on the corporate LAN with no device-posture requirement, and a VPN that drops users onto a flat subnet with broad reachability — classic implicit network trust.",
    refs: [["NIST SP 800-207 Zero Trust Architecture", "https://csrc.nist.gov/pubs/sp/800/207/final"], ["CISA Zero Trust Maturity Model", "https://www.cisa.gov/zero-trust-maturity-model"]],
  },
  "iam-11": {
    artifacts: [
      "The cryptographic inventory / CBOM (Cryptographic Bill of Materials) for certificates and key-exchange — algorithms, key sizes, and where each is used",
      "The list of long-lived certificates/keys and the sensitivity + retention of the data they protect",
      "Crypto-agility evidence — whether cert/key algorithms can be rotated centrally without re-architecting apps",
      "The vendor / PKI post-quantum (PQC) roadmap and the org's migration plan",
    ],
    test: "Assess the certificate and PKI estate for quantum readiness. PASS: a complete CBOM exists; the classical algorithms in use are catalogued; crypto is agile (cert and key types can be rotated centrally); a migration plan to NIST PQC standards (ML-KEM / ML-DSA, FIPS 203/204) and hybrid certificates exists with timelines aligned to CNSA 2.0; and long-lived secrets are prioritised for harvest-now-decrypt-later (HNDL) risk. Exceptions: no crypto inventory, hardcoded/un-agile algorithms, long-lived RSA/ECC protecting data that must outlive a cryptographically-relevant quantum computer, and no vendor PQC commitment.",
    systems: ["PKI with CBOM support — Venafi / Keyfactor", "The TLS + code-signing estate", "KMS / HSM", "Vendor and third-party PKI roadmaps"],
    owners: ["Cryptography / PKI team — owns the CBOM and migration", "Enterprise architecture — owns crypto-agility", "Vendor management — tracks supplier PQC readiness"],
    tools: [
      "CBOM:  generate a cryptography Bill of Materials (e.g. CycloneDX crypto-assets) across the estate",
      "Inventory: Venafi/Keyfactor crypto inventory (algorithm + key size + validity + location)",
      "Scan:  probe endpoints for negotiated key-exchange and any hybrid PQC support",
      "Map:   join data sensitivity + retention period against certificate/key validity to score HNDL exposure",
    ],
    finding: "No CBOM exists; long-lived RSA-2048 certificates protect records with a 25-year retention requirement (squarely in HNDL range); and no key vendor has a published PQC timeline.",
    refs: [["NIST FIPS 203/204/205 (PQC standards)", "https://csrc.nist.gov/projects/post-quantum-cryptography"], ["NSA CNSA 2.0", "https://www.nsa.gov/Cybersecurity/Post-Quantum-Cybersecurity-Resources/"]],
  },

  // ── Vulnerability & Patch Management ────────────────────────────────────────
  "vpm-01": {
    artifacts: [
      "The approved hardening baseline per OS (the CIS Benchmark level or DISA STIG the org committed to)",
      "A configuration-compliance scan of in-scope servers scored against that baseline",
      "The golden-image definition with its build date/version (what new servers are built from)",
      "The exception register for accepted deviations from the baseline",
    ],
    test: "Scan every in-scope server against the approved hardening baseline (CIS Benchmark / DISA STIG for that OS). PASS: each server is built from the current golden image and scores at or above the agreed threshold (e.g. ≥90% CIS Level 1), with documented, time-boxed exceptions for the remainder. Exceptions: servers built off-image or never hardened, baselines scoring below threshold, and 'temporary' exceptions with no expiry.",
    systems: ["CIS-CAT / Tenable Policy Compliance / Qualys PC (configuration-compliance scanner)", "The image pipeline — Packer / golden AMI / VM template", "CMDB (the authoritative in-scope server list)"],
    owners: ["IT Operations / Platform engineering — owns the build", "Security engineering — owns the baseline standard", "Server owners — own any exceptions"],
    tools: [
      "CIS-CAT Pro Assessor run against the CIS Benchmark for each OS (machine-readable score)",
      "Tenable.sc audit policy ('CIS …' / 'DISA STIG …') or Qualys Policy Compliance scan",
      "AWS:  compare each instance's running AMI id against the approved golden-AMI list",
      "Chef InSpec / Ansible compliance profile run against the baseline",
    ],
    finding: "A subset of production servers built from a two-year-old image scoring ~60% against CIS Level 1 — SSH root login enabled, weak ciphers, and no host firewall.",
    refs: [["CIS Benchmarks", "https://www.cisecurity.org/cis-benchmarks"], ["DISA STIGs", "https://public.cyber.mil/stigs/"], ["NIST SP 800-123 Server Security", "https://csrc.nist.gov/pubs/sp/800/123/final"]],
  },
  "vpm-02": {
    artifacts: [
      "The patch-compliance report by host — missing patches with severity and age",
      "The patch SLA policy (e.g. critical ≤7 days, high ≤30 days)",
      "The CISA Known Exploited Vulnerabilities (KEV) list mapped to the estate",
      "The risk-acceptance/exception register for systems that can't be patched on time",
    ],
    test: "Reconcile missing patches against the SLA and the KEV catalogue. PASS: every missing patch is within its severity SLA window; nothing on the CISA KEV list is open past the BOD 22-01 due date; and every overdue item has a formal, time-boxed risk acceptance with a compensating control. Exceptions: critical or KEV-listed vulnerabilities open past SLA, patches missing for months, and 'exceptions' with no owner or expiry date.",
    systems: ["WSUS / SCCM / Intune (Windows) and Satellite / Ansible (Linux) patch state", "Vulnerability scanner (Tenable / Qualys) for missing-patch detection", "CISA KEV feed", "GRC / ticketing for exceptions"],
    owners: ["IT Operations — applies the patches", "Security operations — tracks SLA + KEV", "Risk management — approves exceptions"],
    tools: [
      "SCCM / Intune update-compliance export per device",
      "Tenable: 'missing patch' plugin family + 'vulnerability age' field, filtered to severity",
      "join scan CVEs to the CISA KEV catalogue (cisa.gov/known-exploited-vulnerabilities-catalog)",
      "Linux: dnf/yum updateinfo list security, apt list --upgradable across the fleet",
    ],
    finding: "Several internet-facing hosts missing a KEV-listed critical patch for 90+ days with no risk acceptance on file — exactly the pattern behind most breaches.",
    refs: [["NIST SP 800-40 Patch Management", "https://csrc.nist.gov/pubs/sp/800/40/r4/final"], ["CISA BOD 22-01 / KEV", "https://www.cisa.gov/known-exploited-vulnerabilities-catalog"]],
  },
  "vpm-03": {
    artifacts: [
      "The desired-state configuration baseline held by the CM tool",
      "Drift reports — hosts that deviated from the baseline since the last enforcement run",
      "The change record correlating to any legitimate deviation",
      "Coverage: hosts enrolled in configuration management vs total in the CMDB",
    ],
    test: "Compare running configuration to the enforced baseline. PASS: a configuration-management engine (Ansible/Chef/Puppet/AWS SSM) runs on schedule across ~100% of hosts; drift is detected and auto-remediated or ticketed within SLA; and every legitimate deviation maps to an approved change. Exceptions: hosts not under configuration management at all, drift left unremediated, and unauthorised changes (drift with no corresponding change record).",
    systems: ["Chef / Puppet / Ansible / AWS SSM State Manager (the desired-state engine)", "Drift dashboards / AWS Config", "Change management (to correlate legitimate deviations)"],
    owners: ["Platform / SRE — owns configuration management", "Security engineering — owns the secure baseline", "Change management"],
    tools: [
      "AWS Config rules + SSM State Manager association-compliance report",
      "Chef Automate / Puppet 'corrective vs intentional changes' report",
      "list hosts NOT enrolled in CM (CMDB minus CM inventory) — the blind spots",
      "correlate drift events to ServiceNow change tickets (authorised vs not)",
    ],
    finding: "About 20% of the fleet isn't enrolled in configuration management, so its drift is invisible; among enrolled hosts, several have firewall/security-group drift unremediated for weeks.",
    refs: [["NIST SP 800-128 Configuration Management", "https://csrc.nist.gov/pubs/sp/800/128/final"], ["CIS Control 4 Secure Configuration", "https://www.cisecurity.org/controls"]],
  },
  "vpm-04": {
    artifacts: [
      "The local/privileged administrator membership per server (who can log on as admin)",
      "Bastion / jump-host + PAM checkout logs for every administrative session",
      "MFA-enforcement evidence for administrative logon (RDP/SSH)",
      "The standing-vs-just-in-time (JIT) admin grant list",
    ],
    test: "Enumerate who holds administrative access to in-scope servers and how they reach it. PASS: admin access is least-privilege, brokered through a bastion/PAM with MFA, checkout, and session logging, prefers JIT over standing, and local admin is LAPS-managed; no direct admin logon from user workstations. Exceptions: broad standing admin, shared admin accounts, administrative logon without MFA, and direct RDP/SSH that bypasses the bastion.",
    systems: ["Active Directory / local groups (server admin membership)", "PAM (CyberArk/Delinea) + bastion host", "MFA/IdP for administrative logon"],
    owners: ["Platform / infrastructure — owns server administration", "PAM team — owns the brokered path", "Security operations — monitors sessions"],
    tools: [
      "per host: members of local Administrators (Windows) / sudoers + wheel (Linux)",
      "AD: who holds 'Allow log on through Remote Desktop' / Remote Desktop Users on servers",
      "PAM session logs: which privileged account was checked out, by whom, when",
      "confirm MFA on RDP/SSH (Duo / Entra) and that direct paths to servers are blocked",
    ],
    finding: "A shared local 'admin' account used by 30 engineers with no MFA and direct RDP from workstations, bypassing the bastion entirely — one phished laptop owns every server.",
    refs: [["NIST SP 800-53 AC-6 / AC-17", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"], ["CIS Control 5 Account Management", "https://www.cisecurity.org/controls"]],
  },
  "vpm-05": {
    artifacts: [
      "The authenticated vulnerability-scan results across the asset estate",
      "Scan-coverage report — assets actually scanned vs total in the CMDB, and authenticated vs unauthenticated",
      "Risk-based prioritisation data — CVSS combined with EPSS and the KEV flag and asset exposure",
      "Remediation SLA tracking + aging report, with rescan-verified closures",
    ],
    test: "Assess the vulnerability-management lifecycle end to end. PASS: scans are authenticated and cover ~100% of the CMDB on cadence; findings are prioritised risk-based (CVSS + EPSS + KEV + exposure, not raw CVSS); remediation meets SLA; and closure is verified by rescan. Exceptions: large unscanned or unauthenticated coverage gaps, prioritisation by CVSS alone, SLA breaches, and findings 'closed' without a confirming rescan.",
    systems: ["Tenable / Qualys / Rapid7 (the scanner)", "CMDB (the coverage denominator)", "FIRST EPSS + CISA KEV (prioritisation inputs)", "Ticketing (remediation workflow)"],
    owners: ["Security operations / Vulnerability management — owns the program", "Asset & server owners — remediate", "Risk — accepts residual risk"],
    tools: [
      "Tenable.sc/io: scan-coverage + scan-age report; flag unauthenticated scans (credential failures)",
      "coverage = distinct scanned assets ÷ CMDB assets (the gap is your blind spot)",
      "enrich each CVE with its EPSS score (api.first.org/data/v1/epss) and KEV flag",
      "remediation aging buckets (0-30 / 30-90 / 90+ days) by severity",
    ],
    finding: "Scanner coverage is ~70% of the CMDB and ~40% of scans are unauthenticated (so they miss most host vulnerabilities); a backlog of KEV-listed criticals sits unremediated on the unscanned remainder.",
    refs: [["CISA KEV", "https://www.cisa.gov/known-exploited-vulnerabilities-catalog"], ["FIRST EPSS", "https://www.first.org/epss/"], ["CIS Control 7", "https://www.cisecurity.org/controls"]],
  },
  "vpm-06": {
    artifacts: [
      "The host logging configuration (what's collected: authentication, process-creation, PowerShell script-block, Sysmon, EDR telemetry)",
      "Log-forwarding coverage — hosts shipping to the SIEM vs total in the CMDB",
      "The detection use-case list mapped to MITRE ATT&CK techniques",
      "Log retention period + tamper-protection settings",
    ],
    test: "Verify hosts produce and ship security-relevant logs. PASS: required event sources are enabled (authentication, process-creation with command line, PowerShell script-block, Sysmon, EDR), ~100% of hosts forward to the SIEM, logs are retained per policy and tamper-protected, and key ATT&CK techniques have detections. Exceptions: hosts not forwarding (logging blind spots), missing event sources (e.g. process-creation auditing off), retention below policy, and ATT&CK coverage gaps.",
    systems: ["Sysmon / Windows Event Log / auditd (host configuration)", "SIEM — Splunk / Microsoft Sentinel (forwarding + retention)", "EDR telemetry", "MITRE ATT&CK (coverage mapping)"],
    owners: ["Security operations / detection engineering", "Platform — deploys the agents", "Server owners"],
    tools: [
      "SIEM: hosts reporting in the last 24h vs CMDB (forwarding-coverage gap)",
      "audit policy: confirm Event ID 4688 process-creation + command-line capture and 4104 script-block logging are enabled",
      "Sysmon configuration review (process, network, image-load coverage)",
      "ATT&CK Navigator layer of current detections vs the technique list",
    ],
    finding: "About 15% of servers send no logs to the SIEM, and command-line process auditing (4688) is off fleet-wide — so the single most useful host telemetry for investigations is simply missing.",
    refs: [["NIST SP 800-92 Log Management", "https://csrc.nist.gov/pubs/sp/800/92/final"], ["MITRE ATT&CK", "https://attack.mitre.org/"], ["CIS Control 8", "https://www.cisecurity.org/controls"]],
  },
  "vpm-07": {
    artifacts: [
      "The red-team engagement reports with scope and rules of engagement (RoE)",
      "The blue-team detections that fired (or were missed) per attack technique",
      "The purple-team coverage matrix — techniques exercised vs techniques detected",
      "Remediation tracking + retest evidence for findings",
    ],
    test: "Assess the red/blue/purple program. PASS: adversary-emulation exercises run on cadence against realistic ATT&CK techniques with proper RoE; blue-team detection/response is measured (what was detected, MTTD/MTTR); a purple-team matrix shows technique coverage; and findings are remediated and retested. Exceptions: no adversary emulation, tests not mapped to ATT&CK, detections that silently failed and weren't fixed, and findings with no retest.",
    systems: ["Adversary-emulation tooling — MITRE Caldera / Atomic Red Team / Cobalt Strike", "SIEM/EDR (detection evidence)", "ATT&CK Navigator (coverage)", "Findings tracker"],
    owners: ["Offensive security (red)", "SOC / detection engineering (blue)", "Security leadership"],
    tools: [
      "MITRE Caldera or Atomic Red Team to execute techniques safely",
      "for each executed technique, correlate to a SIEM/EDR alert: detected vs missed",
      "build an ATT&CK Navigator coverage layer from the results",
      "track each finding to closure with retest evidence",
    ],
    finding: "Adversary emulation covers only a handful of ATT&CK techniques; several executed techniques (e.g. LSASS credential dumping) produced no alert, and the detection gap was never remediated.",
    refs: [["MITRE ATT&CK", "https://attack.mitre.org/"], ["NIST SP 800-115 Security Testing", "https://csrc.nist.gov/pubs/sp/800/115/final"]],
  },
  "vpm-08": {
    artifacts: [
      "The malware triage/analysis procedure + sandbox detonation reports",
      "IOC extraction + distribution evidence (hashes/domains/IPs pushed to EDR, SIEM, firewall/DNS)",
      "Sample-handling chain-of-custody + containment evidence",
      "Detection-as-code (YARA/Sigma) produced from the analysis and confirmed deployed",
    ],
    test: "Assess malware-analysis capability and sample handling. PASS: suspected malware is detonated in an isolated sandbox (never production), IOCs are extracted and pushed to enforcement points (EDR block, SIEM watchlist, DNS sinkhole), YARA/Sigma rules are authored and deployed, and samples are contained with chain-of-custody. Exceptions: analysis on production systems, IOCs extracted but never operationalised, no detection content produced, and unsafe sample handling.",
    systems: ["Sandbox — Cuckoo / CAPE / Joe Sandbox, or EDR detonation", "EDR / SIEM / firewall / DNS (IOC enforcement)", "Threat-intel platform (MISP)", "YARA/Sigma rule repository"],
    owners: ["SOC / threat analysis / DFIR", "Detection engineering", "Threat intelligence"],
    tools: [
      "detonate in an isolated VLAN sandbox; capture behavioural + network IOCs",
      "push hashes/domains to the EDR block list + DNS sinkhole + SIEM watchlist (confirm live)",
      "author and deploy YARA/Sigma rules; verify the rule is active in the SIEM/EDR",
      "record the campaign + IOCs in MISP for sharing",
    ],
    finding: "Malware is analysed but the IOCs are never fed back into EDR/SIEM block lists, so the same indicators recur weeks later; no YARA/Sigma detections are produced from the work.",
    refs: [["NIST SP 800-83 Malware Incident Prevention", "https://csrc.nist.gov/pubs/sp/800/83/r1/final"], ["MITRE ATT&CK", "https://attack.mitre.org/"]],
  },
  "vpm-09": {
    artifacts: [
      "The inventory of AI-assisted offensive tooling in use, with its authorisation and guardrails",
      "Logs of AI-generated payloads/recon and the human approval gate before execution",
      "Evidence that AI red-team activity stayed within scope/RoE and is fully logged + attributable",
      "Data-handling controls — proof that target/client data isn't sent to ungoverned model endpoints",
    ],
    test: "Assess governance of AI used in offensive security. PASS: AI-assisted red-team tooling is inventoried and authorised; every AI-generated action runs within scope/RoE behind a human-in-the-loop gate; activity is fully logged and attributable; and sensitive target data is not sent to public/ungoverned models. Exceptions: shadow AI offensive tooling, AI actions taken autonomously outside RoE, missing logging/attribution, and target data leaking to public model endpoints.",
    systems: ["The AI/LLM tooling and its API/usage logs", "C2 / emulation integration", "Authorisation / RoE records", "DLP for prompt content"],
    owners: ["Offensive security", "AI governance / responsible-AI", "Security leadership"],
    tools: [
      "inventory AI offensive tools and confirm each engagement's authorisation",
      "review LLM API logs for prompts/outputs tied to the engagement (attribution)",
      "confirm a human-approval gate exists before any AI-driven action executes",
      "DLP/policy check that target or client data is not pasted into public model endpoints",
    ],
    finding: "An engineer uses a public LLM to generate phishing pretexts with real client data pasted into the prompts — outside RoE, unlogged, and a data-leak in its own right.",
    refs: [["NIST AI Risk Management Framework", "https://www.nist.gov/itl/ai-risk-management-framework"], ["MITRE ATLAS", "https://atlas.mitre.org/"]],
  },
  "vpm-10": {
    artifacts: [
      "The pipeline from cloud vulnerability finding (CSPM/scanner) to a ticket with an owner and SLA",
      "Auto-routing rules (finding → owning team by resource tag) + the deduplication logic",
      "SLA + aging report for cloud-infrastructure vulnerability tickets",
      "Closure verification — a rescan confirms the cloud finding is actually gone",
    ],
    test: "Assess the automated cloud-vulnerability ticketing flow (the Security Ticketing Engine). PASS: every cloud finding (CSPM / Inspector / Wiz) auto-creates a ticket routed to the resource owner by tag, with a severity-based SLA, dedup, and closed-loop verification on rescan. Exceptions: findings with no ticket or owner (orphaned risk), tickets with no SLA, duplicate noise drowning real findings, and tickets closed without a confirming rescan.",
    systems: ["CSPM — Wiz / Prisma Cloud / Microsoft Defender for Cloud, or AWS Inspector + Security Hub", "Ticketing — Jira / ServiceNow", "Cloud tagging (ownership)", "The Security Ticketing Engine automation"],
    owners: ["Cloud security — owns the engine", "Account / resource owners — remediate", "Platform — owns the tagging standard"],
    tools: [
      "AWS Security Hub / Inspector findings → EventBridge → ticket-automation Lambda",
      "route by resource tag (owner/team); dedup by finding id to suppress noise",
      "SLA aging dashboard for cloud tickets by severity",
      "auto-close a ticket only after a rescan shows the finding resolved",
    ],
    finding: "About 30% of cloud findings sit on resources with no owner tag, so they generate orphaned tickets nobody actions; criticals on untagged resources age indefinitely.",
    refs: [["AWS Security Hub", "https://docs.aws.amazon.com/securityhub/"], ["Cloud Security Alliance CCM", "https://cloudsecurityalliance.org/research/cloud-controls-matrix"]],
  },

  // ── Network Security ────────────────────────────────────────────────────────
  "net-01": {
    artifacts: [
      "The network segmentation diagram plus the authoritative VLAN/subnet-to-trust-zone mapping",
      "The firewall/ACL rules that enforce each inter-zone boundary (user→server, app→database, corporate↔OT, CDE↔non-CDE)",
      "East-west traffic-flow logs (NetFlow/IPFIX) showing what actually crosses zone boundaries",
      "The list of flat or over-permissive segments — any-to-any reachability",
    ],
    test: "Validate that the defined trust zones are actually enforced, not just drawn. PASS: each in-scope zone boundary is enforced deny-by-default; observed east-west flows match the documented allow-list; and sensitive zones (PCI CDE, OT, the management plane) are isolated. Exceptions: zones reachable any-to-any, a 'segmented' boundary held open by a permit-ip-any rule, and flows in the logs that no rule should allow (shadow connectivity).",
    systems: ["NGFW — Palo Alto / Fortinet / Cisco (zone enforcement)", "Microsegmentation — Illumio / VMware NSX / cloud security groups", "NetFlow/IPFIX or NDR (observed flows)", "Network/CMDB zone documentation"],
    owners: ["Network engineering — owns the topology", "Network security — owns the zone policy", "Application & data owners — declare which zone their assets belong to"],
    tools: [
      "export the firewall rulebase + interface-to-zone mapping (Panorama / FortiManager)",
      "compare the documented zone matrix against the actual inter-zone permit rules",
      "NetFlow analysis: list cross-zone flows that are NOT in the allow-list",
      "Illumio/NSX policy export + traffic explorer to see real east-west connectivity",
    ],
    finding: "The 'segmented' database VLAN is reachable from the entire user VLAN via a legacy permit-any rule, and NetFlow shows workstations talking straight to the database — the segmentation exists only on the diagram.",
    refs: [["NIST SP 800-207 Zero Trust Architecture", "https://csrc.nist.gov/pubs/sp/800/207/final"], ["PCI DSS — Network Segmentation Guidance", "https://www.pcisecuritystandards.org/"], ["CIS Control 12 Network Infrastructure", "https://www.cisecurity.org/controls"]],
  },
  "net-02": {
    artifacts: [
      "The full firewall rule base export — source, destination, service, action, hit-count, age, owner, last-modified",
      "The change tickets that justify each rule (every rule → an approved change)",
      "The rule-recertification records (periodic review that the business need still exists)",
      "Shadowed / expired / overly-permissive rule analysis (any-any, zero-hit, redundant)",
    ],
    test: "Review the firewall rule base for governance. PASS: every rule has a documented business justification, an owner, and an approval ticket; rules are recertified on cadence; there are no any-any or overly-broad permits; unused (zero-hit) and shadowed/redundant rules are removed; and logging is on for denies and sensitive permits. Exceptions: rules with no owner or justification, permit any-any, zero-hit rules left in place for years, and rules with no approval trail.",
    systems: ["Firewall management — Panorama / FortiManager / Cisco FMC", "Firewall analyzer — Tufin / AlgoSec / FireMon", "Change management (rule ↔ ticket)"],
    owners: ["Network security / firewall team — owns the rulebase", "Application owners — justify their rules", "Change management"],
    tools: [
      "export the rulebase with hit-counts + last-hit (e.g. PAN-OS `show rule-hit-count`)",
      "Tufin/AlgoSec rule-cleanup + risk report (any-any, shadowed, unused, redundant)",
      "join each rule to its change-ticket id (the recertification/approval evidence)",
      "flag any permit to a sensitive zone that has logging disabled",
    ],
    finding: "Hundreds of zero-hit rules accreted over a decade, dozens of permit any-any rules with no owner, and rules whose 'temporary, 2019' justification never expired.",
    refs: [["NIST SP 800-41 Firewall Policy", "https://csrc.nist.gov/pubs/sp/800/41/r1/final"], ["PCI DSS Requirement 1", "https://www.pcisecuritystandards.org/"], ["CIS Control 13 Network Monitoring & Defense", "https://www.cisecurity.org/controls"]],
  },
  "net-03": {
    artifacts: [
      "The remote-access inventory — every VPN gateway and ZTNA application, and who is entitled to each",
      "MFA + device-posture enforcement evidence for remote sessions",
      "The access scope each method grants (full-tunnel / flat subnet vs ZTNA per-application)",
      "Session logs + idle/absolute timeout config + the split-tunnel policy",
    ],
    test: "Assess every remote-access path into the network. PASS: all require phishing-resistant MFA and a posture-checked device; access is least-privilege (ZTNA per-application, or tightly-scoped VPN, not flat-subnet); split/full-tunnel is deliberate; sessions time out and are logged; legacy/unused gateways are decommissioned. Exceptions: a VPN without MFA, a VPN that drops users onto a flat internal subnet, no device-posture check, and forgotten internet-facing remote-access gateways.",
    systems: ["VPN gateways — Cisco AnyConnect / Palo Alto GlobalProtect / Fortinet", "ZTNA — Zscaler Private Access / Cloudflare Access / Netskope", "IdP/MFA + MDM posture — Entra/Okta + Intune/Jamf"],
    owners: ["Network security — owns VPN/ZTNA", "IAM — owns MFA", "Endpoint — owns device posture"],
    tools: [
      "enumerate remote-access gateways (external scan + config) and the auth method each uses",
      "confirm MFA + Conditional Access / device posture on every VPN and ZTNA portal",
      "review the access scope: ZTNA per-app policy vs the routes a VPN actually pushes",
      "Shodan/Censys external scan for exposed remote-access portals you forgot existed",
    ],
    finding: "A legacy SSL-VPN appliance, still internet-facing and unpatched, accepts username + password only (no MFA) and routes onto a flat /16 internal network — the textbook ransomware entry point.",
    refs: [["NIST SP 800-207 Zero Trust Architecture", "https://csrc.nist.gov/pubs/sp/800/207/final"], ["CISA — Securing Remote Access / VPN", "https://www.cisa.gov/"], ["NIST SP 800-46 Telework Security", "https://csrc.nist.gov/pubs/sp/800/46/r2/final"]],
  },
  "net-04": {
    artifacts: [
      "The list of network log sources sending to the SIEM (firewall, VPN, DNS, proxy, NetFlow, NDR) vs the device inventory",
      "The firewall deny + sensitive-permit logging configuration",
      "DNS query logging plus the detections built on it (DGA/tunneling/sinkhole)",
      "NDR/flow coverage of north-south AND east-west, with the retention setting",
    ],
    test: "Verify network telemetry is collected, complete, and actioned. PASS: all in-scope network devices forward logs to the SIEM; firewalls log denies and sensitive permits; DNS and proxy logs are collected; NetFlow/NDR covers north-south and key east-west; detections exist for beaconing/exfiltration/lateral movement; and retention meets policy. Exceptions: devices not forwarding (visibility gaps), deny logging off, no DNS logging, NDR blind to east-west, and retention below policy.",
    systems: ["SIEM — Splunk / Microsoft Sentinel", "NDR — Darktrace / Vectra / Corelight (Zeek)", "Firewall / VPN / DNS / proxy log sources", "NetFlow/IPFIX collectors"],
    owners: ["Security operations / detection engineering", "Network engineering — emits the logs", "SOC"],
    tools: [
      "SIEM: which network devices reported in the last 24h vs the network CMDB",
      "confirm firewalls 'log at session end' on deny and sensitive-permit rules",
      "DNS: query logging enabled + detections (NXDOMAIN spikes, known-bad domains, tunneling)",
      "map NDR sensor placement: which segments are actually monitored vs dark",
    ],
    finding: "Perimeter firewall deny-logging is off, internal DNS isn't logged at all, and the NDR only sees north-south traffic — so lateral movement across the data-center east-west fabric is completely invisible.",
    refs: [["NIST SP 800-92 Log Management", "https://csrc.nist.gov/pubs/sp/800/92/final"], ["MITRE ATT&CK — Command & Control / Exfiltration", "https://attack.mitre.org/"], ["CIS Control 13", "https://www.cisecurity.org/controls"]],
  },
  "net-05": {
    artifacts: [
      "The current-state network architecture diagram + data-flow diagrams for crown-jewel systems",
      "The DMZ/tiering design (no direct internet→internal, proxied/filtered egress, isolated management plane)",
      "The external attack-surface inventory — every internet-facing service",
      "Resilience + out-of-band management-network isolation evidence",
    ],
    test: "Review the network architecture against secure-design principles. PASS: defense-in-depth tiers (DMZ → app → data) with no direct internet-to-internal paths; egress is proxied/filtered (no arbitrary outbound); the management plane is out-of-band and isolated from production/user traffic; the external attack surface is inventoried and minimized; and single points of failure are addressed. Exceptions: internal services directly internet-exposed, unrestricted outbound egress, management interfaces on the user/production network, and an unknown external attack surface.",
    systems: ["Network design docs / enterprise-architecture repository", "External attack-surface management — Censys / Shodan / Microsoft Defender EASM", "Firewalls, forward proxies, load balancers"],
    owners: ["Network architecture / engineering", "Security architecture", "Cloud platform (for cloud network design)"],
    tools: [
      "external attack-surface scan (Shodan/Censys/Defender EASM) across the org's IP ranges + domains",
      "review the egress policy: is outbound default-deny via a proxy allow-list?",
      "confirm out-of-band management isolation (separate VRF/VLAN, not reachable from users)",
      "trace data flows for crown-jewel systems and compare to the documented design",
    ],
    finding: "An internet-exposed RDP service and a server management interface (iLO/IPMI) reachable from the user VLAN, plus wide-open outbound egress that would let any compromised host beacon out unimpeded.",
    refs: [["NIST SP 800-53 SC-7 Boundary Protection", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"], ["CISA — Secure Network Architecture", "https://www.cisa.gov/"], ["CIS Control 12", "https://www.cisecurity.org/controls"]],
  },
  "net-06": {
    artifacts: [
      "Each network device's running-config plus the approved hardened baseline to diff against",
      "Config-backup evidence — every device backed up on schedule and proven restorable",
      "Config-drift/compliance reports (AAA/TACACS+, SSHv2-only, SNMPv3, NTP, logging, no unused services)",
      "Firmware/OS version + end-of-life status per device",
    ],
    test: "Assess network-device configuration governance. PASS: every device's config is backed up automatically and version-controlled; configs are diffed against a hardened baseline (TACACS+/AAA, SSHv2 only, SNMPv3, NTP, logging, no telnet/http); drift is detected; firmware is supported and patched; and changes go through change control. Exceptions: devices with no config backup, telnet/SNMPv1/HTTP enabled, default or shared credentials, end-of-life firmware with known CVEs, and out-of-band config changes.",
    systems: ["NCCM — SolarWinds NCM / Oxidized / RANCID / Cisco DNA Center", "TACACS+/RADIUS (device AAA)", "Config-backup store / git", "Device inventory (firmware + EOL)"],
    owners: ["Network engineering — owns device config", "Network security — owns the hardening baseline", "Change management"],
    tools: [
      "Oxidized/RANCID/NCM: confirm every device has a recent successful config backup",
      "diff running-config vs the hardened baseline (CIS Cisco/Juniper Benchmark)",
      "grep configs for `telnet`, `snmp-server community public|private`, `no aaa`, `ip http server`",
      "map device OS versions to vendor EOL dates + PSIRT advisories",
    ],
    finding: "A dozen access switches still run telnet with a shared 'cisco' enable password, several core devices are past end-of-life with known CVEs, and three devices have no config backup at all — no recovery if they fail.",
    refs: [["NIST SP 800-128 Configuration Management", "https://csrc.nist.gov/pubs/sp/800/128/final"], ["CIS Cisco / Juniper Benchmarks", "https://www.cisecurity.org/cis-benchmarks"], ["CISA — Network Device Hardening", "https://www.cisa.gov/"]],
  },
  "net-07": {
    artifacts: [
      "The inventory of AI/ML-driven networking systems (AIOps anomaly detection, intent-based networking, auto-remediation) and the actions each can take",
      "The guardrails on automated changes — human-approval gates, blast-radius limits, tested rollback",
      "Model + training-data governance for the AIOps platform",
      "Audit logs of AI-initiated network changes and their outcomes",
    ],
    test: "Govern AI/ML in network operations. PASS: every AIOps/intent-based system is inventoried with its authority bounded (what it may change automatically vs what needs approval); automated remediation has blast-radius limits and tested rollback; AI-initiated changes are logged, attributable, and reviewable; and the model/data feeding decisions is governed (no poisoning, no sensitive telemetry leaking to an ungoverned vendor model). Exceptions: AIOps with unbounded auto-remediation authority, AI changes with no logging or rollback, anomaly models trained on unvetted data, and config/telemetry streamed to ungoverned external AI.",
    systems: ["AIOps / AI networking — Cisco AI Network Analytics (DNA) / Juniper Mist AI / Arista CloudVision", "Intent-based networking controllers", "The change/automation pipeline", "Model + data governance tooling"],
    owners: ["Network engineering / NetOps — owns the AIOps platform", "Network security — owns the guardrails", "AI governance — owns model/data risk"],
    tools: [
      "inventory AIOps/IBN systems and the scope of changes each can auto-apply",
      "review auto-remediation policy: approval gate, maximum blast radius, rollback test evidence",
      "pull the audit log of AI-initiated changes (what changed, why, outcome, who reviewed)",
      "confirm telemetry/config sent to vendor AI is governed (DLP + contractual data handling)",
    ],
    finding: "An AIOps platform can auto-apply ACL and routing changes fleet-wide with no human gate and no tested rollback — a single false-positive anomaly could black-hole production — while device telemetry streams to a vendor cloud with no data-handling review.",
    refs: [["NIST AI Risk Management Framework", "https://www.nist.gov/itl/ai-risk-management-framework"], ["NIST SP 800-53 CM-3 / SI-4", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"]],
  },

  // ── Data Protection & Privacy ───────────────────────────────────────────────
  "dpp-01": {
    artifacts: [
      "The data-classification policy + scheme (e.g. Public / Internal / Confidential / Restricted)",
      "The classification coverage report — share of repositories/stores/documents labelled vs unlabelled",
      "Sensitive-data discovery scan results — where PII/PHI/PCI actually lives, including unmanaged shares and dev/test",
      "The handling-rule mapping per class (encryption, access, external sharing, retention)",
    ],
    test: "Verify data is classified and handled per its sensitivity. PASS: a classification scheme exists and is applied (labels/tags) across structured and unstructured stores; a discovery scan finds no high-sensitivity data in unclassified or unmanaged locations; and handling rules (encryption, access, external sharing, retention) are enforced per class. Exceptions: large volumes of unlabelled data, PII/PHI/PCI discovered in unmanaged file shares or dev/test, and sensitive data shared externally against its class rule.",
    systems: ["Microsoft Purview Information Protection / Google DLP / BigID / Varonis (classification)", "Data-discovery scanners", "File shares, SharePoint/OneDrive, databases, data lakes"],
    owners: ["Data Protection Officer / Privacy — owns the scheme", "Data owners / stewards — classify their data", "Security — enforces the handling rules"],
    tools: [
      "Microsoft Purview: sensitivity-label coverage report + auto-labelling scan results",
      "BigID / Varonis sensitive-data discovery across file shares + databases",
      "scan dev/test and unmanaged shares for PII/PHI/PCI patterns (SSNs, PANs, MRNs)",
      "map each class to its handling rules and confirm enforcement (e.g. external-share block on Restricted)",
    ],
    finding: "About 60% of SharePoint sites and most file shares are unlabelled; discovery finds unencrypted spreadsheets of customer SSNs in an open 'Public' share and PHI copied into a developer test database.",
    refs: [["NIST SP 800-60 Information Categorisation", "https://csrc.nist.gov/pubs/sp/800/60/v1/r1/final"], ["GDPR Art. 5 / 32", "https://gdpr-info.eu/"], ["ISO/IEC 27001 A.5.12", "https://www.iso.org/standard/27001"]],
  },
  "dpp-02": {
    artifacts: [
      "The encryption inventory — which stores/links use what (algorithm, key source, TLS version)",
      "TLS configuration of internal and external endpoints (versions, cipher suites, certificate validity)",
      "At-rest encryption status of databases, volumes, object stores, and backups",
      "Key-management evidence — KMS/HSM, customer-managed vs provider-default keys, rotation",
    ],
    test: "Verify sensitive data is encrypted in transit, at rest, and (where required) in use, with managed keys. PASS: data-in-transit uses TLS 1.2+ with strong ciphers (no TLS 1.0/1.1, no weak suites); data-at-rest is encrypted on every store holding sensitive data (DB TDE, volume/object encryption, encrypted backups) with KMS/HSM-managed, rotated keys; and field-level / confidential-compute encryption is used where the data class demands it. Exceptions: cleartext internal links carrying sensitive data, unencrypted databases/volumes/backups, weak TLS, and keys that are provider-default or never rotated.",
    systems: ["KMS/HSM — AWS KMS / Azure Key Vault / HashiCorp Vault", "Databases (TDE), storage (volume/object encryption), load balancers (TLS termination)", "TLS scanners — SSL Labs / testssl.sh / nmap"],
    owners: ["Cryptography/PKI + platform security — own encryption + keys", "Application & data owners — own their stores", "Cloud platform"],
    tools: [
      "testssl.sh / nmap --script ssl-enum-ciphers across internal AND external endpoints",
      "cloud: list unencrypted volumes/buckets/DBs (aws ec2 describe-volumes 'Encrypted==false', S3 default-encryption, RDS StorageEncrypted)",
      "confirm DB TDE / column-level encryption on tables holding sensitive data",
      "KMS: rotation enabled + customer-managed vs provider-default keys for sensitive data",
    ],
    finding: "Internal microservice traffic carrying PII runs over plaintext HTTP, two production databases have TDE off, several customer-data S3 buckets use no encryption, and the keys in use have rotation disabled.",
    refs: [["NIST SP 800-57 Key Management", "https://csrc.nist.gov/projects/key-management"], ["NIST SP 800-52 TLS Guidelines", "https://csrc.nist.gov/pubs/sp/800/52/r2/final"], ["PCI DSS Req. 3 / 4", "https://www.pcisecuritystandards.org/"]],
  },
  "dpp-03": {
    artifacts: [
      "The data-retention schedule by data type (legal/regulatory minimums and maximums)",
      "Evidence that retention/expiry is enforced — storage lifecycle/TTL rules, automated purge jobs",
      "Disposal/destruction records — certificates of destruction, crypto-erase logs (NIST 800-88)",
      "An over-retention scan — data still held past its retention period",
    ],
    test: "Verify data is kept only as long as needed and disposed of securely. PASS: a retention schedule exists per data type and is enforced automatically (storage lifecycle/TTL, DB purge jobs); data past retention is deleted; media/data disposal is secure (crypto-erase / NIST 800-88) with records; and legal holds override deletion correctly. Exceptions: data retained indefinitely with no schedule, retention rules defined but not enforced (data still present years past expiry), insecure disposal, and PII kept beyond its lawful basis.",
    systems: ["Storage lifecycle — S3 Lifecycle / Azure Blob lifecycle; DB purge jobs", "Records-management tooling — Microsoft Purview Data Lifecycle Management", "Media-sanitisation / asset-disposal process"],
    owners: ["Records management / Legal — own the schedule", "Data owners — enforce on their stores", "Privacy — owns PII minimisation"],
    tools: [
      "confirm S3 Lifecycle / Blob lifecycle rules + DB retention jobs exist and actually run",
      "scan for objects/records older than their retention period (last-modified vs schedule)",
      "Purview Data Lifecycle Management retention-label coverage report",
      "disposal: certificates of destruction + crypto-erase logs per NIST 800-88",
    ],
    finding: "PII from closed customer accounts is retained indefinitely — a schedule exists on paper but no lifecycle rule enforces it, so eight years of expired data sits in production, expanding breach and GDPR exposure.",
    refs: [["NIST SP 800-88 Media Sanitisation", "https://csrc.nist.gov/pubs/sp/800/88/r1/final"], ["GDPR Art. 5(1)(e) Storage Limitation", "https://gdpr-info.eu/art-5-gdpr/"]],
  },
  "dpp-04": {
    artifacts: [
      "The backup inventory + schedule per system (what's backed up, frequency, RPO)",
      "Backup success/failure logs across the period",
      "Restore-test evidence — actual test restores, RTO achieved, integrity verified",
      "Backup immutability/air-gap + encryption + access-control configuration (ransomware resilience)",
    ],
    test: "Verify backups exist, work, and would survive an attack. PASS: every in-scope system is backed up to its RPO; backups succeed (failures alerted and fixed); restores are tested on a schedule and meet RTO with verified integrity; and backups are immutable/air-gapped, encrypted, and access-restricted so a compromised production admin can't delete them. Exceptions: systems with no backup, silent backup failures, backups never test-restored, and backups reachable/deletable with the same credentials that run production (no ransomware resilience).",
    systems: ["Backup platform — Veeam / Commvault / Rubrik / AWS Backup", "Immutable storage — S3 Object Lock / immutable vault", "The systems being backed up + the CMDB"],
    owners: ["Backup / Infrastructure operations — own backups", "Business continuity — owns RPO/RTO", "Security — owns immutability"],
    tools: [
      "backup platform: success/failure report per system vs the CMDB (coverage + gaps)",
      "pull restore-test records: date, system, RTO achieved, integrity check result",
      "confirm object-lock/immutability + separate credentials / MFA-delete on the backup store",
      "verify backups are encrypted and NOT reachable from the production domain",
    ],
    finding: "A third of production systems show silent backup failures for months, no restore has been tested this year, and backups sit on a share writable by the production domain-admin account — so one ransomware actor encrypts production and the backups together.",
    refs: [["NIST SP 800-34 Contingency Planning", "https://csrc.nist.gov/pubs/sp/800/34/r1/final"], ["CISA #StopRansomware (3-2-1 + immutable)", "https://www.cisa.gov/stopransomware"]],
  },
  "dpp-05": {
    artifacts: [
      "The DLP policy set — sensitive data types detected, on which channels (email, web, endpoint, cloud)",
      "DLP coverage — endpoints/users/channels enrolled vs total",
      "DLP incident logs — detections, blocks, overrides — and their disposition",
      "The egress channels NOT covered by DLP (personal cloud, USB, unmanaged SaaS)",
    ],
    test: "Verify DLP detects and controls sensitive-data egress across channels. PASS: DLP covers the key sensitive types (PII/PHI/PCI/IP) across email, web/upload, endpoint (USB/print), and cloud (CASB); coverage is near-complete; incidents are triaged and trending down; high-risk channels are blocked or restricted; and policy override requires justification. Exceptions: major channels with no DLP (personal webmail, USB, unmanaged SaaS), large coverage gaps, incidents logged but never triaged, and trivial one-click override of blocks.",
    systems: ["DLP — Microsoft Purview DLP / Forcepoint / Symantec; CASB for cloud", "Email security gateway, web proxy / SWG, endpoint DLP agent", "SIEM (incident triage)"],
    owners: ["Data protection / security operations — own DLP", "Privacy — defines the sensitive types", "HR / Legal — handle insider cases"],
    tools: [
      "DLP console: policy inventory per channel + enrolled-endpoint coverage vs CMDB",
      "incident export: detections / blocks / overrides + disposition + trend over time",
      "test the exfil paths yourself — USB copy, personal webmail upload, unmanaged cloud sync — and see what's caught",
      "CASB: sanctioned vs shadow SaaS data movement",
    ],
    finding: "DLP runs on email only; endpoint USB and personal cloud sync are uncovered, so a test file of customer records copies to USB and uploads to personal Google Drive undetected — and the email DLP alerts route to a queue no one reviews.",
    refs: [["NIST SP 800-53 SC-7 / SI-4", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"], ["Microsoft Purview DLP", "https://learn.microsoft.com/purview/dlp-learn-about-dlp"], ["CIS Control 3 Data Protection", "https://www.cisecurity.org/controls"]],
  },
  "dpp-06": {
    artifacts: [
      "The data-security alert inventory (DLP, classification, access-anomaly, exfil) and where each routes",
      "Alert-triage records — time-to-triage, disposition (true/false positive, escalated), MTTR",
      "The runbooks/playbooks for data-exfiltration and insider alerts",
      "The backlog of un-triaged / aged data alerts",
    ],
    test: "Verify data-security alerts are actually worked, not just generated. PASS: alerts route to a named queue/owner with a triage SLA; true positives are escalated to incident response; the false-positive rate is managed by tuning (not ignored); playbooks exist for exfiltration/insider cases; and the aged-alert backlog is small. Exceptions: alerts firing into an unmonitored mailbox, no triage SLA, a large backlog of un-triaged alerts, no tuning (alert fatigue), and no playbook for confirmed data exfiltration.",
    systems: ["SIEM / SOAR — Sentinel / Splunk + Cortex XSOAR", "DLP / CASB / classification alert sources", "Case management / ITSM"],
    owners: ["Security operations / SOC — triage", "Data protection — owns the policies generating alerts", "Insider-risk / HR-Legal — for people cases"],
    tools: [
      "SIEM/SOAR: data-alert volume, time-to-triage, disposition mix, aged-backlog metrics",
      "confirm each alert source routes to a monitored queue with an owner + SLA",
      "review the exfil/insider playbook and a sample of recent cases for adherence",
      "false-positive rate + tuning history (the alert-fatigue signal)",
    ],
    finding: "DLP and access-anomaly alerts route to a shared mailbox no one owns; ~4,000 alerts sit un-triaged, and a confirmed large download by a departing employee was buried in the noise and never escalated.",
    refs: [["NIST SP 800-61 Incident Handling", "https://csrc.nist.gov/pubs/sp/800/61/r2/final"], ["MITRE ATT&CK — Exfiltration", "https://attack.mitre.org/tactics/TA0010/"]],
  },
  "dpp-07": {
    artifacts: [
      "The Record of Processing Activities (RoPA) — what personal data is processed, why, the lawful basis, and recipients",
      "The data-residency / sovereignty mapping — where each data category is stored/processed vs where it must stay",
      "Cross-border transfer mechanisms (SCCs, adequacy, EU-US DPF) for each export",
      "DSAR + consent + DPIA records",
    ],
    test: "Verify processing of personal data is lawful and data stays where it must. PASS: a RoPA exists with a lawful basis per processing activity; data residency matches regulatory/contractual requirements (e.g. EU data stays in the EU); cross-border transfers have a valid mechanism; DSARs and consent are honoured within statutory timelines; and DPIAs exist for high-risk processing. Exceptions: processing with no lawful basis, regulated data stored/processed in a prohibited region, international transfers with no valid mechanism, missed DSAR deadlines, and high-risk processing with no DPIA.",
    systems: ["Privacy management — OneTrust / TrustArc (RoPA, DSAR, consent)", "Cloud region/residency config + data catalogue", "Contracts / DPAs with processors"],
    owners: ["Data Protection Officer / Privacy — owns compliance", "Legal — owns the transfer mechanisms", "Cloud platform / data owners — control residency"],
    tools: [
      "OneTrust: RoPA completeness + lawful-basis per activity + DSAR-SLA report",
      "cloud: confirm resource regions for PII workloads (e.g. data resident in eu-* only)",
      "map each cross-border data flow to its SCC / adequacy / DPF mechanism",
      "DPIA register for high-risk processing (profiling, large-scale special-category data)",
    ],
    finding: "EU customer data is replicated to a US analytics region with no valid transfer mechanism, the RoPA is two years stale, and ~30% of DSARs missed the 30-day GDPR deadline.",
    refs: [["GDPR", "https://gdpr-info.eu/"], ["ISO/IEC 27701 Privacy Information Management", "https://www.iso.org/standard/71670.html"], ["EU Standard Contractual Clauses", "https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en"]],
  },
  "dpp-08": {
    artifacts: [
      "The enterprise data inventory/catalogue — datasets with owner, classification, and location",
      "Data-lineage maps for key datasets — source → transformations → consumers/reports",
      "Provenance records for critical/regulatory data (where it originated, how it was derived)",
      "Coverage: catalogued / lineage-mapped datasets vs total, including shadow data stores",
    ],
    test: "Verify the organisation knows what data it has, where it came from, and where it flows. PASS: a data catalogue covers the in-scope estate with owner + classification + location; lineage is mapped for regulatory/critical datasets (so the impact of a change or breach is traceable); provenance is recorded for data used in regulatory reporting or AI training; and shadow/undocumented stores are minimal. Exceptions: large uncatalogued/shadow data, no lineage for regulated datasets (a breach's blast radius or a bad figure can't be traced to source), and missing provenance for reported or AI-training data.",
    systems: ["Data catalogue — Collibra / Alation / Microsoft Purview / DataHub", "Lineage tooling (catalogue-native, or via dbt / Spark)", "The data lakes / warehouses / databases being catalogued"],
    owners: ["Data governance / Chief Data Office — owns the catalogue", "Data stewards — maintain entries", "Data engineering — emits lineage"],
    tools: [
      "catalogue coverage report: catalogued datasets vs discovered stores (the shadow-data gap)",
      "trace lineage for a regulatory dataset end-to-end: source → ETL → report",
      "Purview / Collibra scan to discover uncatalogued sources",
      "provenance check on AI-training and regulatory-reporting datasets",
    ],
    finding: "The catalogue covers the warehouse but misses dozens of shadow databases and extracts; a key regulatory report has no lineage, so when a figure was wrong no one could trace it to source — and the same gap means a breach's blast radius can't be scoped.",
    refs: [["DAMA-DMBOK Data Management", "https://www.dama.org/"], ["NIST SP 800-53 — Data Governance (PM/PT)", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"]],
  },
  "dpp-09": {
    artifacts: [
      "Database/data-store activity-monitoring (DAM) configuration — what access/queries are logged on sensitive stores",
      "Access-anomaly detection on data (unusual volume, off-hours, new principal → sensitive table)",
      "Coverage: sensitive data stores under monitoring vs total",
      "Privileged/DBA access-to-data logging + independent review evidence",
    ],
    test: "Verify access to sensitive data is monitored and anomalies are detected. PASS: database activity monitoring logs access to sensitive stores (who ran what query against which sensitive table, when); privileged/DBA access to data is logged and independently reviewed; anomaly detection flags abnormal access (bulk reads, off-hours, first-time principal → sensitive data); and coverage spans the sensitive estate. Exceptions: sensitive databases with no activity monitoring, DBA access to PII unlogged or self-reviewed, no anomaly detection (a mass export looks normal), and monitoring gaps on cloud data stores.",
    systems: ["DAM — Imperva / IBM Guardium / native (SQL Audit, RDS/Redshift logging)", "SIEM / UEBA for anomaly detection", "The sensitive databases / warehouses / object stores"],
    owners: ["Security operations / data security — own monitoring", "DBAs — emit logs (but don't self-audit)", "Data owners"],
    tools: [
      "Guardium/Imperva or native DB audit: which sensitive stores are monitored vs total",
      "UEBA anomaly rules: bulk reads, off-hours access, first-time access to a sensitive table",
      "review DBA/privileged access-to-data logs — captured AND independently reviewed?",
      "cloud: S3 access logging / CloudTrail data events enabled on sensitive buckets",
    ],
    finding: "Production databases holding PII have no activity monitoring, DBAs query customer data freely with no log or review, and S3 data-event logging is off — so a bulk export of the customer table would leave no trace.",
    refs: [["NIST SP 800-53 AU / AC families", "https://csrc.nist.gov/projects/risk-management/sp800-53-controls"], ["PCI DSS Req. 10", "https://www.pcisecuritystandards.org/"]],
  },
  "dpp-10": {
    artifacts: [
      "The inventory of long-lived sensitive data and the confidentiality lifetime each requires",
      "The cryptography protecting that data at rest + in transit (algorithm, key size) — the data-centric CBOM",
      "The harvest-now-decrypt-later (HNDL) exposure assessment",
      "The migration plan to post-quantum cryptography + crypto-agility for data-protection crypto",
    ],
    test: "Assess whether long-lived sensitive data is protected against future quantum decryption. PASS: long-secret data is identified with its required confidentiality lifetime; the crypto protecting it is inventoried; HNDL exposure is scored (data that must stay secret beyond ~2030 and traverses interceptable channels or sits in capturable stores); and a PQC migration plan (NIST FIPS 203/204, hybrid) with crypto-agility exists. Exceptions: long-retention sensitive data protected only by classical RSA/ECC, no HNDL assessment, data-protection crypto that can't be swapped without re-architecture, and no migration timeline.",
    systems: ["Data inventory + retention schedule", "Crypto inventory / CBOM (Venafi/Keyfactor) for data-at-rest + in-transit", "KMS/HSM", "PQC migration tooling"],
    owners: ["Cryptography/PKI + Privacy — own data-protection crypto", "Enterprise architecture — owns crypto-agility", "Data owners — know the retention/secrecy lifetime"],
    tools: [
      "join the retention schedule to data sensitivity → list data needing secrecy beyond ~2030",
      "build a CBOM for data-at-rest (DB/volume/object encryption) + in-transit algorithms",
      "score HNDL: long-secret data on interceptable links or in capturable stores",
      "plan: map current algorithms to NIST PQC (ML-KEM / ML-DSA) + hybrid, with crypto-agility",
    ],
    finding: "Decades-retention health and financial records are protected only by classical RSA/ECC and traverse links an adversary could record today; there is no HNDL assessment and no PQC migration plan, so this data is already at risk.",
    refs: [["NIST FIPS 203/204/205 (PQC)", "https://csrc.nist.gov/projects/post-quantum-cryptography"], ["NIST SP 1800-38 PQC Migration", "https://www.nccoe.nist.gov/crypto-agility-considerations-migrating-post-quantum-cryptographic-algorithms"]],
  },
};
