// Registry for the gated Advanced Audit track — deliberately SEPARATE from the
// main `stages.ts` barrel + stages-meta, so these modules stay off to the side
// (not in the public learner catalog, counts, or validators). Domain epochs are
// generated by scripts/gen-audit-track.mjs; Application Review module 01 is the
// hand-authored exemplar in audit-application-review.ts.
import type { EpochConfig, StageConfig } from "./types";
import { auditApplicationReviewEpoch, auditApplicationReviewStages } from "./audit-application-review";
import { applicationReviewStages } from "./audit-generated/application-review";
import { buildCicdEpoch, buildCicdStages } from "./audit-generated/build-cicd";
import { repositoryMgmtEpoch, repositoryMgmtStages } from "./audit-generated/repository-mgmt";
import { cryptoSecretsEpoch, cryptoSecretsStages } from "./audit-generated/crypto-secrets";
import { secureSdlcEpoch, secureSdlcStages } from "./audit-generated/secure-sdlc";
import { iacEpoch, iacStages } from "./audit-generated/iac";
import { cloudSaasEpoch, cloudSaasStages } from "./audit-generated/cloud-saas";
import { vulnPatchEpoch, vulnPatchStages } from "./audit-generated/vuln-patch";
import { dataPrivacyEpoch, dataPrivacyStages } from "./audit-generated/data-privacy";
import { datacenterEpoch, datacenterStages } from "./audit-generated/datacenter";
import { endpointEpoch, endpointStages } from "./audit-generated/endpoint";
import { networkSecurityEpoch, networkSecurityStages } from "./audit-generated/network-security";
import { iamEpoch, iamStages } from "./audit-generated/iam";
import { changeReleaseEpoch, changeReleaseStages } from "./audit-generated/change-release";
import { sysimplEnterpriseEpoch, sysimplEnterpriseStages } from "./audit-generated/sysimpl-enterprise";
import { sysimplFunctionalEpoch, sysimplFunctionalStages } from "./audit-generated/sysimpl-functional";
import { sysimplAiEpoch, sysimplAiStages } from "./audit-generated/sysimpl-ai";
import { thirdPartyEpoch, thirdPartyStages } from "./audit-generated/third-party";
import { resiliencyEpoch, resiliencyStages } from "./audit-generated/resiliency";
import { incidentMgmtEpoch, incidentMgmtStages } from "./audit-generated/incident-mgmt";
import { itGovernanceEpoch, itGovernanceStages } from "./audit-generated/it-governance";
import { rpaGovernanceEpoch, rpaGovernanceStages } from "./audit-generated/rpa-governance";
import { aiAuditEpoch, aiAuditStages } from "./audit-generated/ai-audit";
import { iotEpoch, iotStages } from "./audit-generated/iot";
import { icsEpoch, icsStages } from "./audit-generated/ics";
import { pqcReadinessEpoch, pqcReadinessStages } from "./audit-generated/pqc-readiness";
import { dataLakesEpoch, dataLakesStages } from "./audit-generated/data-lakes";

export const auditEpochs: EpochConfig[] = [
  auditApplicationReviewEpoch,
  buildCicdEpoch,
  repositoryMgmtEpoch,
  cryptoSecretsEpoch,
  secureSdlcEpoch,
  iacEpoch,
  cloudSaasEpoch,
  vulnPatchEpoch,
  dataPrivacyEpoch,
  datacenterEpoch,
  endpointEpoch,
  networkSecurityEpoch,
  iamEpoch,
  changeReleaseEpoch,
  sysimplEnterpriseEpoch,
  sysimplFunctionalEpoch,
  sysimplAiEpoch,
  thirdPartyEpoch,
  resiliencyEpoch,
  incidentMgmtEpoch,
  itGovernanceEpoch,
  rpaGovernanceEpoch,
  aiAuditEpoch,
  iotEpoch,
  icsEpoch,
  pqcReadinessEpoch,
  dataLakesEpoch,
];

export const auditStages: StageConfig[] = [
  ...auditApplicationReviewStages,
  ...applicationReviewStages,
  ...buildCicdStages,
  ...repositoryMgmtStages,
  ...cryptoSecretsStages,
  ...secureSdlcStages,
  ...iacStages,
  ...cloudSaasStages,
  ...vulnPatchStages,
  ...dataPrivacyStages,
  ...datacenterStages,
  ...endpointStages,
  ...networkSecurityStages,
  ...iamStages,
  ...changeReleaseStages,
  ...sysimplEnterpriseStages,
  ...sysimplFunctionalStages,
  ...sysimplAiStages,
  ...thirdPartyStages,
  ...resiliencyStages,
  ...incidentMgmtStages,
  ...itGovernanceStages,
  ...rpaGovernanceStages,
  ...aiAuditStages,
  ...iotStages,
  ...icsStages,
  ...pqcReadinessStages,
  ...dataLakesStages,
].map((s, i, all) => s); // rank assigned below

// Rank every module across the whole track by easeScore + valueScore.
const _ranked = [...auditStages].sort(
  (a, b) => ((b.easeScore ?? 0) + (b.valueScore ?? 0)) - ((a.easeScore ?? 0) + (a.valueScore ?? 0)),
);
_ranked.forEach((s, i) => { s.rank = i + 1; });

export function auditStagesForEpoch(epochId: string): StageConfig[] {
  return auditStages.filter((s) => s.epochId === epochId).sort((a, b) => a.order - b.order);
}
export function getAuditEpoch(epochId: string): EpochConfig | undefined {
  return auditEpochs.find((e) => e.id === epochId);
}
export function getAuditStage(id: string): StageConfig | undefined {
  return auditStages.find((s) => s.id === id);
}
export function auditRanked(): StageConfig[] {
  return [...auditStages].sort(
    (a, b) => ((b.easeScore ?? 0) + (b.valueScore ?? 0)) - ((a.easeScore ?? 0) + (a.valueScore ?? 0)),
  );
}
