// AUTO-GENERATED by scripts/gen-audit-track.mjs — client-safe Advanced Audit epoch
// list (id / name / emoji only, no stage content). Safe to import into client bundles.
export const auditEpochsMeta: { id: string; name: string; emoji: string }[] = [
  {
    "id": "application-review",
    "name": "Application Review",
    "emoji": "🔎"
  },
  {
    "id": "build-cicd",
    "name": "Build Environment & CI/CD (Continuous Integration / Continuous Delivery)",
    "emoji": "🏗️"
  },
  {
    "id": "repository-mgmt",
    "name": "Repository Management",
    "emoji": "🗂️"
  },
  {
    "id": "crypto-secrets",
    "name": "Cryptographic Key & Secrets Management",
    "emoji": "🔐"
  },
  {
    "id": "secure-sdlc",
    "name": "Secure Software Development",
    "emoji": "🛡️"
  },
  {
    "id": "iac",
    "name": "Infrastructure as Code (IaC)",
    "emoji": "📜"
  },
  {
    "id": "cloud-saas",
    "name": "Cloud Platform & SaaS (Software-as-a-Service)",
    "emoji": "☁️"
  },
  {
    "id": "vuln-patch",
    "name": "Vulnerability & Patch Management",
    "emoji": "🩹"
  },
  {
    "id": "data-privacy",
    "name": "Data Protection & Privacy",
    "emoji": "🔏"
  },
  {
    "id": "datacenter",
    "name": "Datacenter / Lab / Colocation (CoLo)",
    "emoji": "🏢"
  },
  {
    "id": "endpoint",
    "name": "Endpoint Devices",
    "emoji": "💻"
  },
  {
    "id": "network-security",
    "name": "Network Security",
    "emoji": "🌐"
  },
  {
    "id": "iam",
    "name": "Identity & Access Management (IAM)",
    "emoji": "🪪"
  },
  {
    "id": "change-release",
    "name": "Change, Release & Configuration Management",
    "emoji": "🔁"
  },
  {
    "id": "sysimpl-enterprise",
    "name": "System Implementation — Enterprise",
    "emoji": "🏛️"
  },
  {
    "id": "sysimpl-functional",
    "name": "System Implementation — Functional",
    "emoji": "🧩"
  },
  {
    "id": "sysimpl-ai",
    "name": "System Implementation — AI (Artificial Intelligence)",
    "emoji": "🤖"
  },
  {
    "id": "third-party",
    "name": "Third Party Systems",
    "emoji": "🔗"
  },
  {
    "id": "resiliency",
    "name": "Resiliency & Redundancy",
    "emoji": "♻️"
  },
  {
    "id": "incident-mgmt",
    "name": "Incident Management",
    "emoji": "🚨"
  },
  {
    "id": "it-governance",
    "name": "Information Technology (IT) Governance",
    "emoji": "📋"
  },
  {
    "id": "rpa-governance",
    "name": "Robotic Process Automation (RPA) Governance",
    "emoji": "⚙️"
  },
  {
    "id": "ai-audit",
    "name": "Artificial Intelligence (AI)",
    "emoji": "🧠"
  },
  {
    "id": "iot",
    "name": "Internet of Things (IoT)",
    "emoji": "📡"
  },
  {
    "id": "ics",
    "name": "Industrial Control Systems (ICS)",
    "emoji": "🏭"
  },
  {
    "id": "pqc-readiness",
    "name": "Post-Quantum Readiness",
    "emoji": "🧮"
  },
  {
    "id": "data-lakes",
    "name": "Data Lakes & Warehouses",
    "emoji": "🗄️"
  }
];
