import type { ScenarioConfig } from "./types";

// "Read the Play" Decision-Trainer scenarios for the Situational Team Defense
// epoch. Each spot is a deterministic, skill-based defensive decision — the
// correct line is the fundamentally sound team-defense play for the exact
// situation, never a coin-flip outcome. correctIndex and explanation are
// stripped server-side before reaching the client.
export const baseball16Scenarios: Record<string, ScenarioConfig> = {
  "baseball-16-01": {
    intro: "Cutoffs and relays are how a defense turns the whole field into one connected machine. Know who lines up where, who you back up, and who's listening for the call to cut it.",
    spots: [
      {
        id: "bb16-01-s1", label: "Cutoff to the Plate",
        situation: "1 out, 4th inning, runner on second. A clean single is lined to right field and the runner rounds third trying to score. The right fielder comes up throwing toward home.",
        prompt: "Which infielder is the cutoff man for the throw to the plate?",
        options: [
          "The shortstop",
          "The first baseman, lining up between the right fielder and home",
          "The third baseman, standing on the bag",
          "The second baseman trailing the play",
        ],
        correctIndex: 1,
        explanation: "On an outfield throw to home, the first baseman is the cutoff man — he sprints in front of the mound and lines up between the outfielder and the plate so he can cut and redirect an offline throw or hold a trail runner. The third baseman stays home to cover third.",
      },
      {
        id: "bb16-01-s2", label: "Cutoff to Third",
        situation: "No outs, runner on first. A ball splits the gap in left-center for a double and the lead runner is digging for third base. The throw is coming toward third.",
        prompt: "Who is the cutoff man for the throw going to third base?",
        options: [
          "The shortstop, lining up in front of third for the throw",
          "The first baseman",
          "The catcher",
          "The pitcher",
        ],
        correctIndex: 0,
        explanation: "The shortstop cuts throws headed to third base, lining up between the outfielder and the bag; the third baseman stays at the base to take the throw and apply the tag. (On throws to the plate it flips: the first baseman cuts, the catcher receives.)",
      },
      {
        id: "bb16-01-s3", label: "The Relay Man",
        situation: "No outs, batter drives a ball to the wall in the right-center gap. The center fielder runs it down deep, and the batter is trying to stretch it into a triple. It's too far for one throw to reach the infield.",
        prompt: "Who goes out as the relay man?",
        options: [
          "The third baseman",
          "The shortstop",
          "The second baseman, sprinting toward the outfielder to take the relay",
          "The pitcher",
        ],
        correctIndex: 2,
        explanation: "On deep balls to the right side and right-center, the second baseman is the relay man (the shortstop relays balls to the left side and left-center). He sprints out, lines up between the outfielder and the target base, gives a target, and catches-turns-throws in one motion.",
      },
      {
        id: "bb16-01-s4", label: "Listen for the Call",
        situation: "You're the cutoff man, lined up with the throw coming in from the outfield. A teammate near the target base can see the whole play and the trail runner.",
        prompt: "How do you decide whether to cut the throw or let it go through?",
        options: [
          "Always cut every throw to be safe",
          "Always let every throw go through untouched",
          "Listen for the loud verbal command — 'cut' and a base, or 'let it go' — from the teammate who can see the play, and react instantly",
          "Decide on your own without listening to anyone",
        ],
        correctIndex: 2,
        explanation: "The cutoff man reacts to the receiver's voice: 'cut two,' 'cut home,' 'cut and hold,' or silence/'let it go' if the throw is true and no trail runner is advancing. The fielder at the base sees the whole field, so the cutoff man's job is to be lined up and listening.",
      },
      {
        id: "bb16-01-s5", label: "Why Line It Up",
        situation: "A coach asks why the cutoff man must line up directly between the outfielder and the base, even when a throw looks like it'll be a strike.",
        prompt: "What's the main purpose of a properly lined-up cutoff man?",
        options: [
          "To catch an offline throw, redirect to another base, or hold the trail runner from advancing",
          "Only to slow the throw down",
          "To take a break from fielding",
          "Just to block the runner's view",
        ],
        correctIndex: 0,
        explanation: "A lined-up cutoff man gives the defense options: he can cut an offline throw and save a run, redirect to nail a trail runner taking an extra base, or hold runners. A straight line means he can cut without the ball ever leaving the throwing lane.",
      },
    ],
  },

  "baseball-16-02": {
    intro: "Bunt defense is a choreographed scramble — corners charge, the middle infielders rotate to cover the vacated bags, and someone has to get the sure out. Know your job before the bunt is down.",
    spots: [
      {
        id: "bb16-02-s1", label: "Who Covers First",
        situation: "Runner on first, no outs, a clear sacrifice-bunt situation. The pitch is delivered and the first baseman charges hard toward the plate to field the bunt.",
        prompt: "With the first baseman charging, who covers first base for the throw?",
        options: [
          "The catcher",
          "The second baseman, breaking over to cover first",
          "Nobody — leave it uncovered",
          "The shortstop",
        ],
        correctIndex: 1,
        explanation: "When the first baseman charges to field the bunt, the second baseman breaks to cover first base for the throw. The shortstop covers second. This rotation is the foundation of sacrifice-bunt defense — everyone moves the instant the bunt shows.",
      },
      {
        id: "bb16-02-s2", label: "Take the Sure Out",
        situation: "Runner on first, no outs. The batter pushes a bunt softly but a step too firmly toward the charging third baseman. By the time he fields it, the lead runner is nearly to second.",
        prompt: "Where should the third baseman throw?",
        options: [
          "Force the throw to second to get the lead runner",
          "Take the sure out at first base rather than risk an all-or-nothing throw to second",
          "Hold the ball and get nobody",
          "Throw to third base",
        ],
        correctIndex: 1,
        explanation: "When in doubt on a bunt, get the sure out at first. Forcing a low-percentage throw to beat a runner who's nearly safe risks throwing it away and giving up extra bases — the cardinal sin on a bunt. Take the out you're certain of.",
      },
      {
        id: "bb16-02-s3", label: "The Wheel Play",
        situation: "Runners on first and second, no outs, and you read a sacrifice bunt coming to move both runners up. The defense runs the aggressive 'wheel' to try to nail the lead runner at third.",
        prompt: "On the wheel play, who covers third base?",
        options: [
          "The third baseman stays home at the bag",
          "The shortstop rotates over to cover third while the third baseman charges",
          "The left fielder",
          "Nobody covers third",
        ],
        correctIndex: 1,
        explanation: "On the wheel, the third baseman crashes to field the bunt, so the shortstop spins and covers third to take the throw and force out the lead runner. The second baseman covers first. It's the highest-risk, highest-reward bunt defense — if the bunt is good, you still have the out at first.",
      },
      {
        id: "bb16-02-s4", label: "Read the Squeeze",
        situation: "Runner on third, one out, late and close. Before the pitch, the runner is creeping and you suspect a suicide squeeze — the runner will break for home with the pitch and the batter will bunt no matter what.",
        prompt: "What's the best defense if you read the squeeze before the pitch?",
        options: [
          "Throw a normal strike and hope for the best",
          "Pitch out — throw high and to the side so the batter can't bunt it and the catcher can tag the runner coming home",
          "Intentionally walk the batter",
          "Have everyone charge and ignore the runner",
        ],
        correctIndex: 1,
        explanation: "Against a read suicide squeeze, the pitcher throws a pitchout — high and outside, away from the bat — so the batter can't get the bunt down and the catcher has the ball waiting to tag the runner breaking from third. Reading it before the pitch is the only reliable way to beat a suicide squeeze.",
      },
      {
        id: "bb16-02-s5", label: "Field It Right",
        situation: "A sacrifice bunt rolls dead in the grass between the mound and the third-base line. The pitcher and third baseman both converge; the ball has stopped.",
        prompt: "What's the fundamentally sound way to field and throw it?",
        options: [
          "Kick it toward first to save time",
          "Field it with the bare hand off the side, then throw across the body",
          "Circle the ball, field it moving toward your target with feet aligned, and throw from a balanced base",
          "Slide on the ground and flip it blindly",
        ],
        correctIndex: 2,
        explanation: "The fielder circles the bunt so he's moving toward the target as he fields it, with his feet already lined up to throw from a balanced base. That footwork turns the field-and-throw into one motion and prevents the off-balance, across-the-body throw that sails into right field.",
      },
    ],
  },

  "baseball-16-03": {
    intro: "First-and-third is the trickiest defensive puzzle in the game: stop the steal at second without letting the run trot home from third. It's about reading the runner on third before you commit.",
    spots: [
      {
        id: "bb16-03-s1", label: "The Basic Threat",
        situation: "Runners on first and third, one out. The runner on first takes off to steal second. The catcher has the ball and must decide what to do without letting the run score from third.",
        prompt: "What's the heart of the defensive problem here?",
        options: [
          "If the catcher throws through to second, the runner on third may break for home and score",
          "There is no risk — just throw to second every time",
          "The runner on third can never score on this play",
          "The catcher should always throw to third",
        ],
        correctIndex: 0,
        explanation: "The entire first-and-third problem is the trade-off: a throw through to second to nail the stealer leaves home unguarded, so the runner on third can break and score. Every first-and-third defense is built to get an out without surrendering that run.",
      },
      {
        id: "bb16-03-s2", label: "The Cut Play",
        situation: "Runners on first and third. The runner steals second and the catcher fires toward second base. You're the middle infielder who can intercept the throw in front of the bag.",
        prompt: "What's the read once you're set up to cut the throw?",
        options: [
          "Always let it go to second no matter what",
          "Watch the runner on third — if he breaks for home, cut the throw and fire home; if he holds, let it continue to second for the tag",
          "Always cut it and throw to third",
          "Always fake everything and hold the ball",
        ],
        correctIndex: 1,
        explanation: "The classic counter is a cut play: a middle infielder slips in front of second to read the runner on third. If that runner breaks home, the fielder cuts the throw and throws home to get him; if he holds, the ball carries through to second for the tag. The runner on third dictates the play.",
      },
      {
        id: "bb16-03-s3", label: "Look the Runner Back",
        situation: "Runners on first and third, the runner on first breaks for second, and the catcher pump-fakes. The runner on third has taken a big, aggressive secondary lead off the bag.",
        prompt: "What's the catcher's safest aggressive option here?",
        options: [
          "Throw blindly to second and ignore third",
          "Step toward second to freeze and look the runner back to third, then make the safe throw — or snap a throw to third if the runner is hung out",
          "Always throw home",
          "Roll the ball back to the pitcher",
        ],
        correctIndex: 1,
        explanation: "A disciplined catcher uses footwork to look the runner on third back before committing — freezing him with eyes and a step — and will snap a throw to third (or to the bag behind a hung-out runner) if he strays too far. Controlling the lead runner is more important than chasing the steal.",
      },
      {
        id: "bb16-03-s4", label: "Concede the Steal",
        situation: "Big lead late in the game, runners on first and third. The runner on first breaks for second. Giving up second base is meaningless, but a run scoring from third matters.",
        prompt: "What's the right priority?",
        options: [
          "Gun it to second to stop a meaningless steal",
          "Concede second base — hold the ball or throw to a cut — and keep the runner on third from scoring",
          "Throw the ball to the outfield",
          "Walk off the field",
        ],
        correctIndex: 1,
        explanation: "With a comfortable lead, the trail runner advancing to second is irrelevant; the only run that matters is the one on third. The defense concedes the steal and keeps everyone home, rather than open a throwing lane that lets the run score. Situation dictates aggression.",
      },
      {
        id: "bb16-03-s5", label: "The Pitcher's Cut",
        situation: "Runners on first and third. The team has called a play where, on the steal, the pitcher cuts the catcher's throw if needed. The runner on first breaks.",
        prompt: "What does the pitcher do on this designed play?",
        options: [
          "Duck out of the way and ignore the throw",
          "Read the runner on third — let the throw go to second if he holds, or step up and cut it to throw home if he breaks",
          "Always cut the ball and throw to first",
          "Run toward second base himself",
        ],
        correctIndex: 1,
        explanation: "On the pitcher-cut variation, the pitcher acts as the in-line interceptor: he reads the runner on third and either lets the catcher's throw continue to second or cuts it and throws home to catch the breaking runner. It puts the read closer to the plate for a faster reaction.",
      },
    ],
  },

  "baseball-16-04": {
    intro: "A rundown should be a guaranteed out. The keys are simple and unforgiving: drive the runner back toward the lower base, use as few throws as possible, and clear out of the way after you throw.",
    spots: [
      {
        id: "bb16-04-s1", label: "Which Way to Drive",
        situation: "A runner is hung up between first and second base in a rundown. You take the ball and start running at him.",
        prompt: "Which direction should you drive the runner?",
        options: [
          "Back toward first base, the lower base",
          "Toward second base, the higher base",
          "It doesn't matter which way",
          "Toward home plate",
        ],
        correctIndex: 0,
        explanation: "Always run the runner back toward the base he came from — the lower base. That way, if he somehow gets back safely, he's gained nothing; if you drove him toward second and he were safe, you'd have handed him 90 feet. In a pickle, you give up no ground.",
      },
      {
        id: "bb16-04-s2", label: "Minimize Throws",
        situation: "You've got a runner in a rundown and you're closing the distance on him with the ball.",
        prompt: "How many throws should a well-executed rundown ideally take?",
        options: [
          "As many quick throws back and forth as possible to confuse him",
          "Exactly three throws every time",
          "As few as possible — ideally one — run hard to close the gap and throw only when he's committed",
          "Five or more to tire the runner out",
        ],
        correctIndex: 2,
        explanation: "Every throw is a chance for an error. The proper rundown is run hard at the runner to force him to commit, then deliver a single firm throw to the fielder waiting at the base for the tag. Fewer throws, fewer mistakes — ideally just one.",
      },
      {
        id: "bb16-04-s3", label: "After You Throw",
        situation: "You've run at the runner and just made your throw to the fielder covering the base ahead of him. The play may not end on this tag.",
        prompt: "What do you do immediately after releasing the throw?",
        options: [
          "Stand still and watch",
          "Peel off out of the baseline and circle back to back up the base behind the play",
          "Run directly at the fielder you threw to",
          "Argue with the umpire",
        ],
        correctIndex: 1,
        explanation: "After you throw, you peel off to the side and follow your throw to back up the next base, getting out of the runner's path so you can't be called for interference. The defense rotates: thrower-to-the-back-of-the-line keeps a fielder ready at every base.",
      },
      {
        id: "bb16-04-s4", label: "Don't Fake It",
        situation: "You're chasing the runner in the pickle and you're tempted to pump-fake to freeze him before throwing.",
        prompt: "Why is pump-faking discouraged in a rundown?",
        options: [
          "Fakes are against the rules",
          "Fakes waste time, can confuse your own teammate, and turn a sure out into a dropped ball or a hit batter",
          "Fakes always work, so use them",
          "Faking makes the runner faster",
        ],
        correctIndex: 1,
        explanation: "Pump-fakes cause the receiving fielder to break early or hesitate, leading to bad exchanges and errors. The clean method is run hard, make the runner commit, and deliver one true throw. Show the ball up and ready, don't fake.",
      },
      {
        id: "bb16-04-s5", label: "Between Third and Home",
        situation: "A runner is caught in a rundown between third base and home plate with the game close.",
        prompt: "Which way do you drive this runner?",
        options: [
          "Toward home, to get the play over with quickly",
          "Back toward third base — never run a runner toward the plate and risk handing him the run",
          "Let him score to save effort",
          "Toward first base",
        ],
        correctIndex: 1,
        explanation: "Even though the principle is 'toward the lower base,' it matters most here: drive him back toward third, never toward home. Running him at the plate risks a collision, a dropped ball, or simply gifting the run. The lower base is third, so back he goes.",
      },
    ],
  },

  "baseball-16-05": {
    intro: "Turning two is the defense's best friend. It starts before the pitch with double-play depth, and it lives or dies on the feed, the footwork at the bag, and a quick, clean release.",
    spots: [
      {
        id: "bb16-05-s1", label: "Double-Play Depth",
        situation: "Runner on first, one out, ground-ball pitcher working. The middle infielders set up before the pitch hoping to turn two.",
        prompt: "How should the shortstop and second baseman position themselves?",
        options: [
          "As deep as possible for maximum range",
          "A step or two in and toward second base — double-play depth — to shorten the distance to the bag",
          "Standing on second base",
          "In shallow outfield grass",
        ],
        correctIndex: 1,
        explanation: "Double-play depth means moving in a couple steps and toward second so the pivot man can reach the bag in time to take the feed and relay. It trades a little range for the time needed to turn two — the right call with a runner on first and a double play in order.",
      },
      {
        id: "bb16-05-s2", label: "The 6-4-3",
        situation: "Runner on first, one out. A ground ball is hit right to the shortstop. He needs to start the double play.",
        prompt: "How does the 6-4-3 unfold?",
        options: [
          "Shortstop fields and tags the runner himself",
          "Shortstop feeds the second baseman covering second for the force, who relays to first",
          "Shortstop throws straight to first and ignores second",
          "Shortstop throws home",
        ],
        correctIndex: 1,
        explanation: "In a 6-4-3, the shortstop (6) fields and feeds the second baseman (4) covering the bag for the force at second, who pivots and throws to first (3) to complete the double play. The force at second means the pivot man only needs to touch the bag — no tag required.",
      },
      {
        id: "bb16-05-s3", label: "Force, Not Tag",
        situation: "The pivot man catches the feed at second base with the runner from first bearing down, and there are fewer than two outs.",
        prompt: "Does the pivot man need to tag the sliding runner to record the out at second?",
        options: [
          "Yes, he must tag the runner every time",
          "No — with a runner forced from first, he only needs to touch second base before the runner arrives",
          "Only if the runner slides",
          "He must tag the base and the runner",
        ],
        correctIndex: 1,
        explanation: "Because the batter forced the runner on first to advance, the play at second is a force out — touching the bag with possession retires the runner, no tag needed. That's what makes the quick touch-and-relay possible and keeps the pivot man safe from the slide.",
      },
      {
        id: "bb16-05-s4", label: "3-6-1 Coverage",
        situation: "Runner on first, one out. A ground ball is hit sharply to the first baseman, who is near the bag. He throws to second to start the double play.",
        prompt: "After the first baseman throws to second, who covers first for the return throw?",
        options: [
          "The catcher",
          "The second baseman",
          "The pitcher, breaking to cover first",
          "Nobody — the runner is already out",
        ],
        correctIndex: 2,
        explanation: "On a 3-6-3 (or 3-6-1), the first baseman throws to the shortstop covering second, then races back toward the bag — but if he can't get there, the pitcher must break to cover first for the return throw, making it a 3-6-1. The pitcher covering first is a core fundamental.",
      },
      {
        id: "bb16-05-s5", label: "A Turnable Feed",
        situation: "A ground ball comes to the shortstop a few steps from second base with a double play on. He's deciding how to deliver the ball to the second baseman.",
        prompt: "What makes a good double-play feed?",
        options: [
          "The hardest possible throw every time",
          "A bounced throw to slow it down",
          "A catchable, chest-high feed delivered by distance — underhand when close, firmer throw from deep — that leads the pivot man to the bag",
          "A throw that pulls the pivot man into the runner's path",
        ],
        correctIndex: 2,
        explanation: "A good feed is chosen by distance — soft underhand toss when close, a quick backhand flip a few steps away, a firm throw from deep — and is delivered chest-high and catchable, leading the pivot man to the bag without dragging him into the runner. A turnable feed is what lets the relay flow.",
      },
    ],
  },

  "baseball-16-06": {
    intro: "Infield in, halfway, or back? The right depth depends entirely on the inning, the score, and the outs — and getting it wrong either gives up the game or gives up a rally. Decide before the pitch.",
    spots: [
      {
        id: "bb16-06-s1", label: "Infield In",
        situation: "Bottom of the 9th, tie game, runner on third, fewer than two outs. A ground ball anywhere on the infield could end the game.",
        prompt: "How should the infield play?",
        options: [
          "Play back at normal depth and take the out at first",
          "Play in — drawn up on the grass — to field a grounder and throw home to cut the winning run down at the plate",
          "Play deep to prevent a double",
          "Shift everyone to one side",
        ],
        correctIndex: 1,
        explanation: "With the winning run on third and fewer than two outs in a tie game late, the infield draws in to throw home and cut the run off at the plate. A normal-depth out at first would let the run score and lose the game — so you concede range to protect the plate.",
      },
      {
        id: "bb16-06-s2", label: "Play Back",
        situation: "Top of the 2nd inning, runner on third, one out, in a scoreless game. A ground ball is hit to the shortstop.",
        prompt: "What's the correct depth and play this early?",
        options: [
          "Infield in to save the one run at the plate",
          "Play at normal depth — concede the single run, take the sure out at first, and keep the inning moving",
          "Everyone charges the plate",
          "Intentionally boot the ball",
        ],
        correctIndex: 1,
        explanation: "One run in the 2nd inning isn't worth giving up extra hits all game. The infield plays back, concedes the run scoring from third, and takes the reliable out at first. Bringing the infield in early raises the batting average against you for a run that barely matters.",
      },
      {
        id: "bb16-06-s3", label: "Halfway",
        situation: "Middle innings, one-run game, runner on third with one out. The coach sets the infield 'halfway' — neither all the way in nor at normal depth.",
        prompt: "What does playing halfway let the infielders do?",
        options: [
          "Only ever throw to first",
          "Read each ball — come home on a slow roller or a ball hit right at them, but take the out at first if it's hit hard or to the side",
          "Always throw home no matter what",
          "Ignore the runner entirely",
        ],
        correctIndex: 1,
        explanation: "Halfway depth is a compromise: it gives the fielder a beat to read the ball. On a slow roller or one hit right at him he can still get the runner at home; on a hard-hit ball or one he has to range for, he concedes the run and takes the out at first. It balances run prevention against outs.",
      },
      {
        id: "bb16-06-s4", label: "The Cost of In",
        situation: "A coach explains the downside of bringing the infield in to cut off a run at the plate.",
        prompt: "What does playing the infield in cost the defense?",
        options: [
          "Nothing — it's always the best choice",
          "It shrinks the infielders' range, so more ground balls sneak through for hits",
          "It makes throws to first impossible",
          "It only helps the offense bunt",
        ],
        correctIndex: 1,
        explanation: "Drawn-in infielders cover far less ground, so balls that would normally be routine outs scoot through for hits — studies put the batting average against a drawn-in infield much higher. That's why you only pay that price when a single run is decisive late in the game.",
      },
      {
        id: "bb16-06-s5", label: "Look Him Back",
        situation: "Runner on second, one out, infield playing at normal depth. A ground ball is hit to the shortstop's left, in front of the runner.",
        prompt: "What's the disciplined play?",
        options: [
          "Throw home immediately",
          "Glance the runner back toward second to freeze him, then take the sure out at first",
          "Hold the ball and get nobody",
          "Chase the runner toward third",
        ],
        correctIndex: 1,
        explanation: "With a runner on second and a ball hit in front of him, the infielder looks the runner back to keep him from advancing to third, then throws to first for the out. You don't sail a throw home from normal depth — you control the lead runner and bank the certain out.",
      },
    ],
  },

  "baseball-16-07": {
    intro: "Pop-ups and fly balls are won with voices, not just gloves. The priority order is fixed — easier catches and the center of the field win — and the whole defense has to talk, loudly and early.",
    spots: [
      {
        id: "bb16-07-s1", label: "Outfielder's Priority",
        situation: "A short fly ball drifts into shallow left field, splitting the difference between the shortstop ranging back and the left fielder charging in. Both could reach it.",
        prompt: "Who should take the ball?",
        options: [
          "The left fielder — an outfielder coming in has priority over an infielder going back",
          "The shortstop, going back over his head",
          "Whoever yells first, regardless of position",
          "The third baseman",
        ],
        correctIndex: 0,
        explanation: "On a ball between an infielder and an outfielder, the outfielder has priority because catching it coming forward is far easier and safer than an infielder catching it going back over his head. The left fielder calls off the shortstop and makes the play moving toward the infield.",
      },
      {
        id: "bb16-07-s2", label: "Center Field Is King",
        situation: "A fly ball carries into right-center field. Both the center fielder and the right fielder converge on it and either can make the catch.",
        prompt: "Who has priority?",
        options: [
          "The right fielder",
          "The center fielder — he is the captain of the outfield and has priority over both corner outfielders",
          "Whoever is closer to the line",
          "Neither — let it drop",
        ],
        correctIndex: 1,
        explanation: "The center fielder is the captain of the outfield and has priority over the corner outfielders on any ball he can reach, because he typically has the best speed and angle. When he calls it, the right fielder peels off and backs him up.",
      },
      {
        id: "bb16-07-s3", label: "The Infield Pop",
        situation: "A high pop-up goes straight up near the mound. The pitcher, catcher, first baseman, and shortstop all drift toward it.",
        prompt: "Who should take charge of a high infield pop-up like this?",
        options: [
          "The pitcher",
          "The catcher",
          "A middle infielder (typically the shortstop or second baseman) calls it and takes it; the pitcher gets out of the way",
          "Whoever the first baseman points to",
        ],
        correctIndex: 2,
        explanation: "On infield pop-ups, the middle infielders have the best mobility and read on the spin, so the shortstop or second baseman takes charge and calls everyone else off — and the pitcher always clears out. Letting the pitcher or catcher fight a corner infielder for a twisting pop is how balls drop.",
      },
      {
        id: "bb16-07-s4", label: "Call It Loud",
        situation: "Two fielders are converging on a fly ball at full speed and a collision is possible.",
        prompt: "What's the correct communication?",
        options: [
          "Stay silent so you don't distract each other",
          "The fielder taking it calls loudly and repeatedly — 'I got it! I got it!' — and the other acknowledges 'take it!' and peels off",
          "Both call for it equally",
          "Wave your arms but don't speak",
        ],
        correctIndex: 1,
        explanation: "The fielder who's taking it yells loudly and more than once so there's no doubt, and the other fielder verbally yields — 'take it!' — and gets out of the way. Clear, repeated calls and acknowledgment prevent the scary collisions and the balls that fall between two players.",
      },
      {
        id: "bb16-07-s5", label: "Wind-Blown Drift",
        situation: "A towering pop-up near the foul line starts drifting on the wind. The first baseman called it early, but the ball keeps carrying toward the right fielder coming in hard.",
        prompt: "What should happen as the ball drifts?",
        options: [
          "The first baseman keeps charging blindly to his spot",
          "The outfielder, who has priority and a better angle on the drifting ball, takes over the call and the first baseman yields",
          "Both fielders dive at once",
          "Let it drop in foul territory on purpose",
        ],
        correctIndex: 1,
        explanation: "Priority isn't frozen at the first call — as the ball drifts into the outfielder's territory, the right fielder (with priority and a cleaner angle on a wind-blown ball) takes over the call, and the first baseman yields. The defense re-communicates as the play changes.",
      },
    ],
  },

  "baseball-16-08": {
    intro: "Holding and defending runners keeps the running game honest. It's a partnership between the pitcher's looks and timing, the first baseman's hold, and the middle infielders' proximity to the bag.",
    spots: [
      {
        id: "bb16-08-s1", label: "Holding First",
        situation: "Runner on first base, a base-stealing threat. The pitcher is set to deliver and wants to keep the runner close.",
        prompt: "Who holds the runner on, and what does it cost the defense?",
        options: [
          "The first baseman holds the bag with a foot on it, which opens up the hole between first and second",
          "The second baseman stands on first",
          "Nobody holds — let the runner roam",
          "The shortstop covers first",
        ],
        correctIndex: 0,
        explanation: "The first baseman holds the runner on with a foot on the bag, giving the pitcher a close pickoff target and shortening the runner's lead. The cost is range: holding pulls the first baseman to the bag and opens the 3-4 hole on the right side.",
      },
      {
        id: "bb16-08-s2", label: "Controlling the Run",
        situation: "A fast runner on first is timing the pitcher's delivery, trying to get a jump to steal second.",
        prompt: "How does the pitcher best disrupt the runner's timing?",
        options: [
          "Use the exact same long delivery and hold every time",
          "Vary his hold times and pickoff looks, and use a slide step to the plate to give the catcher a chance to throw him out",
          "Always throw over to first ten times in a row",
          "Ignore the runner completely",
        ],
        correctIndex: 1,
        explanation: "A pitcher controls the running game by being unpredictable — varying how long he holds, mixing in pickoff looks, and using a quick slide step to home so the ball gets to the catcher fast enough to throw the runner out. A predictable delivery lets a fast runner time a clean jump.",
      },
      {
        id: "bb16-08-s3", label: "Runner on Second",
        situation: "A runner is on second base with a sizable secondary lead, reading the defense.",
        prompt: "How do the middle infielders help hold him close?",
        options: [
          "They ignore him and play deep",
          "They shorten his lead by holding him close — varying their proximity to the bag and running a timing/daylight pickoff with the pitcher",
          "The catcher runs out to second",
          "The pitcher faces second the whole time",
        ],
        correctIndex: 1,
        explanation: "With a runner on second, the shortstop and second baseman take turns holding him close, sneaking toward the bag to shorten his lead, and coordinating a timing or daylight pickoff with the pitcher. A runner on second is in scoring position, so limiting his secondary lead matters on a base hit.",
      },
      {
        id: "bb16-08-s4", label: "Off the Bag",
        situation: "Two outs, runner on first, and a comfortable lead. The first baseman is deciding whether to hold the runner on the bag.",
        prompt: "What's the smarter positioning here?",
        options: [
          "Hold the runner tight on the bag as always",
          "Play off the bag at normal depth for better range — with two outs and a lead, a steal of second is far less important than fielding range",
          "Stand in foul territory",
          "Cover second base instead",
        ],
        correctIndex: 1,
        explanation: "Holding a runner isn't automatic. With two outs and a lead, the runner advancing to second is low-stakes, so the first baseman plays off the bag at normal depth to restore his range and close the right-side hole. You hold runners when the steal matters, not reflexively.",
      },
      {
        id: "bb16-08-s5", label: "The Catcher's Throw",
        situation: "A fast runner on first takes off to steal second on the pitch. The catcher receives the ball cleanly.",
        prompt: "What most determines whether the catcher throws him out?",
        options: [
          "How hard he can throw alone",
          "His pop time — quick transfer and footwork plus an accurate throw to the bag — combined with the pitcher giving him a chance",
          "The color of his glove",
          "How loud he yells",
        ],
        correctIndex: 1,
        explanation: "Throwing out a stealer is about pop time: a lightning transfer from glove to hand, clean footwork, and an accurate throw to the bag — all set up by the pitcher delivering quickly enough. Raw arm strength without a fast, clean exchange still arrives late.",
      },
    ],
  },

  "baseball-16-09": {
    intro: "Positioning wins games before the ball is hit — but since 2023 the rules box you in. Know exactly what the shift restrictions require, and how to still tilt the defense toward a hitter's tendencies legally.",
    spots: [
      {
        id: "bb16-09-s1", label: "Two on Each Side",
        situation: "It's a current MLB game and the defense wants to load up against a dead-pull left-handed hitter. A coach reminds everyone of the 2023 infield positioning rules at the moment of the pitch.",
        prompt: "What does the rule require about where the four infielders stand?",
        options: [
          "Two infielders must be positioned on each side of second base when the pitch is released",
          "Three infielders may stack on the pull side",
          "All four must stand on the pull side",
          "Infielders can stand anywhere they like",
        ],
        correctIndex: 0,
        explanation: "The 2023 shift-restriction rule requires two infielders on each side of second base at the moment of the pitch. That single requirement outlaws the old three-to-the-pull-side overload that turned so many hard-hit balls into easy outs.",
      },
      {
        id: "bb16-09-s2", label: "Feet on the Dirt",
        situation: "A team wants to station the second baseman as a 'rover' standing on the shallow outfield grass in short right field against a pull hitter.",
        prompt: "Is that legal under the 2023 rules?",
        options: [
          "Yes, outfield grass is fine",
          "No — all four infielders must have both feet on the infield dirt at the moment of the pitch",
          "Only if the runner is on first",
          "Only in extra innings",
        ],
        correctIndex: 1,
        explanation: "The rule also requires all four infielders to have both feet on the infield dirt when the pitch is released, killing the four-man-outfield / short-right-field rover alignment. An infielder can't park on the grass anymore — he must start on the dirt.",
      },
      {
        id: "bb16-09-s3", label: "The Penalty",
        situation: "At the moment of the pitch, the defense has only one infielder on the left side of second base — an illegal alignment — and the batter then lines a single.",
        prompt: "What's the penalty for the shift violation?",
        options: [
          "The batter is automatically out",
          "The offense is awarded an automatic ball — but may instead decline it and take the result of the play",
          "The pitcher is ejected",
          "Nothing happens",
        ],
        correctIndex: 1,
        explanation: "An illegal shift results in an automatic ball added to the count. But the offense can decline the penalty and take the outcome of the play instead — so here, with a single already in, they'd keep the hit. The penalty never costs the offense the better result.",
      },
      {
        id: "bb16-09-s4", label: "Legal Shading",
        situation: "A right-handed hitter pulls almost everything to the left side. The defense still wants to play the percentages within the 2023 rules.",
        prompt: "What can the defense legally do?",
        options: [
          "Nothing — positioning is now fixed and identical for every hitter",
          "Shade both infielders on the left side toward the line and the middle infielders toward the bag, as long as two stay on each side of second with feet on the dirt",
          "Move three infielders to the left side",
          "Put the shortstop in left field",
        ],
        correctIndex: 1,
        explanation: "Shading is still very much allowed. You can pull the left-side infielders toward the hitter's tendency and creep the middle infielders toward the bag — you just can't cross three to one side or leave the dirt. Smart legal positioning still converts tendencies into outs.",
      },
      {
        id: "bb16-09-s5", label: "No Switching Sides",
        situation: "Against a left-handed pull hitter, a coach wants to move the shortstop over to the right (first-base) side of second base, leaving only the third baseman on the left.",
        prompt: "Is that allowed under the 2023 rules?",
        options: [
          "Yes, infielders can position anywhere",
          "Only against lefties",
          "No — moving the shortstop to the right side would put three infielders on one side, which the two-on-each-side rule prohibits",
          "Only with two outs",
        ],
        correctIndex: 2,
        explanation: "Pulling the shortstop to the right side would stack three infielders to the pull side and leave only one on the left — exactly the overload the rule bans. Two infielders must remain on each side of second base, so that alignment is illegal.",
      },
    ],
  },

  "baseball-16-10": {
    intro: "Late innings with a lead, the defense's whole job changes: stop the big inning, not the single run. Play deep, guard the lines, hit your cutoffs, and take the sure out every time.",
    spots: [
      {
        id: "bb16-10-s1", label: "No Doubles",
        situation: "Top of the 9th, your team leads by three runs. The coach calls for a 'no doubles' alignment.",
        prompt: "How does the defense set up?",
        options: [
          "Infield in and outfield shallow to cut off every single",
          "Everyone charges the plate",
          "Pull the outfield way in for a play at home",
          "Outfielders play deep and corner infielders guard the lines — give up the single, prevent the extra-base hit",
        ],
        correctIndex: 3,
        explanation: "Protecting a multi-run lead late, the defense plays 'no doubles': outfielders deep so nothing gets over their heads, and the corner infielders on the lines to take away doubles down the line. You happily concede singles — what you can't allow is the rally-starting extra-base hit.",
      },
      {
        id: "bb16-10-s2", label: "Take the Sure Out",
        situation: "Bottom of the 9th, you lead by one, runner on first, one out. A ground ball is hit to the shortstop, but it's a tough in-between hop and the double play is not cleanly there.",
        prompt: "What's the right decision?",
        options: [
          "Force a risky flip to second for the double play no matter what",
          "Take the sure out — get at least one, at first or second, rather than rush a bad feed and get nobody",
          "Throw home",
          "Hold the ball",
        ],
        correctIndex: 1,
        explanation: "Protecting a one-run lead, the worst outcome is throwing it around and getting no one. When the double play isn't clean, take the certain out. An out in hand keeps the inning moving; a forced, errant feed can blow the lead.",
      },
      {
        id: "bb16-10-s3", label: "Keep the DP in Order",
        situation: "One-run lead, late, nobody on, two outs away from the win. A batter loops a single to the outfield and rounds first aggressively.",
        prompt: "What's the outfielder's priority on the throw?",
        options: [
          "Air it all the way to second to try for the out",
          "Hit the cutoff man and keep the batter at first — don't risk an overthrow that puts the runner in scoring position",
          "Throw it into the stands",
          "Run it back to the infield himself",
        ],
        correctIndex: 1,
        explanation: "With a lead late, the outfielder throws to the cutoff man and keeps the hitter at first rather than gamble on a long throw that could sail and let him reach second. Keeping the runner off scoring position — and the double play in order — is worth more than a low-percentage out.",
      },
      {
        id: "bb16-10-s4", label: "The Ghost Runner",
        situation: "Tie game, bottom of the 10th, the automatic runner is on second base with nobody out. A ground ball is hit to the third baseman to his left.",
        prompt: "What's the fundamentally sound play?",
        options: [
          "Throw home wildly to try to get a runner who isn't going",
          "Look the runner back to keep him from advancing to third, then take the out at first",
          "Tag third base for no reason",
          "Hold the ball and concede everything",
        ],
        correctIndex: 1,
        explanation: "With the winning run on second and nobody out, the priority is to not let him reach third (90 feet from ending it) on a routine grounder. The third baseman checks the runner back, then takes the out at first. Don't invent a play that isn't there.",
      },
      {
        id: "bb16-10-s5", label: "Don't Get Fancy",
        situation: "Two outs, bottom of the 9th, you cling to a one-run lead. A routine ground ball comes to the second baseman for what should be the final out.",
        prompt: "What's the correct mindset and play?",
        options: [
          "Field it cleanly with two hands and make a simple, accurate throw to first for the sure final out",
          "Try a flashy behind-the-back flip to celebrate",
          "Double-clutch to be safe",
          "Run it over to first base yourself to be certain",
        ],
        correctIndex: 0,
        explanation: "The last out of a one-run game is no time for risk. Field it cleanly with two hands and make the routine, accurate throw to first. The disciplined, fundamental play — not a flashy one — is what closes out a lead.",
      },
    ],
  },
};
