import type { ScenarioConfig } from "./types";

// "Decision Trainer" scenarios for the Contract Bridge epoch.
// Each spot is a deterministic, skill-based decision — the correct line is the
// standard Standard American / SAYC play taught in that stage, never a guess.
// correctIndex and explanation are stripped server-side before reaching the client.
export const bridge1Scenarios: Record<string, ScenarioConfig> = {
  "bridge-1-01": {
    intro: "Welcome to the bridge table. Four players, two partnerships, and two phases of play. Let's lock in what bridge actually is before the cards start moving.",
    spots: [
      {
        id: "bridge-01-s1", label: "The Table",
        situation: "You sit down for a deal. Three other players join you and the 52-card deck is dealt out completely.",
        prompt: "How is a game of bridge arranged?",
        options: [
          "Four players in two partnerships, partners sitting opposite each other",
          "Two players head-to-head",
          "Four players, each one for themselves",
          "Six players in three pairs",
        ],
        correctIndex: 0,
        explanation: "Bridge is a partnership game for four: North-South versus East-West, with partners seated across the table from each other.",
      },
      {
        id: "bridge-01-s2", label: "Two Phases",
        situation: "A fresh deal begins. Everyone picks up their 13 cards.",
        prompt: "What are the two phases of every bridge deal, in order?",
        options: [
          "The auction (bidding), then the play of the cards",
          "The shuffle, then the cut",
          "Betting, then a showdown",
          "Dealing, then discarding",
        ],
        correctIndex: 0,
        explanation: "First the partners bid in the auction to set the contract, then all 13 tricks are played out.",
      },
      {
        id: "bridge-01-s3", label: "Trump or Notrump",
        situation: "The auction ends and your side has won the contract.",
        prompt: "What does the auction decide besides how many tricks you'll try to win?",
        options: [
          "Whether there is a trump suit, or the deal is played in notrump",
          "Which player deals next",
          "How many cards each player holds",
          "The order the cards are shuffled",
        ],
        correctIndex: 0,
        explanation: "A contract names a strain — a trump suit (clubs, diamonds, hearts, or spades) or notrump, meaning no trump suit.",
      },
      {
        id: "bridge-01-s4", label: "Silent Partners",
        situation: "You'd love to tell your partner exactly what you hold, but the rules forbid table talk.",
        prompt: "How do you and your partner communicate during a deal?",
        options: [
          "Only through legal bids and the cards you play",
          "By whispering your point count",
          "By passing written notes",
          "By openly naming your best suit",
        ],
        correctIndex: 0,
        explanation: "Communication is itself a skill: partners exchange information only through the coded language of bids and plays.",
      },
    ],
  },

  "bridge-1-02": {
    intro: "Bridge is won one trick at a time. Learn how a trick is taken, why a trump suit is so powerful, and the feature unique to bridge — the dummy.",
    spots: [
      {
        id: "bridge-02-s1", label: "Follow Suit",
        situation: "A spade is led, and you hold two small spades plus cards in the other suits.",
        hand: ["♠ 8 4", "♥ K Q 6", "♦ A 9 5 2", "♣ J 7 3"],
        prompt: "What are you required to do?",
        options: [
          "Follow suit — play a spade, since you have one",
          "Play your highest card in any suit",
          "Play a trump to win the trick",
          "Play whatever card you like",
        ],
        correctIndex: 0,
        explanation: "You must follow the suit led if you can; only when void in that suit may you trump or discard.",
      },
      {
        id: "bridge-02-s2", label: "Trump Power",
        situation: "Hearts are trump. Spades are led, you're void in spades, and you hold the lowly 2 of hearts.",
        prompt: "Can your 2 of hearts win this trick?",
        options: [
          "Yes — any trump beats any card of another suit",
          "No — the 2 is far too low",
          "Only if no ace has been played",
          "Only in a notrump contract",
        ],
        correctIndex: 0,
        explanation: "A trump beats every card of a non-trump suit, so even the trump deuce captures a trick when you can't follow suit.",
      },
      {
        id: "bridge-02-s3", label: "The Dummy",
        situation: "The opening lead is made, and declarer's partner spreads all 13 of their cards face-up on the table.",
        prompt: "Who plays the cards from that face-up dummy hand?",
        options: [
          "The declarer — the dummy's partner plays both hands",
          "The dummy player themselves",
          "The defender on the left",
          "Whoever won the previous trick",
        ],
        correctIndex: 0,
        explanation: "The declarer plays both their own hand and the dummy; the dummy's owner simply watches.",
      },
      {
        id: "bridge-02-s4", label: "Who Wins",
        situation: "It's a notrump deal. Clubs are led: West the 4, North the K, East the 9, South the Ace.",
        board: ["♣ 4 led", "♣ K", "♣ 9", "♣ A"],
        prompt: "Who wins the trick?",
        options: [
          "South — the Ace is the highest club, the suit that was led",
          "North — the King was played first among the honors",
          "West — they led the trick",
          "East — the last card played always wins",
        ],
        correctIndex: 0,
        explanation: "With no trump suit, the highest card of the suit led wins, so South's Ace of clubs takes it.",
      },
    ],
  },

  "bridge-1-03": {
    intro: "Before you bid a single card, you measure your hand. Count high-card points with the 4-3-2-1 scale: Ace 4, King 3, Queen 2, Jack 1.",
    spots: [
      {
        id: "bridge-03-s1", label: "Value an Ace",
        situation: "You're learning the standard high-card point count used to value a hand.",
        prompt: "How many points is an Ace worth?",
        options: ["4", "3", "2", "1"],
        correctIndex: 0,
        explanation: "The 4-3-2-1 scale: Ace = 4, King = 3, Queen = 2, Jack = 1; spot cards count zero.",
      },
      {
        id: "bridge-03-s2", label: "Count the Hand",
        situation: "You pick up the hand below and need its high-card point total.",
        hand: ["♠ A K 7 3", "♥ Q J 5", "♦ K 9 4", "♣ 8 5 2"],
        prompt: "How many high-card points (HCP) does this hand hold?",
        options: ["13", "11", "15", "9"],
        correctIndex: 0,
        explanation: "Spade A+K = 7, heart Q+J = 3, diamond K = 3 → 13 HCP, a sound opening hand.",
      },
      {
        id: "bridge-03-s3", label: "The Whole Deck",
        situation: "You want a yardstick for whether a hand is strong or weak.",
        prompt: "How many high-card points are in the entire 52-card deck?",
        options: ["40", "52", "13", "100"],
        correctIndex: 0,
        explanation: "Four each of A-K-Q-J at 4-3-2-1 gives 4 × (4+3+2+1) = 40 HCP, so an average hand holds about 10.",
      },
      {
        id: "bridge-03-s4", label: "The Magic Number",
        situation: "You and your partner are adding your hands together to judge how high to bid.",
        prompt: "Roughly how many combined points do you need to bid game?",
        options: [
          "About 25 to 26 combined points",
          "About 10 combined points",
          "Exactly 40 combined points",
          "About 15 combined points",
        ],
        correctIndex: 0,
        explanation: "Around 25-26 combined points usually produces enough tricks for game (3NT, 4 of a major, or 5 of a minor).",
      },
    ],
  },

  "bridge-1-04": {
    intro: "The auction is a coded conversation. Each bid names a level and a strain, and every bid must outrank the one before it.",
    spots: [
      {
        id: "bridge-04-s1", label: "Read a Bid",
        situation: "Your partner makes a bid of '4 Hearts'.",
        prompt: "What does that bid mean?",
        options: [
          "Hearts are trump and your side contracts to win 10 tricks (6 + 4)",
          "Your side will win exactly 4 tricks",
          "Your partner holds exactly 4 hearts",
          "Hearts may not be the trump suit",
        ],
        correctIndex: 0,
        explanation: "The level counts tricks above six, so '4' = 10 tricks, with hearts as the trump suit.",
      },
      {
        id: "bridge-04-s2", label: "Which Is Higher",
        situation: "An opponent has just opened the bidding with '1 Heart' and it's your turn.",
        prompt: "Which of these is a legal bid at the same level?",
        options: [
          "1 Spade — spades outrank hearts",
          "1 Club — clubs are cheaper",
          "1 Diamond — diamonds are lower",
          "No same-level bid is legal here",
        ],
        correctIndex: 0,
        explanation: "Strains rank clubs < diamonds < hearts < spades < notrump, so 1 Spade is higher than 1 Heart and legal.",
      },
      {
        id: "bridge-04-s3", label: "Pass or Double",
        situation: "The opponents bid a contract you believe they cannot make.",
        prompt: "What call lets you increase the score they win or lose?",
        options: [
          "Double — used against the opponents to raise the stakes",
          "Pass — it ends your turn quietly",
          "Redouble — only your own side can be doubled first",
          "A new suit at the one level",
        ],
        correctIndex: 0,
        explanation: "A double raises the penalties on the opponents' contract; it often means 'I don't think you can make this'.",
      },
      {
        id: "bridge-04-s4", label: "The Contract",
        situation: "Bidding has gone around the table and a bid is followed by three passes.",
        prompt: "How is the final contract determined?",
        options: [
          "It is the last bid made before three players pass in succession",
          "It is the very first bid of the auction",
          "It is always the highest possible bid, 7NT",
          "The dealer simply chooses it",
        ],
        correctIndex: 0,
        explanation: "When a bid is followed by three consecutive passes, that bid becomes the contract.",
      },
    ],
  },

  "bridge-1-05": {
    intro: "The opening bid is the first word of the conversation. Match each hand to the right Standard American opening.",
    spots: [
      {
        id: "bridge-05-s1", label: "Balanced 16",
        situation: "You're the dealer with a flat, balanced hand and 16 high-card points.",
        hand: ["♠ K J 9", "♥ A Q 7", "♦ K 10 6 4", "♣ Q J 5"],
        prompt: "What is the standard opening bid?",
        options: [
          "1 Notrump — balanced with 15-17 HCP",
          "1 Diamond — open your longest suit",
          "Pass — wait for a better hand",
          "2 Clubs — a strong, forcing opening",
        ],
        correctIndex: 0,
        explanation: "A balanced hand of 15-17 HCP is the classic 1NT opening, describing strength and shape in one bid.",
      },
      {
        id: "bridge-05-s2", label: "A Five-Card Major",
        situation: "You hold a strong hand with five spades and 14 HCP.",
        hand: ["♠ K Q 8 6 5", "♥ A 4", "♦ K 7 3", "♣ Q 9 2"],
        prompt: "In Standard American five-card majors, what do you open?",
        options: [
          "1 Spade — open the five-card major",
          "1 Notrump — you have enough points",
          "1 Club — open your cheapest suit",
          "2 Spades — show extra length",
        ],
        correctIndex: 0,
        explanation: "With opening strength and a five-card major you open it, letting partner raise with three-card support.",
      },
      {
        id: "bridge-05-s3", label: "Too Weak",
        situation: "It's your turn to open and you count only 6 high-card points in a flat hand.",
        hand: ["♠ Q 7 4", "♥ J 8 5", "♦ K 9 6 3", "♣ 10 4 2"],
        prompt: "What's the correct call?",
        options: [
          "Pass — fewer than about 12 points is not enough to open",
          "Open 1 Diamond anyway",
          "Open 1 Notrump",
          "Open 3 Diamonds as a preempt",
        ],
        correctIndex: 0,
        explanation: "You need roughly 12+ points to open at the one level; with 6 HCP and no long suit you pass.",
      },
      {
        id: "bridge-05-s4", label: "Open Your Longest",
        situation: "You have opening strength but no five-card major — your longest suit is diamonds.",
        hand: ["♠ A J", "♥ K Q 7", "♦ A 10 8 6 4", "♣ Q 9 3"],
        prompt: "Which suit do you open?",
        options: [
          "1 Diamond — open your longest suit",
          "1 Club — always open the cheapest suit",
          "1 Heart — bid the higher-ranking suit",
          "Pass — no major means no opening",
        ],
        correctIndex: 0,
        explanation: "With no five-card major, you open your longest suit — here the five-card diamond suit.",
      },
    ],
  },

  "bridge-1-06": {
    intro: "When partner opens, your job is to answer. The prime goal of the early auction is to find an eight-card-or-better trump fit, ideally in a major.",
    spots: [
      {
        id: "bridge-06-s1", label: "The Magic Eight",
        situation: "You're trying to decide whether a suit is good enough to be trump.",
        prompt: "How many cards in a suit does a partnership ideally want between both hands?",
        options: ["At least eight", "At least four", "Exactly thirteen", "At least eleven"],
        correctIndex: 0,
        explanation: "An eight-card fit leaves the opponents only five trumps, giving your side comfortable control.",
      },
      {
        id: "bridge-06-s2", label: "Raise the Major",
        situation: "Partner opens 1 Spade (promising five). You hold three spades and a fair hand.",
        hand: ["♠ K 7 4", "♥ Q 9 6 2", "♦ A 8 5", "♣ 10 3 2"],
        prompt: "What's the natural response?",
        options: [
          "Raise to 2 Spades — three-card support gives an eight-card fit",
          "Pass — you have no five-card suit of your own",
          "Bid 2 Hearts to switch suits",
          "Bid 1 Notrump despite the support",
        ],
        correctIndex: 0,
        explanation: "Five spades opposite your three is an eight-card fit, so you raise to confirm it and show your strength.",
      },
      {
        id: "bridge-06-s3", label: "Stayman",
        situation: "Partner opens 1 Notrump and you'd like to know whether they hold a four-card major.",
        prompt: "What conventional bid asks that question?",
        options: [
          "2 Clubs (Stayman) — asks opener for a four-card major",
          "2 Spades — shows your own spades",
          "Pass — you can never ask after 1NT",
          "3 Notrump — that ends the auction",
        ],
        correctIndex: 0,
        explanation: "Stayman 2 Clubs is artificial, asking opener to reveal a four-card heart or spade suit so you can find a 4-4 fit.",
      },
      {
        id: "bridge-06-s4", label: "A New Suit Forces",
        situation: "Partner opens 1 Diamond and you bid a new suit, 1 Spade.",
        prompt: "What does it mean that a new-suit response is 'forcing'?",
        options: [
          "Partner is obligated to bid again, keeping the auction alive",
          "The contract is now final at 1 Spade",
          "You must pass on your next turn",
          "Partner is required to double the opponents",
        ],
        correctIndex: 0,
        explanation: "A forcing bid commits partner to respond, so the partnership can keep exploring for its best fit.",
      },
    ],
  },

  "bridge-1-07": {
    intro: "When the dummy hits the table, the worst thing you can do is play fast. The expert's first move is to stop and make a plan.",
    spots: [
      {
        id: "bridge-07-s1", label: "Stop and Plan",
        situation: "You are declarer. The opening lead is made and dummy comes down.",
        prompt: "What should you do before playing to the first trick?",
        options: [
          "Pause and make a plan for the whole hand",
          "Win the first trick as cheaply as possible right away",
          "Draw all the trumps immediately, no matter what",
          "Play quickly so the defenders can't think",
        ],
        correctIndex: 0,
        explanation: "Seeing all 26 of your cards, declarer should stop and plan the play before touching a card.",
      },
      {
        id: "bridge-07-s2", label: "Count in Notrump",
        situation: "You are declarer in a notrump contract and want to know if you can make it.",
        prompt: "What's the right way to plan a notrump contract?",
        options: [
          "Count your sure winners and figure out how to develop the extra tricks you need",
          "Count your losers and try to ruff them away",
          "Just play your highest card every trick",
          "Lead trumps until the opponents run out",
        ],
        correctIndex: 0,
        explanation: "In notrump you count winners: tally your sure tricks, then plan how to develop the rest, often from a long suit.",
      },
      {
        id: "bridge-07-s3", label: "Count in a Suit",
        situation: "You are declarer in 4 Spades, a trump contract.",
        prompt: "What's the standard way to plan a suit contract?",
        options: [
          "Count your losers and find ways to avoid them",
          "Count your winners and stop there",
          "Discard your aces to save them",
          "Concede the contract before playing",
        ],
        correctIndex: 0,
        explanation: "In a suit contract it's usually easier to count losers — tricks you might lose — and look for ways to dispose of them.",
      },
      {
        id: "bridge-07-s4", label: "Timing",
        situation: "In notrump you need to set up a long suit, but the opponents are also building tricks in their own suit.",
        prompt: "Why does the ORDER of play matter so much?",
        options: [
          "Whoever sets up and cashes their winners first usually wins the race",
          "The order never matters as long as you have winners",
          "You should always cash your aces last",
          "Drawing trumps is illegal in notrump",
        ],
        correctIndex: 0,
        explanation: "Timing is everything: you must develop your extra tricks before the defenders can develop and cash theirs.",
      },
    ],
  },

  "bridge-1-08": {
    intro: "The finesse is the most common way to win an extra trick — a play that leads toward an honor, hoping a missing high card sits favorably.",
    spots: [
      {
        id: "bridge-08-s1", label: "What Is a Finesse",
        situation: "You're missing the King of a suit but hold the Ace and Queen between your two hands.",
        prompt: "What is a finesse?",
        options: [
          "A play that leads toward an honor, hoping a missing higher card sits favorably",
          "Cashing your highest cards as fast as possible",
          "Trumping a loser in the dummy",
          "Discarding a card you cannot use",
        ],
        correctIndex: 0,
        explanation: "A finesse is an attempt to win a trick with a card that is not the highest, by leading toward it when the missing honor lies favorably.",
      },
      {
        id: "bridge-08-s2", label: "Play the Queen",
        situation: "Dummy holds A Q of hearts; your hand holds two small hearts. You lead a low heart toward dummy and the next player follows low.",
        hand: ["♥ A Q  (dummy)", "♥ 5 3  (your hand)"],
        prompt: "Which card do you play from dummy to take the finesse?",
        options: [
          "The Queen — hoping the King is sitting to your left",
          "The Ace — grab the trick immediately",
          "A low heart from dummy too",
          "Refuse to play hearts at all",
        ],
        correctIndex: 0,
        explanation: "You play the Queen; if the King is on your left it loses to nothing, so the Queen wins and you keep the Ace.",
      },
      {
        id: "bridge-08-s3", label: "Which Way It Wins",
        situation: "You're finessing toward dummy's A-Q, leading from your hand on declarer's right.",
        prompt: "Where must the missing King sit for the finesse to succeed?",
        options: [
          "With the opponent to your left, who plays before the dummy",
          "With the opponent to your right, who plays last",
          "It doesn't matter where the King is",
          "In the dummy itself",
        ],
        correctIndex: 0,
        explanation: "The finesse works when the King is 'onside' — held by the player who must play before dummy's Queen.",
      },
      {
        id: "bridge-08-s4", label: "The Odds",
        situation: "You have no other information about where the missing King lies.",
        prompt: "Roughly what are the chances a simple finesse succeeds?",
        options: [
          "About 50% — the King is equally likely on either side",
          "About 100% — a finesse always works",
          "About 25% — it rarely works",
          "About 9% — like completing a flush",
        ],
        correctIndex: 0,
        explanation: "With no other clues, a missing honor is equally likely to sit on either side, so a finesse is about a 50-50 chance.",
      },
    ],
  },

  "bridge-1-09": {
    intro: "Defense is half the game, and it starts with the opening lead. The defenders' goal is to set — defeat — the contract.",
    spots: [
      {
        id: "bridge-09-s1", label: "The Goal",
        situation: "Your side did not win the contract, so you and your partner are the defenders.",
        prompt: "What are the defenders trying to do?",
        options: [
          "Set the contract — take enough tricks to defeat it",
          "Help declarer make the contract",
          "Win every single trick or none",
          "Bid again during the play",
        ],
        correctIndex: 0,
        explanation: "Defenders work as a partnership to 'set' (defeat) the contract by taking enough tricks to stop declarer.",
      },
      {
        id: "bridge-09-s2", label: "Top of a Sequence",
        situation: "On lead against a contract, you hold a solid sequence of honors in spades.",
        hand: ["♠ K Q J 5", "♥ 9 4 2", "♦ 8 6 3", "♣ 10 7 2"],
        prompt: "From the K-Q-J sequence, which card do you lead?",
        options: [
          "The King — top of the sequence",
          "The Jack — bottom of the sequence",
          "The 5 — fourth from the top",
          "A different suit entirely",
        ],
        correctIndex: 0,
        explanation: "From a sequence of touching honors you lead the top card — here the King from K-Q-J.",
      },
      {
        id: "bridge-09-s3", label: "Fourth Best vs Notrump",
        situation: "The contract is 3 Notrump. You're on lead with no honor sequence, but a decent five-card heart suit.",
        hand: ["♠ A 6", "♥ K 9 6 4 2", "♦ Q 7 3", "♣ 8 5 3"],
        prompt: "What's the standard opening lead against notrump here?",
        options: [
          "The 4 of hearts — fourth-best of your longest, strongest suit",
          "The King of hearts — your highest card",
          "The Ace of spades — cash a sure trick",
          "The 8 of clubs — your shortest suit",
        ],
        correctIndex: 0,
        explanation: "Against notrump, with no sequence you lead fourth-best of your longest and strongest suit to develop it.",
      },
      {
        id: "bridge-09-s4", label: "Why Lead Long vs NT",
        situation: "You're choosing between leading your long suit or a short one against a notrump contract.",
        prompt: "Why lead from your longest suit against notrump?",
        options: [
          "To establish small cards into winners once the suit is exhausted elsewhere",
          "Because short suits make more tricks",
          "Because notrump bans leading long suits",
          "To give declarer a free finesse",
        ],
        correctIndex: 0,
        explanation: "In notrump there's no trump to stop you, so a long suit can set up extra winners from its low cards.",
      },
    ],
  },

  "bridge-1-10": {
    intro: "Bring it together: how deals are scored, what counts as game, part-score, and slam, and the wider world of competitive bridge.",
    spots: [
      {
        id: "bridge-10-s1", label: "Reaching Game",
        situation: "Your partnership wants to bid a 'game' contract for the big bonus.",
        prompt: "Which of these is a game-level contract?",
        options: [
          "4 Hearts — a major-suit game (10 tricks)",
          "2 Hearts — a part-score",
          "1 Notrump — the smallest contract",
          "3 Clubs — a minor part-score",
        ],
        correctIndex: 0,
        explanation: "Game contracts are 3NT, 4 of a major, or 5 of a minor; 4 Hearts is a major-suit game.",
      },
      {
        id: "bridge-10-s2", label: "Part-Score",
        situation: "You stop in a low contract because your side lacks the points for game.",
        prompt: "What is a contract below game called?",
        options: [
          "A part-score",
          "A slam",
          "A grand slam",
          "A redouble",
        ],
        correctIndex: 0,
        explanation: "A contract that falls short of game (like 2 Spades) is a part-score, worth a small score with no game bonus.",
      },
      {
        id: "bridge-10-s3", label: "Slam",
        situation: "Your two hands together are enormous — around 33 combined points — and you contract to win 12 tricks.",
        prompt: "What is a contract to win 12 of the 13 tricks called?",
        options: [
          "A small slam (a 6-level contract)",
          "A part-score",
          "A grand slam",
          "A game",
        ],
        correctIndex: 0,
        explanation: "A 6-level contract is a small slam (12 tricks); a grand slam is the 7-level, all 13 tricks.",
      },
      {
        id: "bridge-10-s4", label: "Duplicate vs Rubber",
        situation: "At a club tournament, the same deals are passed to many tables and replayed.",
        prompt: "What is this skill-emphasizing form of the game called?",
        options: [
          "Duplicate bridge — everyone plays the same hands, so results compare skill, not luck",
          "Rubber bridge — each deal is shuffled fresh",
          "Solitaire bridge — played alone",
          "Auction bridge — the pre-1925 version",
        ],
        correctIndex: 0,
        explanation: "In duplicate bridge the same deals are replayed at every table, so good scores come from outplaying rivals, not lucky cards.",
      },
    ],
  },
};
