import type { ScenarioConfig } from "./types";

// "Count the Hand" Decision-Trainer scenarios for the Expert Cribbage epoch.
// Each spot is a deterministic, skill-based decision — the correct line is the
// rule or +EV play taught in that stage, never luck. Cribbage scoring here is
// exact: fifteens = 2 per distinct combo summing to 15 (A=1, faces=10); pair=2,
// pair royal=6, double pair royal=12; runs = 1 per card (count EVERY distinct
// run, including double/triple runs); a hand flush of 4 = 4 (5 with starter);
// a CRIB flush needs all five cards suited; his nobs = 1 for the held Jack of the
// starter's suit. correctIndex and explanation are stripped server-side.
export const cribbage4Scenarios: Record<string, ScenarioConfig> = {
  "cribbage-4-01": {
    intro: "Counting fast and never missing a point starts with one habit: a fixed order, every hand — fifteens, then runs, pairs, flush, nobs. Run the method and turn each hand into an exact number.",
    spots: [
      {
        id: "crib4-01-s1", label: "Run the Order",
        situation: "At the show you reveal four cards and add the starter, counting in the fixed order.",
        hand: ["6♣", "7♦", "8♠", "9♥"],
        board: ["8♣"],
        prompt: "How many points does this hand score?",
        options: ["14", "16", "12", "18"],
        correctIndex: 1,
        explanation: "Fifteens 6+9 and 7+8 twice = 6; two runs of four (the two 8s) = 8; pair of 8s = 2; total 16.",
      },
      {
        id: "crib4-01-s2", label: "Fifteens First",
        situation: "Three fives sit beside two ten-cards — count the fifteens before anything else.",
        hand: ["5♠", "5♥", "5♦", "10♣"],
        board: ["K♦"],
        prompt: "What is the total for this hand?",
        options: ["18", "23", "20", "14"],
        correctIndex: 2,
        explanation: "Fifteens: each 5 with the 10 and with the K (6 combos) plus 5+5+5 = 7 combos = 14; pair royal of 5s = 6; total 20.",
      },
      {
        id: "crib4-01-s3", label: "The Method",
        situation: "You teach a friend the reliable way to count a hand so nothing is missed.",
        prompt: "What is the recommended counting order?",
        options: [
          "Pairs, then fifteens, then runs",
          "Nobs first, then the flush",
          "Flush first, then fifteens",
          "Fifteens, then runs, pairs, flush, nobs",
        ],
        correctIndex: 3,
        explanation: "Always fifteens first (most points and most misses), then runs, pairs, flush, and nobs last.",
      },
      {
        id: "crib4-01-s4", label: "A Clean Run",
        situation: "Five cards land in perfect sequence — count it in order.",
        hand: ["3♣", "4♦", "5♠", "6♥"],
        board: ["7♣"],
        prompt: "How many points does this hand score?",
        options: ["9", "7", "11", "5"],
        correctIndex: 0,
        explanation: "Fifteens 3+5+7 and 4+5+6 = 4; run of five = 5; total 9.",
      },
    ],
  },

  "cribbage-4-02": {
    intro: "Some hands count higher than they look. A pair inside a run multiplies it; a flush hides among face cards; a rich-looking hand can make zero fifteens. Find the hidden points.",
    spots: [
      {
        id: "crib4-02-s1", label: "Double Double",
        situation: "The classic monster hand turns up at the show.",
        hand: ["7♣", "8♦", "7♠", "8♥"],
        board: ["9♣"],
        prompt: "How many points is this hand worth?",
        options: ["20", "24", "16", "26"],
        correctIndex: 1,
        explanation: "Four fifteens (each 7 with each 8) = 8; four runs of three (two 7s x two 8s x the 9) = 12; two pairs = 4; total 24.",
      },
      {
        id: "crib4-02-s2", label: "Pair in the Run",
        situation: "A pair sits inside a four-card run — easy to under-count.",
        hand: ["6♦", "7♥", "8♠", "6♣"],
        board: ["9♦"],
        prompt: "What is the total?",
        options: ["16", "14", "12", "18"],
        correctIndex: 0,
        explanation: "Fifteens 6+9 (two 6s) and 7+8 = 6; two runs of four (the pair of 6s) = 8; pair of 6s = 2; total 16.",
      },
      {
        id: "crib4-02-s3", label: "The No-Fifteen Trap",
        situation: "A hand full of high cards looks rich — but check the fifteens.",
        hand: ["8♠", "9♦", "9♣", "10♥"],
        board: ["J♠"],
        prompt: "How many points does this hand score?",
        options: ["12", "8", "10", "14"],
        correctIndex: 2,
        explanation: "No fifteens (every combination is too high to sum 15); a double run of four (the pair of 9s) = 8; pair of 9s = 2; total 10.",
      },
      {
        id: "crib4-02-s4", label: "Don't Miss the Flush",
        situation: "All four of your cards are spades; the starter is a diamond.",
        hand: ["4♠", "5♠", "6♠", "7♠"],
        board: ["8♦"],
        prompt: "What does this hand score?",
        options: ["9", "14", "11", "13"],
        correctIndex: 3,
        explanation: "Fifteens 7+8 and 4+5+6 = 4; run of five = 5; four-card flush in hand = 4; total 13.",
      },
    ],
  },

  "cribbage-4-03": {
    intro: "29 is the ceiling, 28 sits just below it, and 19, 25, 26, and 27 can never happen. Know the highest hands and the impossible counts — it proves you truly understand the scoring.",
    spots: [
      {
        id: "crib4-03-s1", label: "The Perfect Hand",
        situation: "You hold three fives and a Jack, and the fourth five — matching the Jack's suit — is cut.",
        hand: ["5♥", "5♠", "5♣", "J♦"],
        board: ["5♦"],
        prompt: "What does this famous hand score?",
        options: ["28", "26", "29", "24"],
        correctIndex: 2,
        explanation: "Eight fifteens (16) + four 5s as double pair royal (12) + his nobs for the J♦ matching the ♦ starter (1) = 29, the maximum.",
      },
      {
        id: "crib4-03-s2", label: "Impossible Count",
        situation: "A friend insists they once counted a hand to a certain total. You know better.",
        prompt: "Which of these scores can a cribbage hand NEVER make?",
        options: ["20", "19", "23", "17"],
        correctIndex: 1,
        explanation: "19, 25, 26, and 27 are impossible counts; 17, 20, and 23 are all reachable. '19' is slang for a zero hand.",
      },
      {
        id: "crib4-03-s3", label: "So Close to 29",
        situation: "You hold all four fives and a Jack is cut as the starter.",
        hand: ["5♥", "5♠", "5♣", "5♦"],
        board: ["J♣"],
        prompt: "What does this hand score?",
        options: ["29", "26", "24", "28"],
        correctIndex: 3,
        explanation: "Eight fifteens (16) + double pair royal of 5s (12) = 28. It is NOT 29 — no nobs, because the Jack is the cut, not held in hand.",
      },
      {
        id: "crib4-03-s4", label: "Spot the Gap",
        situation: "You double-check a count that came out to an unusual number.",
        prompt: "If you count a hand to one of these totals, which means you made an arithmetic error?",
        options: ["27", "22", "16", "20"],
        correctIndex: 0,
        explanation: "27 is an impossible count (along with 19, 25, 26) — reaching it means you miscounted and should recount.",
      },
    ],
  },

  "cribbage-4-04": {
    intro: "The crib counts like a hand — fifteens, runs, pairs, nobs — with one trap: its flush needs all five cards in one suit. Count the dealer's box exactly, and watch that flush.",
    spots: [
      {
        id: "crib4-04-s1", label: "The Flush That Isn't",
        situation: "It is your crib. Four cards are spades, but the starter is a heart.",
        hand: ["2♠", "6♠", "9♠", "K♠"],
        board: ["4♥"],
        prompt: "How many points does this crib score?",
        options: ["8", "9", "4", "5"],
        correctIndex: 2,
        explanation: "Fifteens 6+9 and 2+4+9 = 4. The four spades are NOT a flush in the crib (the starter is a heart), so flush = 0. Total 4.",
      },
      {
        id: "crib4-04-s2", label: "A Real Crib Flush",
        situation: "Your crib turns over all one suit — including the starter.",
        hand: ["3♦", "7♦", "8♦", "Q♦"],
        board: ["5♦"],
        prompt: "What does this crib score?",
        options: ["6", "11", "9", "10"],
        correctIndex: 1,
        explanation: "Fifteens 7+8, Q+5, and 3+5+7 = 6; a full five-card flush (all diamonds) = 5; total 11.",
      },
      {
        id: "crib4-04-s3", label: "The Crib Rule",
        situation: "You explain how scoring the crib differs from scoring a hand.",
        prompt: "What is the one way the crib scores differently?",
        options: [
          "The crib does not score fifteens",
          "The crib does not score nobs",
          "The crib scores every combination double",
          "A crib flush needs all five cards in one suit; four suited scores nothing",
        ],
        correctIndex: 3,
        explanation: "Everything counts the same except the flush — the crib needs all five cards (including the starter) suited.",
      },
      {
        id: "crib4-04-s4", label: "Count the Box",
        situation: "Your crib holds three fives, a ten, and a Jack, with a five cut as the starter.",
        hand: ["5♥", "5♣", "10♦", "J♠"],
        board: ["5♠"],
        prompt: "How many points does this crib score?",
        options: ["21", "20", "18", "24"],
        correctIndex: 0,
        explanation: "Fifteens: each 5 with the 10 and with the J (6 combos) plus 5+5+5 = 7 = 14; pair royal of 5s = 6; nobs for J♠ matching the ♠ starter = 1; total 21.",
      },
    ],
  },

  "cribbage-4-05": {
    intro: "The board is a map of the game. Read your position on its streets, your distance to 121, and the opponent's distance to the 91 skunk line — position decides your plan.",
    spots: [
      {
        id: "crib4-05-s1", label: "The Skunk Line",
        situation: "You reach 121 to win while your opponent's front peg is stuck at hole 84.",
        prompt: "Your opponent is below the 91 line. What does this margin mean?",
        options: [
          "Nothing special, just a win",
          "The opponent gets to redeal",
          "It is a draw",
          "A skunk — it counts as a double game",
        ],
        correctIndex: 3,
        explanation: "Winning while the opponent is below the 91 skunk line (31+ points short) is a skunk, usually scored as a double game.",
      },
      {
        id: "crib4-05-s2", label: "Reading the Streets",
        situation: "You glance at the board to size up the game before deciding how to play.",
        prompt: "Why do players track which 'street' (stretch of holes) they are in?",
        options: [
          "To know if they are early, mid, or near the finish and skunk line",
          "Because the streets change the card values",
          "It is required to peg at all",
          "To decide who deals next",
        ],
        correctIndex: 0,
        explanation: "Reading the streets gives an instant sense of position — whether to attack, grind, or press for a skunk.",
      },
      {
        id: "crib4-05-s3", label: "Distance to Home",
        situation: "Your front peg sits at hole 109 late in the game.",
        board: ["🎯 121"],
        prompt: "How many more points do you need to win?",
        options: ["16", "12", "11", "13"],
        correctIndex: 1,
        explanation: "121 minus 109 = 12 points to reach the finish.",
      },
      {
        id: "crib4-05-s4", label: "Press the Margin",
        situation: "You are at hole 100 with a commanding lead; your opponent is stalled at 70.",
        prompt: "Reading the board, what is your goal this hand?",
        options: [
          "Push to finish before the opponent reaches 91, for a skunk (double game)",
          "Deliberately stall to keep the game going",
          "Give the opponent points so the game ends sooner",
          "Stop counting your hands",
        ],
        correctIndex: 0,
        explanation: "With the opponent below the 91 line, a leader presses to finish for a skunk, worth a double game.",
      },
    ],
  },

  "cribbage-4-06": {
    intro: "The endgame is decided by who counts first. Near 121 the non-dealer (pone) counts before the dealer — and can win before the dealer ever counts. Plan the finish around the order.",
    spots: [
      {
        id: "crib4-06-s1", label: "Who Counts First",
        situation: "Both players are within a hand of 121. The play is over and it is time to count.",
        prompt: "Who counts first, and why does it matter at the finish?",
        options: [
          "The dealer, because they own the crib",
          "The non-dealer (pone) — they can reach 121 and win before the dealer counts",
          "Whoever pegged more in the play",
          "The crib is counted first",
        ],
        correctIndex: 1,
        explanation: "The pone counts first; near 121 they can count out and win before the dealer ever counts a point.",
      },
      {
        id: "crib4-06-s2", label: "The Race to Count Out",
        situation: "The pone needs 8 to win; the dealer needs only 6. Both have enough in their hands.",
        prompt: "The pone's hand counts 9. Who wins?",
        options: [
          "The dealer — they needed fewer points",
          "Whoever has the higher hand",
          "The non-dealer — pone counts first and reaches 121",
          "It is a tie, decided by the crib",
        ],
        correctIndex: 2,
        explanation: "The pone counts first; counting 9 reaches 121 before the dealer ever counts, even though the dealer needed only 6.",
      },
      {
        id: "crib4-06-s3", label: "Peg Out in Play",
        situation: "You need just 1 point to win and it is still the pegging phase.",
        prompt: "Can you win before the show?",
        options: [
          "Yes — reaching 121 on a peg (a go, fifteen, or last card) wins immediately",
          "No, you can only win at the show",
          "No, only the dealer can peg out",
          "Only if you cut a Jack",
        ],
        correctIndex: 0,
        explanation: "Reaching 121 at any moment in the play — even on a single 'go' or last-card point — ends the game on the spot.",
      },
      {
        id: "crib4-06-s4", label: "Do You Count Out?",
        situation: "You are the pone at hole 117, needing 4 to win, and reveal your hand at the show.",
        hand: ["6♥", "7♠", "9♣", "8♦"],
        board: ["7♦"],
        prompt: "Do you count out and win?",
        options: [
          "No, the hand is too small",
          "Only if the dealer misses",
          "Yes — the hand counts 16, far more than the 4 you need, and the pone counts first",
          "No, you need an exact 4",
        ],
        correctIndex: 2,
        explanation: "Fifteens 7+8 (two 7s) and 6+9 = 6; two runs of four = 8; pair of 7s = 2; total 16 — well past the 4 you need, and the pone counts first.",
      },
    ],
  },

  "cribbage-4-07": {
    intro: "There is no single best play — only the best play for your position. Behind, you attack; ahead, you defend; and your discards follow the same logic. Let the score choose your mode.",
    spots: [
      {
        id: "crib4-07-s1", label: "Behind on the Board",
        situation: "You are well behind late in the game, and it is the opponent's crib.",
        prompt: "What general strategy fits being behind?",
        options: [
          "Play offense — take risks and play for maximum points",
          "Play pure defense and concede points",
          "Throw your best cards to the opponent",
          "Stop pegging entirely",
        ],
        correctIndex: 0,
        explanation: "Behind, you must take risks and chase points to catch up — offense.",
      },
      {
        id: "crib4-07-s2", label: "Ahead on the Board",
        situation: "You hold a commanding lead and it is the opponent's deal.",
        prompt: "What strategy fits being ahead?",
        options: [
          "Gamble for big hands to end it fast",
          "Hand the opponent your 5s",
          "Play defense — deny points and throw safe cards",
          "Ignore the crib entirely",
        ],
        correctIndex: 2,
        explanation: "Ahead, you protect the lead by denying the opponent points and conceding only small ones.",
      },
      {
        id: "crib4-07-s3", label: "The Defensive Throw",
        situation: "You are ahead and it is the opponent's crib. You weigh which cards are safe to give away.",
        prompt: "Which is the WORST card to throw into the opponent's crib?",
        options: [
          "A lone King",
          "A 5",
          "A 2 of a different suit",
          "A widely separated low card",
        ],
        correctIndex: 1,
        explanation: "The 5 is the best fifteen-maker in the deck — never hand it to an opponent's crib, especially on defense.",
      },
      {
        id: "crib4-07-s4", label: "The Offensive Throw",
        situation: "You are behind, it is your own deal, and you hold 4-5-5-6-10-J.",
        hand: ["4♦", "5♠", "5♥", "6♣", "10♦", "J♠"],
        prompt: "Playing offense, what is the best keep and discard?",
        options: [
          "Keep 4-5-5-6 (a double run) and throw 10-J to your own crib",
          "Throw both 5s away",
          "Keep 10-J and throw 5-6",
          "Throw 4-6 and keep the ten-cards",
        ],
        correctIndex: 0,
        explanation: "Keep the 12-point 4-5-5-6 double run and load your own crib with 10-J — both ten-cards make fifteens with any 5 cut and form a near-run.",
      },
    ],
  },

  "cribbage-4-08": {
    intro: "Muggins is cribbage's sharpest edge: if your opponent under-counts their own hand, you call 'muggins' and peg the points they missed — but only the points that were really there.",
    spots: [
      {
        id: "crib4-08-s1", label: "The Rule",
        situation: "Your opponent counts their hand aloud and announces fewer points than it holds.",
        prompt: "Under the muggins rule, what may you do?",
        options: [
          "Force a replay of the deal",
          "Peg the points they failed to claim in their own hand",
          "Double your own score",
          "Make them skip a turn",
        ],
        correctIndex: 1,
        explanation: "Muggins lets an alert opponent claim the exact points the counter missed — a reason to count carefully.",
      },
      {
        id: "crib4-08-s2", label: "Spot the Miss",
        situation: "Your opponent shows 7-8-7-8 with a 9 starter and announces 'sixteen.'",
        hand: ["7♥", "8♠", "7♦", "8♣"],
        board: ["9♥"],
        prompt: "How many points can you muggins?",
        options: [
          "0 — they were correct",
          "4",
          "8 — the hand is really worth 24",
          "12",
        ],
        correctIndex: 2,
        explanation: "The hand is 24 (8 fifteens, 12 runs, 4 pairs). They claimed 16, so you call muggins and peg the missing 8.",
      },
      {
        id: "crib4-08-s3", label: "The Limit",
        situation: "Your opponent counts their hand fully and correctly, leaving nothing out.",
        prompt: "Can you call muggins?",
        options: [
          "No — muggins only takes points they actually failed to claim",
          "Yes, you can always muggins",
          "Yes, if you want their crib instead",
          "Only if they hold a Jack",
        ],
        correctIndex: 0,
        explanation: "Muggins covers genuinely missed points only; you cannot invent points that were correctly counted.",
      },
      {
        id: "crib4-08-s4", label: "Spot It Again",
        situation: "Your opponent shows 5-5-5-6 with a 4 starter and announces 'fourteen.'",
        hand: ["5♣", "5♦", "5♠", "6♥"],
        board: ["4♦"],
        prompt: "How many points did they miss?",
        options: ["9 — the hand is really worth 23", "7", "11", "5"],
        correctIndex: 0,
        explanation: "Fifteens: three 5s with 4+6 plus 5+5+5 = 8; triple run (three runs of three) = 9; pair royal of 5s = 6; total 23. They claimed 14, missing 9.",
      },
    ],
  },

  "cribbage-4-09": {
    intro: "At the top level cribbage is probability. The starter is unknown when you discard, so you play the averages — expected value, the 26-theory par, and the average value of the crib.",
    spots: [
      {
        id: "crib4-09-s1", label: "Par for the Round",
        situation: "You want a benchmark for whether you are keeping pace toward 121.",
        prompt: "What per-round point target does the '26 theory' suggest for the dealer?",
        options: [
          "About 10 points",
          "About 26 points across hand, crib, and pegging",
          "Exactly 15 points",
          "About 60 points",
        ],
        correctIndex: 1,
        explanation: "The '26 theory' uses about 26 points per round (hand, crib, and pegging) as a par benchmark.",
      },
      {
        id: "crib4-09-s2", label: "The Average Crib",
        situation: "You weigh how much your crib is typically worth before deciding a throw.",
        prompt: "About how many points is the average crib worth to the dealer?",
        options: [
          "About 1 point",
          "About 15 points",
          "Roughly 4 to 5 points",
          "About 10 points",
        ],
        correctIndex: 2,
        explanation: "The average crib is worth around 4 to 5 points — the steady edge that makes dealing valuable.",
      },
      {
        id: "crib4-09-s3", label: "Why Expected Value",
        situation: "You decide a discard before the starter is cut.",
        prompt: "Why do experts pick a discard by expected value, not just current hand points?",
        options: [
          "The starter is unknown, so EV averages the result over all possible cut cards",
          "Because EV is required by the rules",
          "To always keep a flush",
          "Because hand points never matter",
        ],
        correctIndex: 0,
        explanation: "Since the starter is unknown at the layaway, the best throw is the one with the best average over all cuts.",
      },
      {
        id: "crib4-09-s4", label: "The Best Keep",
        situation: "It is your deal and you hold four fives plus an 8 and a King.",
        hand: ["5♠", "5♥", "5♦", "5♣", "8♦", "K♣"],
        prompt: "For the highest expected total, what is the best keep and throw?",
        options: [
          "Keep 5-5-8-K and throw two 5s",
          "Throw all four 5s to your crib",
          "Keep the four 5s (a 20-point hand) and throw 8-K to your own crib",
          "Keep 8-K and throw the 5s away",
        ],
        correctIndex: 2,
        explanation: "Four 5s already score 20 on their own (eight fifteens + double pair royal) and more with any ten-card cut — the highest-EV keep by far.",
      },
    ],
  },

  "cribbage-4-10": {
    intro: "Expert cribbage is the sum of its parts — exact counting, EV discards, pegging by score, board awareness, and the endgame count — woven into one game plan, the way ACC tournament players do it.",
    spots: [
      {
        id: "crib4-10-s1", label: "The Layaway",
        situation: "It is your deal (your crib) and you are dealt 4-5-6-6-7-J.",
        hand: ["4♠", "5♥", "6♦", "6♣", "7♠", "J♦"],
        prompt: "Which keep scores the most for your hand?",
        options: [
          "Keep 6-6-7-J, throw 4-5",
          "Keep 4-5-6-6 — a 12-point double run — and throw 7-J to your crib",
          "Keep 5-6-6-7, throw 4-J",
          "Keep 4-5-6-7, throw 6-J",
        ],
        correctIndex: 1,
        explanation: "4-5-6-6 makes two runs of three (6), two fifteens of 4+5+6 (4), and a pair (2) = 12 — the highest keep, and 7-J still helps your own crib.",
      },
      {
        id: "crib4-10-s2", label: "The Count-Out",
        situation: "Final hand: you are the pone at hole 116 (need 5) and reveal your hand at the show.",
        hand: ["6♦", "7♥", "8♣", "9♠"],
        board: ["10♦"],
        prompt: "Do you win this game?",
        options: [
          "No, the dealer counts first",
          "Only if you cut a Jack",
          "Yes — the hand counts 9 and the pone counts first",
          "No, you need exactly 5",
        ],
        correctIndex: 2,
        explanation: "Fifteens 6+9 and 7+8 = 4; run of five = 5; total 9 — more than the 5 you need, and the pone counts first, so you count out and win.",
      },
      {
        id: "crib4-10-s3", label: "Tournament Scoring",
        situation: "You enter an American Cribbage Congress sanctioned tournament.",
        prompt: "How are ACC tournament games typically scored?",
        options: [
          "By total pegs across all games",
          "Winner takes a fixed prize only",
          "By the number of 29 hands made",
          "As match points, with skunks counting extra",
        ],
        correctIndex: 3,
        explanation: "ACC play uses match-point scoring, and skunks count for extra — so leaders press to skunk, not just win.",
      },
      {
        id: "crib4-10-s4", label: "The Whole Game",
        situation: "You reflect on everything this epoch has taught about playing at the expert level.",
        prompt: "Which best captures expert cribbage?",
        options: [
          "Always keeping the highest cards",
          "Exact counting, EV discards, pegging by score, and reading the board",
          "Memorizing one fixed opening",
          "Relying on lucky cuts",
        ],
        correctIndex: 1,
        explanation: "Mastery weaves fast exact counting, expected-value discards, score-based pegging, and board awareness into a single plan to the finish.",
      },
    ],
  },
};
