import type { ScenarioConfig } from "./types";

// Decision-Trainer scenarios for the "Cribbage: The Crib & Discarding" epoch.
// Each spot is a real discard read — which two to throw, which four to keep,
// is this throw safe to the opponent's crib — never luck. Cribbage scoring is
// exact: fifteens = 2 per distinct combo summing to 15 (A=1, faces=10); pair=2,
// pair royal=6, double pair royal=12; runs = 1 per card (3+); a four-card flush
// in hand = 4 (5 with the starter), and the crib needs all five one suit; his
// nobs = 1 for the held Jack of the starter's suit. correctIndex and explanation
// are stripped server-side before the client.
export const cribbage2Scenarios: Record<string, ScenarioConfig> = {
  "cribbage-2-01": {
    intro: "The discard is cribbage's pivotal skill. You are dealt six cards and must keep four, laying away two into the crib. Find the strongest four hiding in each hand.",
    spots: [
      {
        id: "crib2-01-s1", label: "The Monster",
        situation: "It's your deal, so the crib is yours. You hold three fives and a Jack alongside two stray cards.",
        hand: ["5♠", "5♥", "5♦", "J♣", "2♦", "8♠"],
        prompt: "Which two cards should you lay away?",
        options: [
          "Throw 5♥ and 5♦ (keep J-5-2-8)",
          "Throw J♣ and 8♠ (keep 5-5-5-2 for eight)",
          "Throw 2♦ and 8♠ (keep 5-5-5-J for fourteen)",
          "Throw 5♠ and J♣ (keep 5-5-2-8)",
        ],
        correctIndex: 2,
        explanation: "5-5-5-J scores fourteen: three fifteens of 5+J plus 5+5+5 (8) and the pair royal of fives (6). The 2 and 8 are the throwaways.",
      },
      {
        id: "crib2-01-s2", label: "Double Run",
        situation: "Your six cards contain a pair of sixes sitting next to a 4 and a 5.",
        hand: ["4♥", "5♠", "6♦", "6♣", "7♥", "9♠"],
        prompt: "Which four cards keep the most points in hand?",
        options: [
          "Keep 5-6-6-7 (eight)",
          "Keep 4-5-6-6, throw 7-9 (twelve)",
          "Keep 4-5-6-7, throw 6-9 (six)",
          "Keep 6-6-7-9, throw 4-5 (six)",
        ],
        correctIndex: 1,
        explanation: "4-5-6-6 scores twelve: 4+5+6 makes fifteen twice through the two sixes (4), a double run of three (6), and the pair of sixes (2).",
      },
      {
        id: "crib2-01-s3", label: "Pick the Keep",
        situation: "It's your deal. You hold a pair of fives wrapped by a 4 and a 6, plus a 3 and a Jack.",
        hand: ["3♠", "4♥", "5♦", "5♣", "6♠", "J♦"],
        prompt: "Which four-card keep is best?",
        options: [
          "Keep 3-4-5-6 (six)",
          "Keep 5-5-6-J (six)",
          "Keep 4-5-5-J (six)",
          "Keep 4-5-5-6, throw 3-J (twelve)",
        ],
        correctIndex: 3,
        explanation: "4-5-5-6 scores twelve: two fifteens of 4+5+6 (4), a double run of three (6), and the pair of fives (2).",
      },
      {
        id: "crib2-01-s4", label: "The Mechanic",
        situation: "You're learning the basic shape of every cribbage deal.",
        prompt: "After the deal, how many cards do you keep and how many do you lay away?",
        options: [
          "Keep four, lay away two into the crib",
          "Keep five, lay away one",
          "Keep all six",
          "Keep three, lay away three",
        ],
        correctIndex: 0,
        explanation: "Each player keeps four cards for the play and the show, and discards exactly two into the crib.",
      },
    ],
  },

  "cribbage-2-02": {
    intro: "Before any throw, ask one question: whose crib is it? On your deal, feed the box; on the opponent's, starve it. The same cards flip from gift to leak.",
    spots: [
      {
        id: "crib2-02-s1", label: "Your Crib",
        situation: "It's your deal, so the crib is yours. You hold a 7-8-9 run plus a pair of fours and a Jack.",
        hand: ["4♠", "4♥", "7♦", "8♣", "9♠", "J♦"],
        prompt: "What's the best layaway?",
        options: [
          "Throw 7-8 (breaks your run)",
          "Throw 9-J",
          "Throw 4♠ 4♥ to your crib (keep 7-8-9-J; the pair builds your box)",
          "Throw 4-J",
        ],
        correctIndex: 2,
        explanation: "It's your crib, so the 4-4 pair's points are yours, and 7-8-9-J still scores five (run of three plus 7+8) in hand.",
      },
      {
        id: "crib2-02-s2", label: "Their Crib",
        situation: "Same six cards, but now it's the opponent's deal — the crib is theirs.",
        hand: ["4♠", "4♥", "7♦", "8♣", "9♠", "J♦"],
        prompt: "What's the safest layaway now?",
        options: [
          "Throw 4 and J (unconnected; keep 7-8-9-4 for five)",
          "Throw 4-4 (hands their crib a pair)",
          "Throw 7-8 (gives a fifteen and a near-run)",
          "Throw 8-9 (a ready-made run starter)",
        ],
        correctIndex: 0,
        explanation: "Their crib, so deny the pair: a lone 4 and a Jack don't connect, and you still keep a five-point 7-8-9 hand.",
      },
      {
        id: "crib2-02-s3", label: "Your Deal",
        situation: "It's your deal and you're deciding what kind of cards to send to the crib.",
        prompt: "On your own deal, you want to throw cards that...",
        options: [
          "...cannot combine at all",
          "...combine for points, because the crib is yours",
          "...are simply your highest",
          "...are all one suit",
        ],
        correctIndex: 1,
        explanation: "The crib is yours, so combining cards — fives and connectors — build points you will collect.",
      },
      {
        id: "crib2-02-s4", label: "Gift or Leak",
        situation: "You notice the same two cards keep coming up in different deals.",
        prompt: "A 5 and a 6 together are...",
        options: [
          "Always thrown, regardless of the crib",
          "Never worth throwing",
          "Only useful during the play",
          "A strong throw to your crib but a leak to the opponent's",
        ],
        correctIndex: 3,
        explanation: "Ownership flips the verdict: a 5-6 builds your box but gifts the opponent's crib a fifteen and a near-run.",
      },
    ],
  },

  "cribbage-2-03": {
    intro: "Sixteen cards count as ten, and a single 5 makes a fifteen with every one of them. Keep fives, feed your own crib with them, and never hand one to the enemy box.",
    spots: [
      {
        id: "crib2-03-s1", label: "Fives and Tens",
        situation: "It's your deal. You hold two fives and a fistful of ten-cards.",
        hand: ["5♠", "5♥", "10♦", "J♣", "Q♠", "K♦"],
        prompt: "Which four cards score the most in hand?",
        options: [
          "Keep 5-5-10-J (ten)",
          "Keep 5-10-J-Q (nine)",
          "Keep 10-J-Q-K (four)",
          "Keep 5-J-Q-K (nine)",
        ],
        correctIndex: 0,
        explanation: "5-5-10-J scores ten: each five pairs with each ten-card for four fifteens (8), plus the pair of fives (2).",
      },
      {
        id: "crib2-03-s2", label: "Why Magic",
        situation: "You're reminding yourself why the 5 is the most prized card in cribbage.",
        prompt: "What makes the 5 so powerful?",
        options: [
          "It is the highest-ranked card",
          "It is wild",
          "Sixteen ten-valued cards each make a fifteen with a five",
          "It beats every pair",
        ],
        correctIndex: 2,
        explanation: "Four 10s plus the twelve face cards are all worth ten, and a 5 makes a fifteen with any one of them.",
      },
      {
        id: "crib2-03-s3", label: "Guard the Five",
        situation: "It's the opponent's deal, so the crib is theirs. You hold a lone 5, a pair of kings, and scraps.",
        hand: ["5♠", "2♥", "7♦", "9♣", "K♠", "K♦"],
        prompt: "What's the right layaway?",
        options: [
          "Throw 5 and K (hands their crib a 5 and a ten)",
          "Throw 2 and 7 (safe junk; keep 5-9-K-K for six)",
          "Throw K-K (gives their crib a pair)",
          "Throw 5 and 2 (hands over the five)",
        ],
        correctIndex: 1,
        explanation: "Keep the 5: it scores in your hand (5-9-K-K is six) and is the worst card to give an enemy crib. The 2 and 7 are dead.",
      },
      {
        id: "crib2-03-s4", label: "Count the Fives",
        situation: "At the show you reveal a five-heavy hand and the starter is yet another five.",
        hand: ["5♠", "5♥", "10♦", "J♣"],
        board: ["5♦"],
        prompt: "How many points does this hand score?",
        options: ["12", "14", "18", "20"],
        correctIndex: 3,
        explanation: "Three fives give seven fifteens (5+10 thrice, 5+J thrice, and 5+5+5) for 14, and the pair royal of fives is 6 — 20 total.",
      },
    ],
  },

  "cribbage-2-04": {
    intro: "Before the crib, see the best hand hiding in your six cards. Double runs, paired runs, dense fifteens, and flushes separate a strong keep from a flat one.",
    spots: [
      {
        id: "crib2-04-s1", label: "Paired Run",
        situation: "Your six cards hold a pair of eights between a 7 and a 9.",
        hand: ["4♠", "7♥", "8♦", "8♣", "9♠", "J♦"],
        prompt: "Which keep scores the most in hand?",
        options: [
          "Keep 4-7-8-9 (five)",
          "Keep 8-8-9-J (two)",
          "Keep 7-8-8-9, throw 4-J (twelve)",
          "Keep 7-8-9-J (five)",
        ],
        correctIndex: 2,
        explanation: "7-8-8-9 scores twelve: the run 7-8-9 twice through the two eights (6), the pair of eights (2), and 7+8 twice for fifteen (4).",
      },
      {
        id: "crib2-04-s2", label: "Double Three",
        situation: "You hold a pair of threes beside a 4-5-6 run fragment and a stray 9.",
        hand: ["3♠", "3♥", "4♦", "5♣", "6♠", "9♦"],
        prompt: "Which four-card keep is best for hand points?",
        options: [
          "Keep 3-3-4-5 (ten)",
          "Keep 4-5-6-9 (seven)",
          "Keep 3-4-5-6 (six)",
          "Keep 3-3-4-9 (four)",
        ],
        correctIndex: 0,
        explanation: "3-3-4-5 scores ten: the double run 3-4-5 through the two threes (6), the pair of threes (2), and the fifteen 3+3+4+5 (2).",
      },
      {
        id: "crib2-04-s3", label: "Hidden Flush",
        situation: "Four of your six cards are spades, and they happen to be in sequence.",
        hand: ["4♠", "5♠", "6♠", "7♠", "8♥", "9♦"],
        prompt: "Which keep scores the most?",
        options: [
          "Keep 6-7-8-9 (eight)",
          "Keep 4-5-6-7 in spades, throw 8-9 (ten)",
          "Keep 5-6-7-8 (six)",
          "Keep 4-5-6-8 (five)",
        ],
        correctIndex: 1,
        explanation: "4-5-6-7 of one suit scores ten: a run of four (4), the 4+5+6 fifteen (2), and the four-card flush (4).",
      },
      {
        id: "crib2-04-s4", label: "The Approach",
        situation: "You're framing how to choose your four-card keep.",
        prompt: "What is the soundest way to pick the keep?",
        options: [
          "Keep the four highest cards",
          "Keep whatever is suited only",
          "Keep the four lowest cards",
          "Keep the four that score the most together, weighing the likely starter",
        ],
        correctIndex: 3,
        explanation: "Find the strongest scoring four first — runs, fifteens, pairs, flush — then refine for the cut and the crib.",
      },
    ],
  },

  "cribbage-2-05": {
    intro: "On your deal the crib is yours, so throw it cards that work together. A handful of pairs — 5-5, 4-5, 2-3, 7-8 — are magic crib fuel.",
    spots: [
      {
        id: "crib2-05-s1", label: "Best of Both",
        situation: "It's your deal. You hold a strong 6-7-8-8 shape plus a pair of fives.",
        hand: ["5♠", "5♥", "6♦", "7♣", "8♠", "8♥"],
        prompt: "What's the ideal layaway?",
        options: [
          "Throw 5-5 to your crib (keep 6-7-8-8 for twelve)",
          "Throw 8-8 (weakens your hand)",
          "Throw 6-7 (breaks the run)",
          "Throw 5-8 (splits both)",
        ],
        correctIndex: 0,
        explanation: "6-7-8-8 scores twelve (double run, pair of eights, two fifteens), and 5-5 is the best crib throw — you collect on both ends.",
      },
      {
        id: "crib2-05-s2", label: "Low Combo",
        situation: "It's your deal. You hold a 7-8-9-10 run plus a 2 and a 3.",
        hand: ["2♠", "3♥", "7♦", "8♣", "9♠", "10♦"],
        prompt: "What's the best throw to your crib?",
        options: [
          "Throw 9-10 (breaks your run)",
          "Throw 7-8 (breaks your run)",
          "Throw 2-10 (splits)",
          "Throw 2-3 to your crib (keep 7-8-9-10; 2-3 makes a fifteen with any ten)",
        ],
        correctIndex: 3,
        explanation: "Keep the run of four for six, and 2-3 in your box makes a fifteen with any ten-card (2+3+10) and threatens a run.",
      },
      {
        id: "crib2-05-s3", label: "Connector Toss",
        situation: "It's your deal. You hold a pair of sevens and a pair of eights plus a 4 and a 5.",
        hand: ["4♠", "5♥", "7♦", "7♣", "8♠", "8♥"],
        prompt: "What's the right layaway?",
        options: [
          "Throw 7-8 (wrecks the hand)",
          "Throw 4-8 (splits)",
          "Throw 4-5 to your crib (keep 7-7-8-8 for twelve)",
          "Throw 5-7 (splits)",
        ],
        correctIndex: 2,
        explanation: "7-7-8-8 scores twelve: four fifteens of 7+8 (8) plus both pairs (4). The leftover 4-5 is a rich connector for your box.",
      },
      {
        id: "crib2-05-s4", label: "The Workhorses",
        situation: "You're memorizing the pairs that build a crib best.",
        prompt: "Which set lists the classic point-rich crib throws?",
        options: [
          "K-2, Q-3, J-4",
          "5-5, 4-5, 2-3, 7-8",
          "A-9, 2-8, 3-7",
          "K-Q, Q-J, J-10",
        ],
        correctIndex: 1,
        explanation: "Fives and connectors that make fifteens and runs are the reliable throws to your own crib.",
      },
    ],
  },

  "cribbage-2-06": {
    intro: "On the opponent's deal the crib is theirs, so starve it. Throw wide, dead cards — and keep fives, pairs, and connectors out of an enemy box.",
    spots: [
      {
        id: "crib2-06-s1", label: "Wide Junk",
        situation: "It's the opponent's deal. You hold a clean 6-7-8-9 run plus a Jack and an Ace.",
        hand: ["6♠", "7♥", "8♦", "9♣", "J♠", "A♦"],
        prompt: "What's the safest throw to their crib?",
        options: [
          "Throw J and A (unconnected; keep 6-7-8-9 for eight)",
          "Throw 6-9 (gives a fifteen)",
          "Throw 7-8 (a fifteen and a connector)",
          "Throw 8-9 (a ready-made run starter)",
        ],
        correctIndex: 0,
        explanation: "A Jack and an Ace make no fifteen together and start no run, and the 6-7-8-9 keep still scores eight.",
      },
      {
        id: "crib2-06-s2", label: "Hold the Five",
        situation: "It's the opponent's deal. Your six cards include a 5 and a 4-5-6 fragment.",
        hand: ["5♠", "4♥", "6♦", "9♣", "9♠", "K♦"],
        prompt: "What's the right defensive layaway?",
        options: [
          "Throw 5 and K (hands their crib a 5 and a ten)",
          "Throw 4-5 (gives the five and a connector)",
          "Throw 9 and K (no 5; keep 4-5-6-9 for seven)",
          "Throw 5-6 (gives the five)",
        ],
        correctIndex: 2,
        explanation: "Keep the 5 inside a seven-point hand (4-5-6-9) and throw the wide 9-K, so the opponent's crib never sees your five.",
      },
      {
        id: "crib2-06-s3", label: "The Danger Cards",
        situation: "You're listing the cards you most want to keep out of an enemy crib.",
        prompt: "Which cards are the worst to give the opponent's crib?",
        options: [
          "High cards only",
          "Fives, pairs, and connected cards",
          "Aces and twos",
          "Cards of different suits",
        ],
        correctIndex: 1,
        explanation: "Fives make fifteens with sixteen cards, pairs are a free two, and connectors make cheap fifteens and runs.",
      },
      {
        id: "crib2-06-s4", label: "Safer Throw",
        situation: "On the opponent's deal you must choose between two candidate throws.",
        prompt: "Which pair is safer to send to their crib?",
        options: [
          "5 and 6",
          "4 and 5",
          "6 and 7",
          "Jack and 4 (no 5, unconnected)",
        ],
        correctIndex: 3,
        explanation: "A Jack and a 4 make no fifteen between them and no run; the others all give the opponent a 5 or a connector.",
      },
    ],
  },

  "cribbage-2-07": {
    intro: "The best discard maximizes hand plus crib, not the hand alone. Add the crib on your deal, subtract it on theirs — sometimes a lower hand wins the total.",
    spots: [
      {
        id: "crib2-07-s1", label: "Same Hand, Better Crib",
        situation: "It's your deal. You hold a pair of fives and a 7-8-9-10 run.",
        hand: ["5♠", "5♥", "7♦", "8♣", "9♠", "10♥"],
        prompt: "Which layaway gives the highest combined total?",
        options: [
          "Keep 7-8-9-10, throw 5-5 to your crib (six in hand, loaded crib)",
          "Keep 5-5-7-10, throw 8-9 (same six, weaker crib)",
          "Keep 5-5-7-8, throw 9-10 (only four in hand)",
          "Keep 5-8-9-10, throw 5-7 (five in hand)",
        ],
        correctIndex: 0,
        explanation: "7-8-9-10 and 5-5-7-10 both score six in hand, but 5-5 in your own crib is worth far more than 8-9, so the total is higher.",
      },
      {
        id: "crib2-07-s2", label: "Sacrifice on Defense",
        situation: "It's the opponent's deal. Your six cards form a long 4-5-6-7-8-9 run.",
        hand: ["4♠", "5♥", "6♦", "7♣", "8♠", "9♥"],
        prompt: "What's the best defensive layaway?",
        options: [
          "Keep 6-7-8-9 (eight), throw 4-5 to their crib",
          "Keep 5-6-7-8 (six), throw 4-9 dead to their crib",
          "Keep 4-5-6-7, throw 8-9 (a connector to their crib)",
          "Keep 4-6-7-9, throw 5-8 (gives them a five)",
        ],
        correctIndex: 1,
        explanation: "6-7-8-9 scores two more, but throwing 4-5 to the opponent's crib gives back more than two; keep 5-6-7-8 and throw the dead 4-9.",
      },
      {
        id: "crib2-07-s3", label: "Why a Lower Hand",
        situation: "On defense you're tempted by the highest-scoring keep.",
        prompt: "Why might you keep a lower-scoring hand on the opponent's deal?",
        options: [
          "Lower hands always win",
          "It avoids a skunk",
          "Throwing the higher hand would force great cards into the opponent's crib",
          "It changes the starter",
        ],
        correctIndex: 2,
        explanation: "Sacrificing a hand point to throw dead cards instead of a 4-5 denies the opponent more than it costs.",
      },
      {
        id: "crib2-07-s4", label: "On Your Deal",
        situation: "It's your deal and you weigh breaking a hand to feed your crib.",
        prompt: "Why can breaking a hand to throw 5-5 to your crib be correct?",
        options: [
          "Because you must always keep the highest hand",
          "Because the crib never matters",
          "Because suits decide the total",
          "Because the combined hand-plus-crib total can be higher even if the hand is lower",
        ],
        correctIndex: 3,
        explanation: "On your deal the crib is added to your score, so a richer crib throw can outweigh a couple of lost hand points.",
      },
    ],
  },

  "cribbage-2-08": {
    intro: "Your four cards aren't the whole story — the starter joins them, and suits begin to matter. Read the flush, his nobs, and how the cut completes a hand.",
    spots: [
      {
        id: "crib2-08-s1", label: "Four-Flush",
        situation: "All four of your cards are spades; the starter is a heart.",
        hand: ["3♠", "6♠", "8♠", "K♠"],
        board: ["9♥"],
        prompt: "How many points does this hand score?",
        options: ["5", "6", "4", "8"],
        correctIndex: 1,
        explanation: "The four-card spade flush is 4 (the heart starter doesn't extend it), and 6+9 makes a fifteen (2) — 6 total.",
      },
      {
        id: "crib2-08-s2", label: "Run, Fifteen & Nobs",
        situation: "You hold the Jack of spades with a 4-5-6, and the cut is a spade 7.",
        hand: ["J♠", "4♥", "5♦", "6♣"],
        board: ["7♠"],
        prompt: "How many points does this hand score?",
        options: ["9", "8", "7", "10"],
        correctIndex: 0,
        explanation: "4+5+6 and J+5 are two fifteens (4), 4-5-6-7 is a run of four (4), and the J♠ matches the spade starter for his nobs (1) — 9.",
      },
      {
        id: "crib2-08-s3", label: "Crib Flush",
        situation: "Your crib shows four hearts plus a spade starter at the show.",
        prompt: "Does the flush score in the crib?",
        options: [
          "Yes, four hearts always score four in the crib",
          "Yes, it scores five",
          "No — a crib flush needs all five cards the same suit",
          "Only if the starter is a Jack",
        ],
        correctIndex: 2,
        explanation: "Unlike the hand, the crib only scores a flush when all five cards (including the starter) share a suit.",
      },
      {
        id: "crib2-08-s4", label: "His Nobs",
        situation: "You hold the Jack of diamonds and the starter cut is a diamond.",
        board: ["8♦"],
        prompt: "What do you score for the Jack?",
        options: [
          "Two points for his heels",
          "One point for his nobs",
          "Nothing",
          "Five for a flush",
        ],
        correctIndex: 1,
        explanation: "Holding the Jack of the starter's suit scores one for his nobs; his heels is the dealer's bonus for cutting a Jack.",
      },
    ],
  },

  "cribbage-2-09": {
    intro: "Your discard depends on your seat. The dealer owns the crib and throws aggressively; the pone feeds the enemy box and throws defensively. Same cards, opposite plays.",
    spots: [
      {
        id: "crib2-09-s1", label: "The Dealer",
        situation: "You're the dealer this hand, so the crib is yours to score.",
        prompt: "How can the dealer afford to discard?",
        options: [
          "By throwing only the lowest cards",
          "Defensively, like the pone",
          "Aggressively — fives and connectors — to build the crib they own",
          "By never throwing fives",
        ],
        correctIndex: 2,
        explanation: "Because the dealer scores the crib, combining cards thrown to it are points the dealer collects.",
      },
      {
        id: "crib2-09-s2", label: "The Pone",
        situation: "You're the non-dealer (pone), so the crib belongs to the opponent.",
        prompt: "How should the pone discard?",
        options: [
          "Throw fives to the crib",
          "Throw dead junk, since the crib belongs to the opponent",
          "Throw connectors to the crib",
          "Break the hand to load the crib",
        ],
        correctIndex: 1,
        explanation: "The pone feeds the opponent's crib, so cautious, dead throws limit what that box can score.",
      },
      {
        id: "crib2-09-s3", label: "As Dealer",
        situation: "It's your deal. You hold 5-6-7-8-9-10 and the crib is yours.",
        hand: ["5♠", "6♥", "7♦", "8♣", "9♠", "10♥"],
        prompt: "What's the strong dealer play?",
        options: [
          "Keep 5-6-7-8, throw 9-10",
          "Throw 6-7 to your crib",
          "Keep 7-8-9-10, throw 5-6",
          "Keep 6-7-8-9, throw 5-10 to your crib (eight in hand, 5-10 makes a fifteen)",
        ],
        correctIndex: 3,
        explanation: "6-7-8-9 scores eight, and as dealer you feed your own box: 5-10 is a built-in fifteen you will collect.",
      },
      {
        id: "crib2-09-s4", label: "As Pone",
        situation: "Same six cards — 5-6-7-8-9-10 — but now it's the opponent's deal.",
        hand: ["5♠", "6♥", "7♦", "8♣", "9♠", "10♥"],
        prompt: "What changes for the pone?",
        options: [
          "Keep 5-6-7-8 (six), throw 9-10 to deny the five",
          "Keep 6-7-8-9 (eight), throw 5-10 to their crib",
          "Keep 6-7-8-10, throw 5-9",
          "Keep 7-8-9-10, throw 5-6",
        ],
        correctIndex: 0,
        explanation: "Throwing 5-10 would gift the opponent's crib a fifteen; as pone, keep the five and throw 9-10 instead, losing only two hand points.",
      },
    ],
  },

  "cribbage-2-10": {
    intro: "At the top level the discard is nearly solved. A discard table averages each throw over every starter; the best one balances hand value against the crib.",
    spots: [
      {
        id: "crib2-10-s1", label: "What a Table Is",
        situation: "You're learning how experts study the layaway.",
        prompt: "What does a discard table tell you?",
        options: [
          "The average value of each two-card throw over all possible starters",
          "Which card will be cut",
          "The opponent's exact hand",
          "The order to play your cards",
        ],
        correctIndex: 0,
        explanation: "It averages each throw's outcome across every possible starter, identifying the discard with the best expectation.",
      },
      {
        id: "crib2-10-s2", label: "The Top Keep",
        situation: "It's your deal. You hold three fives, a Jack, a 4, and a 6.",
        hand: ["4♠", "5♥", "5♦", "6♣", "5♠", "J♦"],
        prompt: "Which keep scores the most in hand?",
        options: [
          "Keep 4-5-5-6 (twelve)",
          "Keep 5-5-6-J (six)",
          "Keep 5-5-5-J (fourteen)",
          "Keep 4-5-6-J (seven)",
        ],
        correctIndex: 2,
        explanation: "5-5-5-J scores fourteen: eight in fifteens (5+J three times plus 5+5+5) and the pair royal of fives (6). Throw 4-6 to your crib.",
      },
      {
        id: "crib2-10-s3", label: "The Objective",
        situation: "You're stating exactly what the best discard maximizes.",
        prompt: "What does the optimal discard maximize?",
        options: [
          "Only the hand value",
          "Only the crib",
          "The number of fives kept",
          "Hand value plus your crib, or minus the opponent's crib",
        ],
        correctIndex: 3,
        explanation: "Net expected value combines the hand with the crib, added on your deal and subtracted on the opponent's.",
      },
      {
        id: "crib2-10-s4", label: "Average Crib",
        situation: "You want a benchmark for how much the deal is worth.",
        prompt: "Roughly how many points is the dealer's crib worth on average?",
        options: [
          "About fifteen points",
          "About four to five points",
          "About twenty points",
          "Exactly zero",
        ],
        correctIndex: 1,
        explanation: "The crib averages roughly four to five points, which is why holding the deal is a real edge.",
      },
    ],
  },
};
