import type { ScenarioConfig } from "./types";

// Decision-Trainer scenarios for the Cribbage: Pegging Mastery epoch. Every spot
// is a deterministic, skill-based pegging decision — the correct line is the rule
// or +EV play taught in that stage, never luck. Pegging math is exact: the running
// total may reach 31 but never pass it; making the total exactly 15 or exactly 31
// each scores 2; pair=2, pair royal=6, double pair royal=12; runs score 1 per card
// (3+) for the last cards forming a consecutive set in any order; "go"/last card = 1.
// Face cards count 10, ace = 1. correctIndex and explanation are stripped
// server-side before reaching the client.
export const cribbage3Scenarios: Record<string, ScenarioConfig> = {
  "cribbage-3-01": {
    intro: "The play is a live scoreboard running from 0 to 31. Before any tactics, prove you can read it: take the 15s and 31s, know your pairs, and handle the go.",
    spots: [
      {
        id: "crib3-01-s1", label: "Make Fifteen",
        situation: "The opponent led a 9, so the running total is 9. It's your play.",
        hand: ["6♠", "2♦", "K♣"],
        board: ["9♥"],
        prompt: "Which card should you play?",
        options: ["The King", "The 2", "The 6 — makes 15 for 2", "Say 'go'"],
        correctIndex: 2,
        explanation: "9 + 6 = 15, pegging 2; the King (19) and 2 (11) score nothing.",
      },
      {
        id: "crib3-01-s2", label: "Hit Thirty-One",
        situation: "Three cards are down and the running total is 22. It's your play.",
        hand: ["9♠", "7♦", "5♣"],
        board: ["6♥", "K♠", "6♦"],
        prompt: "Which card scores here?",
        options: ["The 9 — makes 31 for 2", "The 7", "The 5", "Say 'go'"],
        correctIndex: 0,
        explanation: "22 + 9 = 31, scoring 2 and resetting the count; the 7 (29) and 5 (27) don't score.",
      },
      {
        id: "crib3-01-s3", label: "Pair the Card",
        situation: "The opponent just led a 4, so the running total is 4.",
        hand: ["4♥", "9♦", "J♣"],
        board: ["4♠"],
        prompt: "What's the best card to play?",
        options: ["The 9", "The Jack", "Say 'go'", "The 4 — pairs for 2"],
        correctIndex: 3,
        explanation: "Matching the just-played 4 scores 2 for the pair and keeps the total a safe 8.",
      },
      {
        id: "crib3-01-s4", label: "The Go",
        situation: "The running total is 28 and it's your turn. You hold only high cards.",
        hand: ["6♠", "9♦"],
        board: ["10♥", "8♣", "K♦"],
        prompt: "What must you do?",
        options: ["Play the 6", "Play the 9", "Say 'go' — neither card fits under 31", "Reset the count yourself"],
        correctIndex: 2,
        explanation: "28 + 6 = 34 and 28 + 9 = 37 both exceed 31, so you can't play — you say 'go'.",
      },
    ],
  },

  "cribbage-3-02": {
    intro: "The non-dealer's first card sets the whole sub-count. Lead a four or under so no single card can make 15 — and never, ever lead a 5.",
    spots: [
      {
        id: "crib3-02-s1", label: "The Opening Lead",
        situation: "You're the non-dealer and must lead the first card. The count is 0.",
        hand: ["5♠", "4♥", "J♦", "6♣"],
        prompt: "Which card is the safest opening lead?",
        options: ["The 5", "The 4 — safe, no single card can make 15 on it", "The Jack", "The 6"],
        correctIndex: 1,
        explanation: "A 4 would need an impossible 11 to be fifteened; the 5, Jack, and 6 each give the opponent an easy 15.",
      },
      {
        id: "crib3-02-s2", label: "Why Not a Five",
        situation: "You're on lead and consider opening with your 5.",
        hand: ["5♥", "3♠", "9♦", "K♣"],
        prompt: "Why is leading a 5 the worst possible opening?",
        options: [
          "It is against the rules",
          "It wastes your highest card",
          "It forces you to say 'go'",
          "Any of the sixteen ten-valued cards makes 15 on it for 2",
        ],
        correctIndex: 3,
        explanation: "A third of the deck — the four 10s plus twelve face cards — makes exactly 15 on a 5 lead for an easy 2.",
      },
      {
        id: "crib3-02-s3", label: "The Trap Lead",
        situation: "You're on lead and hold a pair of low cards.",
        hand: ["3♠", "3♥", "9♦", "K♣"],
        prompt: "Which lead is both safe and sets a trap?",
        options: ["The King", "The 3 — safe, and baits the opponent to pair into your pair royal", "The 9", "Say 'go'"],
        correctIndex: 1,
        explanation: "A 3 can't be fifteened by one card; if the opponent pairs it for 2, you re-pair the third 3 for pair royal (6).",
      },
      {
        id: "crib3-02-s4", label: "Pick the Lowest",
        situation: "You're on lead with four connected low-to-middle cards.",
        hand: ["4♠", "5♥", "6♦", "7♣"],
        prompt: "Which is the best lead?",
        options: ["The 4 — the lowest and safest lead", "The 5", "The 6", "The 7"],
        correctIndex: 0,
        explanation: "The 4 is the only card here that can't be fifteened by a single card; the 5, 6, and 7 all give an easy 15.",
      },
    ],
  },

  "cribbage-3-03": {
    intro: "Pairs and runs are the bread-and-butter pegs of the play. See the live sequence — the last cards down — and make the combination that scores, in any order.",
    spots: [
      {
        id: "crib3-03-s1", label: "Complete the Run",
        situation: "The last two cards played were a 7 then a 6; the running total is 13.",
        hand: ["5♠", "9♦", "K♣"],
        board: ["7♥", "6♠"],
        prompt: "What's the best card to play?",
        options: ["The 5 — completes 7-6-5 for a run of three (3)", "The 9", "The King", "Say 'go'"],
        correctIndex: 0,
        explanation: "The tail 7-6-5 is the consecutive set {5,6,7} — a run of three for 3; order doesn't matter.",
      },
      {
        id: "crib3-03-s2", label: "Extend the Run",
        situation: "A run is building: the last cards down are 4, 5, 6 and the running total is 15.",
        hand: ["3♠", "9♦", "K♣"],
        board: ["4♣", "5♥", "6♠"],
        prompt: "Which card scores the most?",
        options: ["The 9", "The 3 — extends to 3-4-5-6, a run of four (4)", "The King", "Say 'go'"],
        correctIndex: 1,
        explanation: "The 3 extends {4,5,6} to {3,4,5,6} for a run of four (4); it also keeps the total a legal 18.",
      },
      {
        id: "crib3-03-s3", label: "Pair Royal",
        situation: "You led a 9, the opponent paired it, and the running total is 18. You hold the last 9.",
        hand: ["9♠", "4♦", "2♣"],
        board: ["9♥", "9♦"],
        prompt: "What's the play?",
        options: ["The 4", "The 2", "The 9 — pair royal for 6", "Say 'go'"],
        correctIndex: 2,
        explanation: "The third 9 in a row scores pair royal (6) and keeps the total a legal 27.",
      },
      {
        id: "crib3-03-s4", label: "Stack the Score",
        situation: "The opponent played a 5 then a 6; the running total is 11.",
        hand: ["4♠", "7♦", "9♣"],
        board: ["5♥", "6♠"],
        prompt: "Which card scores the most?",
        options: ["The 9", "The 7 — makes a run of three (3)", "Say 'go'", "The 4 — makes 15 and a run of three for 5"],
        correctIndex: 3,
        explanation: "11 + 4 = 15 (2) and 4-5-6 is a run of three (3) — 5 points at once, beating the 7's run of three.",
      },
    ],
  },

  "cribbage-3-04": {
    intro: "Fifteen and thirty-one are the only totals that score by themselves. Take them when offered — and never leave the count where one card scores against you.",
    spots: [
      {
        id: "crib3-04-s1", label: "Take the Fifteen",
        situation: "The opponent led a 6, so the running total is 6.",
        hand: ["9♠", "3♦", "K♣"],
        board: ["6♥"],
        prompt: "Which card should you play?",
        options: ["The 3", "The 9 — makes 15 for 2", "The King", "Say 'go'"],
        correctIndex: 1,
        explanation: "6 + 9 = 15 for 2; the King (16) and 3 (9) score nothing.",
      },
      {
        id: "crib3-04-s2", label: "Take the Thirty-One",
        situation: "The running total is 24 and it's your play.",
        hand: ["7♠", "9♦", "K♣"],
        board: ["10♥", "9♣", "5♦"],
        prompt: "Which card scores here?",
        options: ["The 7 — makes 31 for 2", "The 9", "The King", "Say 'go'"],
        correctIndex: 0,
        explanation: "24 + 7 = 31 for 2; the 9 (33) and King (34) would both bust past 31.",
      },
      {
        id: "crib3-04-s3", label: "Dodge the Danger",
        situation: "The running total is 16 and no scoring play is available. It's your turn.",
        hand: ["5♠", "2♦", "K♣"],
        board: ["7♥", "9♠"],
        prompt: "Which is the safest play?",
        options: ["The 5", "The 2 — to 18, leaving no easy 15 or 31", "The King", "Say 'go'"],
        correctIndex: 1,
        explanation: "The 5 makes a deadly 21 (any ten -> 31) and the King makes 26 (a 5 -> 31); the 2 leaves a cold 18.",
      },
      {
        id: "crib3-04-s4", label: "Punish the Five",
        situation: "The opponent carelessly led a 5, so the running total is 5.",
        hand: ["10♠", "7♦", "3♣"],
        board: ["5♥"],
        prompt: "Which card scores?",
        options: ["The 7", "The 3", "Say 'go'", "The 10 — makes 15 for 2"],
        correctIndex: 3,
        explanation: "5 + 10 = 15, punishing their 5 lead for an easy 2 points.",
      },
    ],
  },

  "cribbage-3-05": {
    intro: "When you're ahead or it's the opponent's deal, switch to denial. Play the safe card, break adjacency to refuse runs, and push the count to force a go.",
    spots: [
      {
        id: "crib3-05-s1", label: "The Safe Card",
        situation: "The opponent led a 7, so the running total is 7. You have no scoring play.",
        hand: ["6♠", "9♦", "2♣"],
        board: ["7♥"],
        prompt: "Which is the safe card?",
        options: ["The 6", "The 9", "The 2 — breaks adjacency, denying any run", "Say 'go'"],
        correctIndex: 2,
        explanation: "The 6 and 9 sit beside the 7 and let a 5/8 build a run; the 2 leaves nothing consecutive — the safe card.",
      },
      {
        id: "crib3-05-s2", label: "Force the Go",
        situation: "The running total is 20 and you can't make an exact 31 (you'd need an 11).",
        hand: ["8♠", "3♦", "K♣"],
        board: ["K♥", "10♠"],
        prompt: "What's the defensive play?",
        options: ["The 3", "The 8", "Say 'go'", "The King — to 30, forcing a likely go"],
        correctIndex: 3,
        explanation: "The King pushes the total to 30, so the opponent needs an ace to play — most likely they say 'go' and you peg 1.",
      },
      {
        id: "crib3-05-s3", label: "Pair or Play the Ten?",
        situation: "The opponent led a 5, so the running total is 5. You could pair it or play a ten.",
        hand: ["5♠", "10♦", "2♣"],
        board: ["5♥"],
        prompt: "What's the safer way to score?",
        options: ["Pair the 5 for 2", "Play the 10 — makes 15 for 2 and avoids the pair-royal risk", "Play the 2", "Say 'go'"],
        correctIndex: 1,
        explanation: "Both score 2, but pairing a 5 invites the opponent's third 5 for pair royal AND a 15; the ten makes 15 safely.",
      },
      {
        id: "crib3-05-s4", label: "Refuse the Pair",
        situation: "You hold a comfortable lead late in the game and could pair the opponent's 9 for 2 — but they may hold the other two 9s.",
        prompt: "What's the disciplined play?",
        options: [
          "Always pair for the 2",
          "Pair and hope for the best",
          "Play a safe non-pairing card to deny a possible pair royal",
          "Say 'go' even though you can play",
        ],
        correctIndex: 2,
        explanation: "Protecting a lead, denying a 6-point pair royal is worth more than grabbing a risky 2 — play safe.",
      },
    ],
  },

  "cribbage-3-06": {
    intro: "When you need pegs, go on offense — and bait the opponent's mistake. Spring the pair trap, extend the run, and stack a fifteen with a run for a big single peg.",
    spots: [
      {
        id: "crib3-06-s1", label: "Set the Trap",
        situation: "You're on lead and hold a pair of 4s. The count is 0.",
        hand: ["4♠", "4♥", "8♦", "A♣"],
        prompt: "Which lead is safe and also sets a trap?",
        options: ["Lead a 4 — safe, and if paired you re-pair for pair royal (6)", "Lead the 8", "Lead the ace", "Say 'go'"],
        correctIndex: 0,
        explanation: "A 4 can't be fifteened by one card; if the opponent pairs it for 2, your second 4 makes pair royal (6) for a net +4.",
      },
      {
        id: "crib3-06-s2", label: "Spring It",
        situation: "You led an 8 from a pair, the opponent paired it for 2, and the running total is 16. You hold the third 8.",
        hand: ["8♠", "3♦", "A♣"],
        board: ["8♥", "8♦"],
        prompt: "What's your payoff play?",
        options: ["The 3", "The 8 — pair royal for 6", "Say 'go'", "The ace"],
        correctIndex: 1,
        explanation: "The third 8 scores pair royal (6) on top of their 2, netting +4 and keeping the total a legal 24.",
      },
      {
        id: "crib3-06-s3", label: "Win the Run Race",
        situation: "A run is on the table: the last cards down are 5, 6, 7 and the running total is 18.",
        hand: ["8♠", "K♦", "2♣"],
        board: ["5♣", "6♥", "7♠"],
        prompt: "Which card scores the most?",
        options: ["The King", "The 2", "The 8 — extends to 5-6-7-8 for a run of four (4)", "Say 'go'"],
        correctIndex: 2,
        explanation: "The 8 completes the run of four (4) and keeps the total a legal 26; the completer scores the run's full length.",
      },
      {
        id: "crib3-06-s4", label: "Cash the Trap",
        situation: "You led a 4 from a pair, the opponent paired it (total 8) for 2, and you still hold the third 4.",
        hand: ["4♥", "9♦"],
        board: ["4♦", "4♠"],
        prompt: "What's the play?",
        options: ["Concede the 2", "Play the 9", "Say 'go'", "Play your third 4 — pair royal for 6, netting +4"],
        correctIndex: 3,
        explanation: "The third 4 makes pair royal (6) over their 2 — the trap pays off at +4, total a legal 12.",
      },
    ],
  },

  "cribbage-3-07": {
    intro: "Which card you keep matters as much as which you play. Hold a low card in reserve to make an exact 31, grab the go, and pocket the last-card point.",
    spots: [
      {
        id: "crib3-07-s1", label: "The Held Ace",
        situation: "The running total is 30 and it's your play.",
        hand: ["A♠", "9♦"],
        board: ["10♥", "K♠", "Q♣"],
        prompt: "Which card can you play?",
        options: ["The ace — makes 31 for 2", "The 9", "Say 'go'", "Either card"],
        correctIndex: 0,
        explanation: "At 30 only an ace keeps the total at or under 31 — and 30 + 1 = 31 scores 2; the 9 would bust at 39.",
      },
      {
        id: "crib3-07-s2", label: "Why Hold Back",
        situation: "Early in a sub-count you weigh whether to spend a small card now.",
        prompt: "Why keep a low card like an ace or 2 in reserve?",
        options: [
          "To win more fifteens",
          "To reach exactly 31 or grab the last-card / go point later",
          "To make a flush",
          "To force a redeal",
        ],
        correctIndex: 1,
        explanation: "Low cards still play when the count climbs near 31, letting you peg 31 or take the go that others concede.",
      },
      {
        id: "crib3-07-s3", label: "Sequence It",
        situation: "The opponent led a 5, so the running total is 5. You hold a 4 and two 9s.",
        hand: ["4♠", "9♦", "9♣"],
        board: ["5♥"],
        prompt: "How do you sequence your cards?",
        options: ["Play both 9s at once", "Play the 4 first", "Keep the 4 in reserve and play a 9 now", "Say 'go'"],
        correctIndex: 2,
        explanation: "Spend a high 9 while the count is low and hold the flexible 4 as your 31/go card for the endgame.",
      },
      {
        id: "crib3-07-s4", label: "Don't Burn the Ace",
        situation: "The running total is 12 and you hold an ace, a 7, and a King.",
        hand: ["A♠", "7♦", "K♣"],
        board: ["7♥", "5♠"],
        prompt: "What's the best play to preserve a reserve card?",
        options: ["Play the ace now", "Say 'go'", "Play the 7", "Play the King and keep the ace as a 31/go card"],
        correctIndex: 3,
        explanation: "Spend the high King now (total 22) and hold the ace, which can still play when the count climbs near 31.",
      },
    ],
  },

  "cribbage-3-08": {
    intro: "Expert pegging is partly bookkeeping. Track the running total exactly, remember the cards already played, and reason about what the opponent must still hold.",
    spots: [
      {
        id: "crib3-08-s1", label: "Track to 31",
        situation: "You've tracked the running total carefully — it's 28. It's your play.",
        hand: ["3♠", "J♦"],
        board: ["9♥", "9♠", "10♣"],
        prompt: "Which card scores?",
        options: ["The 3 — makes 31 for 2", "The Jack", "Say 'go'", "Either card"],
        correctIndex: 0,
        explanation: "28 + 3 = 31 for 2; the Jack (10) would bust at 38, so the tracked count points straight to the 3.",
      },
      {
        id: "crib3-08-s2", label: "Count the Rank",
        situation: "You hold two 5s, and a 5 was cut as the starter.",
        hand: ["5♠", "5♥"],
        board: ["5♦"],
        prompt: "How many 5s can the opponent possibly hold?",
        options: ["Two", "At most one (three are accounted for)", "Three", "Four"],
        correctIndex: 1,
        explanation: "Three of the four 5s are visible to you, so the opponent can hold at most one — a pair royal of 5s is impossible.",
      },
      {
        id: "crib3-08-s3", label: "Cards Remaining",
        situation: "Each player started the play with four cards, and six cards are now on the table.",
        prompt: "How many cards remain to be played?",
        options: ["Four", "Three", "Two — one in each hand", "One"],
        correctIndex: 2,
        explanation: "Eight cards are played in a deal; after six, exactly two remain, one in each hand.",
      },
      {
        id: "crib3-08-s4", label: "Danger Lifts",
        situation: "You've counted the deck and know every ten-valued card has already been played. The running total is 16, and playing your 5 would leave it at 21.",
        hand: ["5♠", "9♦"],
        board: ["7♥", "9♠"],
        prompt: "Is leaving the count at 21 safe now?",
        options: [
          "No, never leave 21",
          "Only if you also hold a 5",
          "No, 21 is always fatal",
          "Yes — with all tens gone, no card can make 31 off 21",
        ],
        correctIndex: 3,
        explanation: "21 is dangerous only because a ten makes 31; once all sixteen tens are spent, the total is cold.",
      },
    ],
  },

  "cribbage-3-09": {
    intro: "How you peg should match what your hand is worth. A weak hand needs pegs, so you gamble; a strong hand or a lead is worth protecting, so you deny.",
    spots: [
      {
        id: "crib3-09-s1", label: "Weak Hand",
        situation: "Your four cards will count only 2 points at the show.",
        prompt: "How should you approach the play?",
        options: [
          "Take more risk — a weak hand means you need pegging points",
          "Play it perfectly safe",
          "Fold the hand",
          "Throw the game",
        ],
        correctIndex: 0,
        explanation: "When your hand won't score at the show, the play is your scoring engine — gamble for the pegs you need.",
      },
      {
        id: "crib3-09-s2", label: "Strong Hand",
        situation: "Your hand is a lock for 16 at the show and you lead the game.",
        prompt: "How should you peg?",
        options: [
          "Gamble for every peg",
          "Play safe — you don't need pegs, so deny the opponent",
          "Lead your 5",
          "Say 'go' on purpose",
        ],
        correctIndex: 1,
        explanation: "A strong hand and a lead are worth protecting; don't risk points you don't need — let the show carry you.",
      },
      {
        id: "crib3-09-s3", label: "Weak-Hand Pair",
        situation: "Your hand is weak. The opponent leads a 6, so the running total is 6, and you hold a 6.",
        hand: ["6♠", "9♦", "K♣"],
        board: ["6♥"],
        prompt: "What's the right play for a weak hand?",
        options: ["Play a safe card", "Say 'go'", "Pair the 6 — grab the 2 your weak hand needs", "Hold the 6"],
        correctIndex: 2,
        explanation: "With a weak hand you take the available pair for 2 (total a safe 12) — you need the points more than the safety.",
      },
      {
        id: "crib3-09-s4", label: "Guard the Win",
        situation: "You need only a few points to win and your hand counts plenty.",
        prompt: "How should you peg the play?",
        options: [
          "Take wild risks for more pegs",
          "Lead a 5",
          "Pair every card you can",
          "Play safe and avoid giving the opponent pegs that could win it first",
        ],
        correctIndex: 3,
        explanation: "Protecting a near-certain win, deny the opponent any peg that could let them count out before you.",
      },
    ],
  },

  "cribbage-3-10": {
    intro: "Near 121 the play becomes the finish line. Pegs win the instant they're made — so a fifteen or a go can end the game before the show, and the player on the brink must be denied everything.",
    spots: [
      {
        id: "crib3-10-s1", label: "Peg to Win",
        situation: "You're at 119 (you need 2 to win) and the play offers you a fifteen for 2.",
        prompt: "Do you take it?",
        options: [
          "Yes — pegging to 121 wins immediately, no waiting for the show",
          "No, save the points for the show",
          "Only if you are the dealer",
          "Pegs don't count at 119",
        ],
        correctIndex: 0,
        explanation: "Pegs score live; reaching 121 in the play wins on the spot — there is no saving it for the show.",
      },
      {
        id: "crib3-10-s2", label: "Deny the Out",
        situation: "The opponent needs just 1 point to win and is on lead; you're the dealer.",
        prompt: "What's your priority in the play?",
        options: [
          "Score your own hand",
          "Deny every peg — even one point ends the game for them",
          "Aim for a skunk",
          "Save cards for the crib",
        ],
        correctIndex: 1,
        explanation: "When the opponent is one peg from winning, refuse every possible point — a single go or fifteen loses the game.",
      },
      {
        id: "crib3-10-s3", label: "The Winning Card",
        situation: "You're at 119, the running total is 13, and you hold a 2 and a 9.",
        hand: ["2♠", "9♦"],
        board: ["6♥", "7♣"],
        prompt: "Which card wins the game?",
        options: ["The 9", "Say 'go'", "The 2 — makes 15 for 2 and reaches 121", "Either card"],
        correctIndex: 2,
        explanation: "13 + 2 = 15 pegs 2, bringing you to 121 for the win; the 9 only reaches 22 with no score.",
      },
      {
        id: "crib3-10-s4", label: "Peg Out at 31",
        situation: "You need 1 point to win, the running total is 30, and you hold an ace and a King.",
        hand: ["A♠", "K♣"],
        board: ["Q♥", "J♠", "10♦"],
        prompt: "What's the play?",
        options: ["Concede the game", "Say 'go'", "Play the King", "Play the ace — to 31 for 2, pegging out to win"],
        correctIndex: 3,
        explanation: "At 30 the King (10) busts; the ace makes 31 for 2, more than enough to reach the finish and win.",
      },
    ],
  },
};
