import type { ScenarioConfig } from "./types";

// "Count the Hand" Decision-Trainer scenarios for the Cribbage epoch.
// Each spot is a deterministic, skill-based decision — the correct line is the
// rule or +EV play taught in that stage, never luck. Cribbage scoring here is
// exact: fifteens = 2 per distinct combo summing to 15 (A=1, faces=10); pair=2,
// pair royal=6, double pair royal=12; runs = 1 per card (3+); flush of 4 in
// hand=4 (5 with starter); his nobs=1 for the held Jack of the starter's suit.
// correctIndex and explanation are stripped server-side before the client.
export const cribbage1Scenarios: Record<string, ScenarioConfig> = {
  "cribbage-1-01": {
    intro: "Pull up a chair at the cribbage board. Before any cards are counted, lock in what the game actually is — the object, the race, and how it's scored.",
    spots: [
      {
        id: "crib-01-s1", label: "The Finish",
        situation: "Two players sit down at a standard cribbage board and start a fresh game.",
        prompt: "What is the standard target score that wins a game of cribbage?",
        options: ["61 points", "100 points", "121 points", "52 points"],
        correctIndex: 2,
        explanation: "Standard cribbage is a race to 121 ('twice around' the board); some short games go to 61.",
      },
      {
        id: "crib-01-s2", label: "Keeping Score",
        situation: "You score a few points and reach for the board.",
        prompt: "How is the score traditionally kept in cribbage?",
        options: [
          "By moving pegs along holes on a wooden board",
          "With pencil and paper only",
          "By keeping won cards as tricks",
          "On a dartboard",
        ],
        correctIndex: 0,
        explanation: "Cribbage's signature is the pegging board — score is tracked by moving pegs along rows of holes.",
      },
      {
        id: "crib-01-s3", label: "Two Phases",
        situation: "A single deal is dealt, played out, and then revealed.",
        prompt: "When do you score points during one deal?",
        options: [
          "Only at the show (counting)",
          "During the play (pegging) AND at the show (counting)",
          "Only while the cards are being dealt",
          "Only if you win the deal",
        ],
        correctIndex: 1,
        explanation: "Every deal scores twice: you peg points during the play, then count points at the show.",
      },
      {
        id: "crib-01-s4", label: "The Table",
        situation: "You're learning the classic form of the game.",
        prompt: "What is the classic number of players for cribbage?",
        options: ["Exactly four", "Six", "Only one", "Two (the classic game)"],
        correctIndex: 3,
        explanation: "Cribbage is classically a two-player game, though it adapts well to three or four.",
      },
    ],
  },

  "cribbage-1-02": {
    intro: "Every deal has the same shape: six cards each, two thrown to the crib, a card cut to start. Get the mechanics right and the rest of the game follows.",
    spots: [
      {
        id: "crib-02-s1", label: "The Deal",
        situation: "It's a two-handed game and the dealer is handing out cards.",
        prompt: "How many cards is each player dealt?",
        options: ["Six", "Five", "Four", "Seven"],
        correctIndex: 0,
        explanation: "Each player gets six cards, then discards two to the crib, keeping four.",
      },
      {
        id: "crib-02-s2", label: "The Crib",
        situation: "Both players have laid away two cards into the crib (the 'box').",
        hand: ["5♠", "5♥"],
        prompt: "Who gets to count the crib at the show?",
        options: ["The non-dealer", "The dealer", "Both players split it", "Nobody"],
        correctIndex: 1,
        explanation: "The crib belongs to the dealer alone — the main reason holding the deal is an advantage.",
      },
      {
        id: "crib-02-s3", label: "His Heels",
        situation: "The non-dealer cuts the deck and the dealer flips the top card of the lower half.",
        board: ["J♦"],
        prompt: "The starter cut is a Jack. What happens immediately?",
        options: [
          "Nothing happens",
          "The hand is redealt",
          "The non-dealer pegs 2 points",
          "The dealer pegs 2 points for 'his heels'",
        ],
        correctIndex: 3,
        explanation: "A Jack turned as the starter scores 'his heels' — 2 points pegged by the dealer right away.",
      },
      {
        id: "crib-02-s4", label: "The Starter",
        situation: "A 9 is cut as the starter card and sits face-up on the deck.",
        board: ["9♣"],
        prompt: "How is the starter card used?",
        options: [
          "Only the dealer may use it",
          "It is discarded before play",
          "As a shared fifth card for both hands and the crib at the show",
          "It replaces each player's worst card",
        ],
        correctIndex: 2,
        explanation: "The starter is shared — it counts as a fifth card for both players' hands and the crib when counting.",
      },
    ],
  },

  "cribbage-1-03": {
    intro: "At the show you build a five-card hand from your four cards plus the starter and count everything it contains. Add them in order — fifteens, pairs, runs, flush, nobs — and miss nothing.",
    spots: [
      {
        id: "crib-03-s1", label: "Count It Up",
        situation: "At the show you reveal your four cards and add the starter.",
        hand: ["9♥", "6♠", "8♦", "7♣"],
        board: ["5♠"],
        prompt: "How many points does this five-card hand score in total?",
        options: ["5", "7", "11", "9"],
        correctIndex: 3,
        explanation: "Run of five (5-6-7-8-9 = 5) plus two fifteens (6+9, 7+8 = 4) totals 9 points.",
      },
      {
        id: "crib-03-s2", label: "Pairs & Fifteens",
        situation: "Your hand and the starter together make a tidy, dense count.",
        hand: ["7♥", "8♠", "7♣", "8♦"],
        board: ["10♥"],
        prompt: "What is the total for this hand?",
        options: ["12", "8", "16", "6"],
        correctIndex: 0,
        explanation: "Four fifteens (each 7 with each 8 = 8) plus two pairs (7-7 and 8-8 = 4) make 12.",
      },
      {
        id: "crib-03-s3", label: "His Nobs",
        situation: "You hold a Jack, and the starter is a spade.",
        hand: ["J♠", "2♥", "3♦", "Q♣"],
        board: ["7♠"],
        prompt: "What does this hand score?",
        options: ["2", "4", "5", "6"],
        correctIndex: 2,
        explanation: "Two fifteens (2+3+J, 2+3+Q = 4) plus 'his nobs' for the J♠ matching the spade starter (1) = 5.",
      },
      {
        id: "crib-03-s4", label: "Who Counts First",
        situation: "The play is over and it's time to count hands at the show.",
        prompt: "Whose hand is counted and pegged first?",
        options: [
          "The dealer",
          "The non-dealer",
          "The crib is counted first",
          "Whoever pegged more during the play",
        ],
        correctIndex: 1,
        explanation: "The non-dealer counts first, then the dealer, then the crib — which can decide a close game.",
      },
    ],
  },

  "cribbage-1-04": {
    intro: "Fifteens are the heartbeat of cribbage: every distinct group of cards totaling 15 pips scores 2. Aces are 1, all face cards are 10 — learn to spot every combination.",
    spots: [
      {
        id: "crib-04-s1", label: "Spot the Fifteens",
        situation: "You look at four cards and scan for every combination summing to 15.",
        hand: ["6♦", "9♣", "7♠", "8♥"],
        prompt: "How many fifteens does this hand make, and for how many points?",
        options: ["One (2 points)", "Two (4 points)", "Three (6 points)", "Zero"],
        correctIndex: 1,
        explanation: "6+9 = 15 and 7+8 = 15 — two distinct fifteens, worth 4 points.",
      },
      {
        id: "crib-04-s2", label: "Stacked Fives",
        situation: "Three fives sit alongside a ten-card.",
        hand: ["5♠", "5♥", "5♦", "10♣"],
        prompt: "How many fifteens are in this hand (ignore the pairs)?",
        options: ["One (2 points)", "Two (4 points)", "Four (8 points)", "Three (6 points)"],
        correctIndex: 2,
        explanation: "Each 5 with the 10 makes 15 (three of them) plus 5+5+5 = 15 — four fifteens, 8 points.",
      },
      {
        id: "crib-04-s3", label: "Card Values",
        situation: "You need an ace's pip value to add up a fifteen.",
        hand: ["A♠", "K♥", "4♦", "10♣"],
        prompt: "What is an ace worth when counting fifteens?",
        options: ["1 (always low)", "11", "Either 1 or 11", "10"],
        correctIndex: 0,
        explanation: "The ace is always 1 in cribbage — here A+4+10 = 15 — and is never worth 11.",
      },
      {
        id: "crib-04-s4", label: "The Best Card",
        situation: "Sixteen of the 52 cards (four tens plus twelve face cards) count as 10.",
        prompt: "Which single card is the most valuable for making fifteens?",
        options: ["The Ace", "The King", "The 10", "The 5"],
        correctIndex: 3,
        explanation: "Every 5 pairs with all sixteen ten-valued cards to make a fifteen — unmatched scoring power.",
      },
    ],
  },

  "cribbage-1-05": {
    intro: "Beyond fifteens come runs, pairs, and flushes. Know the exact values — pair royal is 6, four of a kind is 12, runs score one per card — all the way up to the legendary 29.",
    spots: [
      {
        id: "crib-05-s1", label: "Pair Royal",
        situation: "Your hand contains three cards of the same rank.",
        hand: ["8♠", "8♥", "8♦", "2♣"],
        prompt: "How many points is three of a kind ('pair royal') worth?",
        options: ["2", "3", "6", "9"],
        correctIndex: 2,
        explanation: "Three of a kind contains three separate pairs, so it scores 6 — 'pair royal'.",
      },
      {
        id: "crib-05-s2", label: "Double Pair Royal",
        situation: "You turn over four cards of the same rank.",
        hand: ["8♠", "8♥", "8♦", "8♣"],
        prompt: "What does four of a kind score?",
        options: ["12", "8", "4", "16"],
        correctIndex: 0,
        explanation: "Four of a kind makes six pairs, scoring 12 — 'double pair royal' (the 8s make no fifteen).",
      },
      {
        id: "crib-05-s3", label: "The Perfect Hand",
        situation: "You hold three fives and a Jack, and the fourth five — matching the Jack's suit — is cut as the starter.",
        hand: ["5♥", "5♠", "5♣", "J♦"],
        board: ["5♦"],
        prompt: "What does this famous hand score?",
        options: [
          "A pair royal, 6 points",
          "31, an illegal hand",
          "Just 12 points",
          "29 — the highest possible hand",
        ],
        correctIndex: 3,
        explanation: "Eight fifteens (16) + four 5s as double pair royal (12) + his nobs for the J♦ matching the ♦ starter (1) = 29.",
      },
      {
        id: "crib-05-s4", label: "The Flush",
        situation: "All four of your cards share a suit, but the starter is a different suit.",
        hand: ["2♠", "6♠", "9♠", "K♠"],
        board: ["4♥"],
        prompt: "How many points does the flush score?",
        options: ["5", "4", "0", "1"],
        correctIndex: 1,
        explanation: "Four matching suits in hand score 4; it would be 5 only if the starter were also a spade.",
      },
    ],
  },

  "cribbage-1-06": {
    intro: "Before the show, the cards are played out. Players alternate, keeping a running total that may never pass 31, scoring along the way for 15, 31, pairs, and runs. Pick the card that scores.",
    spots: [
      {
        id: "crib-06-s1", label: "Make Fifteen",
        situation: "The running total stands at 10 and it's your turn to play.",
        hand: ["5♠", "8♣", "K♦"],
        board: ["7♥", "3♦"],
        prompt: "Which card should you play?",
        options: [
          "The 5 — makes the total 15 for 2",
          "The 8",
          "The King",
          "Say 'go'",
        ],
        correctIndex: 0,
        explanation: "Playing the 5 brings the total to exactly 15, pegging 2 points.",
      },
      {
        id: "crib-06-s2", label: "Pair the Card",
        situation: "Your opponent just laid a 7; the running total is 7.",
        hand: ["9♥", "2♣", "7♠"],
        board: ["7♦"],
        prompt: "What's the best card to play?",
        options: [
          "The 9",
          "The 2",
          "Say 'go'",
          "The 7 — pairs the opponent's card for 2",
        ],
        correctIndex: 3,
        explanation: "Matching the just-played rank scores 2 for the pair (it also keeps the total a safe 14).",
      },
      {
        id: "crib-06-s3", label: "Hit Thirty-One",
        situation: "The running total is 21 and it's your play.",
        hand: ["4♥", "10♠", "6♣"],
        board: ["J♦", "A♣"],
        prompt: "Which card scores here?",
        options: [
          "The 4",
          "The 10 — makes the total 31 for 2",
          "The 6",
          "Say 'go'",
        ],
        correctIndex: 1,
        explanation: "Playing the 10 brings the total to exactly 31, scoring 2 (and resetting the count).",
      },
      {
        id: "crib-06-s4", label: "Run in Play",
        situation: "The last two cards played were a 5 then a 4; the running total is 9.",
        hand: ["9♦", "2♥", "6♣"],
        board: ["5♥", "4♠"],
        prompt: "What's the best card to play?",
        options: [
          "The 9",
          "The 2",
          "The 6 — a run of three AND fifteen for 5",
          "Say 'go'",
        ],
        correctIndex: 2,
        explanation: "The 6 makes 4-5-6 (a run of three = 3) and brings the total to 15 (= 2) for 5 points at once.",
      },
    ],
  },

  "cribbage-1-07": {
    intro: "Every card you play either offers your opponent a score or denies one. Lead safely, avoid handing over fifteens and 31s, and bait traps when the moment is right.",
    spots: [
      {
        id: "crib-07-s1", label: "The Lead",
        situation: "You're the non-dealer and must lead the first card of the play.",
        hand: ["5♠", "4♥", "J♦", "6♣"],
        prompt: "Which card is the safest opening lead?",
        options: ["The 5", "The 4", "The Jack", "The 6"],
        correctIndex: 1,
        explanation: "Lead a low card like the 4 — never the 5, which any ten-card turns into 15 for an easy 2.",
      },
      {
        id: "crib-07-s2", label: "Why Not a Five",
        situation: "You consider leading a 5 to open the play.",
        hand: ["5♥", "3♠", "9♦", "K♣"],
        prompt: "Why is leading a 5 the worst opening?",
        options: [
          "It is against the rules",
          "It wastes your highest card",
          "Any of the sixteen ten-cards makes 15 on it for 2",
          "It forces you to say 'go'",
        ],
        correctIndex: 2,
        explanation: "A 5 lead lets any of the deck's sixteen ten-valued cards reach exactly 15 for an easy 2 points.",
      },
      {
        id: "crib-07-s3", label: "The Pair Trap",
        situation: "You hold a pair of 8s and lead one of them.",
        hand: ["8♠", "8♥", "3♦", "A♣"],
        prompt: "What's the idea behind leading from a pair?",
        options: [
          "If the opponent pairs it, you play your second 8 for pair royal (6)",
          "It guarantees a run",
          "It reaches 31 automatically",
          "It blocks all scoring",
        ],
        correctIndex: 0,
        explanation: "Leading one of a pair baits a pairing for 2; you re-pair with the third card for pair royal (6), netting +4.",
      },
      {
        id: "crib-07-s4", label: "Pick Your Mode",
        situation: "You hold a comfortable lead and it's the opponent's deal (their crib).",
        prompt: "When should you peg defensively, conceding small points to deny big ones?",
        options: [
          "Always, no matter the score",
          "Only on the first deal",
          "Only when you hold a 5",
          "When you are ahead or it's the opponent's crib",
        ],
        correctIndex: 3,
        explanation: "Protect a lead and starve the opponent's crib by playing safe; gamble for pegs only when behind.",
      },
    ],
  },

  "cribbage-1-08": {
    intro: "The two cards you throw each deal are a real decision. The first question is always: whose crib is it? Feed your own box, starve your opponent's.",
    spots: [
      {
        id: "crib-08-s1", label: "Feed Your Crib",
        situation: "It's your deal, so the crib is yours. You want to throw cards that combine for points.",
        prompt: "Which pair of discards best fuels your own crib?",
        options: ["2-9", "8-3", "King-2", "5-5"],
        correctIndex: 3,
        explanation: "5-5 is classic crib fuel — two fives plus the many ten-cards (and the starter) make abundant fifteens.",
      },
      {
        id: "crib-08-s2", label: "Starve Their Crib",
        situation: "It's the opponent's deal, so the crib is theirs. You want to throw dead cards.",
        prompt: "Which is the safest throw into the OPPONENT'S crib?",
        options: [
          "King and 2 (unconnected, different suits)",
          "5 and 5",
          "7 and 8",
          "4 and 5",
        ],
        correctIndex: 0,
        explanation: "A King and a 2 rarely combine for anything; the others all make easy fifteens or runs for the opponent.",
      },
      {
        id: "crib-08-s3", label: "Guard the Five",
        situation: "On the opponent's deal you're tempted to dump a lone 5.",
        prompt: "Why should you avoid throwing a 5 into the opponent's crib?",
        options: [
          "5s are worthless cards",
          "It is against the rules",
          "A 5 combines with the many ten-cards for easy fifteens",
          "It immediately ends the game",
        ],
        correctIndex: 2,
        explanation: "The 5 is the best fifteen-maker in the deck, so it's the worst card to hand to an opponent's crib.",
      },
      {
        id: "crib-08-s4", label: "The Balance",
        situation: "You weigh which two cards to lay away each deal.",
        prompt: "Good discarding balances which two things?",
        options: [
          "Your pegs versus the opponent's pegs",
          "The value of the four cards you keep versus what your two discards do to the crib",
          "The suits versus the ranks",
          "Your score versus the size of the deck",
        ],
        correctIndex: 1,
        explanation: "Every layaway weighs the points in your kept hand against the crib effect of the two cards you throw.",
      },
    ],
  },

  "cribbage-1-09": {
    intro: "The board is where the drama lives. Pegging up its tracks, the dreaded skunk line, the muggins rule, and the two-peg leapfrog turn raw points into a real game.",
    spots: [
      {
        id: "crib-09-s1", label: "The Skunk",
        situation: "You reach 121 while your opponent is still stuck below the 91-hole line.",
        prompt: "What is this big a margin called?",
        options: [
          "Cutting a Jack",
          "Pegging exactly 31",
          "A skunk — winning while the opponent is 31+ points short",
          "Losing on the final hand",
        ],
        correctIndex: 2,
        explanation: "A skunk is winning before the opponent reaches 91 (31+ short), usually counting as a double game.",
      },
      {
        id: "crib-09-s2", label: "Muggins",
        situation: "Your opponent counts their hand aloud and announces fewer points than it actually contains.",
        prompt: "Under the optional 'muggins' rule, what may you do?",
        options: [
          "Force a replay of the deal",
          "Peg the points they failed to count in their own hand",
          "Make them skip a turn",
          "Double your own score",
        ],
        correctIndex: 1,
        explanation: "Muggins lets an alert opponent claim the points the counter missed — a reason to count carefully.",
      },
      {
        id: "crib-09-s3", label: "The Leapfrog",
        situation: "You just scored 6 points and reach for the board to peg it.",
        prompt: "In the two-peg system, which peg do you move?",
        options: [
          "The front peg, backward",
          "Both pegs together",
          "Neither — you use a pencil",
          "The back peg, ahead of the front by your latest score",
        ],
        correctIndex: 3,
        explanation: "You leapfrog the back peg ahead of the front by your latest score, leaving an honest record of the move.",
      },
      {
        id: "crib-09-s4", label: "The Finish Line",
        situation: "Your peg is at hole 119 and you score 4 points.",
        prompt: "Do you have to land exactly on hole 121 to win?",
        options: [
          "No — reaching or passing 121 wins",
          "Yes, you must land on exactly 121",
          "Yes, then you peg back down",
          "No, you actually need 124",
        ],
        correctIndex: 0,
        explanation: "The first peg to reach or pass hole 121 wins; an exact landing is not required.",
      },
    ],
  },

  "cribbage-1-10": {
    intro: "At the top level, cribbage is a game of expected values and odds. Masters know the average value of every discard, the rough par for a hand, and how to pick the best-scoring keep.",
    spots: [
      {
        id: "crib-10-s1", label: "Discard by EV",
        situation: "You hold six cards and must choose the best two to throw.",
        prompt: "How do expert players decide which two cards to discard?",
        options: [
          "The throw with the best average value over all possible starter cards",
          "Always keep the highest cards",
          "Throw two cards at random",
          "Keep whatever is suited",
        ],
        correctIndex: 0,
        explanation: "Masters pick the discard with the highest expected value, averaged across every possible starter card.",
      },
      {
        id: "crib-10-s2", label: "The 26 Theory",
        situation: "You want a benchmark for whether you're keeping pace toward 121.",
        prompt: "Roughly what per-round point target does the '26 theory' suggest for the dealer?",
        options: [
          "About 10 points",
          "About 60 points",
          "Exactly 15 points",
          "About 26 points per round",
        ],
        correctIndex: 3,
        explanation: "The '26 theory' uses about 26 points per round (hand, crib, and pegging) as a par benchmark.",
      },
      {
        id: "crib-10-s3", label: "Best Keep",
        situation: "You're dealt six cards and want the four-card keep that scores the most on its own.",
        hand: ["6♠", "7♥", "8♦", "9♣", "2♠", "K♦"],
        prompt: "Which four cards should you keep for the most hand points?",
        options: ["6-7-K-2", "6-7-8-9", "8-9-K-2", "7-8-9-K"],
        correctIndex: 1,
        explanation: "6-7-8-9 makes a run of four (4) plus two fifteens (6+9, 7+8 = 4) for 8 — far more than any other keep.",
      },
      {
        id: "crib-10-s4", label: "Par for a Hand",
        situation: "You compare your count to a typical hand to judge how strong it is.",
        prompt: "About how many points does a typical four-card cribbage hand score before the crib?",
        options: ["Around 29 points", "Around 15 points", "Around 4 to 5 points", "Exactly 0 points"],
        correctIndex: 2,
        explanation: "The average hand is roughly 4 to 5 points, which helps you tell when a hand is unusually strong or weak.",
      },
    ],
  },
};
