import type { ScenarioConfig } from "./types";

// "Play the Hand" Decision-Trainer scenarios for the Euchre epoch.
// Each spot is a deterministic, rules-based decision — the correct line is the
// play taught in that stage, never a luck-of-the-draw outcome. correctIndex and
// explanation are stripped server-side before reaching the client.
export const euchre1Scenarios: Record<string, ScenarioConfig> = {
  "euchre-1-01": {
    intro: "You've pulled up a chair for your first hand of Euchre. Before the cards fly, make sure the shape of the game is second nature.",
    spots: [
      {
        id: "euchre-01-s1", label: "Players & Teams",
        situation: "Four people sit down for a friendly game.",
        prompt: "How is Euchre structured?",
        options: [
          "Two players head-to-head",
          "Four players in two fixed partnerships, partners sitting across the table",
          "Six players, each for themselves",
          "Three players in a triangle, no teams",
        ],
        correctIndex: 1,
        explanation: "Standard Euchre is a 2-versus-2 partnership game; your partner sits directly across from you.",
      },
      {
        id: "euchre-01-s2", label: "The Deck",
        situation: "The dealer pulls a stripped deck from the box.",
        prompt: "How many cards are in a standard Euchre deck?",
        options: [
          "52 (a full deck)",
          "32 (7 through Ace)",
          "24 (the 9, 10, J, Q, K, A of each suit)",
          "20 (10 through Ace)",
        ],
        correctIndex: 2,
        explanation: "Euchre uses a short 24-card deck — only the 9 through Ace in each suit.",
      },
      {
        id: "euchre-01-s3", label: "The Target",
        situation: "Someone asks how long the game runs.",
        prompt: "How does a game of Euchre end?",
        options: [
          "The first team to reach 10 points wins",
          "The first team to 21 points wins",
          "The first team to 5 points wins",
          "Whoever has the most tricks after nine deals",
        ],
        correctIndex: 0,
        explanation: "The first partnership to reach 10 points wins the game.",
      },
      {
        id: "euchre-01-s4", label: "The Makers' Job",
        situation: "Your team has just named the trump suit for this hand.",
        prompt: "As the 'makers', what must your team accomplish?",
        options: [
          "Win all five tricks",
          "Win exactly two tricks",
          "Avoid winning any tricks",
          "Win at least three of the five tricks, or be euchred",
        ],
        correctIndex: 3,
        explanation: "The makers must take at least 3 of the 5 tricks; falling short means they are euchred and the opponents score.",
      },
    ],
  },

  "euchre-1-02": {
    intro: "Know which card beats which before a single trick is played. In the plain (non-trump) suits the order is the natural one — high cards rule.",
    spots: [
      {
        id: "euchre-02-s1", label: "Plain-Suit Order",
        situation: "Spades are trump this hand, so clubs are a plain suit.",
        hand: ["A♣", "9♣"],
        prompt: "Which of your two clubs ranks higher?",
        options: [
          "The A♣ — the Ace is high in a plain suit",
          "The 9♣",
          "They are equal",
          "The 9♣, because low cards rule in plain suits",
        ],
        correctIndex: 0,
        explanation: "In any plain suit the order is the natural A, K, Q, J, 10, 9 from high to low.",
      },
      {
        id: "euchre-02-s2", label: "Who Wins",
        situation: "Clubs are trump, but no one played a club this trick. Hearts were led.",
        board: ["K♥", "A♥", "Q♥", "10♥"],
        prompt: "With no trump played, which heart wins the trick?",
        options: [
          "K♥",
          "A♥ — the highest card of the led suit",
          "Q♥",
          "10♥",
        ],
        correctIndex: 1,
        explanation: "When no trump is played, the highest card of the suit that was led wins.",
      },
      {
        id: "euchre-02-s3", label: "The Lowest Card",
        situation: "You're sorting your hand by rank.",
        prompt: "In a non-trump suit, which card is the lowest?",
        options: ["The 10", "The Jack", "The 9", "The Queen"],
        correctIndex: 2,
        explanation: "With no cards below the 9 in a Euchre deck, the 9 is the lowest card of each plain suit.",
      },
      {
        id: "euchre-02-s4", label: "Trump Trumps All",
        situation: "Spades are trump. You lead the A♥ and an opponent is void in hearts.",
        board: ["A♥", "9♠"],
        prompt: "The opponent plays the 9♠ on your Ace. Who wins?",
        options: [
          "Your A♥ — it's an Ace",
          "The 9♠ — any trump beats any plain-suit card",
          "It's a tie",
          "Your A♥, because the 9 is the lowest card",
        ],
        correctIndex: 1,
        explanation: "Every trump outranks every plain card, so even the lowly trump 9 beats a plain Ace.",
      },
    ],
  },

  "euchre-1-03": {
    intro: "The single most important rule in Euchre: the two top trumps are not the Ace and King — they're two Jacks called the bowers, and the left one changes its suit.",
    spots: [
      {
        id: "euchre-03-s1", label: "The Right Bower",
        situation: "Hearts have been named trump for this hand.",
        prompt: "What is the right bower — the highest card in the deck?",
        options: [
          "J♥ — the Jack of the trump suit",
          "A♥",
          "J♦",
          "K♥",
        ],
        correctIndex: 0,
        explanation: "The right bower is the Jack of the trump suit, and it is the single highest card in Euchre.",
      },
      {
        id: "euchre-03-s2", label: "The Left Bower",
        situation: "Hearts are trump (hearts and diamonds are the red suits).",
        prompt: "What is the left bower?",
        options: [
          "J♠",
          "J♣",
          "J♦ — the other red Jack",
          "A♦",
        ],
        correctIndex: 2,
        explanation: "The left bower is the same-COLOR Jack; hearts are red, so it is the Jack of Diamonds.",
      },
      {
        id: "euchre-03-s3", label: "Bower vs Bower",
        situation: "Spades are trump and you hold both black Jacks.",
        hand: ["J♠", "J♣"],
        prompt: "Which of your two Jacks is higher?",
        options: [
          "J♣ (the left bower)",
          "J♠ (the right bower) — the Jack of trump is the highest card",
          "They tie",
          "Neither — the A♠ beats them both",
        ],
        correctIndex: 1,
        explanation: "The right bower (Jack of trump) outranks the left bower (same-color Jack), which in turn outranks the Ace of trump.",
      },
      {
        id: "euchre-03-s4", label: "The Suit Switch",
        situation: "Diamonds are trump, so the left bower is the J♥.",
        prompt: "During this hand, what suit does the left bower (J♥) count as?",
        options: [
          "A heart, its printed suit",
          "A diamond (a trump) for the whole hand",
          "Both red suits at once",
          "No suit at all",
        ],
        correctIndex: 1,
        explanation: "The left bower counts as a trump for the entire hand and is no longer its printed suit.",
      },
    ],
  },

  "euchre-1-04": {
    intro: "Every hand opens the same way: five cards to each player and one card turned face-up in the middle. That turned-up card sets the whole bidding in motion.",
    spots: [
      {
        id: "euchre-04-s1", label: "The Deal",
        situation: "The dealer begins dealing clockwise in batches of two and three.",
        prompt: "How many cards does each player receive?",
        options: ["Five", "Seven", "Six", "Four"],
        correctIndex: 0,
        explanation: "Each of the four players gets five cards (20 total), leaving four cards for the kitty.",
      },
      {
        id: "euchre-04-s2", label: "The Kitty",
        situation: "After everyone has five cards, four cards remain undealt.",
        prompt: "What happens to the four leftover cards?",
        options: [
          "They are discarded immediately",
          "They form the kitty, face-down, and the top card is turned face-up to propose trump",
          "Each player is dealt one more",
          "They all go straight to the dealer's hand",
        ],
        correctIndex: 1,
        explanation: "The four leftover cards are the kitty; its top card is flipped face-up to propose the trump suit.",
      },
      {
        id: "euchre-04-s3", label: "The Turn-Up",
        situation: "The dealer flips the top of the kitty.",
        board: ["J♠"],
        prompt: "The J♠ is turned up. What does this card do?",
        options: [
          "It's the dealer's score marker",
          "It proposes spades as the candidate trump suit",
          "It is automatically trump and cannot be refused",
          "It decides who deals the next hand",
        ],
        correctIndex: 1,
        explanation: "The turn-up's suit is the proposed trump that players will accept or reject during bidding.",
      },
      {
        id: "euchre-04-s4", label: "Dealer's Edge",
        situation: "The dealer's team decides to make the turned-up suit trump.",
        board: ["J♠"],
        prompt: "What happens to the turn-up card?",
        options: [
          "It stays in the center, unused",
          "It is shuffled back into the deck",
          "The dealer picks it up into hand and discards one card face-down",
          "It goes to the player who ordered it up",
        ],
        correctIndex: 2,
        explanation: "If the dealer's side takes the turn-up suit, the dealer gains that known card and discards one — a real advantage.",
      },
    ],
  },

  "euchre-1-05": {
    intro: "Euchre's bidding has no chips and no numbers — just two quick rounds answering one question: what suit is trump? Get it right and your team controls the hand.",
    spots: [
      {
        id: "euchre-05-s1", label: "Round One",
        situation: "The Q♣ has been turned up and bidding begins to the dealer's left.",
        board: ["Q♣"],
        prompt: "In round one, what is each player deciding?",
        options: [
          "Whether to accept clubs as trump ('order it up') or pass",
          "Which of three new suits to name",
          "How many tricks to bid",
          "Whether to redeal the hand",
        ],
        correctIndex: 0,
        explanation: "Round one is only about the turned-up suit: accept it as trump (order it up) or pass.",
      },
      {
        id: "euchre-05-s2", label: "The Forbidden Suit",
        situation: "Everyone passed, so the turned-up heart was turned face-down. Round two begins.",
        prompt: "In round two, which suit may you NOT name as trump?",
        options: [
          "Spades",
          "Clubs",
          "Diamonds",
          "Hearts — the suit that was just turned down",
        ],
        correctIndex: 3,
        explanation: "In round two you may name any suit except the one that was turned up and rejected in round one.",
      },
      {
        id: "euchre-05-s3", label: "Stick the Dealer",
        situation: "You're playing the common 'stick the dealer' house rule, and round two reaches the dealer with everyone having passed.",
        prompt: "What happens?",
        options: [
          "The hand is thrown in and redealt",
          "The dealer is forced to name a trump suit",
          "The opponents choose trump",
          "The game ends in a tie",
        ],
        correctIndex: 1,
        explanation: "Stick-the-dealer forces the dealer to choose trump rather than throwing the hand in.",
      },
      {
        id: "euchre-05-s4", label: "Order to Your Partner",
        situation: "Spades are turned up and the dealer is your PARTNER. Ordering it up puts the J♠ (right bower) into your partner's hand.",
        hand: ["A♠", "K♠", "Q♥", "10♦", "9♣"],
        prompt: "With strong spades of your own, what's the smart play?",
        options: [
          "Pass — never help the dealer",
          "Order it up only to hand the opponents a card",
          "Order it up — your trump plus the right bower in your partner's hand makes three tricks very likely",
          "Name a different suit instead",
        ],
        correctIndex: 2,
        explanation: "When the dealer is your partner, ordering up gives them a known strong card — here, the right bower — strengthening your side.",
      },
    ],
  },

  "euchre-1-06": {
    intro: "The left bower's split personality — printed as one suit, playing as another — creates the most common rules mistake in Euchre. Get following-suit right and you'll never be the one who reneged.",
    spots: [
      {
        id: "euchre-06-s1", label: "The Core Rule",
        situation: "You must follow the suit that was led if you can.",
        prompt: "For following suit, the left bower counts as which suit?",
        options: [
          "The trump suit, not its printed suit",
          "Its printed suit",
          "Whichever suit you choose",
          "No suit at all",
        ],
        correctIndex: 0,
        explanation: "The left bower is a trump for all purposes, so it only ever 'follows' the trump suit.",
      },
      {
        id: "euchre-06-s2", label: "The Trap",
        situation: "Hearts are trump, so the left bower (J♦) is now a trump. A diamond is led, and your only diamond-looking card is the J♦.",
        hand: ["J♦", "A♠", "9♣"],
        board: ["Q♦"],
        prompt: "Must you play the J♦ to follow suit?",
        options: [
          "Yes — it's still a diamond",
          "No — the J♦ is a trump now, so you're void in diamonds and may play anything",
          "Yes — a bower must always be played",
          "Only if you can win the trick",
        ],
        correctIndex: 1,
        explanation: "The left bower is a heart (trump), so you hold no actual diamond — you're void and need not play it.",
      },
      {
        id: "euchre-06-s3", label: "The Other Side",
        situation: "Hearts are trump. A heart (trump) is led, and the J♦ (left bower) is your only trump.",
        hand: ["J♦", "A♠", "9♣"],
        board: ["10♥"],
        prompt: "What must you do?",
        options: [
          "Play the J♦ — it is a trump and trump was led",
          "Keep it and discard a different card",
          "Play any card you like",
          "Pass the trick",
        ],
        correctIndex: 0,
        explanation: "The left bower is a trump, so when trump is led you must play it to follow suit.",
      },
      {
        id: "euchre-06-s4", label: "The Penalty",
        situation: "A player fails to follow suit when they were able to.",
        prompt: "What is the usual penalty for reneging?",
        options: [
          "A warning only",
          "The offending team loses 2 points (the opponents score 2)",
          "The loss of a single trick",
          "Nothing — it's allowed",
        ],
        correctIndex: 1,
        explanation: "Reneging typically costs the offending side 2 points — a major swing in a race to 10.",
      },
    ],
  },

  "euchre-1-07": {
    intro: "Five tricks, a few points, and one harsh punishment for over-reaching. Count the makers' tricks and you can score any hand instantly.",
    spots: [
      {
        id: "euchre-07-s1", label: "A Normal Make",
        situation: "The makers win 3 of the 5 tricks.",
        prompt: "How many points do the makers score?",
        options: ["1 point", "2 points", "3 points", "0 points"],
        correctIndex: 0,
        explanation: "Winning 3 or 4 tricks earns the makers 1 point — the standard result for making trump.",
      },
      {
        id: "euchre-07-s2", label: "The March",
        situation: "The makers sweep all five tricks — a 'march'.",
        prompt: "How many points?",
        options: ["1 point", "2 points", "4 points", "5 points"],
        correctIndex: 1,
        explanation: "Taking all five tricks (a march) scores 2 points for the makers.",
      },
      {
        id: "euchre-07-s3", label: "Euchred",
        situation: "The makers manage only 2 of the 5 tricks, so the defenders took 3.",
        prompt: "What's the result?",
        options: [
          "The makers still score 1",
          "Nobody scores",
          "The makers are euchred — the defenders score 2 points",
          "The hand is replayed",
        ],
        correctIndex: 2,
        explanation: "If the makers fail to win 3 tricks they are euchred, and the defenders score 2 points.",
      },
      {
        id: "euchre-07-s4", label: "Who Wins the Trick",
        situation: "Spades are trump. Clubs are led, and one player is void in clubs.",
        board: ["A♣", "K♣", "9♠", "Q♣"],
        prompt: "The cards played are A♣, K♣, 9♠, Q♣. Which card wins?",
        options: [
          "A♣ — the highest club",
          "9♠ — a trump beats all the clubs",
          "K♣",
          "Q♣",
        ],
        correctIndex: 1,
        explanation: "A trick is won by the highest trump played; even the 9 of trump beats every plain-suit card.",
      },
    ],
  },

  "euchre-1-08": {
    intro: "The biggest swing in Euchre is the loner. When your hand is strong enough, you can wave your partner out and play for four points alone.",
    spots: [
      {
        id: "euchre-08-s1", label: "What It Means",
        situation: "You announce that you are 'going alone'.",
        prompt: "What does going alone (a loner) mean?",
        options: [
          "You play the hand without your partner, who lays their cards face-down and sits out",
          "You are dealt five extra cards",
          "You team up with an opponent",
          "You skip your turn this hand",
        ],
        correctIndex: 0,
        explanation: "Going alone means your partner sits the hand out and you play all five tricks by yourself.",
      },
      {
        id: "euchre-08-s2", label: "The Big Reward",
        situation: "You went alone and won all five tricks.",
        prompt: "How many points do you score?",
        options: ["2 points", "4 points", "10 points", "1 point"],
        correctIndex: 1,
        explanation: "A loner who marches (wins all five tricks) scores the maximum 4 points.",
      },
      {
        id: "euchre-08-s3", label: "Alone, But No Sweep",
        situation: "You went alone but won only 3 of the 5 tricks, not all five.",
        prompt: "How many points?",
        options: [
          "4 points",
          "2 points",
          "1 point — the 4-point bonus requires all five tricks",
          "0 points",
        ],
        correctIndex: 2,
        explanation: "A loner only earns the 4-point bonus for a full march; winning 3 or 4 tricks still scores just 1 point.",
      },
      {
        id: "euchre-08-s4", label: "Spot a Loner",
        situation: "Hearts are trump and you size up your hand.",
        hand: ["J♥", "J♦", "A♥", "K♠", "9♣"],
        prompt: "You hold the right bower, the left bower, and the A♥ of trump. Is this a hand to go alone?",
        options: [
          "No — you should never go alone",
          "Yes — the top three trumps make a sweep very likely, so going alone is well worth considering",
          "Only if your team is losing badly",
          "No, because you also hold off-suit cards",
        ],
        correctIndex: 1,
        explanation: "Holding the top trumps (both bowers plus the trump Ace) makes a march realistic, which is exactly when a loner pays off.",
      },
    ],
  },

  "euchre-1-09": {
    intro: "Good bidding is just disciplined counting: weigh your trumps, your bowers, and your off-suit Aces against the 2-point cost of getting euchred.",
    spots: [
      {
        id: "euchre-09-s1", label: "A Solid Make",
        situation: "Spades are turned up and you count your hand.",
        hand: ["J♠", "A♠", "10♠", "Q♥", "9♦"],
        prompt: "You hold the right bower plus two more spades — three trumps including a bower. Order it up or pass?",
        options: [
          "Pass — three trumps isn't enough",
          "Always go alone instead",
          "Order it up — about three trumps including a bower is a solid make",
          "Name a different suit",
        ],
        correctIndex: 2,
        explanation: "Roughly three trumps including a bower is the classic threshold for ordering up with confidence.",
      },
      {
        id: "euchre-09-s2", label: "Know When to Pass",
        situation: "Hearts are turned up and your hand is weak.",
        hand: ["9♥", "9♣", "10♦", "Q♠", "K♦"],
        prompt: "Your only trump is the 9♥ and the rest are scattered low cards. What's the disciplined play?",
        options: [
          "Order it up anyway",
          "Pass — one weak trump can't make three tricks, and the downside is being euchred for 2",
          "Go alone",
          "Order it up just to help the dealer",
        ],
        correctIndex: 1,
        explanation: "A single low trump can't reliably win three tricks, so passing avoids handing the opponents an easy euchre.",
      },
      {
        id: "euchre-09-s3", label: "Who Is the Dealer",
        situation: "You hold a borderline hand and the dealer is an OPPONENT.",
        prompt: "Why be more reluctant to order it up here?",
        options: [
          "Ordering up hands the opponent dealer the turn-up card, strengthening their hand",
          "It costs you a point to order up",
          "You aren't allowed to order up an opponent",
          "Ordering up skips your turn",
        ],
        correctIndex: 0,
        explanation: "Ordering up an opponent dealer gives them the known turn-up card, so you need a stronger hand to justify it.",
      },
      {
        id: "euchre-09-s4", label: "Off-Suit Aces",
        situation: "Clubs are trump and you weigh your full hand.",
        hand: ["J♣", "K♣", "A♥", "A♠", "9♦"],
        prompt: "You hold the right bower, the K of trump, and the off-suit A♥ and A♠. How do those Aces affect your decision?",
        options: [
          "They're worthless once trump is set",
          "They add trick-taking power, making this a clear make",
          "They force you to go alone",
          "They count as extra trumps",
        ],
        correctIndex: 1,
        explanation: "Off-suit Aces win plain-suit tricks, so they add real value on top of your trumps when deciding to make.",
      },
    ],
  },

  "euchre-1-10": {
    intro: "Euchre is as much culture as cards. Know the common variants and the etiquette so you can sit down at any table — kitchen or tournament — and fit right in.",
    spots: [
      {
        id: "euchre-10-s1", label: "Cutthroat Euchre",
        situation: "Only three players are available, so you play three-handed 'cutthroat'.",
        prompt: "How do partnerships work in cutthroat Euchre?",
        options: [
          "There are no fixed partners — the maker plays alone against the other two, who team up against them",
          "Two players always team against a fixed dealer",
          "Everyone is permanently allied",
          "Partners rotate after every trick",
        ],
        correctIndex: 0,
        explanation: "In three-handed cutthroat there are no fixed teams; whoever names trump plays alone against a temporary alliance of the other two.",
      },
      {
        id: "euchre-10-s2", label: "The Joker",
        situation: "Your group adds the Joker for a 25-card deck, using it as the 'best bower'.",
        prompt: "Where does the Joker rank?",
        options: [
          "Below both bowers",
          "As the single highest trump, above the right bower",
          "As the lowest trump",
          "It has no suit and cannot win a trick",
        ],
        correctIndex: 1,
        explanation: "When used as the best bower, the Joker is the top trump, ranking above even the right bower.",
      },
      {
        id: "euchre-10-s3", label: "Etiquette",
        situation: "You want to play fair, clean Euchre.",
        prompt: "Which of these is good etiquette and rules-keeping?",
        options: [
          "Following suit honestly — reneging is penalized 2 points",
          "Quietly signaling your hand to your partner with table-talk",
          "Reneging whenever it would help your side",
          "Sneaking a look at the kitty cards",
        ],
        correctIndex: 0,
        explanation: "Honest play — following suit and avoiding table-talk — is core Euchre etiquette; reneging carries a 2-point penalty.",
      },
      {
        id: "euchre-10-s4", label: "Declaring a Loner",
        situation: "You hold a hand strong enough to go alone.",
        prompt: "When must you declare that you're going alone?",
        options: [
          "After winning the first trick",
          "When you make trump, before the opening lead",
          "Only if your team falls behind",
          "At any point during the hand",
        ],
        correctIndex: 1,
        explanation: "A loner must be declared at the time you make trump, before the first card is led, so your partner can sit out.",
      },
    ],
  },
};
