import type { ScenarioConfig } from "./types";

// "Decision Trainer" scenarios for the French Basics language epoch.
// Each spot is a single, deterministic language decision — the correct answer is
// genuinely correct standard French (spelling, accents, gender, conjugation).
// correctIndex and explanation are stripped server-side before reaching the client.
export const frenchBasicsScenarios: Record<string, ScenarioConfig> = {
  "french-01": {
    intro: "You've just landed in Paris. Politeness is the entry fee for every interaction — get these reflexes right before you say anything else.",
    spots: [
      {
        id: "fr-01-s1", label: "The Greeting",
        situation: "You walk into a small boulangerie. The owner looks up at you.",
        prompt: "What is the single most important word to say first?",
        options: ["Bonjour", "Bonsoir", "Bonne nuit", "Salut"],
        correctIndex: 0,
        explanation: "'Bonjour' (good day) is non-negotiable on entering any shop. 'Bonsoir' is for the evening, 'Bonne nuit' means goodnight (for bed), and 'Salut' is too informal for a stranger.",
      },
      {
        id: "fr-01-s2", label: "Tu or Vous",
        situation: "You're addressing a shopkeeper you have never met.",
        prompt: "Which form of 'you' is correct with a stranger?",
        options: ["tu", "vous", "toi", "on"],
        correctIndex: 1,
        explanation: "Use the formal 'vous' with anyone you don't know. 'Tu' is informal (friends, children) and presumptuous with strangers.",
      },
      {
        id: "fr-01-s3", label: "Please",
        situation: "You want to add 'please' to a request to someone you address as 'vous'.",
        prompt: "Which is the correct formal 'please'?",
        options: ["S'il te plaît", "De rien", "S'il vous plaît", "Je vous en prie"],
        correctIndex: 2,
        explanation: "'S'il vous plaît' is the formal 'please'. 'S'il te plaît' is the informal (tu) version, 'De rien' means 'you're welcome', and 'Je vous en prie' means 'go ahead / you're welcome'.",
      },
      {
        id: "fr-01-s4", label: "Leaving",
        situation: "You've finished and are walking out of the shop.",
        prompt: "What do you say on the way out?",
        options: ["Bonjour", "Merci", "Allô", "Au revoir"],
        correctIndex: 3,
        explanation: "'Au revoir' (goodbye) closes the interaction politely. 'Allô' is only for answering the telephone.",
      },
    ],
  },

  "french-02": {
    intro: "A Parisian café has its own vocabulary. Order like a local, not like you're at a chain coffee shop.",
    spots: [
      {
        id: "fr-02-s1", label: "An Espresso",
        situation: "You just want a simple single espresso at the counter.",
        prompt: "What do you order?",
        options: ["Un café au lait", "Un café", "Un grand café noir", "Une noisette"],
        correctIndex: 1,
        explanation: "In France 'un café' is a single espresso by default — the standard order. 'Un café au lait' is a large milky breakfast coffee.",
      },
      {
        id: "fr-02-s2", label: "With Milk",
        situation: "You'd like an espresso with steamed milk, good at any time of day.",
        prompt: "How do you ask for it?",
        options: ["Un crème", "Un déca", "Un allongé", "Un thé"],
        correctIndex: 0,
        explanation: "'Un crème' is an espresso with steamed milk. 'Un déca' is decaf, 'un allongé' is watered-down (Americano-style), and 'un thé' is tea.",
      },
      {
        id: "fr-02-s3", label: "What Is It?",
        situation: "The menu lists 'une noisette'.",
        prompt: "What does 'une noisette' mean in a café?",
        options: ["A hazelnut dessert", "A hot chocolate", "An espresso with a dash of milk", "A large latte"],
        correctIndex: 2,
        explanation: "'Une noisette' is an espresso with just a small dash of milk — named for its hazelnut colour.",
      },
      {
        id: "fr-02-s4", label: "Order Politely",
        situation: "You want to place your order to the waiter correctly and politely.",
        prompt: "Which sentence is correct and polite?",
        options: ["Je veux un café.", "Un café, s'il vous plaît.", "Donnez café.", "Moi café maintenant."],
        correctIndex: 1,
        explanation: "'Un café, s'il vous plaît' is natural and polite. 'Je veux' (I want) is grammatical but blunt; the others are ungrammatical.",
      },
    ],
  },

  "french-03": {
    intro: "French restaurant service is formal and professional. Navigate the waiter, the order, and the bill the right way.",
    spots: [
      {
        id: "fr-03-s1", label: "Calling the Waiter",
        situation: "You need to get your waiter's attention across the room.",
        prompt: "What is the correct, polite way?",
        options: ["Garçon!", "Hé, vous!", "Excusez-moi, monsieur", "Eh, monsieur!"],
        correctIndex: 2,
        explanation: "'Excusez-moi, monsieur/madame' is correct. 'Garçon' is outdated and rude, and shouting 'Hé/Eh' is impolite.",
      },
      {
        id: "fr-03-s2", label: "The Bill",
        situation: "You've finished your meal and want to pay.",
        prompt: "How do you ask for the bill?",
        options: ["L'addition, s'il vous plaît", "La carte, s'il vous plaît", "Le menu, s'il vous plaît", "La note maintenant"],
        correctIndex: 0,
        explanation: "'L'addition, s'il vous plaît' asks for the restaurant bill. 'La carte' is the menu list and 'le menu' is the fixed-price set meal.",
      },
      {
        id: "fr-03-s3", label: "Ordering",
        situation: "You'd like to order the fish politely.",
        prompt: "Which is the polite, correct way to say 'I would like the fish'?",
        options: ["Je veux le poisson.", "Je voudrais le poisson.", "J'ai le poisson.", "Moi le poisson."],
        correctIndex: 1,
        explanation: "'Je voudrais' (I would like) is the polite conditional form. 'Je veux' is grammatical but blunt; 'J'ai' means 'I have'.",
      },
      {
        id: "fr-03-s4", label: "Service Compris",
        situation: "Your bill is printed with the words 'service compris'.",
        prompt: "What does 'service compris' mean?",
        options: ["You must tip 15%", "The service charge is already included", "The kitchen is closed", "It is self-service"],
        correctIndex: 1,
        explanation: "'Service compris' means the service charge is included by law — extra tipping is optional, not expected.",
      },
    ],
  },

  "french-04": {
    intro: "Markets and boutiques run on a social code: greet, ask, and pay the right way.",
    spots: [
      {
        id: "fr-04-s1", label: "How Much?",
        situation: "You point to an item at a market stall.",
        prompt: "How do you ask 'How much is this?'",
        options: ["Quel âge?", "Combien d'argent?", "C'est combien?", "Quelle heure?"],
        correctIndex: 2,
        explanation: "'C'est combien?' is the standard way to ask a price. 'Quel âge?' asks an age and 'Quelle heure?' asks the time.",
      },
      {
        id: "fr-04-s2", label: "Just Looking",
        situation: "A sales assistant approaches and asks if you need help.",
        prompt: "What does saying 'Je regarde' signal?",
        options: ["I'll take it", "I'm just looking", "I need help", "Where's the till?"],
        correctIndex: 1,
        explanation: "'Je regarde' (I'm looking) politely signals you'd like to browse without being followed.",
      },
      {
        id: "fr-04-s3", label: "I'll Take It",
        situation: "You've decided to buy a bag — 'le sac' (masculine).",
        prompt: "How do you say 'I'll take it'?",
        options: ["Je le prends.", "Je la prends.", "Je prends le.", "Je les prends."],
        correctIndex: 0,
        explanation: "'Le sac' is masculine, so the object pronoun is 'le': 'Je le prends.' 'Je la prends' would be for a feminine item; 'Je les prends' is plural.",
      },
      {
        id: "fr-04-s4", label: "Paying by Card",
        situation: "At the register, you want to check they accept cards.",
        prompt: "How do you ask 'Do you take card?'",
        options: ["Vous avez la carte?", "Vous acceptez la carte?", "C'est gratuit?", "Je paie demain?"],
        correctIndex: 1,
        explanation: "'Vous acceptez la carte?' asks whether they accept card payment. 'C'est gratuit?' asks if it's free.",
      },
    ],
  },

  "french-05": {
    intro: "Asking directions in Paris works — if you greet first and recognise the key directional words in the reply.",
    spots: [
      {
        id: "fr-05-s1", label: "Where Is It?",
        situation: "You're lost and want to find the Louvre.",
        prompt: "How do you ask 'Where is the Louvre?'",
        options: ["Où est le Louvre?", "Quand le Louvre?", "Comment le Louvre?", "Qui est le Louvre?"],
        correctIndex: 0,
        explanation: "'Où est...?' means 'Where is...?'. 'Quand' is 'when', 'Comment' is 'how', and 'Qui' is 'who'.",
      },
      {
        id: "fr-05-s2", label: "À Gauche",
        situation: "The reply includes the phrase 'à gauche'.",
        prompt: "What does 'à gauche' mean?",
        options: ["To the right", "Straight ahead", "To the left", "Behind"],
        correctIndex: 2,
        explanation: "'À gauche' means to the left. 'À droite' is to the right — don't mix them up.",
      },
      {
        id: "fr-05-s3", label: "Tout Droit",
        situation: "Someone tells you to go 'tout droit'.",
        prompt: "What does 'tout droit' mean?",
        options: ["You're right (correct)", "Straight ahead", "Turn right", "Stop here"],
        correctIndex: 1,
        explanation: "'Tout droit' means straight ahead — easily confused with 'à droite' (to the right), which sounds similar.",
      },
      {
        id: "fr-05-s4", label: "Open Politely",
        situation: "You stop a stranger on the street to ask where the station is.",
        prompt: "Which is the correct, polite way to open?",
        options: ["Où est la gare?!", "Excusez-moi, où est la gare, s'il vous plaît?", "Gare? Où?", "Dis-moi la gare."],
        correctIndex: 1,
        explanation: "Always open with 'Excusez-moi' and close with 's'il vous plaît'. 'Dis-moi' uses the informal 'tu' and is too familiar with a stranger.",
      },
    ],
  },

  "french-06": {
    intro: "French numbers are logical to 60, then they do arithmetic in the words. Master the tricky tens and how to pay.",
    spots: [
      {
        id: "fr-06-s1", label: "Seventy",
        situation: "A vendor needs to tell you a price in the seventies.",
        prompt: "How do you say '70' in standard French?",
        options: ["Septante", "Soixante-dix", "Sept-dix", "Soixante-sept"],
        correctIndex: 1,
        explanation: "Standard French for 70 is 'soixante-dix' (sixty-ten). 'Septante' is used in Belgium and Switzerland, not France. 'Soixante-sept' is 67.",
      },
      {
        id: "fr-06-s2", label: "Eighty",
        situation: "The total comes to eighty euros.",
        prompt: "How do you say '80' in standard French?",
        options: ["Quatre-vingts", "Huitante", "Octante", "Quatre-vingt-dix"],
        correctIndex: 0,
        explanation: "'Quatre-vingts' literally means 'four-twenties' (4×20). 'Quatre-vingt-dix' is 90; 'huitante/octante' are Swiss.",
      },
      {
        id: "fr-06-s3", label: "Ninety",
        situation: "You see the price 'quatre-vingt-dix' euros.",
        prompt: "What does 'quatre-vingt-dix' literally break down to?",
        options: ["Nine tens", "Four-twenties-ten (4×20 + 10)", "Ninety exactly, no logic", "Four nineties"],
        correctIndex: 1,
        explanation: "'Quatre-vingt-dix' = 4×20 + 10 = 90. The arithmetic-in-words is what trips up learners.",
      },
      {
        id: "fr-06-s4", label: "Paying by Card",
        situation: "You want to tell the cashier you'll pay by card.",
        prompt: "Which sentence is correct?",
        options: ["Je carte.", "Carte, oui.", "Je paie par carte.", "Argent non, carte."],
        correctIndex: 2,
        explanation: "'Je paie par carte' is the correct phrase. 'Je paie en espèces' would mean paying cash.",
      },
    ],
  },

  "french-07": {
    intro: "Paris has Europe's most comprehensive transit network. Buy tickets and find your line with confidence.",
    spots: [
      {
        id: "fr-07-s1", label: "Which Line",
        situation: "You're at a métro map trying to get to Bastille.",
        prompt: "How do you ask 'Which line goes to Bastille?'",
        options: ["Quelle ligne pour aller à Bastille?", "Quel bus pour Bastille?", "Où est Bastille?", "Comment Bastille?"],
        correctIndex: 0,
        explanation: "'Quelle ligne pour aller à...?' asks which line goes somewhere. 'Quel bus' specifically asks about a bus.",
      },
      {
        id: "fr-07-s2", label: "Buying a Ticket",
        situation: "At the ticket window you want a ticket to Lyon.",
        prompt: "How do you ask for it?",
        options: ["Un ticket Lyon.", "Je vais Lyon.", "Un billet pour Lyon, s'il vous plaît.", "Lyon, vite."],
        correctIndex: 2,
        explanation: "'Un billet pour Lyon, s'il vous plaît' is the complete, polite request. 'Un billet' is the standard word for a travel ticket.",
      },
      {
        id: "fr-07-s3", label: "Direction",
        situation: "Métro platforms are labelled by 'direction', e.g. 'direction Château de Vincennes'.",
        prompt: "What does the line's 'direction' refer to?",
        options: ["The ticket price", "The terminus (final stop) of the line", "The platform colour", "The next train time"],
        correctIndex: 1,
        explanation: "Paris métro lines are identified by their terminus station — you board in the 'direction' of the line's final stop.",
      },
      {
        id: "fr-07-s4", label: "Asking the Driver",
        situation: "You want to check a bus goes to the Eiffel Tower.",
        prompt: "How do you ask 'Does this bus go to the Eiffel Tower?'",
        options: ["Ce bus, Tour Eiffel?", "Est-ce que ce bus va à la Tour Eiffel?", "Le bus Tour Eiffel où?", "Tour Eiffel bus?"],
        correctIndex: 1,
        explanation: "'Est-ce que ce bus va à...?' is the correct full question form. The others are ungrammatical fragments.",
      },
    ],
  },

  "french-08": {
    intro: "France's museums are extraordinary. Buy your ticket, find your gallery, and ask before you snap a photo.",
    spots: [
      {
        id: "fr-08-s1", label: "May I Photograph?",
        situation: "You want to take a photo of a painting and ask the guard first.",
        prompt: "How do you ask 'May I take a photo?'",
        options: ["Photo possible?", "Puis-je prendre une photo?", "Je photo ici?", "Prendre photo bon?"],
        correctIndex: 1,
        explanation: "'Puis-je prendre une photo?' is the polite, correct form. The others are not grammatical French.",
      },
      {
        id: "fr-08-s2", label: "A Ticket",
        situation: "At the museum desk you want one entry ticket.",
        prompt: "How do you ask for 'a ticket, please'?",
        options: ["Un billet, s'il vous plaît.", "Une place libre?", "Un billet gratuit.", "Entrée?"],
        correctIndex: 0,
        explanation: "'Un billet, s'il vous plaît' requests a ticket politely. 'Un billet gratuit' would demand a free ticket.",
      },
      {
        id: "fr-08-s3", label: "Exposition",
        situation: "A sign advertises 'une exposition temporaire'.",
        prompt: "What does 'une exposition' mean?",
        options: ["An exit", "An exhibition", "An explosion", "A guided tour"],
        correctIndex: 1,
        explanation: "'Une exposition' is an exhibition. A false friend with English 'exposition'; an exit is 'une sortie'.",
      },
      {
        id: "fr-08-s4", label: "Student Discount",
        situation: "You're a student and want to ask about a reduced rate.",
        prompt: "How do you ask 'Do you have a student discount?'",
        options: ["Étudiant gratuit?", "C'est cher?", "Je suis jeune.", "Avez-vous une réduction étudiant?"],
        correctIndex: 3,
        explanation: "'Avez-vous une réduction étudiant?' asks for a student discount. 'C'est cher?' just asks if it's expensive.",
      },
    ],
  },

  "french-09": {
    intro: "Know the emergency words and numbers before you ever need them. These spots could matter most.",
    spots: [
      {
        id: "fr-09-s1", label: "Help!",
        situation: "You witness an accident and need to shout for help.",
        prompt: "How do you shout 'Help!' in French?",
        options: ["Au secours!", "Pardon!", "Attention!", "Bonjour!"],
        correctIndex: 0,
        explanation: "'Au secours!' means 'Help!'. 'Attention!' means 'Watch out!' and 'Pardon!' means 'Sorry/Excuse me'.",
      },
      {
        id: "fr-09-s2", label: "I Need a Doctor",
        situation: "Someone has fallen ill and you must get medical help.",
        prompt: "How do you say 'I need a doctor'?",
        options: ["Je suis médecin.", "Où le docteur?", "J'ai besoin d'un médecin.", "Médecin!"],
        correctIndex: 2,
        explanation: "'J'ai besoin d'un médecin' means 'I need a doctor'. 'Je suis médecin' would mean 'I am a doctor'.",
      },
      {
        id: "fr-09-s3", label: "The Right Number",
        situation: "There's a medical emergency and you reach for your phone.",
        prompt: "Which number reaches the SAMU (medical emergency) in France?",
        options: ["18", "15", "17", "118"],
        correctIndex: 1,
        explanation: "15 is the SAMU (medical). 17 is the police, 18 is the fire brigade (Pompiers), and 112 is the EU-wide number.",
      },
      {
        id: "fr-09-s4", label: "Lost Passport",
        situation: "You realise your passport is gone and tell a police officer.",
        prompt: "How do you say 'I've lost my passport'?",
        options: ["J'ai trouvé mon passeport.", "J'ai perdu mon passeport.", "Mon passeport est beau.", "Où mon passeport?"],
        correctIndex: 1,
        explanation: "'J'ai perdu mon passeport' = 'I've lost my passport'. 'J'ai trouvé' would mean 'I found'.",
      },
    ],
  },

  "french-10": {
    intro: "Parisians aren't rude — they're direct. Decode the slang and social codes that reveal what they really mean.",
    spots: [
      {
        id: "fr-10-s1", label: "Verlan: Meuf",
        situation: "A young Parisian uses the slang word 'meuf'.",
        prompt: "What does the verlan word 'meuf' mean?",
        options: ["a man", "the police", "a woman", "money"],
        correctIndex: 2,
        explanation: "'Meuf' is verlan (back-slang) for 'femme' — a woman. 'Keuf' is back-slang for police.",
      },
      {
        id: "fr-10-s2", label: "T'inquiète",
        situation: "You apologise for being late and your friend replies 'T'inquiète'.",
        prompt: "What does 'T'inquiète' mean?",
        options: ["I'm worried", "Don't worry", "Be careful", "Hurry up"],
        correctIndex: 1,
        explanation: "'T'inquiète' is short for 'ne t'inquiète pas' — 'don't worry'.",
      },
      {
        id: "fr-10-s3", label: "Bof",
        situation: "You ask a Parisian how the film was and they just say 'Bof'.",
        prompt: "What does 'Bof' express?",
        options: ["Enthusiasm", "Anger", "Indifference / 'meh'", "Strong agreement"],
        correctIndex: 2,
        explanation: "'Bof' is the quintessential French sound of indifference — a verbal shrug meaning 'meh'.",
      },
      {
        id: "fr-10-s4", label: "Verlan: Ouf",
        situation: "Something wild happens and a Parisian calls it 'un truc de ouf'.",
        prompt: "What does the verlan word 'ouf' mean (it reverses 'fou')?",
        options: ["soft", "fast", "loud", "crazy"],
        correctIndex: 3,
        explanation: "'Ouf' is verlan for 'fou' — crazy. 'Un truc de ouf' = 'a crazy thing'.",
      },
    ],
  },

  "french-11": {
    intro: "The boulangerie is the heart of the French morning. Order bread and pastries with the right words — and the right genders.",
    spots: [
      {
        id: "fr-11-s1", label: "A Baguette",
        situation: "You want to buy one baguette.",
        prompt: "Which is correct for 'a baguette, please'?",
        options: ["Une baguette, s'il vous plaît.", "Un baguette, s'il vous plaît.", "Une pain long.", "Baguette, donne."],
        correctIndex: 0,
        explanation: "'Baguette' is feminine, so it takes 'une': 'Une baguette, s'il vous plaît.' 'Un baguette' has the wrong article.",
      },
      {
        id: "fr-11-s2", label: "The Right Article",
        situation: "You want to order a croissant and need the correct article.",
        prompt: "Which article is correct: '___ croissant'?",
        options: ["la", "une", "un", "les"],
        correctIndex: 2,
        explanation: "'Croissant' is masculine and singular, so it takes 'un': 'un croissant'.",
      },
      {
        id: "fr-11-s3", label: "Pain au Chocolat",
        situation: "The display case lists 'un pain au chocolat'.",
        prompt: "What is 'un pain au chocolat'?",
        options: ["A chocolate-filled pastry", "A hot chocolate drink", "Burnt bread", "A chocolate cake"],
        correctIndex: 0,
        explanation: "'Un pain au chocolat' is a buttery pastry filled with chocolate. (In Paris, never call it 'chocolatine' — that's southwestern French.)",
      },
      {
        id: "fr-11-s4", label: "Two Croissants",
        situation: "You'd like two croissants and want to ask politely.",
        prompt: "Which sentence is correct and polite?",
        options: ["Je veux deux croissants.", "Je voudrais deux croissants, s'il vous plaît.", "Deux croissant.", "Donne deux croissants."],
        correctIndex: 1,
        explanation: "'Je voudrais deux croissants, s'il vous plaît' is polite and correct, with the plural -s. 'Deux croissant' is missing the plural.",
      },
    ],
  },

  "french-12": {
    intro: "A French menu is full of false friends. Decode the courses and the steak temperatures before you order.",
    spots: [
      {
        id: "fr-12-s1", label: "L'Entrée",
        situation: "The menu is split into 'entrées', 'plats', and 'desserts'.",
        prompt: "In France, what is 'l'entrée'?",
        options: ["The main course", "The exit", "The starter / first course", "The bill"],
        correctIndex: 2,
        explanation: "False friend: in France 'l'entrée' is the starter, NOT the main course (which it means in American English).",
      },
      {
        id: "fr-12-s2", label: "Le Plat",
        situation: "You're choosing from the 'plats'.",
        prompt: "What is 'le plat' (le plat principal)?",
        options: ["The dessert", "The main course", "The plate to wash", "The wine list"],
        correctIndex: 1,
        explanation: "'Le plat' (or 'le plat principal') is the main course — the centre of the meal.",
      },
      {
        id: "fr-12-s3", label: "Steak: Medium",
        situation: "The waiter asks how you'd like your steak cooked.",
        prompt: "Which French term means 'medium'?",
        options: ["bleu", "saignant", "à point", "bien cuit"],
        correctIndex: 2,
        explanation: "'À point' is medium (the French default). 'Bleu' is very rare, 'saignant' is rare, 'bien cuit' is well-done.",
      },
      {
        id: "fr-12-s4", label: "Plat du Jour",
        situation: "A blackboard advertises the 'plat du jour'.",
        prompt: "What is 'le plat du jour'?",
        options: ["Yesterday's leftovers", "The dish of the day", "The most expensive dish", "A dessert special"],
        correctIndex: 1,
        explanation: "'Le plat du jour' is the dish of the day — usually the freshest, best-value choice.",
      },
    ],
  },

  "french-13": {
    intro: "France is the world's wine benchmark. Read a wine list and order the best value without hesitation.",
    spots: [
      {
        id: "fr-13-s1", label: "Rouge",
        situation: "The wine list groups bottles by colour.",
        prompt: "What does 'rouge' mean on a wine list?",
        options: ["rosé", "white", "red", "sparkling"],
        correctIndex: 2,
        explanation: "'Rouge' means red. 'Blanc' is white, 'rosé' is rosé, and 'pétillant/mousseux' is sparkling.",
      },
      {
        id: "fr-13-s2", label: "Sec",
        situation: "A wine is described as 'sec'.",
        prompt: "What does 'sec' mean for wine?",
        options: ["sweet", "dry", "sparkling", "warm"],
        correctIndex: 1,
        explanation: "'Sec' means dry. 'Doux' is sweet, 'demi-sec' is medium, and 'brut' is very dry (for Champagne).",
      },
      {
        id: "fr-13-s3", label: "A Glass of Red",
        situation: "You'd like a single glass of red wine.",
        prompt: "How do you order it?",
        options: ["Un verre de vin rouge, s'il vous plaît.", "Une bouteille blanche.", "Un vin, vite.", "Du rouge maintenant."],
        correctIndex: 0,
        explanation: "'Un verre de vin rouge, s'il vous plaît' = 'a glass of red wine, please'. 'Une bouteille blanche' is a bottle of white.",
      },
      {
        id: "fr-13-s4", label: "Un Pichet",
        situation: "To save money you consider ordering 'un pichet'.",
        prompt: "What is 'un pichet'?",
        options: ["A single wine glass", "A carafe of house wine", "A wine cellar", "A cork"],
        correctIndex: 1,
        explanation: "'Un pichet' is a carafe of house wine — usually excellent and much cheaper than bottled wine.",
      },
    ],
  },

  "french-14": {
    intro: "French pharmacists are highly trained and can treat minor problems on the spot. Describe your symptoms clearly.",
    spots: [
      {
        id: "fr-14-s1", label: "A Headache",
        situation: "You have a pounding headache and approach the pharmacist.",
        prompt: "How do you say 'I have a headache'?",
        options: ["J'ai mal à la tête.", "J'ai mal au ventre.", "J'ai mal à la gorge.", "Je suis fatigué."],
        correctIndex: 0,
        explanation: "'J'ai mal à la tête' = 'I have a headache' (literally 'I have pain to the head'). The others are stomach ache, sore throat, and tiredness.",
      },
      {
        id: "fr-14-s2", label: "Sans Ordonnance",
        situation: "The pharmacist mentions a medicine is available 'sans ordonnance'.",
        prompt: "What does 'sans ordonnance' mean?",
        options: ["With a prescription", "Without a prescription", "Out of stock", "Free of charge"],
        correctIndex: 1,
        explanation: "'Sans ordonnance' means without a prescription (over-the-counter). 'Avec une ordonnance' means with a prescription.",
      },
      {
        id: "fr-14-s3", label: "Stomach Ache",
        situation: "The pharmacist asks what's wrong and you say 'J'ai mal au ventre'.",
        prompt: "What does 'J'ai mal au ventre' mean?",
        options: ["I have a sore throat", "I have a headache", "I have a stomach ache", "I have a fever"],
        correctIndex: 2,
        explanation: "'J'ai mal au ventre' = 'I have a stomach ache'. 'Le ventre' is the stomach/belly.",
      },
      {
        id: "fr-14-s4", label: "Without a Prescription",
        situation: "You want something for a cold but have no prescription.",
        prompt: "How do you ask 'Do you have something without a prescription?'",
        options: ["Avez-vous quelque chose sans ordonnance?", "C'est gratuit?", "Où est le médecin?", "Je suis malade."],
        correctIndex: 0,
        explanation: "'Avez-vous quelque chose sans ordonnance?' asks for an over-the-counter option directly from the pharmacist.",
      },
    ],
  },

  "french-15": {
    intro: "Check in, make requests, and understand French hotels — including what 'le petit déjeuner' really costs.",
    spots: [
      {
        id: "fr-15-s1", label: "Checking In",
        situation: "You arrive at reception with a booking under the name Martin.",
        prompt: "Which sentence correctly says 'I have a reservation in the name of Martin'?",
        options: ["Je veux une chambre.", "Réservé Martin.", "J'ai une réservation au nom de Martin.", "Martin chambre."],
        correctIndex: 2,
        explanation: "'J'ai une réservation au nom de Martin' is the correct, complete phrase. The others are fragments or just request a room.",
      },
      {
        id: "fr-15-s2", label: "Le Petit Déjeuner",
        situation: "The desk asks if you'd like 'le petit déjeuner' added to your stay.",
        prompt: "What is 'le petit déjeuner'?",
        options: ["A small lunch", "Breakfast", "A tip", "The minibar"],
        correctIndex: 1,
        explanation: "'Le petit déjeuner' is breakfast. Note 'le déjeuner' (without 'petit') is lunch.",
      },
      {
        id: "fr-15-s3", label: "Check-out Time",
        situation: "You want to know when you must vacate the room.",
        prompt: "How do you ask 'What time is check-out?'",
        options: ["À quelle heure est le check-out?", "Où est ma chambre?", "C'est combien?", "La clé, s'il vous plaît?"],
        correctIndex: 0,
        explanation: "'À quelle heure est le check-out?' asks the check-out time. The others ask for your room, the price, or the key.",
      },
      {
        id: "fr-15-s4", label: "Gender of 'Room'",
        situation: "You want to say 'a room' and need the correct article for 'chambre'.",
        prompt: "Which article is correct: '___ chambre'?",
        options: ["un", "une", "le", "des"],
        correctIndex: 1,
        explanation: "'Chambre' is feminine and singular, so it takes 'une': 'une chambre'.",
      },
    ],
  },

  "french-16": {
    intro: "Telling time in French has its own quirks — quarter-hours, the 24-hour clock, and the 'polite quarter hour'.",
    spots: [
      {
        id: "fr-16-s1", label: "What Time?",
        situation: "You need to ask a passerby the time.",
        prompt: "How do you ask 'What time is it?'",
        options: ["Quelle heure est-il?", "Quel jour?", "C'est quand?", "Où est l'heure?"],
        correctIndex: 0,
        explanation: "'Quelle heure est-il?' = 'What time is it?'. 'Quel jour?' asks the day; 'C'est quand?' asks 'when?'.",
      },
      {
        id: "fr-16-s2", label: "Moins le Quart",
        situation: "Someone tells you it's 'dix heures moins le quart'.",
        prompt: "What time is 'dix heures moins le quart'?",
        options: ["10:15", "9:45", "10:45", "9:15"],
        correctIndex: 1,
        explanation: "'Dix heures moins le quart' = ten o'clock minus a quarter = 9:45. 'Moins le quart' subtracts 15 minutes.",
      },
      {
        id: "fr-16-s3", label: "24-Hour Clock",
        situation: "A train schedule lists a departure at '15h30'.",
        prompt: "What time is '15h30'?",
        options: ["13:30", "5:30 AM", "3:15 PM", "3:30 PM"],
        correctIndex: 3,
        explanation: "France uses the 24-hour clock for schedules: 15h30 = 3:30 PM (15 − 12 = 3).",
      },
      {
        id: "fr-16-s4", label: "Et Demie",
        situation: "Someone says the meeting is at 'neuf heures et demie'.",
        prompt: "What does adding 'et demie' to an hour mean?",
        options: ["quarter past", "quarter to", "half past", "on the hour"],
        correctIndex: 2,
        explanation: "'Et demie' means half past — 'neuf heures et demie' is 9:30. 'Et quart' is quarter past; 'moins le quart' is quarter to.",
      },
    ],
  },

  "french-17": {
    intro: "Describe the Paris forecast and dress for the day. French weather uses two fixed grammar patterns.",
    spots: [
      {
        id: "fr-17-s1", label: "Il Fait Chaud",
        situation: "The forecast says 'Il fait chaud' today.",
        prompt: "What does 'Il fait chaud' mean?",
        options: ["It's cold", "It's hot", "It's raining", "It's windy"],
        correctIndex: 1,
        explanation: "'Il fait chaud' = 'It's hot'. 'Il fait froid' is 'It's cold'.",
      },
      {
        id: "fr-17-s2", label: "Il Pleut",
        situation: "You look outside and someone says 'Il pleut'.",
        prompt: "What does 'Il pleut' mean?",
        options: ["It's snowing", "It's sunny", "It's raining", "It's foggy"],
        correctIndex: 2,
        explanation: "'Il pleut' = 'It's raining' (from 'pleuvoir'). 'Il neige' is 'It's snowing'.",
      },
      {
        id: "fr-17-s3", label: "It's Cold",
        situation: "A cold front hits Paris and you want to comment on it.",
        prompt: "How do you say 'It's cold'?",
        options: ["Il fait froid.", "Il fait beau.", "Il neige.", "Il fait chaud."],
        correctIndex: 0,
        explanation: "'Il fait froid' = 'It's cold'. 'Il fait beau' is 'It's nice/sunny'; 'Il fait chaud' is 'It's hot'.",
      },
      {
        id: "fr-17-s4", label: "It's Windy",
        situation: "There's a strong wind and you want to say so correctly.",
        prompt: "Which sentence correctly says 'It's windy'?",
        options: ["Il a vent.", "Il y a du vent.", "Il est vent.", "Il fait le vent."],
        correctIndex: 1,
        explanation: "Wind uses the 'Il y a' pattern: 'Il y a du vent.' The others are ungrammatical.",
      },
    ],
  },

  "french-18": {
    intro: "Phone calls, WiFi, and signal — the digital vocabulary you'll actually need on the ground in France.",
    spots: [
      {
        id: "fr-18-s1", label: "Allô",
        situation: "Your phone rings and you answer 'Allô?'.",
        prompt: "When is 'Allô' used in French?",
        options: ["Greeting someone in person", "Only on the telephone", "Saying goodbye", "Ordering food"],
        correctIndex: 1,
        explanation: "'Allô' is used only to answer the phone — never as an in-person greeting (that's 'Bonjour').",
      },
      {
        id: "fr-18-s2", label: "WiFi Password",
        situation: "You sit in a café and want the WiFi password.",
        prompt: "How do you ask 'What is the WiFi password?'",
        options: ["Quel est le mot de passe WiFi?", "Où est le WiFi?", "Le WiFi marche?", "Internet gratuit?"],
        correctIndex: 0,
        explanation: "'Quel est le mot de passe WiFi?' asks for the password ('le mot de passe' = the password).",
      },
      {
        id: "fr-18-s3", label: "No Signal",
        situation: "Your call keeps dropping and you say 'Mon téléphone ne capte pas'.",
        prompt: "What does 'Mon téléphone ne capte pas' mean?",
        options: ["My phone is broken", "My phone has no signal", "My phone is switched off", "My phone is lost"],
        correctIndex: 1,
        explanation: "'Capter' means to pick up a signal, so 'ne capte pas' = 'has no signal/reception'.",
      },
      {
        id: "fr-18-s4", label: "Asking for Someone",
        situation: "You phone an office and want to reach Madame Dubois.",
        prompt: "How do you say 'I'd like to speak to Madame Dubois'?",
        options: ["Je voudrais parler à Madame Dubois.", "Madame Dubois où?", "Donne Madame Dubois.", "Je suis Madame Dubois."],
        correctIndex: 0,
        explanation: "'Je voudrais parler à...' is the polite phone phrase for asking to speak to someone.",
      },
    ],
  },

  "french-19": {
    intro: "Small social rules separate a respected visitor from a rude one. Pick the move that won't raise eyebrows.",
    spots: [
      {
        id: "fr-19-s1", label: "Entering a Shop",
        situation: "You walk into a small boutique with a single shopkeeper inside.",
        prompt: "What is the correct thing to do on entry?",
        options: ["Say nothing and browse", "Wave silently", "Say 'Bonjour, madame/monsieur'", "Call out 'Hey!'"],
        correctIndex: 2,
        explanation: "Greeting the shopkeeper with 'Bonjour, madame/monsieur' is expected etiquette — silence is read as rude.",
      },
      {
        id: "fr-19-s2", label: "Hands at the Table",
        situation: "You're at a French dinner and unsure what to do with your hands between courses.",
        prompt: "Where should you keep your hands during the meal?",
        options: ["In your lap", "Resting on the table", "Behind your back", "One in your pocket"],
        correctIndex: 1,
        explanation: "French etiquette is to keep your hands (wrists) visible on the table — not in your lap, which reads as Anglo habit.",
      },
      {
        id: "fr-19-s3", label: "Tu vs Vous",
        situation: "You've just been formally introduced to an older French colleague.",
        prompt: "When is it appropriate to switch to 'tu' with them?",
        options: ["Immediately, to seem friendly", "Never, with anyone", "Only with elders", "Only once they invite it or use 'tu' with you"],
        correctIndex: 3,
        explanation: "Stay on 'vous' until the other person invites 'tu' (or uses it with you). Switching early is presumptuous.",
      },
      {
        id: "fr-19-s4", label: "Leaving Politely",
        situation: "A waiter gave you excellent service and you're leaving the restaurant.",
        prompt: "What's the right thing to say on the way out?",
        options: ["Merci, au revoir!", "Garçon!", "You must tip 20%", "Nothing — just leave"],
        correctIndex: 0,
        explanation: "'Merci, au revoir!' is the polite close. Service is included, so a tip isn't required, and 'garçon' is rude.",
      },
    ],
  },

  "french-20": {
    intro: "Paris is 20 arrondissements spiralling out from the centre. Learn to read the numbers like a local.",
    spots: [
      {
        id: "fr-20-s1", label: "What They Are",
        situation: "People keep referring to 'le 5e' or 'le 16e arrondissement'.",
        prompt: "What are the 20 'arrondissements' of Paris?",
        options: ["Bus routes", "Administrative districts", "Wine regions", "Métro lines"],
        correctIndex: 1,
        explanation: "Arrondissements are the 20 administrative districts of Paris, numbered 1–20 in a clockwise spiral from the centre.",
      },
      {
        id: "fr-20-s2", label: "Reading a Postcode",
        situation: "An address ends in the postcode '75004'.",
        prompt: "What does the '75004' tell you?",
        options: ["The building's age", "The street length", "The arrondissement (the 4th)", "The métro line"],
        correctIndex: 2,
        explanation: "Paris postcodes are 750xx, where the last two digits are the arrondissement — 75004 = the 4th arrondissement.",
      },
      {
        id: "fr-20-s3", label: "Asking the District",
        situation: "You want to know which district the Louvre sits in.",
        prompt: "How do you ask 'Which arrondissement is the Louvre in?'",
        options: ["Le Louvre est dans quel arrondissement?", "Le Louvre quand?", "Combien le Louvre?", "Le Louvre est beau?"],
        correctIndex: 0,
        explanation: "'Le Louvre est dans quel arrondissement?' correctly asks which district it's in. The others ask 'when', 'how much', or 'is it beautiful'.",
      },
      {
        id: "fr-20-s4", label: "The Spiral",
        situation: "You notice the arrondissement numbers wind outward like a snail's shell.",
        prompt: "Where is the 1st arrondissement located?",
        options: ["At the outer edge", "The historic centre, by the Île de la Cité", "At the airport", "In the north only"],
        correctIndex: 1,
        explanation: "The numbering spirals outward from the centre: the 1st is the historic heart by the Île de la Cité; high numbers are outer Paris.",
      },
    ],
  },
};
