import type { ScenarioConfig } from "./types";

// "Play the Hand" Decision-Trainer scenarios for the Hearts epoch.
// Standard four-player Hearts: follow suit if able; the highest card of the
// LED suit wins (no trump); each heart = 1 point, the Q♠ = 13; LOW score wins,
// game ends at 100. Each spot is a deterministic, skill-based decision — the
// correct line is the rule or tactic taught in that stage, never luck.
// correctIndex and explanation are stripped server-side before the client.
export const hearts1Scenarios: Record<string, ScenarioConfig> = {
  "hearts-1-01": {
    intro: "Welcome to the Hearts table. Before the cards start flying, lock in the four ideas that make Hearts unlike almost every other trick game: you DODGE points, you don't chase them.",
    spots: [
      {
        id: "hearts-01-s1", label: "The Object",
        situation: "You've just sat down at a four-player Hearts table for your first hand.",
        prompt: "What are you actually trying to do in Hearts?",
        options: [
          "Win as many tricks as you can",
          "Collect every heart in the deck",
          "Avoid taking penalty points — the LOWEST score wins",
          "Be the first player to reach 100 points",
        ],
        correctIndex: 2,
        explanation: "Hearts is an evasion game: you dodge penalty points, and the player with the lowest total wins.",
      },
      {
        id: "hearts-01-s2", label: "Counting the Danger",
        situation: "All 52 cards are dealt out, 13 to each player.",
        prompt: "How many penalty points are in play every single hand?",
        options: [
          "26 — the 13 hearts (1 each) plus the 13-point Queen of Spades",
          "13 — only the hearts count",
          "52 — one for every card",
          "100 — the game-ending total",
        ],
        correctIndex: 0,
        explanation: "Thirteen hearts at 1 point each plus the 13-point Queen of Spades make exactly 26 points per hand.",
      },
      {
        id: "hearts-01-s3", label: "No Trump",
        situation: "A trick is led with a club, and a player tosses a high heart on it.",
        board: ["8♣", "K♣", "A♥"],
        prompt: "Which suit is trump in standard Hearts?",
        options: [
          "Hearts — they outrank everything",
          "There is no trump — the highest card of the LED suit wins",
          "Spades — because of the Queen",
          "Whatever suit is led first each trick becomes trump",
        ],
        correctIndex: 1,
        explanation: "Standard Hearts has no trump; an off-suit card like that A♥ cannot win — the highest club takes the trick.",
      },
      {
        id: "hearts-01-s4", label: "Winning the Game",
        situation: "Hand after hand is played until someone's running total crosses 100.",
        prompt: "When the game ends, who is the winner?",
        options: [
          "The player who reached 100 first",
          "The player who won the most tricks",
          "The player who took the Queen of Spades the fewest times",
          "The player with the LOWEST total score",
        ],
        correctIndex: 3,
        explanation: "The game ends when any player hits 100, and the player with the lowest cumulative score wins.",
      },
    ],
  },

  "hearts-1-02": {
    intro: "Every hand opens with the pass: three cards handed to an opponent, chosen blind before you see what comes back. Shed your liabilities and the hand gets a lot safer.",
    spots: [
      {
        id: "hearts-02-s1", label: "The Deal",
        situation: "The dealer deals out the full 52-card deck to the four players.",
        prompt: "How many cards does each player receive?",
        options: [
          "13",
          "10",
          "7",
          "26",
        ],
        correctIndex: 0,
        explanation: "The 52-card deck divides evenly among four players: 13 cards each, with nothing held back.",
      },
      {
        id: "hearts-02-s2", label: "What to Pass",
        situation: "It's the pass. You must hand three cards to your left.",
        hand: ["A♠", "K♠", "5♠", "2♠", "A♥", "K♥", "4♥", "9♦", "6♦", "3♦", "J♣", "7♣", "2♣"],
        prompt: "Which three cards are the best to pass away?",
        options: [
          "2♣, 3♦, 2♠ — just dump your three lowest cards",
          "A♠, K♠, A♥ — shed the high spades that can catch the Queen, plus a high heart",
          "Keep everything high so you can win tricks",
          "J♣, 7♣, 2♣ — pass away your whole club holding",
        ],
        correctIndex: 1,
        explanation: "High spades can be forced to capture the Queen and high hearts win heart tricks, so they're the dangerous cards to shed.",
      },
      {
        id: "hearts-02-s3", label: "The Rotation",
        situation: "You're trying to remember which way the cards go this hand.",
        prompt: "What is the standard pass rotation in Hearts?",
        options: [
          "Left, right, across, then a 'hold' hand with no pass — repeating",
          "Always to the left, every hand",
          "Right, then hold, then right again",
          "There is never any passing in Hearts",
        ],
        correctIndex: 0,
        explanation: "The pass rotates left, right, across, then a hold hand with no pass, and the cycle repeats.",
      },
      {
        id: "hearts-02-s4", label: "The Hold Hand",
        situation: "It's the fourth hand of the cycle — the 'hold' or 'keeper' hand.",
        prompt: "What do you do on the hold hand?",
        options: [
          "Pass six cards instead of three",
          "Pass three cards across only",
          "Pass nothing — play the cards exactly as they were dealt",
          "Skip the hand entirely",
        ],
        correctIndex: 2,
        explanation: "On the hold hand there is no pass, so you must play the hand exactly as dealt — pure in-game skill.",
      },
    ],
  },

  "hearts-1-03": {
    intro: "A trick is one card from each player. Three rules run the whole engine: follow the led suit if you can, the highest card of that suit wins, and the winner leads next.",
    spots: [
      {
        id: "hearts-03-s1", label: "Follow Suit",
        situation: "The trick is led with a club and the action comes to you.",
        board: ["6♣"],
        hand: ["A♣", "9♣", "Q♠", "4♥", "K♦"],
        prompt: "Clubs were led and you hold clubs. What must you do?",
        options: [
          "Play the Q♠ to get rid of it",
          "Play your K♦ instead",
          "Play a club — you must follow the led suit if you're able",
          "Play the 4♥",
        ],
        correctIndex: 2,
        explanation: "You must follow suit if you can; you may only play off-suit when you're void in the led suit.",
      },
      {
        id: "hearts-03-s2", label: "Who Wins",
        situation: "All four cards are down on a club-led trick.",
        board: ["J♣", "4♣", "A♣", "9♣"],
        prompt: "Which card wins this trick?",
        options: [
          "The J♣ — it was led first",
          "The A♣ — the highest card of the led suit",
          "The 9♣ — it was played last",
          "Whichever card is a face card",
        ],
        correctIndex: 1,
        explanation: "With no trump, the highest card of the led suit wins — here the Ace of clubs takes the trick.",
      },
      {
        id: "hearts-03-s3", label: "Safe Following",
        situation: "Clubs are led, the K♣ is currently winning, and you don't want the lead.",
        board: ["K♣", "9♣"],
        hand: ["A♣", "2♣", "3♦", "4♥"],
        prompt: "You must follow clubs. What's the safe play?",
        options: [
          "Play the A♣ to win the trick",
          "Play any other suit you like",
          "Play the 2♣ — duck under the King and avoid taking the trick",
          "Play a heart to break hearts",
        ],
        correctIndex: 2,
        explanation: "Slide a low club under the King so someone else wins; ducking keeps you off the lead and out of trouble.",
      },
      {
        id: "hearts-03-s4", label: "Void Power",
        situation: "Diamonds are led and you have no diamonds at all.",
        board: ["8♦", "J♦"],
        hand: ["Q♠", "5♥", "K♣"],
        prompt: "You're void in the led suit. What may you do?",
        options: [
          "You're forced to play your K♣",
          "Play any card — including the Q♠ or a heart, to slough it off safely",
          "Nothing — you must pass your turn",
          "You automatically win the trick",
        ],
        correctIndex: 1,
        explanation: "Void in the led suit, you may play anything — and since off-suit cards can't win, it's the moment to dump points.",
      },
    ],
  },

  "hearts-1-04": {
    intro: "Points are punishment. Know exactly which cards hurt and how much, so you can see the danger in a trick before you take it.",
    spots: [
      {
        id: "hearts-04-s1", label: "Heart Value",
        situation: "You take a trick containing a single heart.",
        prompt: "How many penalty points is one heart worth?",
        options: [
          "1",
          "2",
          "13",
          "0",
        ],
        correctIndex: 0,
        explanation: "Each heart is worth 1 penalty point; with 13 hearts, the whole suit totals 13 points.",
      },
      {
        id: "hearts-04-s2", label: "The Black Lady",
        situation: "The Queen of Spades — 'the Black Lady' — lands in a trick you took.",
        prompt: "How many penalty points is the Queen of Spades worth?",
        options: [
          "10",
          "26",
          "13",
          "1",
        ],
        correctIndex: 2,
        explanation: "The Queen of Spades alone is worth 13 points — as much as every heart in the deck combined.",
      },
      {
        id: "hearts-04-s3", label: "Reading the Damage",
        situation: "Spades were led, your K♠ is the highest spade, so you'll win this trick.",
        board: ["K♠", "Q♠", "2♥", "5♥"],
        prompt: "How many penalty points are you about to take?",
        options: [
          "13 — only the Queen counts",
          "15 — the Q♠ (13) plus the two hearts (2)",
          "2 — just the hearts",
          "0 — spade tricks are always safe",
        ],
        correctIndex: 1,
        explanation: "The trick holds the 13-point Queen plus two hearts (2 points), so winning it costs you 15.",
      },
      {
        id: "hearts-04-s4", label: "Safe Cards",
        situation: "You're deciding which cards you can take freely without any cost.",
        prompt: "Which cards carry NO penalty points?",
        options: [
          "All clubs and diamonds, plus every spade except the Queen",
          "All face cards",
          "Every red card",
          "Only the two of clubs",
        ],
        correctIndex: 0,
        explanation: "Only hearts and the Queen of Spades score; every other card — clubs, diamonds, non-Queen spades — is harmless.",
      },
    ],
  },

  "hearts-1-05": {
    intro: "One spectacular exception flips the scoring: take ALL 26 points and you 'shoot the moon' — zero for you, 26 for everyone else. Learn to spot it, attempt it, and stop it.",
    spots: [
      {
        id: "hearts-05-s1", label: "Read the Threat",
        situation: "One opponent has won every trick so far and has already scooped up several hearts and the Q♠.",
        prompt: "What is that opponent most likely doing?",
        options: [
          "Shooting the moon — trying to take all 26 points",
          "Just running into bad luck",
          "Deliberately trying to lose the hand",
          "Breaking the rules",
        ],
        correctIndex: 0,
        explanation: "Winning every trick while gathering hearts and the Queen is the signature of a moon attempt.",
      },
      {
        id: "hearts-05-s2", label: "Go for It?",
        situation: "You're dealt a powerhouse with winners in multiple suits and good control of the lead.",
        hand: ["A♠", "K♠", "A♥", "K♥", "Q♥"],
        prompt: "When is shooting the moon actually a good idea?",
        options: [
          "Never — it's against the rules",
          "When you hold high cards and can control the lead to win EVERY points trick",
          "Only on the very first hand of the game",
          "When your hand is full of low cards",
        ],
        correctIndex: 1,
        explanation: "Shooting needs high cards and lead control so you can drag every heart and the Queen into your own tricks.",
      },
      {
        id: "hearts-05-s3", label: "Break the Moon",
        situation: "You suddenly realize an opponent is on track to take all 26 points.",
        prompt: "How do you stop the moonshot?",
        options: [
          "Pass them all your hearts",
          "Deliberately take at least one point yourself to break it up",
          "Concede the game",
          "Lead the two of clubs",
        ],
        correctIndex: 1,
        explanation: "If even one point lands on someone else, the moon fails — so grab a cheap point to deny all 26.",
      },
      {
        id: "hearts-05-s4", label: "The Payoff",
        situation: "You pull it off and capture all 26 penalty points in the hand.",
        prompt: "What happens to the scores?",
        options: [
          "You score 0 and each opponent gets 26 (or, by some rules, you subtract 26 from your own score)",
          "You score 26 and everyone else scores 0",
          "Everyone at the table scores 13",
          "Nothing changes — the hand is replayed",
        ],
        correctIndex: 0,
        explanation: "A successful moonshot scores you 0 and slaps each opponent with 26 — or lets you take −26 instead.",
      },
    ],
  },

  "hearts-1-06": {
    intro: "Every hand opens the same way and follows a few special early rules: the two of clubs leads, no points fall on the first trick, and hearts must be 'broken' before they can be led.",
    spots: [
      {
        id: "hearts-06-s1", label: "The Forced Lead",
        situation: "The hand is about to begin and you look down at your cards.",
        hand: ["2♣", "9♣", "K♦", "7♥", "A♠"],
        prompt: "You were dealt the two of clubs. What happens?",
        options: [
          "You must lead the 2♣ as the very first card of the hand",
          "You may lead any card you choose",
          "The dealer leads the first card",
          "You're required to lead a heart",
        ],
        correctIndex: 0,
        explanation: "Whoever holds the two of clubs must lead it to open the hand — a fixed, neutral start.",
      },
      {
        id: "hearts-06-s2", label: "First-Trick Safety",
        situation: "It's the first trick, clubs are led, and you have no clubs at all.",
        board: ["2♣", "9♣", "K♣"],
        hand: ["Q♠", "4♦", "10♥"],
        prompt: "You're void in clubs — can you dump the Q♠ here?",
        options: [
          "Yes — you're void, so anything goes",
          "No — no penalty cards may be played on the first trick",
          "Only if you also hold a heart",
          "Yes, but only the Queen, not hearts",
        ],
        correctIndex: 1,
        explanation: "No points may be played on the first trick, so you must throw a safe card (here, the 4♦), not the Queen.",
      },
      {
        id: "hearts-06-s3", label: "Leading Hearts",
        situation: "Hearts have NOT been broken yet, and you've just won the lead.",
        prompt: "May you lead a heart now?",
        options: [
          "Yes, you can lead a heart any time",
          "No — you can't lead hearts until they've been 'broken'",
          "Only the two of hearts",
          "Only if you also hold the Queen of Spades",
        ],
        correctIndex: 1,
        explanation: "Hearts cannot be led until they're broken; until then you must lead clubs, diamonds, or spades.",
      },
      {
        id: "hearts-06-s4", label: "Breaking Hearts",
        situation: "You're waiting for the moment hearts become legal to lead.",
        prompt: "How do hearts get 'broken'?",
        options: [
          "The dealer announces it",
          "Automatically after four tricks",
          "A player void in the led suit discards a heart on a trick",
          "Someone leads the Queen of Spades",
        ],
        correctIndex: 2,
        explanation: "Hearts are broken when a void player sloughs a heart onto a trick of another suit.",
      },
    ],
  },

  "hearts-1-07": {
    intro: "The most powerful tool in Hearts is the void — an empty suit. When that suit is led you can play anything, which means you can 'slough' your Queen and hearts onto someone else's trick.",
    spots: [
      {
        id: "hearts-07-s1", label: "Define It",
        situation: "A strong player keeps talking about being 'void' in a suit.",
        prompt: "What does it mean to be void in a suit?",
        options: [
          "Holding only the Ace of that suit",
          "Holding no cards of that suit at all",
          "Holding a trick that contains no points",
          "Being the player who leads that suit",
        ],
        correctIndex: 1,
        explanation: "A void is zero cards of a suit, which lets you play any card when that suit is led.",
      },
      {
        id: "hearts-07-s2", label: "Slough the Queen",
        situation: "Diamonds are led and you have no diamonds.",
        board: ["7♦", "J♦"],
        hand: ["Q♠", "9♥", "4♥"],
        prompt: "You're void in diamonds. What's the best card to play?",
        options: [
          "The 9♥",
          "The 4♥",
          "The Q♠ — slough your most dangerous card onto someone else's trick",
          "You must pass your turn",
        ],
        correctIndex: 2,
        explanation: "An off-suit card can't win, so a void is the perfect chance to dump the 13-point Queen on the trick's winner.",
      },
      {
        id: "hearts-07-s3", label: "Engineer a Void",
        situation: "You want to set up a void before play even starts.",
        prompt: "What's the easiest way to create a void during the pass?",
        options: [
          "Pass away all the cards in your shortest suit",
          "Keep one card in every suit",
          "Pass away your three lowest cards",
          "Win the first trick",
        ],
        correctIndex: 0,
        explanation: "Passing away the few cards of your shortest suit empties it, making you void before the first trick.",
      },
      {
        id: "hearts-07-s4", label: "Best Slough",
        situation: "You're void and the led suit means you can play absolutely anything.",
        prompt: "Which card is the most valuable to dump?",
        options: [
          "A low club",
          "The Queen of Spades (13 points)",
          "A non-Queen spade",
          "The two of diamonds",
        ],
        correctIndex: 1,
        explanation: "Sloughing the 13-point Queen of Spades onto an opponent is the single biggest dump in the game.",
      },
    ],
  },

  "hearts-1-08": {
    intro: "So much of Hearts is one card: the Queen of Spades. Hunt her out of opponents' hands, respect the danger of your own high spades, and know when to let her go.",
    spots: [
      {
        id: "hearts-08-s1", label: "Smoke Her Out",
        situation: "The Queen of Spades hasn't appeared and you want to force her into the open.",
        hand: ["4♠", "6♠", "9♣", "3♦", "8♥"],
        prompt: "How do you 'smoke out' the Queen of Spades?",
        options: [
          "Lead spades to force the Queen-holder to eventually play her",
          "Lead hearts over and over",
          "Never play a spade",
          "Lead the two of clubs every trick",
        ],
        correctIndex: 0,
        explanation: "Leading spades makes everyone follow, squeezing the Queen-holder until they're forced to drop her.",
      },
      {
        id: "hearts-08-s2", label: "The High-Spade Trap",
        situation: "You hold the A♠ and the Queen of Spades is still loose somewhere.",
        hand: ["A♠", "7♠", "5♥", "9♦"],
        prompt: "Why is holding the A♠ risky right now?",
        options: [
          "The Ace is worth penalty points by itself",
          "An Ace can never win a trick",
          "It stops you from following suit",
          "If the Queen falls on a spade trick, your A♠ wins it and catches her 13 points",
        ],
        correctIndex: 3,
        explanation: "The highest spade wins the spade trick — so your Ace can scoop up the 13-point Queen if she's in it.",
      },
      {
        id: "hearts-08-s3", label: "Letting Her Go",
        situation: "You're holding the Queen of Spades and looking for a safe exit.",
        hand: ["Q♠", "3♠", "6♦", "2♥"],
        prompt: "When should you get rid of the Queen?",
        options: [
          "Lead her on the very first trick",
          "Slough her when you're void, or play her on a spade trick you can't win",
          "Hold her until the very last card, always",
          "Lead her the moment you get the lead",
        ],
        correctIndex: 1,
        explanation: "Dump her off-suit on a void, or lose a spade trick with her, so she lands in someone else's pile.",
      },
      {
        id: "hearts-08-s4", label: "Holding A-K of Spades",
        situation: "You were dealt the A♠ and K♠ and the Queen is still out in the wild.",
        prompt: "What's the safest plan with those high spades?",
        options: [
          "Lead them early to win some tricks",
          "Shed them via the pass or get void in spades so you can't catch the Queen",
          "Hold them all the way to the end",
          "Use them to lead hearts",
        ],
        correctIndex: 1,
        explanation: "High spades are liabilities while the Queen is loose, so pass them away or void spades to avoid catching her.",
      },
    ],
  },

  "hearts-1-09": {
    intro: "Hearts rewards memory. Track what's been played — spades first, then hearts and voids — control the lead, and you can steer every remaining point onto your opponents.",
    spots: [
      {
        id: "hearts-09-s1", label: "Count This First",
        situation: "The hand is in full swing and you want to count efficiently, not memorize all 52 cards.",
        prompt: "Which cards should you track first and foremost?",
        options: [
          "The spades — especially whether the Ace, King, and Queen are still out",
          "The diamonds",
          "Only the cards in your own hand",
          "The two of clubs and nothing else",
        ],
        correctIndex: 0,
        explanation: "Tracking the high spades tells you whether leading spades is safe and where the Queen might be hiding.",
      },
      {
        id: "hearts-09-s2", label: "Why the Lead Matters",
        situation: "The hand is winding down and the lead keeps changing hands.",
        prompt: "Why is controlling the lead so valuable, especially late?",
        options: [
          "It scores you bonus points",
          "It lets you choose the suit, dodge bad tricks, and flush out danger cards",
          "It forces opponents to pass you cards",
          "It ends the hand immediately",
        ],
        correctIndex: 1,
        explanation: "Whoever leads picks the suit, so controlling the lead lets you steer play and avoid taking points.",
      },
      {
        id: "hearts-09-s3", label: "Low Cards Are Gold",
        situation: "It's the endgame and you've deliberately held back a tiny card.",
        hand: ["2♦", "A♠"],
        prompt: "Why is keeping a low card like the 2♦ for late so valuable?",
        options: [
          "It wins the most tricks",
          "It's secretly worth minus points",
          "It lets you 'duck' under a trick and avoid taking points",
          "It automatically breaks hearts",
        ],
        correctIndex: 2,
        explanation: "A held-back 2 or 3 lets you slide under a trick and dodge the points exactly when it matters most.",
      },
      {
        id: "hearts-09-s4", label: "Engineer the Endgame",
        situation: "You've accurately counted the cards down to the final few tricks.",
        prompt: "What can a perfect count let you do?",
        options: [
          "Force a specific opponent to win the last, point-laden tricks",
          "Guarantee the Queen never appears",
          "Always shoot the moon",
          "Skip the final trick",
        ],
        correctIndex: 0,
        explanation: "By counting and controlling the lead, an expert can steer the final points squarely onto an opponent.",
      },
    ],
  },

  "hearts-1-10": {
    intro: "Once you know standard Hearts, a whole family of variants opens up. The scoring changes, but the core tactics — pass, void, slough, count, control the lead — carry over everywhere.",
    spots: [
      {
        id: "hearts-10-s1", label: "The Bonus Card",
        situation: "You sit down to a game of Omnibus Hearts, a popular variant.",
        prompt: "What is special about the Jack of Diamonds in this variant?",
        options: [
          "It's worth 13 points, just like the Queen of Spades",
          "It's worth MINUS 10 — capturing it actually helps your score",
          "It can never be played",
          "It must be passed every single hand",
        ],
        correctIndex: 1,
        explanation: "Omnibus Hearts adds the Jack of Diamonds as a −10 bonus card, so taking it lowers your score.",
      },
      {
        id: "hearts-10-s2", label: "Crowded Table",
        situation: "Six people want to play, but a single 52-card deck won't divide evenly.",
        prompt: "What makes Cancellation Hearts work for 5 or more players?",
        options: [
          "It uses two decks; identical cards in a trick 'cancel' and can't win",
          "It removes the Queen of Spades",
          "Each player gets only seven cards",
          "It bans passing entirely",
        ],
        correctIndex: 0,
        explanation: "Cancellation Hearts shuffles two decks together; when matching cards meet in a trick they cancel and can't win.",
      },
      {
        id: "hearts-10-s3", label: "Play the Scoreboard",
        situation: "You're far behind late in the game and the scores are lopsided.",
        prompt: "How should that change your play?",
        options: [
          "Play exactly the same as always",
          "Take more risk — an aggressive line or a moonshot may be your best path back",
          "Concede immediately",
          "Only ever play low cards",
        ],
        correctIndex: 1,
        explanation: "Reading the scoreboard tells you when to gamble: when you're far behind, bold risks like a moonshot are worth it.",
      },
      {
        id: "hearts-10-s4", label: "What Always Transfers",
        situation: "You move from standard Hearts to Black Maria, Spot Hearts, and beyond.",
        prompt: "Across every variant, what stays the same?",
        options: [
          "The core tactics — pass liabilities, build voids, slough, count cards, control the lead",
          "Nothing — each variant is played completely differently",
          "The Queen of Spades is always worth just 1 point",
          "You always pass to the left",
        ],
        correctIndex: 0,
        explanation: "Variants change the emphasis, but passing, voiding, sloughing, counting, and lead control carry across them all.",
      },
    ],
  },
};
