import type { ScenarioConfig } from "./types";

// "Decision Trainer" scenarios for the Italian Basics language epoch.
// Each spot is a deterministic language decision — the correct line is genuinely
// correct standard Italian (spelling, accents, gender, conjugation verified).
// correctIndex and explanation are stripped server-side before reaching the client.
export const italianBasicsScenarios: Record<string, ScenarioConfig> = {
  "italian-01": {
    intro: "Greetings open every Italian door — and in Milan, formality matters more than tourists expect. Pick the right words for each encounter.",
    spots: [
      {
        id: "it-01-s1", label: "Good Day",
        situation: "You walk into a shop on a weekday morning and greet the assistant, a stranger.",
        prompt: "How do you say 'Good morning / good day' (formal hello) in Italian?",
        options: ["Buongiorno", "Buonanotte", "Buonasera", "Arrivederci"],
        correctIndex: 0,
        explanation: "'Buongiorno' is the standard formal hello used until early afternoon. 'Buonanotte' is good night, 'Buonasera' good evening, 'Arrivederci' goodbye.",
      },
      {
        id: "it-01-s2", label: "Tu or Lei",
        situation: "You're addressing a shop assistant you've never met in a Milan boutique.",
        prompt: "Which form of 'you' is correct with a stranger in a formal setting?",
        options: ["Tu", "Lei", "Voi", "Noi"],
        correctIndex: 1,
        explanation: "'Lei' is the formal 'you' for strangers and professionals — standard in Milan shops. 'Tu' is informal (friends, children); 'Noi' means 'we'.",
      },
      {
        id: "it-01-s3", label: "Peers Only",
        situation: "You're with friends your own age who have invited a relaxed tone.",
        prompt: "Which greeting is informal — used only with friends and peers?",
        options: ["Buongiorno", "Buonasera", "Salve", "Ciao"],
        correctIndex: 3,
        explanation: "'Ciao' is informal (hi/bye) — only for friends and peers. 'Buongiorno', 'Buonasera', and the neutral 'Salve' all work with strangers.",
      },
      {
        id: "it-01-s4", label: "Warm Thanks",
        situation: "A shopkeeper has been especially helpful and you want to thank them warmly.",
        prompt: "How do you say 'Thank you very much' in standard Italian?",
        options: ["Molto grazie", "Grazie tanto", "Grazie mille", "Grande grazie"],
        correctIndex: 2,
        explanation: "'Grazie mille' (literally 'a thousand thanks') is the standard warm thank-you. 'Molto grazie' and 'Grande grazie' are not idiomatic Italian.",
      },
    ],
  },

  "italian-02": {
    intro: "The Italian bar is the centre of daily life — and coffee has its own unwritten rules. Order like a local, not a tourist.",
    spots: [
      {
        id: "it-02-s1", label: "Just a Coffee",
        situation: "You step up to the counter and want a standard espresso.",
        prompt: "What do Italians say to order a regular espresso?",
        options: ["Un caffè", "Un espresso", "Un americano", "Un cappuccino"],
        correctIndex: 0,
        explanation: "'Un caffè' means an espresso in Italy — the default. Saying 'un espresso' sounds foreign; 'caffè' is the natural term.",
      },
      {
        id: "it-02-s2", label: "The Latte Trap",
        situation: "You're craving a milky coffee and almost ask for 'un latte'.",
        prompt: "What will you actually be served if you order 'un latte'?",
        options: ["A milky coffee", "A glass of milk", "A latte macchiato", "A small black coffee"],
        correctIndex: 1,
        explanation: "'Latte' simply means milk in Italian — you'll get a glass of milk. Ask for a 'caffè latte' or 'caffè macchiato' for coffee with milk.",
      },
      {
        id: "it-02-s3", label: "Counter Price",
        situation: "You want the cheaper price and don't mind drinking standing up.",
        prompt: "Which phrase means 'at the counter' (where coffee is cheaper)?",
        options: ["Alla cassa", "Al tavolo", "Al banco", "In piazza"],
        correctIndex: 2,
        explanation: "'Al banco' means at the counter — always cheaper than sitting 'al tavolo' (at a table). 'Alla cassa' is at the till; 'in piazza' means in the square.",
      },
      {
        id: "it-02-s4", label: "Morning Only",
        situation: "It's 3 PM, just after lunch, and you're tempted by a frothy milk drink.",
        prompt: "Which drink is morning-only and marks you as a tourist if ordered after a meal?",
        options: ["Un caffè", "Un caffè macchiato", "Un caffè lungo", "Un cappuccino"],
        correctIndex: 3,
        explanation: "Cappuccino is a morning-only drink — Italians never order it after a meal. A 'caffè', 'macchiato', or 'lungo' is fine any time.",
      },
    ],
  },

  "italian-03": {
    intro: "An Italian restaurant meal has a structure and a rhythm. Order the courses, the water, and the bill the right way.",
    spots: [
      {
        id: "it-03-s1", label: "The Bill",
        situation: "You've finished eating. In Italy the bill never comes automatically — you must ask.",
        prompt: "How do you ask for the bill?",
        options: ["La fattura, per favore", "Il conto, per favore", "Il totale, per favore", "Pagare, per favore"],
        correctIndex: 1,
        explanation: "'Il conto, per favore' is the standard request for the bill. 'La fattura' is a formal invoice for business purposes.",
      },
      {
        id: "it-03-s2", label: "Still Water",
        situation: "The waiter asks which water you'd like. You want still mineral water.",
        prompt: "How do you order still water?",
        options: ["Acqua naturale", "Acqua frizzante", "Acqua minerale gassata", "Acqua tonica"],
        correctIndex: 0,
        explanation: "'Acqua naturale' is still water; 'acqua frizzante' (and 'gassata') is sparkling. 'Acqua tonica' is tonic water.",
      },
      {
        id: "it-03-s3", label: "The Primo",
        situation: "The menu is divided into courses and you're deciding what 'primo' to order.",
        prompt: "What is the 'primo' in an Italian meal?",
        options: ["The starter", "The dessert", "The first course — pasta or risotto", "The main meat course"],
        correctIndex: 2,
        explanation: "The 'primo' is the first course — typically pasta, risotto, or soup. The 'antipasto' is the starter; the 'secondo' is the main.",
      },
      {
        id: "it-03-s4", label: "Ordering Politely",
        situation: "You want to order the risotto and want the polite 'I would like...' form.",
        prompt: "Which is the polite way to say 'I would like the risotto'?",
        options: ["Voglio il risotto", "Mi dia il risotto", "Ho bisogno il risotto", "Vorrei il risotto"],
        correctIndex: 3,
        explanation: "'Vorrei' (the conditional of 'volere') is the polite 'I would like'. 'Voglio' ('I want') is blunt, and 'Ho bisogno il risotto' is grammatically wrong (it needs 'di').",
      },
    ],
  },

  "italian-04": {
    intro: "Milan is the fashion capital of the world. Shop the boutiques and markets with the phrases that matter.",
    spots: [
      {
        id: "it-04-s1", label: "Try It On",
        situation: "You've found a jacket you like and want to try it on.",
        prompt: "How do you ask 'Can I try it on?'",
        options: ["Posso vedere questo?", "Posso provarlo?", "Posso comprarlo?", "Posso misurare?"],
        correctIndex: 1,
        explanation: "'Posso provarlo?' means 'Can I try it on?' ('provare' = to try). 'Posso comprarlo?' is 'Can I buy it?'; 'vedere' is to see.",
      },
      {
        id: "it-04-s2", label: "The Price",
        situation: "You point at an item and want to know its price.",
        prompt: "How do you ask 'How much does it cost?'",
        options: ["Che cosa è questo?", "Com'è caro?", "Quanto costa?", "Quanto pesa?"],
        correctIndex: 2,
        explanation: "'Quanto costa?' is 'How much does it cost?'. 'Quanto pesa?' asks how much it weighs; 'Che cosa è questo?' asks what it is.",
      },
      {
        id: "it-04-s3", label: "I'll Take It",
        situation: "You've decided on a handbag — 'la borsa', a feminine noun — and want to buy it.",
        prompt: "Which is correct for 'I'll take it' referring to la borsa (feminine)?",
        options: ["La prendo", "Lo prendo", "Le prendo", "Li prendo"],
        correctIndex: 0,
        explanation: "'La borsa' is feminine singular, so the pronoun is 'la': 'La prendo'. 'Lo' is masculine singular; 'le/li' are plural.",
      },
      {
        id: "it-04-s4", label: "Paying by Card",
        situation: "At the till, you want to check that the shop takes cards.",
        prompt: "How do you ask 'Do you accept credit cards?'",
        options: ["Avete carte?", "Pagate voi?", "Solo contanti?", "Accettate carte di credito?"],
        correctIndex: 3,
        explanation: "'Accettate carte di credito?' is 'Do you accept credit cards?'. 'Solo contanti?' means 'Cash only?'; 'Pagate voi?' means 'Are you paying?'.",
      },
    ],
  },

  "italian-05": {
    intro: "Milan's metro, trams, and buses are dense and easy once you can ask the right questions. One ticket covers them all for 90 minutes.",
    spots: [
      {
        id: "it-05-s1", label: "Where's the Metro",
        situation: "You're at street level and need to find the underground.",
        prompt: "How do you ask 'Where do I catch the metro?'",
        options: ["Dov'è il treno?", "Dove si prende la metropolitana?", "Come si va a casa?", "Dove andiamo?"],
        correctIndex: 1,
        explanation: "'Dove si prende la metropolitana?' is 'Where do I catch the metro?'. 'Dov'è il treno?' asks where the (main-line) train is.",
      },
      {
        id: "it-05-s2", label: "One Ticket",
        situation: "At the tabaccheria you want to buy a single transit ticket.",
        prompt: "How do you ask for one ticket?",
        options: ["Un biglietto, per favore", "Una multa, per favore", "Un binario, per favore", "Una fermata, per favore"],
        correctIndex: 0,
        explanation: "'Un biglietto, per favore' is 'One ticket, please'. 'Una multa' is a fine; 'un binario' a platform; 'una fermata' a stop.",
      },
      {
        id: "it-05-s3", label: "Which Stop",
        situation: "You're on the tram and want to know where to get off for the Duomo.",
        prompt: "How do you ask 'What is the stop for the Duomo?'",
        options: ["Dov'è il Duomo?", "Quando arriva il Duomo?", "Qual è la fermata per il Duomo?", "Che cos'è il Duomo?"],
        correctIndex: 2,
        explanation: "'Qual è la fermata per il Duomo?' precisely asks which stop serves the Duomo. 'Dov'è il Duomo?' just asks where it is.",
      },
      {
        id: "it-05-s4", label: "On Rails",
        situation: "The historic orange vehicles run on rails through Milan's streets.",
        prompt: "What is the Italian word for a tram?",
        options: ["L'autobus", "Il tram", "La metropolitana", "Il traghetto"],
        correctIndex: 1,
        explanation: "'Il tram' is a tram. 'L'autobus' is a bus, 'la metropolitana' the metro, 'il traghetto' a ferry.",
      },
    ],
  },

  "italian-06": {
    intro: "Italian numbers are beautifully regular — no French-style anomalies. The market will test them, and the right paying phrase too.",
    spots: [
      {
        id: "it-06-s1", label: "Say Eighty",
        situation: "A stallholder quotes a round number and you want to confirm it.",
        prompt: "How do you say '80' in Italian?",
        options: ["Settanta", "Ottanta", "Novanta", "Sessanta"],
        correctIndex: 1,
        explanation: "'Ottanta' is 80. 'Settanta' is 70, 'novanta' 90, 'sessanta' 60 — the tens are completely regular in Italian.",
      },
      {
        id: "it-06-s2", label: "Paying by Card",
        situation: "At checkout you want to say you'll pay by card.",
        prompt: "Which is correct for 'I'll pay by card'?",
        options: ["Pago con carta", "Pago in carta", "Pago la carta", "Carta per pagare"],
        correctIndex: 0,
        explanation: "'Pago con carta' ('I pay with card') is correct — the preposition is 'con'. 'Pago in carta' and 'Pago la carta' are wrong.",
      },
      {
        id: "it-06-s3", label: "Twenty-One",
        situation: "The total comes to twenty-one euros and you want to say the number.",
        prompt: "How is '21' written in standard Italian?",
        options: ["Ventiuno", "Venti uno", "Ventuno", "Vent'uno"],
        correctIndex: 2,
        explanation: "'Ventuno' is correct — 'venti' drops its final vowel before 'uno'. It's written as one word, no apostrophe.",
      },
      {
        id: "it-06-s4", label: "What Do I Owe",
        situation: "At a market stall you've chosen your produce and want the total.",
        prompt: "Which phrase means 'How much do I owe?' at a stall?",
        options: ["Quanto costa Lei?", "Quanto mi fa?", "Quanto pago io?", "Quanto è grande?"],
        correctIndex: 1,
        explanation: "'Quanto mi fa?' is the idiomatic 'How much do I owe / what's the total?' at a market. 'Quanto è grande?' asks how big something is.",
      },
    ],
  },

  "italian-07": {
    intro: "Italians communicate with their hands and eyes as much as their words. Read the gesture, and a few key phrases for when language runs out.",
    spots: [
      {
        id: "it-07-s1", label: "Pinched Fingers",
        situation: "Someone holds all fingertips together, pointing up, and rotates the wrist at you.",
        prompt: "What does Italy's famous 'pinched fingers' gesture mean?",
        options: ["Something is delicious", "What do you want? / What's going on?", "Money, please", "Let's leave now"],
        correctIndex: 1,
        explanation: "The pinched-fingers gesture means 'What do you want?', 'What are you talking about?', or general exasperation — Italy's most recognisable gesture.",
      },
      {
        id: "it-07-s2", label: "Eye Contact",
        situation: "During a conversation you keep looking away from the person speaking.",
        prompt: "In Italian conversation, how is averting your gaze read?",
        options: ["As polite and respectful", "As a sign of deep thought", "As evasive or untrustworthy", "As a request to speak"],
        correctIndex: 2,
        explanation: "Eye contact matters in Italian conversation; averting your gaze reads as evasive or untrustworthy. Maintain natural eye contact.",
      },
      {
        id: "it-07-s3", label: "I Don't Understand",
        situation: "The conversation has outrun your Italian and you need to say so politely.",
        prompt: "How do you say 'I don't understand'?",
        options: ["Non capisco", "Non lo so", "Non mi piace", "Non c'è"],
        correctIndex: 0,
        explanation: "'Non capisco' is 'I don't understand'. 'Non lo so' means 'I don't know it'; 'Non mi piace' 'I don't like it'.",
      },
      {
        id: "it-07-s4", label: "Got It?",
        situation: "After explaining something, an Italian looks at you and says 'Capito?'",
        prompt: "What does 'Capito?' mean?",
        options: ["Are you hungry?", "Understood? / Got it?", "Are you leaving?", "Is it expensive?"],
        correctIndex: 1,
        explanation: "'Capito?' is the colloquial 'Understood? / Got it?' (from 'capire', to understand). You can reply 'Capito!' to confirm.",
      },
    ],
  },

  "italian-08": {
    intro: "Italian churches and museums have rules — dress codes, discounts, and photo etiquette. Know the phrases before the queue.",
    spots: [
      {
        id: "it-08-s1", label: "May I Photograph",
        situation: "Inside a museum you want to check whether photos are allowed.",
        prompt: "How do you ask 'Can I take photos?'",
        options: ["Posso entrare?", "Posso fotografare?", "Posso toccare?", "Posso uscire?"],
        correctIndex: 1,
        explanation: "'Posso fotografare?' is 'Can I take photos?'. 'Posso entrare?' is 'Can I come in?'; 'toccare' to touch; 'uscire' to leave.",
      },
      {
        id: "it-08-s2", label: "Any Discount",
        situation: "You're a student buying a ticket and want to ask about reduced fares.",
        prompt: "How do you ask 'Is there a discount?'",
        options: ["C'è una riduzione?", "C'è un problema?", "C'è un bagno?", "C'è una fila?"],
        correctIndex: 0,
        explanation: "'C'è una riduzione?' asks if there's a discount (for students, seniors, EU under-18s). 'C'è una fila?' asks if there's a queue.",
      },
      {
        id: "it-08-s3", label: "Dress Code",
        situation: "It's summer and you're about to enter the Duomo in shorts and a vest top.",
        prompt: "Italian church dress codes require you to cover what?",
        options: ["Hair and face", "Shoulders and knees", "Hands and feet", "Only the head"],
        correctIndex: 1,
        explanation: "Italian churches require shoulders and knees covered for everyone — you'll be turned away otherwise. Carry a scarf or layer.",
      },
      {
        id: "it-08-s4", label: "Flash Forbidden",
        situation: "A sign reads 'È vietato usare il flash' next to a painting.",
        prompt: "What does that sign mean?",
        options: ["The museum is closed today", "Tickets are sold here", "Flash is forbidden", "Photography is allowed"],
        correctIndex: 2,
        explanation: "'È vietato usare il flash' means 'It is forbidden to use flash'. 'Vietato' = forbidden — flash damages artworks.",
      },
    ],
  },

  "italian-09": {
    intro: "Know how to get help before you need it. The right emergency number and phrase can matter a great deal.",
    spots: [
      {
        id: "it-09-s1", label: "Ambulance",
        situation: "Someone has collapsed and you need to call for an ambulance.",
        prompt: "What is the Italian number for a medical emergency (ambulance)?",
        options: ["112", "113", "115", "118"],
        correctIndex: 3,
        explanation: "118 is the medical emergency / ambulance number. 113 is police, 115 fire, and 112 is the universal EU number that also works.",
      },
      {
        id: "it-09-s2", label: "Help!",
        situation: "You need to call out urgently for help in the street.",
        prompt: "How do you shout 'Help!' in Italian?",
        options: ["Aiuto!", "Attento!", "Basta!", "Forza!"],
        correctIndex: 0,
        explanation: "'Aiuto!' is 'Help!'. 'Attento!' is 'Watch out!', 'Basta!' 'Enough!', 'Forza!' 'Come on!'.",
      },
      {
        id: "it-09-s3", label: "I Need a Doctor",
        situation: "You feel seriously unwell and need to tell someone.",
        prompt: "How do you say 'I need a doctor'?",
        options: ["Ho fame", "Ho bisogno di un medico", "Ho freddo", "Ho ragione"],
        correctIndex: 1,
        explanation: "'Ho bisogno di un medico' is 'I need a doctor'. 'Ho fame' = I'm hungry, 'Ho freddo' = I'm cold, 'Ho ragione' = I'm right.",
      },
      {
        id: "it-09-s4", label: "Denuncia",
        situation: "Your wallet has been stolen and you go to the Carabinieri to file a report.",
        prompt: "What is a 'denuncia'?",
        options: ["A prescription from a doctor", "A written police report — needed for insurance", "A hotel bill", "A train ticket"],
        correctIndex: 1,
        explanation: "A 'denuncia' is a written police report filed at a Carabinieri or Polizia station — essential for insurance claims after theft or loss.",
      },
    ],
  },

  "italian-10": {
    intro: "Aperitivo is Milan's great social ritual — one drink buys a buffet. Order the classics and toast correctly.",
    spots: [
      {
        id: "it-10-s1", label: "Cheers",
        situation: "Glasses are raised around the table and everyone is about to clink.",
        prompt: "How do you say 'Cheers!' in Italian?",
        options: ["Arrivederci!", "Per favore!", "Cin cin!", "Buonasera!"],
        correctIndex: 2,
        explanation: "'Cin cin!' is 'Cheers!' — always clink with eye contact. 'Arrivederci' is goodbye; 'Buonasera' good evening.",
      },
      {
        id: "it-10-s2", label: "Buffet Included",
        situation: "You want to confirm the food spread comes with your drink.",
        prompt: "How do you ask 'Is the buffet included?'",
        options: ["Il buffet è incluso?", "Quanto è il conto?", "Dov'è il bagno?", "A che ora chiude?"],
        correctIndex: 0,
        explanation: "'Il buffet è incluso?' asks whether the food buffet is included with the drink — the heart of Milanese aperitivo.",
      },
      {
        id: "it-10-s3", label: "Local Classic",
        situation: "You want the most classically Milanese bitter-and-soda aperitivo, not the touristy option.",
        prompt: "Which drink should you order?",
        options: ["Un Aperol Spritz", "Un Campari Soda", "Una birra", "Un caffè"],
        correctIndex: 1,
        explanation: "'Un Campari Soda' is the classic Milanese aperitivo. Aperol Spritz reads as more touristy in Milan.",
      },
      {
        id: "it-10-s4", label: "The Negroni",
        situation: "You're explaining what's in a Negroni to a friend.",
        prompt: "A Negroni combines gin, sweet vermouth, and which third ingredient?",
        options: ["Prosecco", "Aperol", "Limoncello", "Campari"],
        correctIndex: 3,
        explanation: "A Negroni is gin + sweet vermouth + Campari. Swap the gin for Prosecco and it becomes a Negroni Sbagliato (the 'wrong' Negroni).",
      },
    ],
  },

  "italian-11": {
    intro: "Real gelato is dense, muted in colour, and kept under metal lids. Order it in three easy steps.",
    spots: [
      {
        id: "it-11-s1", label: "Today's Flavours",
        situation: "You approach the counter and want to know what's on offer today.",
        prompt: "How do you ask 'What flavours do you have today?'",
        options: ["Che gusti avete oggi?", "Quanto costa il gelato?", "Dov'è la gelateria?", "Avete un cono?"],
        correctIndex: 0,
        explanation: "'Che gusti avete oggi?' is 'What flavours do you have today?' ('gusto' = flavour). A short seasonal list signals an artisan shop.",
      },
      {
        id: "it-11-s2", label: "May I Taste",
        situation: "You're undecided and would like a small spoonful before choosing.",
        prompt: "How do you ask 'May I taste?'",
        options: ["Posso pagare?", "Posso assaggiare?", "Posso vedere?", "Posso entrare?"],
        correctIndex: 1,
        explanation: "'Posso assaggiare?' ('May I taste?', from 'assaggiare') is always acceptable at a gelateria. 'Posso pagare?' is 'May I pay?'.",
      },
      {
        id: "it-11-s3", label: "Cup not Cone",
        situation: "You'd rather have your gelato in a cup than a cone.",
        prompt: "What is the Italian word for a gelato cup?",
        options: ["Il cono", "Il bicchiere", "La coppetta", "Il piatto"],
        correctIndex: 2,
        explanation: "'La coppetta' is the gelato cup (as opposed to 'il cono', the cone). 'Il bicchiere' is a drinking glass; 'il piatto' a plate.",
      },
      {
        id: "it-11-s4", label: "Pistachio",
        situation: "You spot a muted olive-green tub — the sign of real pistachio.",
        prompt: "What is the Italian flavour name for pistachio?",
        options: ["Fragola", "Nocciola", "Limone", "Pistacchio"],
        correctIndex: 3,
        explanation: "'Pistacchio' (note the double 'c') is pistachio. 'Fragola' is strawberry, 'nocciola' hazelnut, 'limone' lemon.",
      },
    ],
  },

  "italian-12": {
    intro: "Milanese cooking is butter-based and rice-forward — not the tomato-heavy south. Navigate the menu with confidence.",
    spots: [
      {
        id: "it-12-s1", label: "Milan's Signature",
        situation: "You want to order the dish most associated with Milan as your first course.",
        prompt: "Which is Milan's signature first course?",
        options: ["Spaghetti al pomodoro", "Risotto alla Milanese", "Pizza margherita", "Lasagne"],
        correctIndex: 1,
        explanation: "'Risotto alla Milanese' — golden saffron risotto — is Milan's signature dish, eaten as a 'primo'.",
      },
      {
        id: "it-12-s2", label: "The Cutlet",
        situation: "You want the breaded veal cutlet on the bone, fried in butter.",
        prompt: "What is that classic Milanese dish called?",
        options: ["Ossobuco", "Bresaola", "Cotoletta alla Milanese", "Polenta"],
        correctIndex: 2,
        explanation: "'Cotoletta alla Milanese' is the bone-in breaded veal cutlet fried in butter — unlike the boneless Wiener Schnitzel. 'Ossobuco' is braised veal shank.",
      },
      {
        id: "it-12-s3", label: "The Secondo",
        situation: "You've had your pasta and the menu lists the 'secondo' section.",
        prompt: "In a full Italian meal, what is the 'secondo'?",
        options: ["The main course — meat or fish", "The first course of pasta", "The dessert", "The starter"],
        correctIndex: 0,
        explanation: "The 'secondo' is the main course — meat or fish. The 'primo' is pasta/risotto and the 'antipasto' is the starter.",
      },
      {
        id: "it-12-s4", label: "Coperto",
        situation: "The printed menu lists a 'coperto' of 2 euros per person.",
        prompt: "What is the 'coperto'?",
        options: ["A tip you must add", "A charge for parking", "A discount for locals", "A per-person cover charge"],
        correctIndex: 3,
        explanation: "'Coperto' is a legal, standard per-person cover charge (typically 1–4 euros), always printed on the menu — not a scam or a tip.",
      },
    ],
  },

  "italian-13": {
    intro: "Italy has more grape varieties than any country on earth. The classification and a few phrases let you order with confidence.",
    spots: [
      {
        id: "it-13-s1", label: "Top Tier",
        situation: "You're reading wine labels and want the highest quality classification.",
        prompt: "Which is the highest Italian wine quality tier?",
        options: ["Vino da Tavola", "IGT", "DOC", "DOCG"],
        correctIndex: 3,
        explanation: "DOCG (Denominazione di Origine Controllata e Garantita) is the highest tier — guaranteed origin plus tasting-panel approval. Then DOC, IGT, Vino da Tavola.",
      },
      {
        id: "it-13-s2", label: "A Glass of Red",
        situation: "You'd like a single glass of red wine.",
        prompt: "How do you order a glass of red wine?",
        options: ["Un bicchiere di vino bianco", "Un bicchiere di vino rosso", "Una bottiglia di rosato", "Un bicchiere d'acqua"],
        correctIndex: 1,
        explanation: "'Un bicchiere di vino rosso' is 'a glass of red wine'. 'Bianco' is white, 'rosato' rosé, 'acqua' water.",
      },
      {
        id: "it-13-s3", label: "House Wine",
        situation: "At a trattoria you want the affordable, honest house wine by the carafe.",
        prompt: "What is house wine called in Italian?",
        options: ["Vino pregiato", "Vino frizzante", "Vino della casa", "Vino dolce"],
        correctIndex: 2,
        explanation: "'Vino della casa' is the house wine — perfectly acceptable by the 'quarto' (quarter-litre) or 'mezza' (half-litre). 'Pregiato' means fine/prized.",
      },
      {
        id: "it-13-s4", label: "Lombard Sparkling",
        situation: "You want Lombardy's prestigious traditional-method sparkling wine — Italy's answer to Champagne.",
        prompt: "Which wine should you choose?",
        options: ["Franciacorta", "Barolo", "Chianti", "Brunello"],
        correctIndex: 0,
        explanation: "Franciacorta is Lombardy's DOCG traditional-method sparkling wine. Barolo and Brunello are still reds; Chianti is a Tuscan red.",
      },
    ],
  },

  "italian-14": {
    intro: "Italian pharmacists are frontline healthcare advisors — describe your symptoms and they'll help. Just know the words.",
    spots: [
      {
        id: "it-14-s1", label: "Headache",
        situation: "You have a pounding headache and want to ask the pharmacist for something.",
        prompt: "How do you say 'I have a headache'?",
        options: ["Ho la febbre", "Ho fame", "Ho mal di testa", "Ho sonno"],
        correctIndex: 2,
        explanation: "'Ho mal di testa' is 'I have a headache'. 'Ho la febbre' = I have a fever, 'Ho fame' = I'm hungry, 'Ho sonno' = I'm sleepy.",
      },
      {
        id: "it-14-s2", label: "Ricetta",
        situation: "The pharmacist mentions you may need a 'ricetta' for a particular medicine.",
        prompt: "In a pharmacy, what does 'ricetta' mean?",
        options: ["A prescription", "A recipe card", "A receipt", "A refund"],
        correctIndex: 0,
        explanation: "In a pharmacy 'ricetta' means a prescription. (The same word means 'recipe' in a kitchen — context decides.)",
      },
      {
        id: "it-14-s3", label: "Green Cross",
        situation: "You're looking for a pharmacy on a Milan street.",
        prompt: "What sign identifies an Italian pharmacy?",
        options: ["A red cross", "A green cross", "A blue star", "A white circle"],
        correctIndex: 1,
        explanation: "Italian pharmacies are marked by a green cross — usually illuminated and animated. A red cross signals medical/first-aid, not a pharmacy.",
      },
      {
        id: "it-14-s4", label: "Something For...",
        situation: "You want to ask the pharmacist for a remedy for a specific ailment.",
        prompt: "Which phrase means 'I need something for...'?",
        options: ["Ho perso il passaporto", "Vorrei vedere il menù", "Dov'è il bagno?", "Ho bisogno di qualcosa per..."],
        correctIndex: 3,
        explanation: "'Ho bisogno di qualcosa per...' is 'I need something for...' — finish with the ailment, e.g. '...il mal di testa'.",
      },
    ],
  },

  "italian-15": {
    intro: "Italy effectively invented the tourist hotel. Check in smoothly and understand the local customs.",
    spots: [
      {
        id: "it-15-s1", label: "Checking In",
        situation: "You arrive at reception with a booking and want to identify yourself.",
        prompt: "How do you say 'I have a reservation under the name...'?",
        options: ["Ho una prenotazione a nome...", "Vorrei una camera doppia", "Ho perso la chiave", "Dov'è l'ascensore?"],
        correctIndex: 0,
        explanation: "'Ho una prenotazione a nome...' is 'I have a reservation under the name...' ('prenotazione' = booking). Then carry your passport for the legal ID check.",
      },
      {
        id: "it-15-s2", label: "Double Bed",
        situation: "You and your partner want a room with one large double bed.",
        prompt: "Which room do you ask for?",
        options: ["Una camera singola", "Una camera doppia", "Una camera matrimoniale", "Una camera libera"],
        correctIndex: 2,
        explanation: "'Una camera matrimoniale' has one large double bed (for a couple). 'Doppia' is a twin (two beds); 'singola' a single; 'libera' just means vacant.",
      },
      {
        id: "it-15-s3", label: "Breakfast Included",
        situation: "You want to confirm whether breakfast comes with the room.",
        prompt: "How do you ask 'Is breakfast included?'",
        options: ["A che ora è il check-out?", "La colazione è inclusa?", "Avete una camera?", "Dov'è l'ascensore?"],
        correctIndex: 1,
        explanation: "'La colazione è inclusa?' is 'Is breakfast included?' — note 'inclusa' agrees with the feminine 'colazione'. Usually included at 3-star and above.",
      },
      {
        id: "it-15-s4", label: "Check-Out Time",
        situation: "You're planning your last morning and want to know when you must leave.",
        prompt: "What time is Italian hotel check-out typically?",
        options: ["8 AM", "9 AM", "11 AM", "Midday (mezzogiorno)"],
        correctIndex: 3,
        explanation: "Italian check-out is typically midday ('mezzogiorno'). Ask the desk to hold your bags: 'Potete tenere i bagagli?'",
      },
    ],
  },

  "italian-16": {
    intro: "Italian time expressions are logical, and Italy runs on the 24-hour clock officially. Master the hours and the half-hours.",
    spots: [
      {
        id: "it-16-s1", label: "Half Past Three",
        situation: "Someone asks the time and it's 3:30.",
        prompt: "How do you say 'It's half past three'?",
        options: ["Sono le tre e un quarto", "Sono le tre e mezza", "Sono le tre meno un quarto", "È le tre e trenta"],
        correctIndex: 1,
        explanation: "'Sono le tre e mezza' ('and a half') is half past three. 'E un quarto' is quarter past; 'meno un quarto' is quarter to.",
      },
      {
        id: "it-16-s2", label: "One O'Clock",
        situation: "It's exactly 1 PM — the one hour that takes a special singular form.",
        prompt: "Which is correct for 'It's 1 o'clock'?",
        options: ["Sono le una", "Sono l'uno", "È le una", "È l'una"],
        correctIndex: 3,
        explanation: "'È l'una' is the exception — singular, because it's one hour. Every other hour uses plural 'Sono le...'. Noon is 'È mezzogiorno'.",
      },
      {
        id: "it-16-s3", label: "What Time",
        situation: "You stop a passer-by to ask the time.",
        prompt: "How do you ask 'What time is it?'",
        options: ["Che ore sono?", "Quanto tempo?", "Quando è?", "Che giorno è?"],
        correctIndex: 0,
        explanation: "'Che ore sono?' (or 'Che ora è?') is 'What time is it?'. 'Che giorno è?' asks what day it is; 'Quanto tempo?' how long.",
      },
      {
        id: "it-16-s4", label: "Timetable Time",
        situation: "A train timetable shows '17:30' and you read it aloud in Italian.",
        prompt: "How is '17:30' read in Italian (24-hour clock)?",
        options: ["le cinque e mezza di mattina", "mezzogiorno e mezzo", "le diciassette e trenta", "le sette e trenta"],
        correctIndex: 2,
        explanation: "On the 24-hour clock, 17:30 is 'le diciassette e trenta' — standard in all official Italian timetables and reservations.",
      },
    ],
  },

  "italian-17": {
    intro: "Milan's climate is continental — foggy winters, muggy August afa. Talk about the weather and plan your day around it.",
    spots: [
      {
        id: "it-17-s1", label: "It's Hot",
        situation: "It's a sweltering Milan summer afternoon.",
        prompt: "How do you say 'It's hot'?",
        options: ["Fa freddo", "Fa caldo", "Piove", "C'è vento"],
        correctIndex: 1,
        explanation: "'Fa caldo' is 'It's hot'. 'Fa freddo' is cold, 'Piove' it's raining, 'C'è vento' it's windy.",
      },
      {
        id: "it-17-s2", label: "Foggy",
        situation: "A winter morning in the Po Valley brings the city's defining grey blanket.",
        prompt: "How do you say 'It's foggy'?",
        options: ["C'è sole", "Fa bello", "Nevica", "C'è nebbia"],
        correctIndex: 3,
        explanation: "'C'è nebbia' is 'It's foggy' — a defining feature of Milan's winters. 'C'è sole' is sunny, 'Nevica' it's snowing.",
      },
      {
        id: "it-17-s3", label: "What's the Weather",
        situation: "You're deciding whether to take an umbrella and ask a local.",
        prompt: "How do you ask 'What's the weather like?'",
        options: ["Che tempo fa?", "Che ora è?", "Quanto costa?", "Come stai?"],
        correctIndex: 0,
        explanation: "'Che tempo fa?' is 'What's the weather like?' ('tempo' = weather here). 'Come stai?' asks how you are.",
      },
      {
        id: "it-17-s4", label: "Afa",
        situation: "A local warns 'C'è afa' before you head out in August.",
        prompt: "What does 'afa' describe?",
        options: ["A cold Alpine wind", "Heavy snowfall", "Muggy, sticky summer humidity", "Dense fog"],
        correctIndex: 2,
        explanation: "'Afa' is the muggy, sticky summer humidity that makes northern Italian cities oppressive, especially in August.",
      },
    ],
  },

  "italian-18": {
    intro: "Milan is the only city where two great clubs share one stadium — and hate each other for it. Calcio is an easy conversation-starter.",
    spots: [
      {
        id: "it-18-s1", label: "Rossoneri",
        situation: "A fan in red-and-black tells you their club's colours.",
        prompt: "What is AC Milan's nickname and colours?",
        options: ["i nerazzurri — black and blue", "i rossoneri — red and black", "i bianconeri — black and white", "i giallorossi — yellow and red"],
        correctIndex: 1,
        explanation: "AC Milan are 'i rossoneri' — red and black. 'i nerazzurri' (black-blue) is Inter; 'i bianconeri' is Juventus.",
      },
      {
        id: "it-18-s2", label: "Which Team",
        situation: "You want to ask a Milanese which football club they support.",
        prompt: "How do you ask 'Which team do you support?'",
        options: ["Di che squadra sei?", "Che ore sono?", "Quanto costa?", "Dove giochi?"],
        correctIndex: 0,
        explanation: "'Di che squadra sei?' (literally 'Of which team are you?') is the natural way to ask someone's football allegiance.",
      },
      {
        id: "it-18-s3", label: "Nerazzurri",
        situation: "The other Milan club, founded in 1908 as an internationalist breakaway, wears black and blue.",
        prompt: "What is Inter's nickname?",
        options: ["i rossoneri", "i bianconeri", "i viola", "i nerazzurri"],
        correctIndex: 3,
        explanation: "FC Internazionale are 'i nerazzurri' — black and blue. 'i rossoneri' is AC Milan; 'i viola' is Fiorentina.",
      },
      {
        id: "it-18-s4", label: "The Score",
        situation: "You arrive mid-match and want to ask how it stands.",
        prompt: "How do you ask 'What's the score?'",
        options: ["Chi gioca?", "Dov'è lo stadio?", "Che risultato è?", "Quando inizia?"],
        correctIndex: 2,
        explanation: "'Che risultato è?' asks 'What's the score / result?'. 'Chi gioca?' is 'Who's playing?'; 'Quando inizia?' 'When does it start?'.",
      },
    ],
  },

  "italian-19": {
    intro: "Italy has one overriding social value — la bella figura — and most faux pas violate it. Learn the unwritten rules.",
    spots: [
      {
        id: "it-19-s1", label: "May I?",
        situation: "At a market stall you're about to pick up a peach to inspect it.",
        prompt: "What should you say before touching the produce?",
        options: ["Grazie!", "Posso?", "Basta!", "Vai!"],
        correctIndex: 1,
        explanation: "'Posso?' ('May I?') is essential before touching produce — helping yourself is a brutta figura. The stallholder selects the fruit.",
      },
      {
        id: "it-19-s2", label: "Cheese on Fish",
        situation: "You're tempted to ask for parmesan to sprinkle on your seafood pasta.",
        prompt: "In Italy, asking for cheese on seafood pasta is...",
        options: ["A polite compliment", "Expected by waiters", "A genuine culinary faux pas", "Required at trattorie"],
        correctIndex: 2,
        explanation: "Cheese on seafood pasta is a real culinary faux pas — the waiter may politely decline. Italians believe it clashes with the fish.",
      },
      {
        id: "it-19-s3", label: "La Bella Figura",
        situation: "Italians constantly invoke this central social value.",
        prompt: "What does 'la bella figura' refer to?",
        options: ["Presenting yourself well — style, grace, consideration", "A beautiful landscape view", "A Milan fashion runway show", "A formal hand-on-heart greeting"],
        correctIndex: 0,
        explanation: "'La bella figura' is presenting yourself well — in appearance, conduct, and consideration for others. Its opposite, 'la brutta figura', is deeply shameful.",
      },
      {
        id: "it-19-s4", label: "Eating on the Move",
        situation: "You're in a hurry and think about grabbing a slice to eat as you walk.",
        prompt: "Which is considered poor form throughout Italy?",
        options: ["Greeting with Buongiorno", "Asking for the bill", "Ordering house wine", "Eating while walking down the street"],
        correctIndex: 3,
        explanation: "Eating while walking is considered poor form in Italy — sit, eat, and give the food attention. The other three are perfectly normal.",
      },
    ],
  },

  "italian-20": {
    intro: "Milan is a city of neighbourhoods radiating from the Duomo, each with its own character and metro stop. Know where to go.",
    spots: [
      {
        id: "it-20-s1", label: "The Canals",
        situation: "You want the canal district known for aperitivo bars and a monthly flea market.",
        prompt: "Which Milan neighbourhood is this?",
        options: ["Brera", "Isola", "Navigli", "San Siro"],
        correctIndex: 2,
        explanation: "Navigli is the canal district — aperitivo culture, street art, and a flea market on the last Sunday of the month (M2 Porta Genova).",
      },
      {
        id: "it-20-s2", label: "The Art Quarter",
        situation: "You're after the art neighbourhood with the Pinacoteca and antique dealers.",
        prompt: "Which neighbourhood is the art quarter?",
        options: ["Navigli", "Brera", "Isola", "Porta Romana"],
        correctIndex: 1,
        explanation: "Brera is the art neighbourhood — galleries, antique dealers, the Pinacoteca di Brera, cobblestone streets (M2 Lanza).",
      },
      {
        id: "it-20-s3", label: "Vertical Forest",
        situation: "You want to photograph the Bosco Verticale (Vertical Forest) towers.",
        prompt: "In which neighbourhood are the Bosco Verticale towers?",
        options: ["Isola", "Brera", "Navigli", "Duomo"],
        correctIndex: 0,
        explanation: "The Bosco Verticale (2014) stands in Isola, the design neighbourhood near Garibaldi (M2/M5) — Italy's most photographed modern buildings.",
      },
      {
        id: "it-20-s4", label: "Where Is...?",
        situation: "You're lost and want to ask a local for directions to a neighbourhood.",
        prompt: "Which phrase means 'Where is...?'",
        options: ["Quanto costa...?", "Che ore sono...?", "Come stai...?", "Dov'è...?"],
        correctIndex: 3,
        explanation: "'Dov'è...?' is 'Where is...?' (a contraction of 'dove è'). 'Quanto costa?' is 'How much?'; 'Come stai?' 'How are you?'.",
      },
    ],
  },
};
