import type { ScenarioConfig } from "./types";

// "Decision Trainer" scenarios for the Milan in July travel epoch.
// Each spot is a practical, real-world travel decision — the correct line is the
// best move a savvy visitor makes in that situation. correctIndex and explanation
// are stripped server-side before reaching the client.
export const milanScenarios: Record<string, ScenarioConfig> = {
  "milan-01": {
    intro: "You've just stepped off the train at Milano Centrale. Before you sightsee, get the transport basics right.",
    spots: [
      {
        id: "milan-01-s1", label: "Buy the Pass",
        situation: "You'll be in Milan for two full days and expect a dozen metro and tram rides each day.",
        prompt: "What's the most cost-effective ticket to buy?",
        options: [
          "An ATM 3-day (72-hour) pass (€13) — unlimited metro, tram, and bus",
          "A single €2.20 ticket each time you ride",
          "A first-class Trenitalia day ticket",
          "Nothing — Milan public transport is free for tourists",
        ],
        correctIndex: 0,
        explanation: "The ATM 3-day (72-hour) pass (€13) covers unlimited metro, tram, and bus. At €2.20 per single ride, a dozen rides a day over two days would cost far more.",
      },
      {
        id: "milan-01-s2", label: "To the Duomo",
        situation: "From Centrale you want to reach the Duomo as fast as possible.",
        prompt: "Which line do you take?",
        options: [
          "Tram 9 around the ring road",
          "Walk — it's only ten minutes",
          "Metro Line 3 (yellow) direct to Duomo station",
          "Metro Line 2 (green) to Cadorna, then change",
        ],
        correctIndex: 2,
        explanation: "Line 3 (yellow) runs directly from Centrale FS to Duomo station with no changes — the fastest option to the city centre.",
      },
      {
        id: "milan-01-s3", label: "Validate It",
        situation: "You bought a single paper ATM ticket and you're about to board a tram.",
        prompt: "What must you do?",
        options: [
          "Nothing — buying it is enough",
          "Validate (stamp) it in the on-board machine when you board",
          "Show it to the driver and keep it unstamped",
          "Validate it only if an inspector asks",
        ],
        correctIndex: 1,
        explanation: "You must validate the ticket in the machine when you board — an unvalidated ticket counts as fare evasion and is fined, even if you paid for it.",
      },
      {
        id: "milan-01-s4", label: "Day-Trip Tickets",
        situation: "You're planning a day trip to Varenna on Lake Como and head to buy a train ticket at Centrale.",
        prompt: "Where do you buy the right ticket?",
        options: [
          "At the Trenord regional kiosk or trenord.it — the Como line is Trenord",
          "From the ATM metro machine — it covers regional trains too",
          "Only from a travel agency in advance",
          "On board from the conductor, cash only",
        ],
        correctIndex: 0,
        explanation: "Lake Como, Pavia, and Bergamo regional trains run on Trenord — buy from Trenord kiosks or trenord.it, not the ATM city machines or Trenitalia.",
      },
    ],
  },

  "milan-02": {
    intro: "The Duomo's roof terrace is the highlight — but only if you plan the visit right. Make the smart calls.",
    spots: [
      {
        id: "milan-02-s1", label: "Book Ahead",
        situation: "It's July and you want to walk the Duomo roof terrace among the spires.",
        prompt: "What's the best plan?",
        options: [
          "Just show up at noon when groups are at lunch",
          "Book a timed roof slot at duomomilano.it about a week ahead, aiming for the 9am opening",
          "Buy from a street tout outside the cathedral",
          "Skip the roof — it's closed to the public",
        ],
        correctIndex: 1,
        explanation: "Book a timed slot at duomomilano.it at least a week ahead in July. The 9am opening has the fewest crowds and the best morning light.",
      },
      {
        id: "milan-02-s2", label: "Dress Code",
        situation: "You're heading into the cathedral interior on a hot July day in a tank top and shorts.",
        prompt: "What's the issue?",
        options: [
          "No issue — there's no dress code",
          "Bare shoulders and knees aren't allowed; you'll need to cover up to enter",
          "You must remove your shoes inside",
          "Shorts are fine but tank tops require a ticket upgrade",
        ],
        correctIndex: 1,
        explanation: "The Duomo is an active church and enforces a dress code — shoulders and knees must be covered. Carry a light scarf or layer in summer.",
      },
      {
        id: "milan-02-s3", label: "Stairs or Lift",
        situation: "You're reasonably fit, the lift queue is long, and you want to save a few euros.",
        prompt: "Which roof ticket makes sense?",
        options: [
          "The lift ticket (€25) — always worth it",
          "The stairs ticket (€18) — cheaper and skips the lift queue",
          "Neither — climb the bell tower instead",
          "Buy both to keep your options open",
        ],
        correctIndex: 1,
        explanation: "The stairs ticket (€18) is cheaper than the lift (€25) and, for a fit visitor, often faster because it avoids the lift queue.",
      },
      {
        id: "milan-02-s4", label: "Next Stop",
        situation: "You've finished the roof and want to reach La Scala opera house on foot.",
        prompt: "What's the route?",
        options: [
          "Walk straight through the Galleria Vittorio Emanuele II — La Scala is at its north exit, 5 minutes",
          "Take a taxi across town",
          "Metro two stops to Cordusio then walk back",
          "Walk south down Via Torino for 20 minutes",
        ],
        correctIndex: 0,
        explanation: "La Scala sits directly at the north exit of the Galleria Vittorio Emanuele II — a free, covered 5-minute walk from the Duomo piazza.",
      },
    ],
  },

  "milan-03": {
    intro: "The Galleria is free, grand, and full of small rituals. Walk it like someone who knows.",
    spots: [
      {
        id: "milan-03-s1", label: "Cost of Entry",
        situation: "A friend assumes the glamorous arcade must charge admission.",
        prompt: "What do you tell them?",
        options: [
          "It's a €15 ticketed monument",
          "It's free and open to walk through at any hour",
          "Entry is free but requires a purchase",
          "It's only open during shopping hours",
        ],
        correctIndex: 1,
        explanation: "The Galleria Vittorio Emanuele II is a public arcade — free to walk through, open 24 hours, no ticket or minimum purchase.",
      },
      {
        id: "milan-03-s2", label: "Good-Luck Ritual",
        situation: "You see a small crowd taking turns spinning on the central mosaic floor.",
        prompt: "What are they doing?",
        options: [
          "Spinning a heel on the Turin bull's emblem for good luck",
          "Polishing a coin into the marble for a wish",
          "Standing on the architect's name plaque",
          "Walking the octagon three times",
        ],
        correctIndex: 0,
        explanation: "The tradition is to plant your heel on the Turin bull in the central mosaic and spin — the marble is visibly worn from a century of it.",
      },
      {
        id: "milan-03-s3", label: "Coffee Choice",
        situation: "You want a historic, atmospheric drink without paying restaurant prices.",
        prompt: "What's the move?",
        options: [
          "Sit for a full lunch at the historic Savini restaurant",
          "A Campari Seltz standing at the bar in Camparino (open since 1915)",
          "Buy a coffee from a vending machine outside",
          "There's nowhere historic to drink here",
        ],
        correctIndex: 1,
        explanation: "Camparino (1915), at the Duomo entrance, serves the original Campari Seltz. Standing at the bar is far cheaper than table service — and authentically Milanese.",
      },
      {
        id: "milan-03-s4", label: "Bar vs Table",
        situation: "You order an espresso. The barista asks if you'll take it 'al banco' (at the bar) or at a table.",
        prompt: "If you want the local price, what do you choose?",
        options: [
          "A table on the arcade — same price either way",
          "At the bar (al banco) — table service costs noticeably more",
          "Take it to go in a paper cup",
          "Ask for it delivered to a nearby bench",
        ],
        correctIndex: 1,
        explanation: "In Italy, drinking 'al banco' (standing at the bar) is cheapest. Table service ('al tavolo') carries a service surcharge, especially in tourist squares.",
      },
    ],
  },

  "milan-04": {
    intro: "Leonardo's Last Supper is the hardest ticket in Milan. Treat it like a logistics puzzle and you'll get in.",
    spots: [
      {
        id: "milan-04-s1", label: "The Booking Window",
        situation: "You want to see the Last Supper during your July trip.",
        prompt: "When and where do you book?",
        options: [
          "Walk up on the day and queue",
          "Book at vivaticket.com about 3 months ahead, when the slots open at midnight CET",
          "Buy at the door an hour before",
          "Email the church to reserve a spot",
        ],
        correctIndex: 1,
        explanation: "Tickets release at vivaticket.com roughly 3 months in advance at midnight CET. July slots sell out within hours — set a reminder and book the instant they open.",
      },
      {
        id: "milan-04-s2", label: "Sold Out",
        situation: "The 3-month window passed and official tickets are gone, but you really want to see it.",
        prompt: "What's your realistic backup?",
        options: [
          "A licensed guided tour (Viator, Context) with guaranteed-entry blocks at a premium",
          "Bribe the door staff",
          "Give up — there is no other way in",
          "Sneak in with a Santa Maria delle Grazie church ticket",
        ],
        correctIndex: 0,
        explanation: "Licensed operators like Viator and Context Travel hold guaranteed small-group entry blocks (€50–€80). It's pricier than the €15 ticket but a legitimate fallback.",
      },
      {
        id: "milan-04-s3", label: "On Arrival",
        situation: "Your slot is at 11:15am. You're enjoying coffee nearby and figure you'll wander over a bit late.",
        prompt: "What's the risk?",
        options: [
          "None — they hold your spot all afternoon",
          "Slots are strict 15-minute timed entries; arrive late and you forfeit it entirely",
          "You'll just join the next group informally",
          "They'll refund you and rebook for tomorrow",
        ],
        correctIndex: 1,
        explanation: "Entry is a strict 15-minute timed slot through a humidity airlock. Arrive 15–20 minutes early; miss your window and the ticket is gone with no refund.",
      },
      {
        id: "milan-04-s4", label: "Getting There",
        situation: "You're at the Duomo and need to reach the refectory at Santa Maria delle Grazie.",
        prompt: "What's the simplest route?",
        options: [
          "Metro M1 (red) to Cadorna, then walk about 7 minutes west on Corso Magenta",
          "Metro M3 to Centrale, then a taxi",
          "Tram to the Navigli, then walk north",
          "It's next door to the Duomo — just walk across the piazza",
        ],
        correctIndex: 0,
        explanation: "Take M1 (red) to Cadorna and walk ~7 minutes west to the Cenacolo Vinciano entrance — which is separate from the church itself.",
      },
    ],
  },

  "milan-05": {
    intro: "The Castello Sforzesco hides a Michelangelo and opens onto Milan's biggest park. Spend your time well.",
    spots: [
      {
        id: "milan-05-s1", label: "Grounds vs Museums",
        situation: "You want to wander the fortress courtyards but aren't sure you'll do all the museums.",
        prompt: "What does it cost just to walk the grounds?",
        options: [
          "€15, same as the museums",
          "Nothing — the courtyards and ramparts are free; museums are a separate €5",
          "€5 for the grounds, museums extra",
          "Free only on the first Sunday",
        ],
        correctIndex: 1,
        explanation: "The castle grounds and courtyards are free to enter. The €5 ticket adds all 7 museum collections inside — optional if you only want the atmosphere.",
      },
      {
        id: "milan-05-s2", label: "The One Must-See",
        situation: "You have limited time and the €5 museum ticket. One work is unmissable.",
        prompt: "What do you make sure to see?",
        options: [
          "Michelangelo's unfinished Pietà Rondanini, his final sculpture",
          "A Caravaggio altarpiece",
          "The crown jewels of the Sforza dukes",
          "Napoleon's coronation robes",
        ],
        correctIndex: 0,
        explanation: "The Pietà Rondanini — Michelangelo worked on it until days before his death in 1564 — is the castle's most affecting piece, raw and unfinished.",
      },
      {
        id: "milan-05-s3", label: "Closed Day",
        situation: "It's a Monday and you planned the castle museums for today.",
        prompt: "What's the problem?",
        options: [
          "Nothing — they're open daily",
          "The museums are closed Mondays; reschedule for Tue–Sun (grounds still open)",
          "Mondays are free, so it'll be packed",
          "Only the Egyptian collection is open Mondays",
        ],
        correctIndex: 1,
        explanation: "Like many Italian museums, the Castello collections close on Mondays. The outdoor grounds remain open, but plan the Pietà for Tue–Sun.",
      },
      {
        id: "milan-05-s4", label: "Cool Off After",
        situation: "It's a hot afternoon and you want green space right after the castle.",
        prompt: "Where do you go?",
        options: [
          "Take the metro back to Centrale for the gardens",
          "Walk through the castle's north exit straight into Parco Sempione",
          "There's no park nearby",
          "Head to the Navigli — it's the closest green space",
        ],
        correctIndex: 1,
        explanation: "Parco Sempione — 47 hectares, Milan's Central Park — sits directly behind the castle. Walk out the north exit and you're in it, open until 9pm in July.",
      },
    ],
  },

  "milan-06": {
    intro: "The Ambrosiana is the connoisseur's museum — quiet, deep, and five minutes from the chaos of the Duomo.",
    spots: [
      {
        id: "milan-06-s1", label: "Beat the Crowd",
        situation: "You want to see the Ambrosiana's treasures without queueing in the July heat.",
        prompt: "What's the smart timing?",
        options: [
          "Arrive at the 10am opening — queues rarely form before 11am",
          "Go at 5pm just before closing",
          "Visit on a Monday when it's quietest",
          "Book a midnight slot online",
        ],
        correctIndex: 0,
        explanation: "Arrive at the 10am opening: the Ambrosiana rarely queues before 11am, and you'll have the Raphael cartoon and Leonardo gallery nearly to yourself. (It's closed Mondays.)",
      },
      {
        id: "milan-06-s2", label: "The Leonardo",
        situation: "A guide mentions the museum holds Leonardo's largest surviving manuscript.",
        prompt: "What is it called?",
        options: [
          "The Codex Atlanticus",
          "The Mona Lisa notebooks",
          "The Vitruvian folios",
          "The Turin Shroud studies",
        ],
        correctIndex: 0,
        explanation: "The Codex Atlanticus — 1,119 pages spanning 40 years — is the largest single collection of Leonardo's drawings and writings, kept in Milan since 1637.",
      },
      {
        id: "milan-06-s3", label: "The Raphael",
        situation: "In Room 5 you find a 7-metre-wide preparatory drawing.",
        prompt: "What is this cartoon for?",
        options: [
          "Raphael's Vatican fresco, The School of Athens",
          "Michelangelo's Sistine ceiling",
          "Leonardo's Last Supper",
          "Botticelli's Birth of Venus",
        ],
        correctIndex: 0,
        explanation: "It's Raphael's full-scale cartoon for The School of Athens in the Vatican — and it survives in better condition than the fresco itself.",
      },
      {
        id: "milan-06-s4", label: "What's Next Door",
        situation: "After the Ambrosiana you have an hour and want one more free, historic site nearby.",
        prompt: "Where do you head?",
        options: [
          "The Sant'Ambrogio basilica, about 10 minutes west — free entry, 4th-century church",
          "Back to Centrale for the train museum",
          "Lake Como — it's just down the road",
          "There's nothing else worth seeing nearby",
        ],
        correctIndex: 0,
        explanation: "Sant'Ambrogio, Milan's great 4th-century basilica, is a ~10-minute walk west and free to enter — a natural next stop from the Ambrosiana.",
      },
    ],
  },

  "milan-07": {
    intro: "The Brera is Milan's great painting gallery, tucked in its most charming quarter. Plan the visit and the timing.",
    spots: [
      {
        id: "milan-07-s1", label: "Free Sunday",
        situation: "You're flexible on dates and want to save on admission to the Pinacoteca di Brera.",
        prompt: "When is entry free?",
        options: [
          "Every Monday",
          "The first Sunday of the month",
          "Only on Italian national holidays",
          "Never — Brera has no free days",
        ],
        correctIndex: 1,
        explanation: "State museums in Italy, including the Brera, offer free entry on the first Sunday of each month — though it's busier, so go early.",
      },
      {
        id: "milan-07-s2", label: "The Masterpiece",
        situation: "A friend says you can't leave Brera without seeing the dramatically foreshortened body of Christ in Room VI.",
        prompt: "Which painting is that?",
        options: [
          "Mantegna's Lamentation over the Dead Christ",
          "Caravaggio's Supper at Emmaus",
          "Raphael's The Marriage of the Virgin",
          "Hayez's The Kiss",
        ],
        correctIndex: 0,
        explanation: "Mantegna's Dead Christ, with its startling foreshortening, is the Brera's signature work — in Room VI. (Raphael's Marriage of the Virgin and Hayez's The Kiss are also here.)",
      },
      {
        id: "milan-07-s3", label: "Closed Day",
        situation: "You planned the Brera for a Monday morning.",
        prompt: "What should you check first?",
        options: [
          "Nothing — it's open every day",
          "It's closed Mondays — pick another day",
          "It only opens Monday afternoons",
          "Mondays require advance booking only",
        ],
        correctIndex: 1,
        explanation: "The Pinacoteca di Brera is closed on Mondays, like most Italian state museums — plan it for Tuesday through Sunday.",
      },
      {
        id: "milan-07-s4", label: "The Neighbourhood",
        situation: "After the gallery you want to enjoy the surrounding Brera district.",
        prompt: "What is the Brera quarter known for?",
        options: [
          "Industrial warehouses and nightclubs",
          "Cobbled artist-quarter streets, galleries, and aperitivo cafés",
          "A modern financial-tower district",
          "A purely residential suburb with nothing to do",
        ],
        correctIndex: 1,
        explanation: "Brera is Milan's bohemian artist quarter — narrow cobbled lanes, galleries, the botanical garden, and excellent aperitivo spots steps from the museum.",
      },
    ],
  },

  "milan-08": {
    intro: "Aperitivo is Milan's gift to the evening: a drink that comes with food, around 6:30pm. Learn the etiquette.",
    spots: [
      {
        id: "milan-08-s1", label: "What It Is",
        situation: "A local invites you for 'aperitivo' at 6:30pm and you're not sure what to expect.",
        prompt: "What is aperitivo?",
        options: [
          "A pre-dinner drink that comes with a spread of snacks or a buffet, usually for one set price",
          "A full three-course dinner",
          "A late-night dessert course",
          "A morning coffee ritual",
        ],
        correctIndex: 0,
        explanation: "Aperitivo is the early-evening ritual: you buy a drink and food comes with it — small plates or a buffet — typically from around 6 to 9pm.",
      },
      {
        id: "milan-08-s2", label: "Order the Classic",
        situation: "You want the iconic Milanese aperitivo cocktail.",
        prompt: "What do you order?",
        options: [
          "A Negroni or Campari Spritz — both built on Milan's own Campari",
          "A piña colada",
          "A pint of lager",
          "An espresso martini",
        ],
        correctIndex: 0,
        explanation: "Campari was invented in Milan, so the Negroni and the Campari/Aperol Spritz are the quintessential aperitivo orders here.",
      },
      {
        id: "milan-08-s3", label: "Buffet Etiquette",
        situation: "The bar lays out a generous aperitivo buffet with your €12 drink.",
        prompt: "What's the polite way to use it?",
        options: [
          "Pile a dinner-sized plate and skip paying for food",
          "Take a reasonable plate to accompany your drink — it's a snack, not a free dinner",
          "Don't touch the buffet; it's only for staff",
          "Ask to take the leftovers home",
        ],
        correctIndex: 1,
        explanation: "The buffet accompanies your drink — take a sensible plate. Treating it as an all-you-can-eat dinner is poor form ('apericena' exists, but the classic buffet is a snack).",
      },
      {
        id: "milan-08-s4", label: "Tipping",
        situation: "Your aperitivo bill comes to €12 and you wonder about a tip.",
        prompt: "What's customary in Milan?",
        options: [
          "A 20% tip is expected, as in the US",
          "Tipping is not obligatory; rounding up or leaving small change is plenty",
          "You must tip exactly 15% or it's an insult",
          "Never leave anything — tipping is forbidden",
        ],
        correctIndex: 1,
        explanation: "Italy has no strong tipping culture. A service charge ('coperto') is often included; rounding up or leaving a euro or two is generous, not the US-style 20%.",
      },
    ],
  },

  "milan-09": {
    intro: "The Navigli canals are Milan's nightlife heart — and a Leonardo engineering relic. Navigate them like a regular.",
    spots: [
      {
        id: "milan-09-s1", label: "Getting There",
        situation: "You want to reach the Navigli district for the evening.",
        prompt: "Which metro stop is the gateway?",
        options: [
          "Duomo, then a long walk",
          "Porta Genova (M2 green), at the top of the Naviglio Grande",
          "Centrale FS",
          "Cairoli, by the castle",
        ],
        correctIndex: 1,
        explanation: "Porta Genova on M2 (green) sits right at the head of the Naviglio Grande — the simplest metro access to the canal district.",
      },
      {
        id: "milan-09-s2", label: "The Antique Market",
        situation: "You love browsing antiques and want to time your Navigli visit for the famous market.",
        prompt: "When is the big canal-side antiques market?",
        options: [
          "The last Sunday of each month, along the Naviglio Grande",
          "Every weekday morning",
          "Only during December",
          "There is no market on the canals",
        ],
        correctIndex: 0,
        explanation: "The Mercatone dell'Antiquariato lines the Naviglio Grande on the last Sunday of every month — hundreds of stalls of antiques and vintage finds.",
      },
      {
        id: "milan-09-s3", label: "The Leonardo Link",
        situation: "A guide notes Leonardo da Vinci's connection to these canals.",
        prompt: "What did Leonardo contribute?",
        options: [
          "He painted murals along the canal banks",
          "He designed lock systems (the mitre-gate locks) to manage the canal water levels",
          "He personally dug the Naviglio Grande",
          "He had no real connection to the canals",
        ],
        correctIndex: 1,
        explanation: "Leonardo worked on the canal lock engineering, refining mitre-gate locks that let boats move between water levels — part of Milan's medieval canal network.",
      },
      {
        id: "milan-09-s4", label: "Pickpocket Sense",
        situation: "It's a packed Saturday night on the crowded canal-side, drink in hand.",
        prompt: "What's the sensible precaution?",
        options: [
          "Keep your phone and wallet in a front or zipped pocket and stay aware in the crush",
          "Leave your bag open for easy access",
          "Carry your passport and all your cash with you",
          "Hang your bag on the back of your chair facing the crowd",
        ],
        correctIndex: 0,
        explanation: "Crowded nightlife areas attract pickpockets. Front or zipped pockets, a crossbody bag kept in front, and leaving your passport at the hotel are the basics.",
      },
    ],
  },

  "milan-10": {
    intro: "San Lorenzo's Roman columns are free, ancient, and a magnet at dusk. Know what you're looking at.",
    spots: [
      {
        id: "milan-10-s1", label: "What They Are",
        situation: "You stand before a row of sixteen tall columns in front of the Basilica of San Lorenzo.",
        prompt: "What are these columns?",
        options: [
          "Modern replicas built for a film set",
          "Genuine 2nd–3rd-century Roman columns, reused here from an earlier imperial structure",
          "Medieval church buttresses",
          "Renaissance follies from the 1500s",
        ],
        correctIndex: 1,
        explanation: "The Colonne di San Lorenzo are real Roman columns (2nd–3rd century), relocated in late antiquity to front the basilica — a survival of imperial Mediolanum.",
      },
      {
        id: "milan-10-s2", label: "Cost",
        situation: "You want to see and photograph the columns and the square.",
        prompt: "What does it cost?",
        options: [
          "€10 entry to the colonnade",
          "Nothing — the columns stand free in a public square",
          "€5, cash only",
          "Free only after 7pm",
        ],
        correctIndex: 1,
        explanation: "The columns and the piazza are free public space, open at all hours — one of central Milan's great free sights.",
      },
      {
        id: "milan-10-s3", label: "Evening Scene",
        situation: "It's around 7pm and the square is filling with young people sitting on the steps.",
        prompt: "What's happening?",
        options: [
          "A ticketed concert is starting",
          "It's a popular pre-night-out gathering spot — locals meet here for drinks at dusk",
          "A protest is forming",
          "The square is closing for the night",
        ],
        correctIndex: 1,
        explanation: "The Colonne are a beloved evening gathering point — students and locals sit on the steps with takeaway drinks before heading to the nearby Navigli and Ticinese bars.",
      },
      {
        id: "milan-10-s4", label: "Step Inside",
        situation: "Behind the columns is the Basilica of San Lorenzo, and you have 20 minutes.",
        prompt: "Why is it worth a look?",
        options: [
          "It's a modern concrete church of no historic note",
          "It's an early-Christian basilica with a 4th-century chapel and ancient mosaics",
          "It's permanently closed to visitors",
          "It only contains a gift shop",
        ],
        correctIndex: 1,
        explanation: "San Lorenzo is one of Europe's oldest churches, with the 4th-century Chapel of Sant'Aquilino and surviving early-Christian mosaics — well worth the short visit.",
      },
    ],
  },

  "milan-11": {
    intro: "Sant'Ambrogio is older and quieter than the Duomo — and central to Milan's identity. Visit it thoughtfully.",
    spots: [
      {
        id: "milan-11-s1", label: "Who It Honours",
        situation: "The basilica is named for Milan's patron saint, who shaped the early Church.",
        prompt: "Who was he?",
        options: [
          "Saint Ambrose (Sant'Ambrogio), 4th-century bishop of Milan",
          "Saint Peter",
          "Saint Francis of Assisi",
          "Saint Mark of Venice",
        ],
        correctIndex: 0,
        explanation: "Sant'Ambrogio is dedicated to Saint Ambrose, the 4th-century bishop and patron of Milan, who famously baptised Saint Augustine here in 387 AD.",
      },
      {
        id: "milan-11-s2", label: "Cost & Crowds",
        situation: "You want a calm, free historic church away from the Duomo throngs.",
        prompt: "What's true of Sant'Ambrogio?",
        options: [
          "It's a €20 ticketed attraction, always packed",
          "It's free to enter and far less crowded than the Duomo",
          "It's open only to worshippers, never tourists",
          "It charges the same as the Duomo roof",
        ],
        correctIndex: 1,
        explanation: "Sant'Ambrogio is free to enter and undervisited compared with the Duomo — one of Milan's most rewarding quiet stops.",
      },
      {
        id: "milan-11-s3", label: "Get There",
        situation: "You're plotting the metro route to the basilica.",
        prompt: "Which stop serves it?",
        options: [
          "Sant'Ambrogio station on M2 (green), right by the church",
          "Duomo on M1",
          "Centrale FS",
          "Porta Genova on the canals",
        ],
        correctIndex: 0,
        explanation: "The M2 (green) line has a stop named Sant'Ambrogio, a 2-minute walk from the basilica — the obvious approach.",
      },
      {
        id: "milan-11-s4", label: "Respect the Space",
        situation: "A Mass is in progress in a side chapel as you arrive to sightsee.",
        prompt: "What's the right behaviour?",
        options: [
          "Walk through the service taking flash photos",
          "Visit quietly, avoid the area in use, and skip flash — it's an active place of worship",
          "Ask the priest to pause so you can photograph the altar",
          "Leave immediately; tourists aren't allowed during Mass",
        ],
        correctIndex: 1,
        explanation: "Active churches welcome respectful visitors: keep quiet, stay clear of any service in progress, dress modestly, and don't use flash.",
      },
    ],
  },

  "milan-12": {
    intro: "Porta Garibaldi and Isola show Milan's modern face — vertical forests and design towers. See it smartly.",
    spots: [
      {
        id: "milan-12-s1", label: "The Vertical Forest",
        situation: "Two residential towers covered in thousands of trees and shrubs dominate the skyline here.",
        prompt: "What are they called?",
        options: [
          "Bosco Verticale (the Vertical Forest)",
          "The Pirelli Gardens",
          "Torre Velasca",
          "The Green Galleria",
        ],
        correctIndex: 0,
        explanation: "The Bosco Verticale ('Vertical Forest'), completed in 2014, is a pair of residential towers planted with trees and shrubs — a landmark of sustainable design.",
      },
      {
        id: "milan-12-s2", label: "Can You Go Up?",
        situation: "You'd love to ride to the top of the Bosco Verticale for the view.",
        prompt: "What's the reality?",
        options: [
          "There's a public observation deck at the top",
          "They're private apartments — you admire them from the piazza below, not inside",
          "Free rooftop tours run hourly",
          "You can rent a room by the hour to see the view",
        ],
        correctIndex: 1,
        explanation: "The Bosco Verticale towers are private residences with no public access — you photograph and enjoy them from Piazza Gae Aulenti and the surrounding streets.",
      },
      {
        id: "milan-12-s3", label: "The Square",
        situation: "Nearby is a modern raised piazza ringed by glass towers and fountains.",
        prompt: "What is it?",
        options: [
          "Piazza Gae Aulenti — a modern pedestrian square in the Porta Nuova district",
          "Piazza del Duomo",
          "Piazza della Scala",
          "Piazza San Babila",
        ],
        correctIndex: 0,
        explanation: "Piazza Gae Aulenti is the centrepiece of the redeveloped Porta Nuova business district — a circular elevated plaza with fountains, shops, and skyscrapers.",
      },
      {
        id: "milan-12-s4", label: "Getting There",
        situation: "You're at the Duomo and want to reach Porta Garibaldi / Isola.",
        prompt: "What's the easy route?",
        options: [
          "It's a 2-minute walk from the Duomo",
          "Metro to Garibaldi FS (M2 green / M5 purple) — about 15 minutes from the centre",
          "Only reachable by regional train",
          "Take a ferry up the canal",
        ],
        correctIndex: 1,
        explanation: "Garibaldi FS, served by M2 (green) and M5 (purple), drops you right at Porta Nuova — roughly 15 minutes from the Duomo by metro.",
      },
    ],
  },

  "milan-13": {
    intro: "La Scala is the world's most famous opera house. In July the season's over — but there's still a way in.",
    spots: [
      {
        id: "milan-13-s1", label: "July Reality",
        situation: "You hoped to see a grand opera at La Scala during your July visit.",
        prompt: "What's the situation?",
        options: [
          "The main opera season runs through summer with nightly shows",
          "The main season ends around June/July, but summer concerts and the museum continue",
          "La Scala is shut entirely all summer with nothing to see",
          "Only ballet runs in July, never music",
        ],
        correctIndex: 1,
        explanation: "La Scala's main season traditionally closes by July (the famous opening is December 7, Saint Ambrose's day). Summer brings occasional concerts, and the museum stays open.",
      },
      {
        id: "milan-13-s2", label: "The Museum",
        situation: "With no opera tonight, you still want to experience La Scala.",
        prompt: "What can you do?",
        options: [
          "Visit the Teatro alla Scala Museum (€9), which usually includes a peek into the auditorium",
          "Nothing — the building is sealed when there's no show",
          "Only attend a rehearsal by invitation",
          "Buy a standing-room ticket for an empty hall",
        ],
        correctIndex: 0,
        explanation: "The theatre museum (around €9) lets you see costumes, instruments, and — when no rehearsal is on — a view into the red-and-gold auditorium itself.",
      },
      {
        id: "milan-13-s3", label: "Cheap Seats Trick",
        situation: "Back in season, you want to see an opera on a budget at La Scala.",
        prompt: "What's the classic budget option?",
        options: [
          "Same-day discounted gallery (loggione) tickets sold from the box office",
          "There are no cheap tickets ever",
          "Sneak in during intermission",
          "Standing on the street to hear it through the doors",
        ],
        correctIndex: 0,
        explanation: "La Scala releases a limited number of same-day gallery (loggione) seats at low prices from the box office — the traditional way budget opera-lovers and students get in.",
      },
      {
        id: "milan-13-s4", label: "Dress Code",
        situation: "You do get to an evening performance during the season.",
        prompt: "How should you dress?",
        options: [
          "Beachwear is fine",
          "Smart attire — Milanese audiences dress up, and very casual dress is frowned upon",
          "Costume is mandatory",
          "There's a strict white-tie-only rule for all seats",
        ],
        correctIndex: 1,
        explanation: "While full black-tie isn't required outside galas, La Scala expects smart dress — no shorts, flip-flops, or beachwear. Milanese audiences take it seriously.",
      },
    ],
  },

  "milan-14": {
    intro: "Lake Como is the easiest, most beautiful day trip from Milan. Pick the right train and town.",
    spots: [
      {
        id: "milan-14-s1", label: "Which Station",
        situation: "You're heading to Varenna on Lake Como for the day.",
        prompt: "Where and how do you go?",
        options: [
          "Trenord from Milano Centrale to Varenna-Esino, about 1 hour for €7.50",
          "A 3-hour bus from the Duomo",
          "Trenitalia high-speed from Rogoredo",
          "There's no direct train; you must drive",
        ],
        correctIndex: 0,
        explanation: "Trenord regional trains run from Centrale to Varenna-Esino in about 1 hour (~€7.50 each way) — the classic, cheap Lake Como day trip.",
      },
      {
        id: "milan-14-s2", label: "Best Base",
        situation: "You want a pretty lakeside town that's also a ferry hub to Bellagio and Menaggio.",
        prompt: "Which town makes the best day base?",
        options: [
          "Varenna — small, scenic, and on the central ferry triangle",
          "A random industrial suburb of Como city",
          "Milan itself — there's no need to leave",
          "Lugano, in Switzerland",
        ],
        correctIndex: 0,
        explanation: "Varenna sits on the mid-lake ferry triangle with Bellagio and Menaggio — charming, walkable, and ideally placed for a boat hop. (Como city is the other main option.)",
      },
      {
        id: "milan-14-s3", label: "Crossing the Lake",
        situation: "From Varenna you want to reach Bellagio across the water.",
        prompt: "How do you get there?",
        options: [
          "Take the regular lake ferry — a short, scenic crossing",
          "Swim across",
          "There's no connection; go back to Milan and around",
          "Only by private helicopter",
        ],
        correctIndex: 0,
        explanation: "Frequent passenger ferries link Varenna, Bellagio, and Menaggio in minutes — buy tickets at the lakeside dock; it's part of the day's pleasure.",
      },
      {
        id: "milan-14-s4", label: "Beat the Crowds",
        situation: "You can choose which day to go, and you want the lake at its calmest.",
        prompt: "What's the smarter choice in July?",
        options: [
          "A summer weekend, when day-trippers flood in",
          "A weekday like Tuesday, before the weekend crush",
          "Ferragosto (Aug 15), the busiest day of all",
          "It makes no difference in summer",
        ],
        correctIndex: 1,
        explanation: "Lake Como is mobbed on summer weekends. A weekday — Tuesday is a good bet — means fewer crowds on the ferries and in Bellagio.",
      },
    ],
  },

  "milan-15": {
    intro: "Pavia is the quieter, cheaper day trip — and the Certosa is a genuine wonder. Get the logistics right.",
    spots: [
      {
        id: "milan-15-s1", label: "The Trip",
        situation: "You're considering Pavia as a half-day escape from Milan.",
        prompt: "How far and how much?",
        options: [
          "Trenord, about 30 minutes for roughly €4",
          "A 2-hour express for €30",
          "Only reachable by a long bus ride",
          "It's a 5-minute metro ride",
        ],
        correctIndex: 0,
        explanation: "Pavia is about 30 minutes south of Milan by Trenord for around €4 — one of the cheapest, easiest day trips from the city.",
      },
      {
        id: "milan-15-s2", label: "The Main Sight",
        situation: "Everyone says the unmissable site near Pavia is a vast Carthusian monastery.",
        prompt: "What is it?",
        options: [
          "The Certosa di Pavia, a lavish 14th–15th-century monastery",
          "A modern outlet shopping mall",
          "A Roman amphitheatre",
          "A ski resort",
        ],
        correctIndex: 0,
        explanation: "The Certosa di Pavia is an extraordinarily ornate Carthusian monastery begun in 1396 — the area's star attraction, with a marble façade unlike anything else in Lombardy.",
      },
      {
        id: "milan-15-s3", label: "Entry Cost",
        situation: "You arrive at the Certosa wondering what to pay.",
        prompt: "What's the deal on admission?",
        options: [
          "Entry is free, though a donation/tip to the guiding monk is customary",
          "A strict €40 ticket",
          "It's permanently closed to visitors",
          "Only paid guided coach tours can enter",
        ],
        correctIndex: 0,
        explanation: "The Certosa is free to enter; visits to the inner cloister are often led by a monk, and a small donation is appreciated. Check it's not closed midday or Monday.",
      },
      {
        id: "milan-15-s4", label: "Don't Get Stranded",
        situation: "The Certosa is a few km outside Pavia town, and you used a local connection to reach it.",
        prompt: "What should you plan for?",
        options: [
          "Nothing — trains run every two minutes",
          "Check return train/bus times in advance — the Certosa stop has infrequent service, especially midday",
          "Assume a taxi will always be waiting",
          "Walk the 30 km back to Milan",
        ],
        correctIndex: 1,
        explanation: "The Certosa di Pavia rail stop has sparse service. Note your return times before you go, and beware the long midday closure (riposo) of the monastery itself.",
      },
    ],
  },

  "milan-16": {
    intro: "The Monumental Cemetery is an open-air sculpture gallery. Free, moving, and easy to misjudge the etiquette.",
    spots: [
      {
        id: "milan-16-s1", label: "What It Is",
        situation: "A guidebook calls the Cimitero Monumentale a must-see.",
        prompt: "Why visit a cemetery?",
        options: [
          "It's a vast open-air museum of dramatic 19th–20th-century funerary sculpture by major artists",
          "It's a hidden shopping arcade",
          "It hosts nightly concerts",
          "It's simply a place to avoid",
        ],
        correctIndex: 0,
        explanation: "Milan's wealthy bourgeoisie commissioned spectacular tombs and monuments here, making the Cimitero Monumentale one of Italy's great open-air sculpture collections.",
      },
      {
        id: "milan-16-s2", label: "Cost & Days",
        situation: "You're planning when to go.",
        prompt: "What's true?",
        options: [
          "Free entry, open Tuesday–Sunday (closed Mondays)",
          "€25 timed tickets only",
          "Open only one Sunday a year",
          "Closed to all visitors permanently",
        ],
        correctIndex: 0,
        explanation: "Entry is free; the cemetery is open Tuesday through Sunday and closed Mondays — pick up the free map at the entrance to find the notable tombs.",
      },
      {
        id: "milan-16-s3", label: "Behave Well",
        situation: "You want photos of the sculptures, but families are visiting graves nearby.",
        prompt: "What's appropriate?",
        options: [
          "Loud group selfies right beside mourners",
          "Photograph the monuments quietly and respectfully — it's still an active cemetery",
          "Climb the statues for a better angle",
          "Picnic on the tomb slabs",
        ],
        correctIndex: 1,
        explanation: "It remains a working cemetery. Quiet, respectful photography is fine; climbing monuments, loud behaviour, or intruding on mourners is not.",
      },
      {
        id: "milan-16-s4", label: "Getting There",
        situation: "You're choosing how to reach the Cimitero Monumentale.",
        prompt: "What's a straightforward route?",
        options: [
          "Metro M5 (purple) to Monumentale, or a tram to the entrance",
          "It's only reachable by regional train",
          "A 3-hour walk from the Duomo",
          "By boat along the Navigli",
        ],
        correctIndex: 0,
        explanation: "The M5 (purple) line has a Monumentale stop near the entrance, and several trams serve it too — an easy ride north of the centre.",
      },
    ],
  },

  "milan-17": {
    intro: "The Quadrilatero della Moda is Milan's luxury heart. You don't need to buy a thing to enjoy it.",
    spots: [
      {
        id: "milan-17-s1", label: "The Streets",
        situation: "You want to wander Milan's famous fashion district.",
        prompt: "Which streets form the Quadrilatero della Moda?",
        options: [
          "Via Montenapoleone, Via della Spiga, and the surrounding luxury blocks near San Babila",
          "The streets around the Navigli canals",
          "The Isola design district",
          "Corso Buenos Aires only",
        ],
        correctIndex: 0,
        explanation: "The 'fashion quadrilateral' centres on Via Montenapoleone and Via della Spiga near San Babila — the flagship homes of Prada, Armani, Versace, and the rest.",
      },
      {
        id: "milan-17-s2", label: "Cost of Looking",
        situation: "You're on a budget but love the spectacle of the boutiques.",
        prompt: "What does window-shopping the Quadrilatero cost?",
        options: [
          "An entry fee per street",
          "Nothing — it's free to walk and window-shop; browsing is the experience",
          "A minimum purchase to enter the area",
          "A guided-tour ticket is required",
        ],
        correctIndex: 1,
        explanation: "Walking the Quadrilatero and admiring the windows costs nothing — the people-watching and shop displays are the point, no purchase needed.",
      },
      {
        id: "milan-17-s3", label: "Sale Season",
        situation: "You actually do want to buy something and hope to catch a discount.",
        prompt: "When are Italy's summer sales (saldi)?",
        options: [
          "They start in early July and run through summer",
          "Only in December",
          "There are never sales in luxury Milan",
          "Random unannounced days",
        ],
        correctIndex: 0,
        explanation: "Italy's regulated summer sales (saldi) begin in early July — good timing for a July visit if you want a genuine markdown on Italian fashion.",
      },
      {
        id: "milan-17-s4", label: "Tax Refund",
        situation: "As a non-EU visitor you make a large purchase and want money back at the airport.",
        prompt: "What should you do?",
        options: [
          "Ask the shop for a tax-free (VAT refund) form and present it with goods at airport customs when you leave the EU",
          "Nothing can be reclaimed",
          "Mail the receipt back from home for a refund",
          "Refunds only apply to EU residents",
        ],
        correctIndex: 0,
        explanation: "Non-EU shoppers can reclaim VAT on qualifying purchases: get the tax-free form in-store, then validate it with goods and receipts at customs on departure from the EU.",
      },
    ],
  },

  "milan-18": {
    intro: "Beneath modern Milan lies Roman Mediolanum, once a capital of the empire. Trace it on foot.",
    spots: [
      {
        id: "milan-18-s1", label: "Imperial Past",
        situation: "A plaque notes Milan's surprising importance in late antiquity.",
        prompt: "What was Mediolanum?",
        options: [
          "An unimportant frontier village",
          "A capital of the Western Roman Empire, where the Edict of Milan (313 AD) was issued",
          "A Greek trading colony",
          "Never part of the Roman Empire",
        ],
        correctIndex: 1,
        explanation: "Roman Mediolanum served as a capital of the Western Empire; the Edict of Milan (313 AD) granting Christians toleration was issued here under Constantine and Licinius.",
      },
      {
        id: "milan-18-s2", label: "The Museum",
        situation: "You want to see Roman Milan's artefacts and remains in one place.",
        prompt: "Where do you go?",
        options: [
          "The Museo Archeologico on Corso Magenta (around €5)",
          "The Duomo treasury",
          "The Stock Exchange",
          "There's no Roman museum in Milan",
        ],
        correctIndex: 0,
        explanation: "The Civico Museo Archeologico on Corso Magenta (~€5) houses Roman Mediolanum's finds and incorporates surviving Roman tower-and-wall remains on its grounds.",
      },
      {
        id: "milan-18-s3", label: "Still Standing",
        situation: "Behind the archaeological museum you find a large surviving Roman structure.",
        prompt: "What is it?",
        options: [
          "A Roman tower linked to the circus/amphitheatre area, still standing in the street",
          "A medieval clock tower",
          "A 19th-century folly",
          "A modern art installation",
        ],
        correctIndex: 0,
        explanation: "A Roman tower (associated with the imperial palace/circus complex) survives by the museum — a tangible piece of Mediolanum standing amid the modern city.",
      },
      {
        id: "milan-18-s4", label: "Combine the Walk",
        situation: "You want to fold the Roman sites into a coherent walking route.",
        prompt: "What's a sensible pairing nearby?",
        options: [
          "Add Sant'Ambrogio and the San Lorenzo Roman columns — both close and on theme",
          "Take a train to Pavia mid-walk",
          "Drive to Lake Como first",
          "There's nothing else Roman or historic nearby",
        ],
        correctIndex: 0,
        explanation: "The Archaeological Museum, Sant'Ambrogio, and the Colonne di San Lorenzo are all in the same southwest quarter — an easy, themed walking loop through old Milan.",
      },
    ],
  },

  "milan-19": {
    intro: "Italy's August holiday changes everything. Knowing the rhythm of July vs August saves your trip.",
    spots: [
      {
        id: "milan-19-s1", label: "Ferragosto",
        situation: "You hear locals talk about 'Ferragosto' affecting your plans.",
        prompt: "What is Ferragosto?",
        options: [
          "The August 15 national holiday, the peak of Italy's summer break",
          "A spring food festival",
          "A type of train pass",
          "Milan's New Year celebration",
        ],
        correctIndex: 0,
        explanation: "Ferragosto, August 15, is Italy's mid-summer public holiday — the high point of the August exodus, when many Milanese leave the city entirely.",
      },
      {
        id: "milan-19-s2", label: "August Closures",
        situation: "You're deciding between a late-July and a mid-August visit to Milan.",
        prompt: "What's the practical difference?",
        options: [
          "August is busier in the city with everything open",
          "In August many family-run shops, restaurants, and businesses close for weeks; July keeps the city more normal",
          "Nothing changes between the months",
          "July is when everything shuts down",
        ],
        correctIndex: 1,
        explanation: "Around Ferragosto, many independent Milan shops and trattorias close for one to several weeks. July keeps the city far more functional — a reason July beats August.",
      },
      {
        id: "milan-19-s3", label: "Still Open",
        situation: "If you do visit around mid-August, you want things that stay reliably open.",
        prompt: "What's the safe bet?",
        options: [
          "Major museums and sights (Duomo, castle, big galleries) and tourist-area restaurants",
          "Only neighbourhood family trattorias",
          "Nothing at all is open",
          "Just the financial district offices",
        ],
        correctIndex: 0,
        explanation: "Major monuments and tourist-oriented venues generally stay open through August; it's the small, local, family-run places that take the long Ferragosto break.",
      },
      {
        id: "milan-19-s4", label: "Beat the Heat",
        situation: "It's a 34°C July afternoon and you're flagging in the sun.",
        prompt: "What's the local-savvy move?",
        options: [
          "Sightsee hardest in the early morning and evening; spend the hot midday in cool museums, churches, or the Galleria",
          "Push through noon outdoors with no water",
          "Only go out between 1 and 3pm",
          "Avoid all air-conditioned spaces",
        ],
        correctIndex: 0,
        explanation: "Mirror the Italian rhythm: early-morning and evening sightseeing, with the hot midday spent indoors (museums, churches, the shaded Galleria) and plenty of water.",
      },
    ],
  },

  "milan-20": {
    intro: "Tie it together. A week in Milan works only if you sequence the bookings and the day trips correctly.",
    spots: [
      {
        id: "milan-20-s1", label: "Book First",
        situation: "You're building your week and want to lock in the hardest reservation before anything else.",
        prompt: "What do you book first?",
        options: [
          "The Last Supper at vivaticket.com — it sells out months ahead and dictates the rest of your schedule",
          "A canal-side dinner",
          "Your aperitivo bar",
          "Nothing needs booking in advance",
        ],
        correctIndex: 0,
        explanation: "The Last Supper has the tightest supply of any Milan sight. Book it first (months ahead) and plan the week around the slot you can get.",
      },
      {
        id: "milan-20-s2", label: "Can't-Miss Core",
        situation: "A friend has only two days and asks what they absolutely cannot skip.",
        prompt: "What's the irreducible Milan shortlist?",
        options: [
          "The Duomo (and roof), the Galleria, the Last Supper, and Castello Sforzesco",
          "Only the fashion shops",
          "Just a day trip to Como and nothing in the city",
          "The financial district towers",
        ],
        correctIndex: 0,
        explanation: "The core that defines a first Milan visit: the Duomo and its roof, the Galleria, Leonardo's Last Supper, and the Castello Sforzesco — fit everything else around these.",
      },
      {
        id: "milan-20-s3", label: "Slot the Day Trip",
        situation: "You want one day trip (Como or Pavia) without wrecking your city days.",
        prompt: "How do you schedule it?",
        options: [
          "Give it a full dedicated weekday and keep city sights for the other days",
          "Cram it into the same afternoon as the Last Supper",
          "Try to do both Como and Pavia in one morning",
          "Skip planning and decide at the station each day",
        ],
        correctIndex: 0,
        explanation: "Day trips eat a whole day with travel. Dedicate one weekday (Como or Pavia, not both), and keep your timed city bookings on separate days.",
      },
      {
        id: "milan-20-s4", label: "Daily Rhythm",
        situation: "You want each day to flow the way Milan actually lives in July.",
        prompt: "What's the right daily shape?",
        options: [
          "Morning sights → cool midday indoors/lunch → late-afternoon sights → aperitivo around 6:30pm → late dinner",
          "Big lunch, nap all afternoon, skip the evening",
          "Sightsee only between noon and 3pm",
          "Dinner at 5pm, then straight to bed",
        ],
        correctIndex: 0,
        explanation: "Match the local rhythm: front-load mornings, retreat from the midday heat, sightsee again late afternoon, hit aperitivo around 6:30pm, and dine late (8:30–9pm).",
      },
    ],
  },
};
