import type { ScenarioConfig } from "./types";

// "Decision Trainer" scenarios for the Paris in July travel epoch.
// Each spot is a real, practical Paris travel decision — navigation, ordering,
// museum logistics, etiquette, money/safety, and day-trips. The marked answer
// is the genuinely correct/best choice. correctIndex and explanation are
// stripped server-side before reaching the client.
export const parisScenarios: Record<string, ScenarioConfig> = {
  "paris-01": {
    intro: "You've just landed and you're learning to move around Paris by Metro and RER. Make the smart transport calls.",
    spots: [
      {
        id: "paris-01-s1", label: "From the Airport",
        situation: "You land at Charles de Gaulle (CDG) on a Monday morning and want the cheapest fast way into central Paris (Gare du Nord / Châtelet).",
        prompt: "What's the best move?",
        options: [
          "Take a taxi — it's the only reliable option",
          "Take RER B straight to Gare du Nord / Châtelet in about 35 minutes",
          "Wait for the last Metro at 2:15am",
          "Take RER A toward Versailles",
        ],
        correctIndex: 1,
        explanation: "RER B runs from CDG to Gare du Nord and Châtelet-Les Halles in around 35 minutes — far cheaper than a taxi and faster in traffic.",
      },
      {
        id: "paris-01-s2", label: "Buy the Pass",
        situation: "You'll be in Paris from Monday to Sunday and will ride the Metro, RER, and buses many times each day, including a trip to Versailles.",
        prompt: "Which ticket gives the best value?",
        options: [
          "A single t+ ticket each time you ride",
          "The Navigo Semaine weekly pass, zones 1–5 (~€30)",
          "A Mobilis one-day pass bought fresh every morning",
          "Nothing — just walk everywhere",
        ],
        correctIndex: 1,
        explanation: "The Navigo Semaine (weekly pass, zones 1–5, ~€30) covers all Metro, RER, bus and tram including Versailles. Buy it on a Monday for full value.",
      },
      {
        id: "paris-01-s3", label: "Beat the Heat",
        situation: "It's a 35°C July afternoon and you need to cross the city. Several lines could get you there.",
        prompt: "Which line is the most comfortable choice?",
        options: [
          "Line 14 — fully automated and air-conditioned",
          "Any line — they're all the same",
          "An old rolling-stock line with open windows",
          "Skip the Metro and stand on a hot platform",
        ],
        correctIndex: 0,
        explanation: "Line 14 is fully automated and always air-conditioned — the best bet in July heat (most older lines are not).",
      },
      {
        id: "paris-01-s4", label: "Last Train Home",
        situation: "It's a Friday and you're out at 1am, worried you've missed the Metro back to your flat.",
        prompt: "What's true about late-night transport?",
        options: [
          "The Metro shut at 9pm — you must walk",
          "On weekends the last Metro runs around 2:15am, with Noctilien night buses after",
          "Trains run 24 hours every day",
          "Only taxis operate after midnight",
        ],
        correctIndex: 1,
        explanation: "On weekend nights the last Metro is around 2:15am; the Noctilien night-bus network then covers all arrondissements until early morning.",
      },
    ],
  },

  "paris-02": {
    intro: "You want to see the Palais Garnier, the opulent 19th-century opera house. Plan the visit and mind the etiquette.",
    spots: [
      {
        id: "paris-02-s1", label: "Book Ahead",
        situation: "It's July and the self-guided visit queue without a ticket is running about 45 minutes.",
        prompt: "What's the smart way to visit?",
        options: [
          "Book the €14 self-guided visit online at operadeparis.fr",
          "Just queue — it's quicker than booking",
          "Wait for a free open day that doesn't exist in July",
          "Only a full performance ticket gets you inside",
        ],
        correctIndex: 0,
        explanation: "A self-guided visit costs €14 and booking online at operadeparis.fr skips the long July queue. No performance ticket is needed to see the interior.",
      },
      {
        id: "paris-02-s2", label: "Hidden View",
        situation: "You've finished the grand staircase and grand foyer and have 20 minutes left. Almost nobody finds the next spot.",
        prompt: "What's worth seeking out?",
        options: [
          "The underground lake — open to tourists by boat",
          "The Bibliothèque-Musée de l'Opéra, off the grand foyer — opera manuscripts, models, and costumes most visitors walk past",
          "The orchestra pit during a live show",
          "The Phantom's actual lair beneath the stage",
        ],
        correctIndex: 1,
        explanation: "The Bibliothèque-Musée de l'Opéra, included in a Palais Garnier visit, holds a quiet collection of opera history most tourists miss. The underground lake is real but closed to the public.",
      },
      {
        id: "paris-02-s3", label: "Add a Free View",
        situation: "After the Garnier you want one more good viewpoint nearby, for free, without booking.",
        prompt: "Where do you go?",
        options: [
          "The Arc de Triomphe roof",
          "The Galeries Lafayette rooftop, a 5-minute walk north on Boulevard Haussmann",
          "Back down into the Metro",
          "The top of the Eiffel Tower",
        ],
        correctIndex: 1,
        explanation: "The Galeries Lafayette rooftop is free, open daily, and only 5 minutes north — a panoramic view over Haussmann's grid with no ticket required.",
      },
      {
        id: "paris-02-s4", label: "Getting There",
        situation: "You're at Châtelet and want to reach the Opéra Garnier by Metro.",
        prompt: "What's the simplest route?",
        options: [
          "Take Line 7 north a few stops to Opéra",
          "Take RER B to the airport first",
          "There's no Metro near the opera house",
          "Walk for an hour — no line serves it",
        ],
        correctIndex: 0,
        explanation: "Lines 3, 7, and 8 all serve Opéra; from Châtelet, Line 7 runs straight north a few stops to the station right by the Palais Garnier.",
      },
    ],
  },

  "paris-03": {
    intro: "The Louvre is the world's busiest museum and July is peak chaos. Plan entry, timing, and what to prioritise.",
    spots: [
      {
        id: "paris-03-s1", label: "Reserve First",
        situation: "You want to visit the Louvre next Tuesday in July. You're tempted to just show up.",
        prompt: "What do you do first?",
        options: [
          "Show up at 10am and buy at the desk",
          "Book a timed slot online at ticketlouvre.fr (€22) — July slots sell out days ahead",
          "Assume EU under-26 free entry means no booking needed",
          "Skip it; tickets are impossible",
        ],
        correctIndex: 1,
        explanation: "Booking is mandatory in July; timed slots at ticketlouvre.fr (€22 adult) sell out days in advance. Even free under-26 EU entry still needs a reserved slot.",
      },
      {
        id: "paris-03-s2", label: "The Right Door",
        situation: "It's 10am on a busy July morning and the glass pyramid entrance has a huge line.",
        prompt: "Which entrance do you use?",
        options: [
          "The Richelieu wing entrance on Rue de Rivoli — far less crowded",
          "The pyramid, since it's the only one",
          "The Tuileries fountain",
          "Climb in via the Carrousel gift shop queue",
        ],
        correctIndex: 0,
        explanation: "The Richelieu wing (Rue de Rivoli) and the Porte des Lions are much quieter than the pyramid at peak times. Enter there in July.",
      },
      {
        id: "paris-03-s3", label: "Quietest Hours",
        situation: "You'd rather not fight the crowds and can choose any visiting time during the week.",
        prompt: "When is the Louvre quietest?",
        options: [
          "Monday mornings",
          "Tuesday at noon",
          "Friday evenings, when it's open until 9:45pm",
          "It's identically packed at all times",
        ],
        correctIndex: 2,
        explanation: "The Friday late opening (to 9:45pm) is consistently among the quietest slots, with no price premium — the smart choice in July.",
      },
      {
        id: "paris-03-s4", label: "Three Hours",
        situation: "You realistically have about three hours and can't see all 35,000 works on display.",
        prompt: "What's the best plan?",
        options: [
          "Try to walk every gallery quickly",
          "Pick a focused highlights route — the Denon wing for the Mona Lisa and Winged Victory, plus the Sully wing for the Venus de Milo",
          "Spend the whole time queueing for the gift shop",
          "Only sit in the café",
        ],
        correctIndex: 1,
        explanation: "A focused 3-hour highlights visit beats rushing everything. The Denon wing holds the Mona Lisa and Winged Victory; the Venus de Milo is over in the Sully wing.",
      },
    ],
  },

  "paris-04": {
    intro: "Everyone wants the Eiffel Tower in July. Know your ticket options and the best free angles.",
    spots: [
      {
        id: "paris-04-s1", label: "Summit Sold Out",
        situation: "You forgot to book and the €32 summit lift tickets are sold out for your dates.",
        prompt: "What's the reliable backup?",
        options: [
          "Queue from 6am hoping for returns",
          "Buy a €14 staircase ticket to Level 2 — walk-up and never sells out",
          "Pay a tout triple price",
          "Give up on going up entirely",
        ],
        correctIndex: 1,
        explanation: "Staircase tickets to Level 2 (€14) are walk-up and never sell out — same Level-2 views, and you can add the lift to the summit for €7 if available.",
      },
      {
        id: "paris-04-s2", label: "The Classic Photo",
        situation: "You want the iconic, symmetrical photograph of the whole tower for free.",
        prompt: "Where do you stand?",
        options: [
          "Directly underneath on the Champ de Mars",
          "Trocadéro (Metro line 9), best at sunset or during the hourly light display",
          "Inside the first-floor restaurant",
          "From the Louvre courtyard",
        ],
        correctIndex: 1,
        explanation: "Trocadéro on Metro line 9 gives the classic symmetrical view; the tower sparkles for 5 minutes every hour after dark — the 11pm display is the most atmospheric.",
      },
      {
        id: "paris-04-s3", label: "Evening Picnic",
        situation: "It's 5pm in July and locals are spreading blankets on the lawn behind the tower.",
        prompt: "What's the move for a perfect free evening?",
        options: [
          "Buy picnic supplies from the Rue Cler market and join the Champ de Mars picnic",
          "Eat at the most expensive tower restaurant only",
          "Leave — the park closes at 5pm",
          "Picnics are banned in Paris parks",
        ],
        correctIndex: 0,
        explanation: "The Champ de Mars is free and Parisians picnic there from 5pm. Grab wine and food at the Rue Cler market street 10 minutes north and settle in.",
      },
      {
        id: "paris-04-s4", label: "Booking Window",
        situation: "Your July dates are confirmed and you definitely want the summit by lift.",
        prompt: "When should you book?",
        options: [
          "The day before you go",
          "On arrival at the ticket booth",
          "Weeks ahead at tickets.toureiffel.paris, ideally the 9am slot",
          "There's no need to book the summit",
        ],
        correctIndex: 2,
        explanation: "Summit lift tickets sell out weeks ahead in July. Book early at tickets.toureiffel.paris and take the 9am slot for the fewest crowds and clearest light.",
      },
    ],
  },

  "paris-05": {
    intro: "Les Invalides holds Napoleon's tomb and France's army museum — grand and far less crowded than Versailles. Plan it.",
    spots: [
      {
        id: "paris-05-s1", label: "The Ticket",
        situation: "You want to see Napoleon's tomb and skip the long ticket queue.",
        prompt: "What do you buy?",
        options: [
          "Nothing — the tomb is always free",
          "The €15 combined ticket, booked online at musee-armee.fr",
          "A separate €40 guided-only tour",
          "A Versailles ticket by mistake",
        ],
        correctIndex: 1,
        explanation: "The €15 combined ticket covers the Dôme church (Napoleon's tomb) and the Musée de l'Armée; booking at musee-armee.fr skips the 20-minute queue.",
      },
      {
        id: "paris-05-s2", label: "Priorities",
        situation: "You only have about 45 minutes before meeting friends.",
        prompt: "What should you prioritise?",
        options: [
          "The full Musée de l'Armée, rushing every gallery",
          "Go straight to the Dôme church for Napoleon's tomb",
          "The gift shop",
          "The outdoor courtyard cannons only",
        ],
        correctIndex: 1,
        explanation: "The essential visit is Napoleon's tomb in the golden Dôme church (~45 min). The army-museum galleries deserve a separate 2–3 hours if you have them.",
      },
      {
        id: "paris-05-s3", label: "Pair It Up",
        situation: "You have a free afternoon in the 7th arrondissement and want a second nearby site.",
        prompt: "What pairs perfectly with Les Invalides?",
        options: [
          "The Louvre, a Metro ride across town",
          "The Musée Rodin, a 10-minute walk east on Rue de Varenne",
          "Versailles, 40 minutes away",
          "Disneyland Paris",
        ],
        correctIndex: 1,
        explanation: "The Musée Rodin is a 10-minute walk east on Rue de Varenne — combining Invalides then Rodin makes an ideal full afternoon with no Metro trip.",
      },
      {
        id: "paris-05-s4", label: "Beat the Heat",
        situation: "It's a sweltering July afternoon and the open courtyard is sun-baked.",
        prompt: "What's the comfortable plan?",
        options: [
          "Arrive before 3pm and shelter in the cool church interior and air-conditioned galleries",
          "Sit in the exposed courtyard at the 3pm heat peak",
          "Only visit at midnight when it's closed",
          "Skip indoor spaces entirely",
        ],
        correctIndex: 0,
        explanation: "The church interior is cool and the Musée de l'Armée galleries are air-conditioned. Arriving before 3pm dodges the afternoon heat peak.",
      },
    ],
  },

  "paris-06": {
    intro: "The Musée Rodin is the city's best outdoor museum — a sculptor's mansion and garden. Find the value play.",
    spots: [
      {
        id: "paris-06-s1", label: "The Smart Ticket",
        situation: "You mainly want to see The Thinker and the big outdoor bronzes, in the garden, on a sunny July day.",
        prompt: "Which ticket is the secret deal?",
        options: [
          "The €4 garden-only ticket",
          "The €14 full museum ticket only",
          "A €25 combined Rodin-plus-Orsay pass",
          "Nothing is cheaper than €20 here",
        ],
        correctIndex: 0,
        explanation: "The €4 garden-only ticket includes The Thinker, the Burghers of Calais, the Gates of Hell, and Balzac — the bronzes are all outdoors. Most visitors miss it.",
      },
      {
        id: "paris-06-s2", label: "Lunch Plan",
        situation: "It's noon and you'd like to eat while enjoying the garden.",
        prompt: "What's allowed and ideal here?",
        options: [
          "Eating is banned, so leave to find a restaurant",
          "Bring a picnic — eating in the garden is permitted; the shaded benches by The Thinker are best",
          "You must eat only in the Metro",
          "Picnics require a separate €20 permit",
        ],
        correctIndex: 1,
        explanation: "Eating in the Rodin garden is permitted. The shaded benches on the gravel path facing The Thinker are the quietest, best picnic spot — supplies from Rue Cler nearby.",
      },
      {
        id: "paris-06-s3", label: "The Mansion",
        situation: "You decide to add the €14 full ticket and go inside the Hôtel Biron.",
        prompt: "What's the highlight indoors?",
        options: [
          "Nothing — it's empty rooms",
          "Rodin's personal Monet, Van Gogh, and Renoir works, plus Camille Claudel's sculptures",
          "A modern shopping mall",
          "The Mona Lisa",
        ],
        correctIndex: 1,
        explanation: "The mansion holds Rodin's personal collection — paintings by Monet, Van Gogh, and Renoir — and the emotionally charged Camille Claudel rooms.",
      },
      {
        id: "paris-06-s4", label: "The Door Stop",
        situation: "You want the Metro stop that drops you right at the museum gate.",
        prompt: "Which is it?",
        options: [
          "Line 1, Louvre–Rivoli",
          "Line 9, Trocadéro",
          "Line 13, Varenne — exits directly outside the gate",
          "Line 4, Saint-Germain-des-Prés",
        ],
        correctIndex: 2,
        explanation: "Metro line 13 at Varenne exits directly onto Rue de Varenne outside the museum gate. Les Invalides is a 10-minute walk west to combine the two.",
      },
    ],
  },

  "paris-07": {
    intro: "The Musée d'Orsay holds the world's great Impressionist collection inside a former railway station. Time it right.",
    spots: [
      {
        id: "paris-07-s1", label: "Quiet Evening",
        situation: "You want the masterpieces with fewer crowds and a beautiful light through the building's huge clock windows.",
        prompt: "When do you go?",
        options: [
          "Sunday at noon, the busiest slot",
          "Thursday evening, when it's open late until 9:45pm",
          "Monday — even though it's closed",
          "Only at 8am opening, always packed",
        ],
        correctIndex: 1,
        explanation: "The d'Orsay stays open until 9:45pm on Thursdays — about half the crowds, the same masterpieces, and the giant clock windows glowing at sunset.",
      },
      {
        id: "paris-07-s2", label: "Closed Day",
        situation: "You're planning your museum days and pencil in the d'Orsay for a Monday.",
        prompt: "What's the problem?",
        options: [
          "Nothing — it's open daily",
          "The Musée d'Orsay is closed on Mondays — pick another day",
          "It's only open on Mondays",
          "Mondays are free, so go then",
        ],
        correctIndex: 1,
        explanation: "The Musée d'Orsay is closed on Mondays (like many Paris museums). The Louvre, by contrast, closes Tuesdays — plan around each museum's closing day.",
      },
      {
        id: "paris-07-s3", label: "The Building",
        situation: "A friend asks why the d'Orsay looks so unlike a normal museum, with a vast arched hall and a giant clock.",
        prompt: "What's the true story?",
        options: [
          "It was purpose-built as a museum in 2000",
          "It's a converted 1900 railway station saved from demolition",
          "It was once a royal palace",
          "It was a Napoleonic fort",
        ],
        correctIndex: 1,
        explanation: "The d'Orsay is a converted Beaux-Arts railway station (Gare d'Orsay, 1900) that was nearly demolished before being saved and reopened as a museum in 1986.",
      },
      {
        id: "paris-07-s4", label: "Getting There",
        situation: "You're coming from the Left Bank and want the closest station to the d'Orsay entrance.",
        prompt: "What's the best option?",
        options: [
          "RER C to Musée d'Orsay, which exits right at the entrance (or Metro 12 to Solférino)",
          "Metro line 1 to Bastille",
          "RER B to the airport",
          "There's no rail access nearby",
        ],
        correctIndex: 0,
        explanation: "RER C stops at Musée d'Orsay, exiting directly at the museum; Metro line 12 to Solférino is a 3-minute walk. Both are covered by the Navigo pass.",
      },
    ],
  },

  "paris-08": {
    intro: "Saint-Germain-des-Prés: literary cafés, the best bakery in the 6th, and the etiquette that makes a Paris café work for you.",
    spots: [
      {
        id: "paris-08-s1", label: "Greeting First",
        situation: "You walk into a café or small shop. The first thing out of your mouth matters in France.",
        prompt: "What's the polite opening?",
        options: [
          "Launch straight into your order in English",
          "Say \"Bonjour\" (or \"Bonjour madame/monsieur\") before anything else",
          "Whistle for the waiter",
          "Say nothing and point",
        ],
        correctIndex: 1,
        explanation: "Always open with \"Bonjour\" (or \"Bonsoir\" in the evening). Skipping the greeting is considered rude in France; it sets the whole interaction's tone.",
      },
      {
        id: "paris-08-s2", label: "Free Water",
        situation: "You sit on the terrace and want still tap water with your meal rather than paying for a bottle.",
        prompt: "What's the correct phrase to ask?",
        options: [
          "\"Une carafe d'eau, s'il vous plaît\"",
          "\"Water now\"",
          "\"Un café, s'il vous plaît\"",
          "\"L'addition, s'il vous plaît\"",
        ],
        correctIndex: 0,
        explanation: "\"Une carafe d'eau, s'il vous plaît\" asks for a free jug of tap water — your right in any French café. (\"Un café\" orders coffee; \"l'addition\" asks for the bill.)",
      },
      {
        id: "paris-08-s3", label: "The Bill",
        situation: "You've finished and the waiter hasn't brought the check — in France they won't until you ask.",
        prompt: "What do you say?",
        options: [
          "\"Bonjour, s'il vous plaît\"",
          "\"L'addition, s'il vous plaît\"",
          "\"Excusez-moi, où sont les toilettes ?\"",
          "\"Je voudrais un café\"",
        ],
        correctIndex: 1,
        explanation: "\"L'addition, s'il vous plaît\" asks for the bill. In France it's polite to leave you in peace, so you must request the check — it won't be rushed to you.",
      },
      {
        id: "paris-08-s4", label: "Café vs Bakery",
        situation: "You want the real reason to come to Saint-Germain in the morning, not just an €8 espresso at a famous terrace.",
        prompt: "What's the local move?",
        options: [
          "Pay €8 only for the espresso at Les Deux Magots",
          "Get fresh bread and pastries from Poilâne bakery at 8am",
          "Skip breakfast entirely",
          "Eat at a chain fast-food outlet",
        ],
        correctIndex: 1,
        explanation: "The famous cafés (Café de Flore, Les Deux Magots) are worth it for the spectacle, not the coffee. Poilâne on Rue du Cherche-Midi at 8am is the genuine draw.",
      },
    ],
  },

  "paris-09": {
    intro: "The Jardin du Luxembourg is where Paris relaxes in July. Learn how locals use the garden — and avoid the rookie mistakes.",
    spots: [
      {
        id: "paris-09-s1", label: "The Free Afternoon",
        situation: "You want the best low-cost couple of hours in Paris on a warm afternoon.",
        prompt: "What's the plan?",
        options: [
          "Pay for a guided garden tour",
          "Bring a picnic from the Rue Mouffetard market and claim a green metal chair",
          "Pay an entry fee at the gate",
          "There's nowhere to sit, so keep walking",
        ],
        correctIndex: 1,
        explanation: "Entry is free, the iconic green metal chairs are free to move and sit in, and a picnic from nearby Rue Mouffetard makes a perfect low-cost afternoon.",
      },
      {
        id: "paris-09-s2", label: "Keep Off the Grass",
        situation: "You spot a big inviting lawn and think about spreading out on it.",
        prompt: "What should you know?",
        options: [
          "Most lawns are pelouse interdite (no walking) — use the open chairs instead",
          "All grass is always open everywhere",
          "You can light a barbecue on the lawn",
          "The garden bans sitting entirely",
        ],
        correctIndex: 0,
        explanation: "Many Luxembourg lawns are protected (\"pelouse interdite\") and policed by gardiens. Use the famous movable chairs around the central basin instead.",
      },
      {
        id: "paris-09-s3", label: "The Hidden Corner",
        situation: "You want the most romantic, shaded spot in the garden to read for an hour.",
        prompt: "Where do you head?",
        options: [
          "The exposed gravel main path at midday",
          "The Fontaine de Médicis — a shaded, leafy ornamental basin",
          "The car park",
          "The Metro platform",
        ],
        correctIndex: 1,
        explanation: "The Fontaine de Médicis, built for Marie de Médicis, is a shaded, tree-lined basin — the garden's most atmospheric and coolest reading corner in July.",
      },
      {
        id: "paris-09-s4", label: "Nearby Landmark",
        situation: "You have an extra hour and want a major monument a short walk from the garden's east side.",
        prompt: "What's right there?",
        options: [
          "The Eiffel Tower",
          "The Panthéon, resting place of Voltaire, Rousseau, and Marie Curie",
          "Versailles",
          "The Louvre pyramid",
        ],
        correctIndex: 1,
        explanation: "The Panthéon sits just east of the garden in the Latin Quarter, holding the tombs of Voltaire, Rousseau, Victor Hugo, and Marie Curie — a natural add-on.",
      },
    ],
  },

  "paris-10": {
    intro: "Notre-Dame reopened in December 2024 after the 2019 fire. Booking and pairing it with a neighbour are the keys.",
    spots: [
      {
        id: "paris-10-s1", label: "Free but Booked",
        situation: "You want to go inside Notre-Dame in July. Entry is free.",
        prompt: "What's the catch?",
        options: [
          "There's no catch — just walk in anytime",
          "Timed entry is free but mandatory; book at notredamedeparis.fr weeks ahead for July",
          "It costs €30 with no booking",
          "It's still closed from the fire",
        ],
        correctIndex: 1,
        explanation: "Since reopening, Notre-Dame uses free but mandatory timed-entry slots. Book ahead at notredamedeparis.fr — July slots go fast.",
      },
      {
        id: "paris-10-s2", label: "The Neighbour",
        situation: "You're on the Île de la Cité and want to add the dazzling stained-glass chapel a 5-minute walk away.",
        prompt: "What do you plan for?",
        options: [
          "Sainte-Chapelle — but note it needs its own separate ticket",
          "Nothing else is on the island",
          "The Eiffel Tower, right next door",
          "Versailles, a short stroll away",
        ],
        correctIndex: 0,
        explanation: "Sainte-Chapelle, with its 13th-century stained glass, is a 5-minute walk on the same island but requires its own paid ticket — book it separately.",
      },
      {
        id: "paris-10-s3", label: "The Fire",
        situation: "A friend asks what happened to Notre-Dame and how the rebuild went.",
        prompt: "What's accurate?",
        options: [
          "It was bombed in WWII and never repaired",
          "A fire on 15 April 2019 destroyed the spire and roof; it reopened in December 2024 after restoration",
          "It was demolished and rebuilt as a museum",
          "Nothing ever happened to it",
        ],
        correctIndex: 1,
        explanation: "The 15 April 2019 fire collapsed the spire and the oak-framed roof. A five-year restoration followed, and the cathedral reopened to the public in December 2024.",
      },
      {
        id: "paris-10-s4", label: "Getting There",
        situation: "You want the Metro stop that puts you right on the Île de la Cité by the cathedral.",
        prompt: "Which is it?",
        options: [
          "Metro line 4 to Cité, which exits directly onto the island",
          "Metro line 9 to Trocadéro",
          "RER B to the airport",
          "Metro line 13 to Varenne",
        ],
        correctIndex: 0,
        explanation: "Metro line 4 to Cité exits right onto the Île de la Cité by Notre-Dame; RER B/C to Saint-Michel–Notre-Dame is the alternative.",
      },
    ],
  },

  "paris-11": {
    intro: "Île Saint-Louis is the quieter island, famous for its ice cream — and Sainte-Chapelle is just across the water. Time it well.",
    spots: [
      {
        id: "paris-11-s1", label: "The Ice Cream",
        situation: "You want the legendary Berthillon ice cream on Île Saint-Louis without a brutal queue.",
        prompt: "What's the timing tip?",
        options: [
          "Queue at 4pm with everyone else",
          "Go before noon, before the lines build",
          "It's only sold at midnight",
          "Berthillon is in Versailles, not Paris",
        ],
        correctIndex: 1,
        explanation: "Berthillon is an Île Saint-Louis institution; queues build through the afternoon, so go before noon for the shortest wait.",
      },
      {
        id: "paris-11-s2", label: "The Glass Chapel",
        situation: "You want Sainte-Chapelle's stained glass at its best, before tour groups pack the upper chapel.",
        prompt: "When do you arrive?",
        options: [
          "At 9am opening, before the tour groups fill the chapel",
          "At 2pm, peak crowd time",
          "Right at closing",
          "It doesn't matter — it's never busy",
        ],
        correctIndex: 0,
        explanation: "Arrive at 9am opening so you get the 15 windows of 13th-century glass before tour groups fill the small upper chapel.",
      },
      {
        id: "paris-11-s3", label: "Reaching the Island",
        situation: "You're at Notre-Dame and want to walk to Île Saint-Louis, which has no Metro station.",
        prompt: "How do you get there?",
        options: [
          "There's a dedicated Metro line onto the island",
          "Cross the Pont Saint-Louis on foot from the Île de la Cité",
          "Only by boat tour",
          "You can't reach it",
        ],
        correctIndex: 1,
        explanation: "Île Saint-Louis has no Metro station; the Pont Saint-Louis footbridge links it directly to the Île de la Cité by Notre-Dame — a 5-minute walk.",
      },
      {
        id: "paris-11-s4", label: "The History",
        situation: "Someone marvels that Sainte-Chapelle was built remarkably fast for a Gothic monument.",
        prompt: "What's the true detail?",
        options: [
          "It took 300 years to build",
          "It was built in about 7 years to house the relic of the Crown of Thorns",
          "It was never finished",
          "It was built in the 20th century",
        ],
        correctIndex: 1,
        explanation: "Louis IX (Saint Louis) had Sainte-Chapelle built in roughly seven years (consecrated 1248) as a royal reliquary for the Crown of Thorns.",
      },
    ],
  },

  "paris-12": {
    intro: "Le Marais is the historic district that stays alive on Sundays when much of Paris shuts. Use that to your advantage.",
    spots: [
      {
        id: "paris-12-s1", label: "Sunday Plan",
        situation: "It's a July Sunday and most Paris shops, boutiques, and many cafés are closed.",
        prompt: "Where do you go?",
        options: [
          "Le Marais, where shops, galleries, and cafés stay open on Sundays",
          "Stay in — nothing is open anywhere",
          "A business district that's dead on Sundays",
          "A suburban office park",
        ],
        correctIndex: 0,
        explanation: "Le Marais is the rare central neighbourhood lively on Sundays — its shops, galleries, and cafés stay open, making it the go-to day plan.",
      },
      {
        id: "paris-12-s2", label: "Shade in the Heat",
        situation: "It's a hot July afternoon and you want a beautiful, shaded square to rest in the Marais.",
        prompt: "Where do you sit?",
        options: [
          "An exposed parking lot",
          "Place des Vosges, ringed by shaded arcades and a central garden",
          "The middle of a busy boulevard",
          "On the Metro tracks",
        ],
        correctIndex: 1,
        explanation: "Place des Vosges, Paris's oldest planned square, has shaded arcades and a leafy central garden — an ideal cool resting spot in July heat.",
      },
      {
        id: "paris-12-s3", label: "The Museum",
        situation: "You want a major art museum in the Marais and prefer to skip the entrance queue.",
        prompt: "What's the plan?",
        options: [
          "The Musée Picasso — book tickets ahead at museepicassoparis.fr",
          "The Louvre, which isn't in the Marais",
          "Nothing — there are no museums here",
          "Versailles",
        ],
        correctIndex: 0,
        explanation: "The Musée Picasso sits in a 17th-century Marais mansion (the Hôtel Salé); booking online at museepicassoparis.fr skips the queue.",
      },
      {
        id: "paris-12-s4", label: "A Sober Memory",
        situation: "You read that the Marais carries a heavy WWII history tied to July.",
        prompt: "What is the Vel d'Hiv Roundup?",
        options: [
          "A bicycle race",
          "The July 1942 mass arrest of Jewish Parisians by French police under Nazi occupation",
          "A summer music festival",
          "A 19th-century market fair",
        ],
        correctIndex: 1,
        explanation: "The Vél d'Hiv Roundup (16–17 July 1942) was the mass arrest of over 13,000 Jews in Paris by French police — a defining tragedy remembered in the Marais.",
      },
    ],
  },

  "paris-13": {
    intro: "You're in Paris for July 14 — Bastille Day. Know where to be for the fireworks and the locals-only celebration.",
    spots: [
      {
        id: "paris-13-s1", label: "The Fireworks",
        situation: "It's the evening of July 14 and you want the famous Bastille Day fireworks over the Eiffel Tower.",
        prompt: "Where and when do you go?",
        options: [
          "Trocadéro around 11pm for the fireworks over the Eiffel Tower",
          "Versailles at noon",
          "There are no fireworks on July 14",
          "Inside a closed museum",
        ],
        correctIndex: 0,
        explanation: "The Bastille Day fireworks launch from around the Eiffel Tower at about 11pm on July 14; Trocadéro is the classic vantage point.",
      },
      {
        id: "paris-13-s2", label: "The Locals' Secret",
        situation: "You want the free, joyful, low-tourist celebration the night before, on July 13.",
        prompt: "What is it?",
        options: [
          "A paid gala dinner",
          "The Bal des Pompiers — free firefighters' balls held at fire stations on July 13 and 14",
          "A closed private party",
          "Nothing happens on the 13th",
        ],
        correctIndex: 1,
        explanation: "The Bal des Pompiers (firefighters' ball) runs at fire stations across Paris on the nights of July 13 and 14 — free, festive, and known to few tourists.",
      },
      {
        id: "paris-13-s3", label: "The Parade",
        situation: "On the morning of July 14 there's a major national event on the Champs-Élysées.",
        prompt: "What's happening?",
        options: [
          "A shopping sale",
          "The military parade down the Champs-Élysées, France's national day",
          "Nothing — the avenue is empty",
          "A marathon only",
        ],
        correctIndex: 1,
        explanation: "July 14 is France's Fête nationale, marked by the military parade down the Champs-Élysées in the morning — arrive early for a spot along the avenue.",
      },
      {
        id: "paris-13-s4", label: "The History",
        situation: "A friend asks what July 14 actually commemorates.",
        prompt: "What's correct?",
        options: [
          "The coronation of Napoleon",
          "The storming of the Bastille prison on 14 July 1789, a spark of the French Revolution",
          "The end of WWII",
          "The opening of the Eiffel Tower",
        ],
        correctIndex: 1,
        explanation: "Bastille Day marks the storming of the Bastille fortress-prison on 14 July 1789, an early flashpoint of the French Revolution and a symbol of the people's uprising.",
      },
    ],
  },

  "paris-14": {
    intro: "Belleville and Ménilmontant are cheaper, livelier, and hold the best free panorama in Paris. Explore them like a local.",
    spots: [
      {
        id: "paris-14-s1", label: "The Free View",
        situation: "You want the best free panoramic view of the Paris skyline, including the Eiffel Tower in the distance.",
        prompt: "Where do you go?",
        options: [
          "Parc de Belleville, the terraced park with a panoramic overlook",
          "A windowless basement bar",
          "The bottom of a Metro tunnel",
          "A shopping mall food court",
        ],
        correctIndex: 0,
        explanation: "Parc de Belleville sits on a hill with a terraced overlook giving one of the best free skyline panoramas in Paris.",
      },
      {
        id: "paris-14-s2", label: "Best Light",
        situation: "You want that Belleville panorama at its most beautiful and least crowded.",
        prompt: "When do you visit?",
        options: [
          "Midday under harsh flat light",
          "Around 7am for golden light and no crowds, or at sunset",
          "The middle of the night",
          "Only on December mornings",
        ],
        correctIndex: 1,
        explanation: "Early morning (around 7am) gives golden light and an empty terrace; sunset is the other prime window for the Belleville view.",
      },
      {
        id: "paris-14-s3", label: "The Market",
        situation: "You want the lively, affordable Belleville street market for fresh produce.",
        prompt: "What's the timing?",
        options: [
          "It only runs at midnight",
          "Tuesday and Friday mornings on Boulevard de Belleville — arrive by 9am",
          "Sundays only, in winter",
          "There's no market here",
        ],
        correctIndex: 1,
        explanation: "The Belleville street market runs Tuesday and Friday mornings along Boulevard de Belleville; arriving by 9am gets the best produce and the real local bustle.",
      },
      {
        id: "paris-14-s4", label: "Local Legend",
        situation: "A friend mentions a famous Parisian singer tied to Belleville.",
        prompt: "Who is it?",
        options: [
          "Édith Piaf, who legend says was born on a Belleville street",
          "Mozart",
          "Elvis Presley",
          "Beethoven",
        ],
        correctIndex: 0,
        explanation: "Belleville claims Édith Piaf, whom legend says was born on the pavement of Rue de Belleville — a plaque marks the spot, though records place her birth in a hospital.",
      },
    ],
  },

  "paris-15": {
    intro: "Les passages couverts are Paris's 19th-century covered arcades — free, glass-roofed, and perfect for a rainy or scorching day.",
    spots: [
      {
        id: "paris-15-s1", label: "Cost of Entry",
        situation: "You're curious about the covered arcades and wonder if you need tickets.",
        prompt: "What's the deal?",
        options: [
          "All the passages are free to enter and walk through",
          "Each passage charges €15",
          "You need a guided tour to get in",
          "They're closed to the public",
        ],
        correctIndex: 0,
        explanation: "The passages couverts are public walkways — free to enter and stroll, lined with shops, cafés, and bookstores under glass roofs.",
      },
      {
        id: "paris-15-s2", label: "The Loop",
        situation: "You want an efficient walking loop hitting the three best arcades from one Metro stop.",
        prompt: "What's the route?",
        options: [
          "From Metro Grands Boulevards: Passage Jouffroy → Passage Verdeau → Galerie Vivienne",
          "A 5-hour trek across the suburbs",
          "There's only one passage in all of Paris",
          "You must drive between them",
        ],
        correctIndex: 0,
        explanation: "A neat 30-minute loop from Metro Grands Boulevards links Passage Jouffroy, Passage Verdeau, and Galerie Vivienne — three of the finest surviving arcades.",
      },
      {
        id: "paris-15-s3", label: "Right Weather",
        situation: "It's pouring rain — or alternatively a 36°C scorcher — and you want shelter that's still atmospheric.",
        prompt: "What's the ideal use of the passages?",
        options: [
          "Avoid them in bad weather",
          "Walk them precisely on a rainy or very hot day — the glass roofs shelter you",
          "Only visit them in perfect sunshine",
          "They're outdoors and offer no cover",
        ],
        correctIndex: 1,
        explanation: "The glass-roofed arcades were built for exactly this — sheltered strolling. A rainy day or a July heatwave is the perfect time to walk them.",
      },
      {
        id: "paris-15-s4", label: "Closed-Day Backup",
        situation: "It's a Tuesday and several museums you wanted are closed.",
        prompt: "What's a good fallback?",
        options: [
          "Go home — there's nothing to do",
          "Walk the free passages couverts, which stay open and don't depend on museum hours",
          "Wait outside a closed museum all day",
          "Take a train out of the city",
        ],
        correctIndex: 1,
        explanation: "The passages are free and always walkable, making them an ideal fallback on a Tuesday (or any day) when museums are closed.",
      },
    ],
  },

  "paris-16": {
    intro: "Père Lachaise is the world's most-visited cemetery — beautiful and easy to get lost in. Get the map and the right graves.",
    spots: [
      {
        id: "paris-16-s1", label: "Get the Map",
        situation: "The cemetery is a huge maze of divisions and you'll never find the famous graves blind.",
        prompt: "What's the first move?",
        options: [
          "Wander randomly and hope",
          "Pick up the grave map at the Philippe Auguste main entrance gate",
          "Pay €50 for a private guide as the only option",
          "Use no map — graves are signposted everywhere",
        ],
        correctIndex: 1,
        explanation: "Get the free grave map at the main Philippe Auguste entrance (not the side gates). Père Lachaise is a sprawling maze of numbered divisions.",
      },
      {
        id: "paris-16-s2", label: "Cost",
        situation: "You wonder whether visiting Père Lachaise costs anything.",
        prompt: "What's true?",
        options: [
          "Entry is free",
          "It costs €25",
          "Only paying tour groups may enter",
          "It's permanently closed",
        ],
        correctIndex: 0,
        explanation: "Père Lachaise is free to enter and open daily — you only pay if you choose a guided tour.",
      },
      {
        id: "paris-16-s3", label: "Quieter Graves",
        situation: "Jim Morrison's grave (Division 6) is mobbed and you'd like more moving, quieter spots.",
        prompt: "Where do you go?",
        options: [
          "Only Morrison's grave is worth seeing",
          "Édith Piaf (Division 97) and Chopin (Division 11) — far quieter and more moving",
          "There are no other notable graves",
          "Leave the cemetery entirely",
        ],
        correctIndex: 1,
        explanation: "Morrison's grave stays crowded; Édith Piaf (Div. 97) and Frédéric Chopin (Div. 11), among others, are quieter and often more moving.",
      },
      {
        id: "paris-16-s4", label: "The History",
        situation: "You reach a wall at the cemetery with a heavy history from 1871.",
        prompt: "What is the Communards' Wall?",
        options: [
          "A modern art installation",
          "The Mur des Fédérés, where the last fighters of the Paris Commune were executed in 1871",
          "A garden feature with no history",
          "A WWII bunker",
        ],
        correctIndex: 1,
        explanation: "The Mur des Fédérés (Communards' Wall) marks where the last defenders of the 1871 Paris Commune were shot — a site of pilgrimage in the cemetery's east.",
      },
    ],
  },

  "paris-17": {
    intro: "Marché d'Aligre is where Paris chefs shop on Saturday mornings. Learn the timing, the ritual, and the market etiquette.",
    spots: [
      {
        id: "paris-17-s1", label: "The Window",
        situation: "You want Marché d'Aligre at its liveliest, with the full produce market and covered hall in full swing.",
        prompt: "When do you go?",
        options: [
          "Saturday around 8–11am, the prime window",
          "Sunday at midnight",
          "Monday afternoon when it's closed",
          "Any weekday at 6pm",
        ],
        correctIndex: 0,
        explanation: "Saturday 8–11am is the market's peak — the open-air stalls, the covered Beauvau hall, and the buzz are all at their best.",
      },
      {
        id: "paris-17-s2", label: "Touching the Produce",
        situation: "At a fruit and veg stall you reach to pick your own tomatoes.",
        prompt: "What's the etiquette?",
        options: [
          "Grab and squeeze everything yourself",
          "Don't handle the produce — tell the vendor what you want and let them serve you",
          "Sample anything without asking",
          "Rearrange the whole display",
        ],
        correctIndex: 1,
        explanation: "At French market stalls you don't pick or squeeze the produce yourself — greet the vendor with \"Bonjour,\" say what you'd like, and let them choose and bag it.",
      },
      {
        id: "paris-17-s3", label: "The Ritual",
        situation: "It's 10am Saturday and locals are drifting next door for a famous market tradition.",
        prompt: "What is it?",
        options: [
          "A glass of wine and oysters at the standing bar of Le Baron Rouge",
          "A formal black-tie dinner",
          "A closed members-only club",
          "Nothing happens near the market",
        ],
        correctIndex: 0,
        explanation: "Le Baron Rouge wine bar beside the market opens around 10am; a glass of wine and oysters at its standing bar on a Saturday is a cherished Paris ritual.",
      },
      {
        id: "paris-17-s4", label: "Getting There",
        situation: "You want the closest Metro to Place d'Aligre.",
        prompt: "Which works?",
        options: [
          "Metro line 8 to Ledru-Rollin, then a short walk south",
          "RER B to the airport",
          "Metro line 9 to Trocadéro",
          "There's no Metro within miles",
        ],
        correctIndex: 0,
        explanation: "Metro line 8 to Ledru-Rollin leaves a short walk to Place d'Aligre; Faidherbe-Chaligny (also line 8) is the alternative.",
      },
    ],
  },

  "paris-18": {
    intro: "Canal Saint-Martin is where young Paris picnics on summer evenings. Time the walk and pick the right stretch.",
    spots: [
      {
        id: "paris-18-s1", label: "Best Time",
        situation: "You want the canal at its most alive, when locals gather after work along the water.",
        prompt: "When do you go?",
        options: [
          "5–7pm, when Parisians arrive after work to picnic on the banks",
          "3am, when it's deserted",
          "Only at sunrise",
          "Midweek lunchtime, the deadest hour",
        ],
        correctIndex: 0,
        explanation: "The canal comes alive from about 5–7pm in summer as locals settle on the banks with wine and food after work — the prime time to soak up the atmosphere.",
      },
      {
        id: "paris-18-s2", label: "The Walk",
        situation: "You want a flat, scenic walk along the canal towpath toward a major square.",
        prompt: "What's the route?",
        options: [
          "An uphill mountain trail",
          "The towpath from Rue de la Grange-aux-Belles south to Place de la République, about 30 minutes flat",
          "There's no walkable path",
          "Only a boat can pass",
        ],
        correctIndex: 1,
        explanation: "The towpath from Rue de la Grange-aux-Belles south to Place de la République is a flat 30-minute canal-side walk past the iron footbridges.",
      },
      {
        id: "paris-18-s3", label: "The Terrace",
        situation: "You want a classic canal-side café terrace to sit at.",
        prompt: "Where do you head?",
        options: [
          "Chez Prune, with one of the best terraces on the canal",
          "A windowless basement",
          "A motorway service station",
          "Nowhere has a terrace here",
        ],
        correctIndex: 0,
        explanation: "Chez Prune is the canal's emblematic café, with a prized terrace right on the water — a long-standing meeting spot in the 10th.",
      },
      {
        id: "paris-18-s4", label: "Why It Exists",
        situation: "A friend asks why a canal runs through this part of Paris at all.",
        prompt: "What's the historical reason?",
        options: [
          "It was a natural river",
          "Napoleon ordered it built to bring clean drinking water to Paris and fight disease",
          "It was dug for tourism in the 1990s",
          "It was a failed subway tunnel",
        ],
        correctIndex: 1,
        explanation: "Napoleon ordered the Canal Saint-Martin built in the early 1800s to supply Paris with clean water and ease the city's deadly water shortages.",
      },
    ],
  },

  "paris-19": {
    intro: "Versailles is a day-trip from Paris — vast, dazzling, and mobbed in July. Plan the train, the booking, and the crowds.",
    spots: [
      {
        id: "paris-19-s1", label: "The Train",
        situation: "You want the simplest rail route from central Paris to the palace, covered by your Navigo weekly pass.",
        prompt: "What do you take?",
        options: [
          "RER C toward Versailles Château–Rive Gauche, about 40 minutes",
          "RER B to the airport",
          "A 3-hour intercity train",
          "There's no train to Versailles",
        ],
        correctIndex: 0,
        explanation: "RER C runs from central stations (Musée d'Orsay, Saint-Michel, Invalides) to Versailles Château–Rive Gauche in about 40 minutes, covered by the Navigo pass.",
      },
      {
        id: "paris-19-s2", label: "Check the Board",
        situation: "On the RER C platform, several trains are heading toward Versailles but not all to the right station.",
        prompt: "What do you do?",
        options: [
          "Board the first train labelled \"Versailles\" without checking",
          "Confirm the train goes to Versailles Château–Rive Gauche, the closest station to the palace",
          "Get on a train going the opposite way",
          "Trains to Versailles don't exist",
        ],
        correctIndex: 1,
        explanation: "RER C has branches; only trains to Versailles Château–Rive Gauche stop closest to the palace. Check the destination board — other Versailles stations are further away.",
      },
      {
        id: "paris-19-s3", label: "Book Ahead",
        situation: "It's July and the palace draws enormous crowds.",
        prompt: "How do you avoid the worst lines?",
        options: [
          "Show up at midday with no ticket",
          "Book a timed-entry slot weeks ahead at en.chateauversailles.fr and arrive early",
          "Assume there's never a queue",
          "Only buy tickets from street touts",
        ],
        correctIndex: 1,
        explanation: "Book a timed-entry slot ahead at en.chateauversailles.fr and arrive early; midday in July means the longest queues at the palace itself.",
      },
      {
        id: "paris-19-s4", label: "The Gardens",
        situation: "The palace interior is packed, but you want the famous gardens and a calmer experience.",
        prompt: "What's smart?",
        options: [
          "Skip the gardens entirely",
          "See the gardens and the quieter Trianon estate, which spread the crowds out",
          "Only stand in the entrance hall",
          "The gardens are closed in summer",
        ],
        correctIndex: 1,
        explanation: "The vast gardens and the Trianon estate (Marie-Antoinette's hamlet) absorb the crowds far better than the palace interior — a calmer, beautiful use of a July day.",
      },
    ],
  },

  "paris-20": {
    intro: "Sacré-Cœur crowns Montmartre with the best free sunset in Paris. Climb it smartly and dodge the classic scams.",
    spots: [
      {
        id: "paris-20-s1", label: "The Climb",
        situation: "You're at the foot of the Montmartre hill and the funicular has a long queue.",
        prompt: "What's the move?",
        options: [
          "Climb the east-side stairs (Rue du Chevalier de la Barre) to skip the funicular queue",
          "Wait an hour for the funicular no matter what",
          "Give up and leave",
          "Take a taxi up the pedestrian steps",
        ],
        correctIndex: 0,
        explanation: "Climbing the east-side stairs via Rue du Chevalier de la Barre avoids the funicular queue and brings you up a quieter, prettier approach to the basilica.",
      },
      {
        id: "paris-20-s2", label: "The Sunset",
        situation: "You want the finest free view and sunset in Paris from the basilica steps.",
        prompt: "When do you stay?",
        options: [
          "Leave before sunset",
          "Stay on the parvis (forecourt) until around 9:30pm in July for the sunset over the city",
          "Only visit at 6am",
          "The view is blocked, so don't bother",
        ],
        correctIndex: 1,
        explanation: "The Sacré-Cœur parvis gives a sweeping free view over Paris; in July, sunset around 9:30pm from the steps is one of the city's best free experiences.",
      },
      {
        id: "paris-20-s3", label: "The Scam",
        situation: "On the steps below the basilica, a friendly man tries to tie a woven string around your wrist \"as a gift.\"",
        prompt: "What do you do?",
        options: [
          "Let him tie it — it's truly free",
          "Keep your hands in your pockets, say \"Non merci,\" and walk on — it's the friendship-bracelet scam",
          "Hand over your wallet to be polite",
          "Follow him somewhere quieter",
        ],
        correctIndex: 1,
        explanation: "The Montmartre \"friendship bracelet\" (bracelet) men tie a string on, then aggressively demand money. Keep your hands down, say \"Non merci,\" and keep walking.",
      },
      {
        id: "paris-20-s4", label: "Mind Your Bag",
        situation: "The basilica steps and the busy Place du Tertre nearby are crowded with tourists — and pickpockets.",
        prompt: "What's the safe habit?",
        options: [
          "Keep your bag zipped and in front of you, phone secured, in the crowds",
          "Hang your open bag loosely behind you",
          "Wave your phone and wallet around",
          "Leave your bag on a bench while you photograph",
        ],
        correctIndex: 0,
        explanation: "Montmartre's crowded steps and Place du Tertre are pickpocket hotspots. Keep bags zipped and in front, and don't flash phones or wallets in the crush.",
      },
    ],
  },
};
