import type { ScenarioConfig } from "./types";

// "Play the Hand" Decision-Trainer scenarios for the Texas Hold'em epoch.
// Each spot is a deterministic, skill-based decision — the correct line is the
// +EV play taught in that stage, never a luck-of-the-draw outcome. correctIndex
// and explanation are stripped server-side before reaching the client.
export const poker1Scenarios: Record<string, ScenarioConfig> = {
  "poker-1-01": {
    intro: "You've just sat down at a 6-handed No-Limit Hold'em table. Let's make sure the basics are second nature before the chips fly.",
    spots: [
      {
        id: "p1-01-s1", label: "The Deal",
        situation: "A new hand begins. You're two seats to the left of the button.",
        hand: ["A♠", "K♦"],
        prompt: "How many private 'hole cards' have you been dealt?",
        options: ["Two", "Five", "Seven", "Three"],
        correctIndex: 0,
        explanation: "Each player gets exactly two private hole cards in Texas Hold'em.",
      },
      {
        id: "p1-01-s2", label: "The Board",
        situation: "The dealer spreads the five community cards over the course of the hand.",
        board: ["Q♣", "J♦", "9♠", "4♥", "2♣"],
        hand: ["A♠", "K♦"],
        prompt: "How do you build your final five-card hand?",
        options: [
          "Any combination of your 2 cards and the 5 on the board",
          "Only your two hole cards",
          "Only the five community cards",
          "Exactly two hole cards plus three board cards, always",
        ],
        correctIndex: 0,
        explanation: "In Hold'em you make the best five-card hand from any mix of your two cards and the five community cards.",
      },
      {
        id: "p1-01-s3", label: "Winning",
        situation: "You bet the river and your only opponent folds.",
        prompt: "Do you have to show your cards to win the pot?",
        options: [
          "No — if everyone folds, you win without showing",
          "Yes — you must always reveal your hand",
          "Only if you were bluffing",
          "Only on the river",
        ],
        correctIndex: 0,
        explanation: "There are two ways to win: the best hand at showdown, or making everyone fold (no showdown needed).",
      },
      {
        id: "p1-01-s4", label: "No-Limit",
        situation: "It's No-Limit Hold'em and you have a strong hand and a big stack.",
        hand: ["A♠", "A♣"],
        prompt: "How much are you allowed to bet?",
        options: [
          "Any amount up to all your chips (all-in)",
          "Only the size of the big blind",
          "Never more than the current pot",
          "A fixed amount set by the dealer",
        ],
        correctIndex: 0,
        explanation: "No-Limit means you can move all-in at any time — bet sizing becomes a weapon.",
      },
    ],
  },

  "poker-1-02": {
    intro: "Know what beats what, instantly. Each spot shows a finished board — pick the truth about hand strength.",
    spots: [
      {
        id: "p1-02-s1", label: "Flush vs Straight",
        situation: "Two players turn over their hands at showdown.",
        prompt: "Which hand wins: a flush or a straight?",
        options: ["The flush", "The straight", "They tie and split", "Whichever has higher suits"],
        correctIndex: 0,
        explanation: "A flush is rarer than a straight, so it wins — the classic beginner trap.",
      },
      {
        id: "p1-02-s2", label: "Read Your Hand",
        situation: "The board is paired and you hold two more of the same rank.",
        board: ["K♠", "K♦", "7♣", "7♥", "2♦"],
        hand: ["K♣", "Q♠"],
        prompt: "What is your best five-card hand?",
        options: [
          "Four of a kind (quad Kings)",
          "A full house",
          "Two pair",
          "Three of a kind",
        ],
        correctIndex: 0,
        explanation: "Your two Kings plus the two on the board make four Kings — quads.",
      },
      {
        id: "p1-02-s3", label: "Full House?",
        situation: "You hold a pair and the board gives you trips of another rank.",
        board: ["8♠", "8♦", "8♣", "3♥", "K♦"],
        hand: ["K♠", "K♣"],
        prompt: "What do you have?",
        options: [
          "A full house (eights full of kings)",
          "Four of a kind",
          "Just three of a kind",
          "Two pair",
        ],
        correctIndex: 0,
        explanation: "Three 8s on the board plus your pair of Kings = a full house, 8s full of Ks.",
      },
      {
        id: "p1-02-s4", label: "Kicker Trouble",
        situation: "You and an opponent both pair the Ace on the board. You hold A-9, they hold A-K.",
        board: ["A♥", "8♣", "5♦", "3♠", "Q♦"],
        hand: ["A♠", "9♣"],
        prompt: "Who wins?",
        options: [
          "Your opponent — same pair, but their King kicker beats your Nine",
          "You — your Nine plays",
          "It's a tie",
          "You — Aces always split",
        ],
        correctIndex: 0,
        explanation: "Equal pairs are broken by the kicker; A-K outkicks A-9. This is why kickers matter.",
      },
    ],
  },

  "poker-1-03": {
    intro: "A hand moves through four betting rounds. Navigate the streets and your options on each.",
    spots: [
      {
        id: "p1-03-s1", label: "Name the Street",
        situation: "The dealer has just spread the first three community cards.",
        board: ["J♠", "7♦", "2♣"],
        prompt: "Which street are you on?",
        options: ["The flop", "The turn", "The river", "Preflop"],
        correctIndex: 0,
        explanation: "The flop is the first three community cards. The turn (4th) and river (5th) come next.",
      },
      {
        id: "p1-03-s2", label: "Your Options",
        situation: "It's checked to you on the flop — no one has bet yet.",
        board: ["J♠", "7♦", "2♣"],
        hand: ["A♣", "J♦"],
        prompt: "Which action is available to you right now?",
        options: ["Check (pass without betting)", "Call a bet", "Raise a bet", "Fold to a bet"],
        correctIndex: 0,
        explanation: "Checking is only legal when there's no bet to you yet — which is the case here.",
      },
      {
        id: "p1-03-s3", label: "Closing the Action",
        situation: "An opponent bets, a second player calls, and the action is back to you.",
        prompt: "When does this betting round end?",
        options: [
          "When everyone still in has matched the largest bet or folded",
          "After exactly three actions",
          "When the dealer decides",
          "Immediately after the first bet",
        ],
        correctIndex: 0,
        explanation: "A round closes only once all remaining players have put in equal chips or folded.",
      },
      {
        id: "p1-03-s4", label: "No Showdown",
        situation: "You make a big river bet and both opponents fold.",
        prompt: "What happens?",
        options: [
          "You win the pot immediately — no showdown",
          "You must reveal your cards",
          "The hand is replayed",
          "The pot is split three ways",
        ],
        correctIndex: 0,
        explanation: "If everyone folds, the last player standing takes the pot without showing.",
      },
    ],
  },

  "poker-1-04": {
    intro: "Most of poker is decided before the flop. Use your cards AND your seat to choose whether to enter.",
    spots: [
      {
        id: "p1-04-s1", label: "UTG",
        situation: "You're first to act (under the gun) at a full table. It's folded to you.",
        hand: ["7♣", "2♦"],
        prompt: "What's the correct play?",
        options: ["Fold", "Raise", "Call the big blind", "Go all-in"],
        correctIndex: 0,
        explanation: "7-2 offsuit is the worst hand in poker — an easy fold, especially in early position.",
      },
      {
        id: "p1-04-s2", label: "Premium Hand",
        situation: "It's folded to you in middle position with a monster.",
        hand: ["A♠", "A♥"],
        prompt: "What's the standard play?",
        options: ["Raise", "Fold", "Just call to disguise it", "Check"],
        correctIndex: 0,
        explanation: "Pocket Aces is the best starting hand — raise to build the pot and play it aggressively.",
      },
      {
        id: "p1-04-s3", label: "Position Power",
        situation: "You hold a marginal-but-playable hand. You want the seat with the most information.",
        hand: ["J♠", "T♠"],
        prompt: "Which position is best to play this hand from?",
        options: [
          "The button (you act last on every street)",
          "Under the gun (you act first)",
          "The small blind",
          "Position doesn't matter",
        ],
        correctIndex: 0,
        explanation: "The button acts last postflop — the biggest information edge in poker.",
      },
      {
        id: "p1-04-s4", label: "Late Steal",
        situation: "It's folded to you on the button with a decent hand and only the blinds left to act.",
        hand: ["K♦", "T♦"],
        prompt: "What's the standard play?",
        options: [
          "Raise — attack the blinds from late position",
          "Fold — it's not premium",
          "Limp (just call)",
          "Check",
        ],
        correctIndex: 0,
        explanation: "On the button with only the blinds behind, a suited K-T is a clear raise to steal/play in position.",
      },
    ],
  },

  "poker-1-05": {
    intro: "Drawing hands are about math, not hope. Count your outs and compare to the price.",
    spots: [
      {
        id: "p1-05-s1", label: "Count the Outs",
        situation: "You have four cards to a flush after the flop.",
        board: ["K♠", "8♠", "2♦"],
        hand: ["A♠", "J♠"],
        prompt: "How many 'outs' (cards that complete your flush) do you have?",
        options: ["9", "4", "13", "2"],
        correctIndex: 0,
        explanation: "13 spades minus the 4 you can see = 9 spades left to complete the flush.",
      },
      {
        id: "p1-05-s2", label: "Rule of 4",
        situation: "You have your 9-out flush draw on the flop, with two cards to come.",
        board: ["K♠", "8♠", "2♦"],
        hand: ["A♠", "J♠"],
        prompt: "Roughly what % are you to hit by the river (Rule of 4)?",
        options: ["About 36%", "About 9%", "About 70%", "About 50%"],
        correctIndex: 0,
        explanation: "9 outs × 4 ≈ 36% to complete by the river with two cards to come.",
      },
      {
        id: "p1-05-s3", label: "Price the Call",
        situation: "On the flop the pot is $100 and your opponent bets, making it $20 for you to call.",
        board: ["K♠", "8♠", "2♦"],
        hand: ["A♠", "J♠"],
        pot: "$120", toCall: "$20",
        prompt: "Your 36% flush draw vs roughly 17% needed to call — what's the play?",
        options: [
          "Call — your equity (36%) beats the price (17%)",
          "Fold — draws never pay",
          "Fold — you have nothing yet",
          "It doesn't matter",
        ],
        correctIndex: 0,
        explanation: "Getting ~5-to-1, you need ~17% to break even; at 36% the call is clearly +EV.",
      },
      {
        id: "p1-05-s4", label: "Don't Chase",
        situation: "You have a weak gutshot (4 outs, ~16% by the river) and face a huge bet that gives you only ~3-to-1.",
        board: ["Q♥", "9♣", "4♠"],
        hand: ["J♦", "T♦"],
        pot: "$200", toCall: "$70",
        prompt: "The price demands ~25% and you have ~16%. What's correct?",
        options: [
          "Fold — your equity doesn't meet the price",
          "Call — always chase a straight draw",
          "Raise as a bluff every time",
          "Call because it's suited",
        ],
        correctIndex: 0,
        explanation: "When your hit % is below the pot-odds %, folding is correct — chasing bad draws is a major leak.",
      },
    ],
  },

  "poker-1-06": {
    intro: "The shared board tells a story. Read what it makes possible — and where your hand really stands.",
    spots: [
      {
        id: "p1-06-s1", label: "Find the Nuts",
        situation: "Three spades are on the board.",
        board: ["A♠", "K♠", "5♠", "9♦", "2♣"],
        prompt: "What is 'the nuts' (the best possible hand) here?",
        options: [
          "The Q♠ J♠ flush (highest possible flush)",
          "A pair of Aces",
          "Any two spades",
          "Two pair",
        ],
        correctIndex: 0,
        explanation: "With three spades out, the nut hand is the highest flush — here, holding Q♠ J♠ over the A-K-5 of spades.",
      },
      {
        id: "p1-06-s2", label: "Made or Draw",
        situation: "You flop four to a flush but have no pair.",
        board: ["T♠", "6♠", "2♥"],
        hand: ["A♠", "9♠"],
        prompt: "Right now, do you have a made hand or a draw?",
        options: [
          "A draw — you need one more spade to complete it",
          "A made flush already",
          "A made straight",
          "A full house",
        ],
        correctIndex: 0,
        explanation: "Four to a flush is a draw, not a made hand — you still need a fifth spade.",
      },
      {
        id: "p1-06-s3", label: "Wet Board",
        situation: "You have an overpair on a very coordinated flop full of straight and flush possibilities.",
        board: ["9♠", "8♠", "7♦"],
        hand: ["A♥", "A♣"],
        prompt: "How should you treat your aces here?",
        options: [
          "Strong but vulnerable — bet to charge the many draws",
          "The nuts — slow-play it",
          "Worthless — check-fold",
          "A drawing hand",
        ],
        correctIndex: 0,
        explanation: "On a wet board, a big made hand should bet to make draws pay; checking lets them hit cheaply.",
      },
      {
        id: "p1-06-s4", label: "Paired Board Caution",
        situation: "You hold a flush, but the board just paired on the river.",
        board: ["A♠", "J♠", "6♠", "6♦", "K♣"],
        hand: ["Q♠", "9♠"],
        prompt: "Why should you be a little cautious despite your flush?",
        options: [
          "A paired board means a full house is now possible and beats your flush",
          "Flushes can't win on paired boards",
          "Your flush is the nuts no matter what",
          "Suits don't count when the board pairs",
        ],
        correctIndex: 0,
        explanation: "Once the board pairs, someone could have a full house — which beats a flush. Respect what the board allows.",
      },
    ],
  },

  "poker-1-07": {
    intro: "Bluffing is logical, not reckless. Tell a believable story and pick the right targets.",
    spots: [
      {
        id: "p1-07-s1", label: "Semi-Bluff",
        situation: "On the flop you have a big draw (no made hand yet) and you're first to act.",
        board: ["K♠", "Q♠", "4♦"],
        hand: ["J♠", "T♠"],
        prompt: "What's the strongest reason to bet here?",
        options: [
          "It's a semi-bluff — you can win now by a fold OR hit a monster later",
          "You already have the nuts",
          "You should never bet a draw",
          "To see your opponent's cards",
        ],
        correctIndex: 0,
        explanation: "Betting a strong draw is a semi-bluff: two ways to win — folds now, or completing your draw.",
      },
      {
        id: "p1-07-s2", label: "Wrong Target",
        situation: "A loose opponent who calls with almost anything ('a calling station') is in the pot, and you have a weak hand.",
        prompt: "Should you try to bluff them?",
        options: [
          "No — bluffing a calling station just loses chips; value bet them instead",
          "Yes — bluff them every street",
          "Yes — they always fold",
          "Only bluff with the worst hand",
        ],
        correctIndex: 0,
        explanation: "Calling stations don't fold, so save bluffs for players who can; value-bet the stations.",
      },
      {
        id: "p1-07-s3", label: "Bet Sizing",
        situation: "You want your bluff to look exactly like your value bets.",
        prompt: "How should you size a bluff?",
        options: [
          "Like your value bets, so opponents can't tell them apart",
          "Always tiny, to risk less",
          "Always all-in, to look scary",
          "A random amount each time",
        ],
        correctIndex: 0,
        explanation: "Matching bluff and value sizing makes you unpredictable; odd sizing gives the bluff away.",
      },
      {
        id: "p1-07-s4", label: "Table Image",
        situation: "You've been playing very tight all session, then make a big bet.",
        prompt: "How does your tight image help?",
        options: [
          "Opponents are more likely to believe your bet and fold",
          "It makes opponents call more",
          "Image has no effect on bluffs",
          "It forces a showdown",
        ],
        correctIndex: 0,
        explanation: "A respected tight image earns folds — table image is a real, usable weapon.",
      },
    ],
  },

  "poker-1-08": {
    intro: "Cash games and tournaments are the same cards played two different ways. Adjust to the format.",
    spots: [
      {
        id: "p1-08-s1", label: "Short Stack",
        situation: "Late in a tournament, the blinds are huge and you have just 9 big blinds left.",
        hand: ["A♣", "T♦"],
        prompt: "With about 9 BB, how should you generally play preflop?",
        options: [
          "Push or fold — move all-in or fold, no flat-calling",
          "Limp and see a cheap flop",
          "Call and play small pots",
          "Always fold and wait",
        ],
        correctIndex: 0,
        explanation: "With ~10 BB or fewer there's no room to play postflop — the optimal style is push/fold.",
      },
      {
        id: "p1-08-s2", label: "Rising Blinds",
        situation: "You're sitting on a big chip count but the blinds keep climbing each level.",
        prompt: "Why can't you just sit and fold forever in a tournament?",
        options: [
          "Rising blinds shrink every stack in big blinds, so you must keep accumulating",
          "Blinds never change in tournaments",
          "Folding is illegal",
          "The chips are worth cash",
        ],
        correctIndex: 0,
        explanation: "Tournament blinds rise on a timer; even a big stack becomes short in BB terms if you stall.",
      },
      {
        id: "p1-08-s3", label: "ICM Pressure",
        situation: "You're on the money bubble with a medium stack and face an all-in with a hand you'd happily call for cash.",
        hand: ["A♠", "J♣"],
        prompt: "Why might you fold here that you wouldn't in a cash game?",
        options: [
          "ICM — survival has value; busting near a pay jump forfeits all prize equity",
          "The cards are worth less suits",
          "Folding is always right",
          "Cash and tournaments are identical",
        ],
        correctIndex: 0,
        explanation: "ICM makes the chips you'd lose worth more than the chips you'd win near a pay jump, so you tighten up.",
      },
      {
        id: "p1-08-s4", label: "Cash Game Chip",
        situation: "You're now in a cash game with deep stacks and fixed blinds.",
        prompt: "How is a chip valued differently than in a tournament?",
        options: [
          "A chip is always real money — no ICM, so make the most +EV play every hand",
          "Chips have no value at all",
          "Chips are worth more as you win",
          "You can never rebuy",
        ],
        correctIndex: 0,
        explanation: "In cash games a chip equals a fixed dollar amount, so survival has no special value — just play +EV.",
      },
    ],
  },

  "poker-1-09": {
    intro: "Skill is only half of it. These spots are off-the-felt discipline — the habits that keep winners winning.",
    spots: [
      {
        id: "p1-09-s1", label: "Variance",
        situation: "You've played well all week but you're down money.",
        prompt: "What is this short-term losing stretch called?",
        options: [
          "Variance — natural short-term swings around your long-term edge",
          "Proof you're a losing player",
          "The house rake",
          "A rule violation",
        ],
        correctIndex: 0,
        explanation: "Even winning players have downswings; variance is the noise, your edge is the signal over time.",
      },
      {
        id: "p1-09-s2", label: "Bankroll Rule",
        situation: "You have $1,000 set aside for poker and want to sit in a cash game.",
        prompt: "Which choice respects bankroll management?",
        options: [
          "Play a stake where $1,000 is many buy-ins (e.g. 20–40)",
          "Sit with your entire $1,000 in one game",
          "Play the biggest game you can afford one buy-in for",
          "Borrow more to play higher",
        ],
        correctIndex: 0,
        explanation: "Keeping many buy-ins means a normal downswing can't bust you, so your edge can play out.",
      },
      {
        id: "p1-09-s3", label: "Tilt",
        situation: "You just took a brutal bad beat and feel the urge to win it back fast.",
        prompt: "What's the disciplined response?",
        options: [
          "Take a break and stick to good decisions — don't chase losses",
          "Immediately play double stakes to recover",
          "Bluff every hand out of anger",
          "Play more hands, faster",
        ],
        correctIndex: 0,
        explanation: "Chasing losses on tilt turns a small loss into a disaster — breaks and discipline protect your edge.",
      },
      {
        id: "p1-09-s4", label: "Judge the Decision",
        situation: "You made a mathematically correct call, but the river beat you.",
        prompt: "How should you evaluate that play?",
        options: [
          "It was a good decision — judge by the decision, not the one result",
          "It was a bad call because you lost",
          "You should never call again",
          "Results are all that matter",
        ],
        correctIndex: 0,
        explanation: "A correct, +EV decision can still lose a single hand; long-term, good decisions win.",
      },
    ],
  },

  "poker-1-10": {
    intro: "Bring it all together — ranges, board reading, odds and discipline in one sequence.",
    spots: [
      {
        id: "p1-10-s1", label: "Think in Ranges",
        situation: "Instead of guessing your opponent's exact two cards, you consider everything they'd play this way.",
        prompt: "What is this called?",
        options: [
          "Thinking in ranges",
          "Counting outs",
          "Bluff-catching",
          "Going on tilt",
        ],
        correctIndex: 0,
        explanation: "Range thinking — weighing the whole set of hands an opponent could hold — is poker's biggest mental upgrade.",
      },
      {
        id: "p1-10-s2", label: "Preflop",
        situation: "It's folded to you on the button with a strong, in-position hand.",
        hand: ["A♣", "Q♣"],
        prompt: "What's the standard line?",
        options: [
          "Raise — strong hand, best position",
          "Fold — wait for aces",
          "Limp to disguise it",
          "Check",
        ],
        correctIndex: 0,
        explanation: "A-Q suited on the button is a clear raise: a strong hand played aggressively in position.",
      },
      {
        id: "p1-10-s3", label: "Exploit the Leak",
        situation: "An opponent has folded to almost every river bet all night — they over-fold.",
        prompt: "How do you exploit this specific leak?",
        options: [
          "Bluff them more often on the river",
          "Bluff them less",
          "Only ever value bet",
          "Stop playing pots with them",
        ],
        correctIndex: 0,
        explanation: "Against an over-folder, increasing your bluff frequency directly profits from their mistake (exploitative play).",
      },
      {
        id: "p1-10-s4", label: "GTO Baseline",
        situation: "You're up against a strong, observant player with no obvious leaks.",
        prompt: "What's the soundest default approach?",
        options: [
          "Play a balanced (GTO) range so you can't be exploited",
          "Bluff every hand",
          "Never bluff at all",
          "Play completely randomly",
        ],
        correctIndex: 0,
        explanation: "Against tough players, a balanced GTO baseline makes you unexploitable; save exploits for players who show leaks.",
      },
    ],
  },
};
