import type { ScenarioConfig } from "./types";

// "Beyond Hold'em" Decision-Trainer scenarios for the Poker Variants epoch.
// Each spot is a deterministic, rules-based decision — the correct line follows
// the RULES of the specific variant being taught, never a luck-of-the-draw
// outcome. correctIndex and explanation are stripped server-side before reaching
// the client. ACCURACY MATTERS: the rules differ per game.
export const poker3Scenarios: Record<string, ScenarioConfig> = {
  "poker-3-01": {
    intro: "Hold'em is one branch of a big family tree. Learn to classify any poker game by how cards are dealt and how the pot is awarded.",
    spots: [
      {
        id: "p3-01-s1", label: "Draw vs Stud vs Community",
        situation: "A game deals everyone five cards face down, lets them discard and replace cards, then goes to showdown. No shared cards, no exposed cards.",
        prompt: "Which family of poker is this?",
        options: ["Draw poker", "Stud poker", "Community-card poker", "Lowball-only poker"],
        correctIndex: 0,
        explanation: "Drawing and replacing cards from a private hand with no exposed or shared cards is the defining trait of draw poker (e.g. Five-Card Draw).",
      },
      {
        id: "p3-01-s2", label: "Spot the Stud Game",
        situation: "A game deals each player a mix of face-down and face-up cards across several betting rounds, with no shared community cards.",
        prompt: "What family is this?",
        options: ["Community-card poker", "Draw poker", "Stud poker", "Badugi"],
        correctIndex: 2,
        explanation: "Stud games (like Seven-Card Stud) deal a mix of up-cards and down-cards to each player with no community cards.",
      },
      {
        id: "p3-01-s3", label: "High vs Lowball",
        situation: "In this game, the player with the LOWEST-ranked hand at showdown wins the entire pot.",
        prompt: "What kind of game is this?",
        options: ["A high game", "A lowball (low) game", "A hi-lo split game", "A community game"],
        correctIndex: 1,
        explanation: "When the lowest hand wins the whole pot, it is a lowball game (e.g. Razz, 2-7 lowball).",
      },
      {
        id: "p3-01-s4", label: "Hi-Lo Split",
        situation: "At showdown the pot is divided: half goes to the best high hand and half to the best qualifying low hand.",
        prompt: "How is this game classified?",
        options: ["High-only", "Low-only", "Hi-lo split (the pot is split two ways)", "Winner-take-all draw"],
        correctIndex: 2,
        explanation: "Splitting the pot between the best high and the best qualifying low is the signature of a hi-lo split game like Omaha Eight-or-Better.",
      },
    ],
  },

  "poker-3-02": {
    intro: "Pot-Limit Omaha looks like Hold'em with extra cards, but the most important rule trips up newcomers: you get four hole cards and MUST use EXACTLY two of them.",
    spots: [
      {
        id: "p3-02-s1", label: "How Many to Use",
        situation: "It's your first hand of Omaha. You've been dealt four hole cards.",
        hand: ["A♠", "K♠", "Q♦", "J♦"],
        board: ["T♣", "9♣", "2♥", "5♦", "3♠"],
        prompt: "How many of your four hole cards do you use to make your final hand?",
        options: ["Any number you like, 0 to 4", "Exactly two — always", "Exactly three", "At least one"],
        correctIndex: 1,
        explanation: "In Omaha you must use EXACTLY two of your four hole cards plus exactly three board cards — no more, no fewer.",
      },
      {
        id: "p3-02-s2", label: "The Fake Flush",
        situation: "Three spades are on the board and you excitedly think you have a flush — but you hold only ONE spade among your four cards.",
        hand: ["A♠", "K♥", "Q♦", "J♣"],
        board: ["9♠", "6♠", "2♠", "8♦", "4♥"],
        prompt: "Do you have a flush?",
        options: [
          "Yes — the Ace of spades plus three board spades makes the nut flush",
          "No — a flush needs TWO of your hole cards in the suit; you only have one spade",
          "Yes — any single spade plays for a flush in Omaha",
          "Only if the Ace is the highest spade",
        ],
        correctIndex: 1,
        explanation: "You must use exactly two hole cards, so one spade can never make a flush in Omaha — this is the classic Omaha trap.",
      },
      {
        id: "p3-02-s3", label: "Real Omaha Flush",
        situation: "The board shows three hearts. You hold two hearts among your four cards.",
        hand: ["A♥", "Q♥", "8♣", "7♠"],
        board: ["K♥", "9♥", "3♥", "4♣", "2♠"],
        prompt: "What is your hand?",
        options: [
          "Just a pair — single cards don't count",
          "The nut flush — your A♥ Q♥ plus three board hearts",
          "No flush, because you can't use both hearts",
          "A straight",
        ],
        correctIndex: 1,
        explanation: "Using your two hearts (A♥ Q♥) with the three board hearts makes a legitimate, in-fact nut, flush in Omaha.",
      },
      {
        id: "p3-02-s4", label: "Reading the Board",
        situation: "The board is paired. You hold a pair in your hand that matches a single board card, plus an unrelated pair.",
        hand: ["K♠", "K♦", "7♥", "6♣"],
        board: ["K♣", "9♠", "9♦", "4♥", "2♠"],
        prompt: "What is your best five-card Omaha hand?",
        options: [
          "Kings full of nines (use K♠ K♦ + K♣ 9♠ 9♦)",
          "Quad kings",
          "Two pair only",
          "Nines full of kings",
        ],
        correctIndex: 0,
        explanation: "Using exactly two hole cards (K♠ K♦) with three board cards (K♣ 9♠ 9♦) gives three kings and two nines — kings full of nines.",
      },
    ],
  },

  "poker-3-03": {
    intro: "PLO is a game of the nuts and big draws. Equities run close, so you want hands that make the BEST hand, position to control the pot, and you can only bet the size of the pot.",
    spots: [
      {
        id: "p3-03-s1", label: "Nut Draw vs Weak Draw",
        situation: "You can continue with one of two flush draws. A board has two diamonds.",
        prompt: "Which flush draw do you most want to be playing for big pots in PLO?",
        options: [
          "The ace-high (nut) flush draw",
          "A seven-high flush draw",
          "Any flush draw — they're all equal",
          "The lowest flush draw, to disguise it",
        ],
        correctIndex: 0,
        explanation: "In PLO, non-nut flushes get you stacked against bigger flushes — you want the nut (ace-high) draw, not a weak one.",
      },
      {
        id: "p3-03-s2", label: "The Wrap",
        situation: "On a 9-8-x board you hold J-T-7-6, giving you a huge straight 'wrap' draw with many cards that complete a straight.",
        hand: ["J♠", "T♦", "7♣", "6♥"],
        board: ["9♣", "8♦", "2♠"],
        prompt: "Why is a wrap so strong in PLO?",
        options: [
          "It gives far more outs (often 13–20) than a single open-ender's 8",
          "It can never be beaten",
          "Wraps only count in Hold'em",
          "It guarantees the nut flush",
        ],
        correctIndex: 0,
        explanation: "A wrap uses multiple connected hole cards to draw to a straight with many more outs than a Hold'em open-ender — a premium PLO draw.",
      },
      {
        id: "p3-03-s3", label: "Pot-Limit Sizing",
        situation: "It's pot-limit. The pot is $100 and no one has bet on this street yet.",
        pot: "$100",
        prompt: "What is the largest bet you are allowed to make?",
        options: ["$200", "$100 (the size of the pot)", "All your chips", "$300"],
        correctIndex: 1,
        explanation: "In pot-limit, with no prior bet on the street the maximum bet equals the current pot — here $100.",
      },
      {
        id: "p3-03-s4", label: "Use Your Position",
        situation: "You hold a strong but draw-heavy hand and must choose a seat to play it from.",
        hand: ["A♠", "A♦", "K♠", "Q♦"],
        prompt: "Why is acting in late position especially valuable in PLO?",
        options: [
          "Equities run close, so the extra information and pot control of last action is a big edge",
          "Position doesn't matter in PLO",
          "Early position lets you bluff more",
          "You must always be first to act with aces",
        ],
        correctIndex: 0,
        explanation: "Because PLO equities are tight and draws are huge, the information and pot-control edge of position is even more valuable than in Hold'em.",
      },
    ],
  },

  "poker-3-04": {
    intro: "Omaha Hi-Lo (Omaha Eight-or-Better) splits the pot. The low half only exists if someone makes a five-card low of eight-or-better. Aces play low; A-2-3-4-5 is the best low.",
    spots: [
      {
        id: "p3-04-s1", label: "Does a Low Qualify?",
        situation: "A player needs to make a qualifying low. The rule is 'eight or better.'",
        prompt: "What does a qualifying low require?",
        options: [
          "Five distinct card ranks all eight or lower (no pairs)",
          "Any five low cards, pairs allowed",
          "Exactly A-2-3-4-5",
          "Three cards under eight",
        ],
        correctIndex: 0,
        explanation: "A qualifying low needs five cards of five DIFFERENT ranks, all eight-or-lower — straights and flushes don't hurt a low.",
      },
      {
        id: "p3-04-s2", label: "The Best Low",
        situation: "Several players hold qualifying lows at showdown.",
        prompt: "Which is the best possible low hand ('the wheel')?",
        options: ["8-7-6-5-4", "A-2-3-4-5", "2-3-4-5-6", "A-2-3-4-6"],
        correctIndex: 1,
        explanation: "A-2-3-4-5 (the wheel) is the lowest possible five-card low and beats every other low.",
      },
      {
        id: "p3-04-s3", label: "No Low Possible",
        situation: "The five community cards are all nine or higher.",
        board: ["K♠", "Q♦", "T♣", "9♥", "9♠"],
        prompt: "What happens to the low half of the pot?",
        options: [
          "It is split among the lowest cards anyway",
          "There is no qualifying low, so the high hand scoops the entire pot",
          "The pot is held over to the next hand",
          "Aces automatically make a low",
        ],
        correctIndex: 1,
        explanation: "A low needs three distinct board cards eight-or-lower; with no qualifying low possible, the best high hand wins (scoops) the whole pot.",
      },
      {
        id: "p3-04-s4", label: "Scoop vs Quarter",
        situation: "You and one opponent both make the identical nut low (A-2 each), but you also have the best high hand.",
        hand: ["A♠", "2♠", "K♦", "Q♣"],
        prompt: "What's the ideal outcome you're aiming for in O8?",
        options: [
          "Getting 'quartered' on the low while winning high",
          "Scooping — winning BOTH the high and the low for the whole pot",
          "Splitting the low and losing high",
          "Tying the high",
        ],
        correctIndex: 1,
        explanation: "Scooping both halves is the goal; when two players tie the low they each get a quarter, so a one-way low can be a trap.",
      },
    ],
  },

  "poker-3-05": {
    intro: "Seven-Card Stud has no community cards. You ante, a forced 'bring-in' starts the action, and your edge comes from reading exposed up-cards and remembering folded cards.",
    spots: [
      {
        id: "p3-05-s1", label: "The Bring-In",
        situation: "Everyone has anted and received two down-cards and one up-card (third street). Action must begin.",
        prompt: "Who is forced to make the 'bring-in' bet?",
        options: [
          "The player showing the LOWEST up-card",
          "The player showing the highest up-card",
          "The player to the dealer's left",
          "Whoever has the best down-cards",
        ],
        correctIndex: 0,
        explanation: "In Seven-Card Stud (high), the player with the lowest exposed up-card is forced to post the bring-in.",
      },
      {
        id: "p3-05-s2", label: "Reading Up-Cards",
        situation: "You hold a pair of jacks. An opponent's up-cards show a pair of kings.",
        hand: ["J♥", "J♦", "8♣"],
        prompt: "What key advantage does Stud give you that Hold'em does not?",
        options: [
          "You can see several of each opponent's actual cards face up",
          "You share community cards",
          "You can draw new cards",
          "There is no betting",
        ],
        correctIndex: 0,
        explanation: "Stud has no community cards; instead you read opponents' exposed up-cards directly, which is a core source of edge.",
      },
      {
        id: "p3-05-s3", label: "Card Memory",
        situation: "You hold three hearts and are drawing to a flush. Earlier, two other hearts were folded face-up by opponents.",
        hand: ["A♥", "9♥", "4♥"],
        prompt: "Why does remembering those folded hearts matter?",
        options: [
          "It doesn't — folded cards are irrelevant",
          "Dead cards reduce your outs, lowering your real chance to complete the flush",
          "Folded cards come back into play",
          "It increases your outs",
        ],
        correctIndex: 1,
        explanation: "Tracking folded ('dead') cards is essential in Stud — hearts already gone reduce the live cards that complete your draw.",
      },
      {
        id: "p3-05-s4", label: "No Community Cards",
        situation: "A newcomer asks where the flop is in Seven-Card Stud.",
        prompt: "What do you tell them?",
        options: [
          "The flop comes after third street",
          "There are NO community cards in Stud — each player makes a hand from their own seven cards",
          "Stud shares three community cards",
          "Stud uses five community cards like Hold'em",
        ],
        correctIndex: 1,
        explanation: "Stud deals each player their own seven cards (mixed up and down) with no shared board at all.",
      },
    ],
  },

  "poker-3-06": {
    intro: "Razz is Seven-Card Stud played for low only. The LOWEST hand wins, straights and flushes don't count against you, and pairs and high cards are your enemy.",
    spots: [
      {
        id: "p3-06-s1", label: "Best Razz Hand",
        situation: "Razz uses your five best low cards out of seven.",
        prompt: "What is the best possible hand in Razz?",
        options: ["A-2-3-4-5 (the wheel)", "A pair of aces", "7-5-4-3-2", "K-Q-J-T-9"],
        correctIndex: 0,
        explanation: "In Razz, straights and flushes don't count, so A-2-3-4-5 (the wheel) is the lowest and therefore best hand.",
      },
      {
        id: "p3-06-s2", label: "Pairs Hurt",
        situation: "You hold A-2-3-3-8 versus an opponent's 2-4-5-6-8.",
        hand: ["A♠", "2♦", "3♣", "3♥", "8♠"],
        prompt: "Who has the better Razz (low) hand?",
        options: [
          "You — you have an ace",
          "Your opponent — your pair of threes forces your hand up to 8-3-3-2-A, worse than their 8-6-5-4-2",
          "It's a tie",
          "You — pairs help in Razz",
        ],
        correctIndex: 1,
        explanation: "Pairs are bad in lowball; your pair of 3s makes your best five 8-3-3-2-A, which loses to an unpaired 8-6-5-4-2.",
      },
      {
        id: "p3-06-s3", label: "Flushes Don't Count",
        situation: "Your five lowest cards happen to all be the same suit: A-2-3-4-6 of clubs.",
        hand: ["A♣", "2♣", "3♣", "4♣", "6♣"],
        prompt: "Does the flush hurt your Razz hand?",
        options: [
          "Yes — a flush ruins a low",
          "No — flushes and straights are ignored in Razz; this is a strong 6-4-3-2-A low",
          "Yes — you must discard a card",
          "Only if it's a straight flush",
        ],
        correctIndex: 1,
        explanation: "Razz ignores straights and flushes entirely, so five suited low cards still play as a clean low (here 6-4-3-2-A).",
      },
      {
        id: "p3-06-s4", label: "Bring-In Reversed",
        situation: "On third street in Razz, the forced bring-in must be posted.",
        prompt: "Which up-card is forced to bring it in?",
        options: [
          "The lowest up-card",
          "The HIGHEST up-card (because high cards are bad in a low game)",
          "An ace",
          "The player left of the dealer",
        ],
        correctIndex: 1,
        explanation: "Because low is good, Razz reverses Stud: the player showing the HIGHEST up-card posts the bring-in.",
      },
    ],
  },

  "poker-3-07": {
    intro: "Five-Card Draw and 2-7 Triple Draw are draw games. In deuce-to-seven lowball the twist is brutal: straights and flushes COUNT AGAINST you and the ace is always HIGH (bad).",
    spots: [
      {
        id: "p3-07-s1", label: "The Nut Low (2-7)",
        situation: "You're playing 2-7 (deuce-to-seven) Triple Draw lowball.",
        prompt: "What is the best possible hand?",
        options: ["A-2-3-4-5", "7-5-4-3-2 (not all one suit)", "2-3-4-5-6", "7-6-5-4-3"],
        correctIndex: 1,
        explanation: "In 2-7, straights/flushes count against you and the ace is high, so the unsuited 7-5-4-3-2 is the best low ('the wheel' of deuce-to-seven).",
      },
      {
        id: "p3-07-s2", label: "Ace Is High",
        situation: "You hold A-2-3-4-6 in 2-7 lowball.",
        hand: ["A♠", "2♦", "3♣", "4♥", "6♠"],
        prompt: "How good is this hand in deuce-to-seven?",
        options: [
          "It's the nuts — A-2-3-4 is the lowest",
          "It's weak — the ace plays HIGH, so this is an ace-high hand, worse than a seven-low",
          "It's a guaranteed low",
          "It's a straight, which wins",
        ],
        correctIndex: 1,
        explanation: "In 2-7 the ace is always high, so an ace in your hand makes it an ace-high — far worse than a clean seven- or eight-low.",
      },
      {
        id: "p3-07-s3", label: "Straights Hurt",
        situation: "You make 7-6-5-4-3, all different suits, in 2-7 lowball.",
        hand: ["7♠", "6♦", "5♣", "4♥", "3♠"],
        prompt: "What's the problem with this hand?",
        options: [
          "Nothing — it's a great seven-low",
          "It's a STRAIGHT, which counts against you in 2-7 and is a high hand, not a low",
          "The ace makes it weak",
          "It's a flush",
        ],
        correctIndex: 1,
        explanation: "Even though those are low cards, 7-6-5-4-3 is a straight — and straights count against you in deuce-to-seven, ruining the low.",
      },
      {
        id: "p3-07-s4", label: "Five-Card Draw Basics",
        situation: "In standard high Five-Card Draw you hold a pair of kings and three unrelated low cards.",
        hand: ["K♠", "K♦", "8♣", "5♥", "2♠"],
        prompt: "What's the standard draw to improve this hand?",
        options: [
          "Discard the three unrelated cards and draw three, keeping the pair of kings",
          "Discard the kings",
          "Stand pat (draw nothing)",
          "Draw all five",
        ],
        correctIndex: 0,
        explanation: "In high draw you keep your made pair and draw three new cards, aiming for trips, two pair, or a better kicker.",
      },
    ],
  },

  "poker-3-08": {
    intro: "Badugi is a four-card draw lowball with a unique hand rank. A 'badugi' is four cards of four DIFFERENT ranks AND four DIFFERENT suits. Duplicate suits or ranks simply don't count.",
    spots: [
      {
        id: "p3-08-s1", label: "Best Badugi",
        situation: "Players draw toward the best possible four-card badugi.",
        prompt: "What is the best hand in Badugi?",
        options: ["A-2-3-4 of four different suits", "A-A-2-3", "2-3-4-5 of one suit", "A-2-3-4 all spades"],
        correctIndex: 0,
        explanation: "A-2-3-4 with four different suits (a 'four-card badugi') is the lowest and best possible Badugi hand.",
      },
      {
        id: "p3-08-s2", label: "Duplicate Suit",
        situation: "You hold A♠ 2♠ 3♥ 4♦ — two of your cards share the spade suit.",
        hand: ["A♠", "2♠", "3♥", "4♦"],
        prompt: "What hand do you actually have?",
        options: [
          "A four-card badugi",
          "Only a THREE-card badugi — one spade must be discarded for ranking, leaving 4-3-A (or 4-3-2)",
          "A full badugi worth A-2-3-4",
          "A flush",
        ],
        correctIndex: 1,
        explanation: "Two spades can't both count, so one is dropped and you hold a three-card badugi — always beaten by any true four-card badugi.",
      },
      {
        id: "p3-08-s3", label: "Duplicate Rank",
        situation: "You hold 5♠ 5♥ 8♦ K♣ — two cards share the rank five.",
        hand: ["5♠", "5♥", "8♦", "K♣"],
        prompt: "How does this count in Badugi?",
        options: [
          "As a four-card badugi",
          "One five is dropped (paired ranks don't count), leaving a three-card K-8-5",
          "As a pair, which is strong",
          "As a flush draw",
        ],
        correctIndex: 1,
        explanation: "Duplicate ranks don't both count, so one five is removed, leaving a weak three-card badugi (K-8-5).",
      },
      {
        id: "p3-08-s4", label: "Four Beats Three",
        situation: "Player A shows a four-card badugi 8-6-4-2 (four suits). Player B shows a three-card badugi 3-2-A.",
        prompt: "Who wins?",
        options: [
          "Player B — their cards are lower",
          "Player A — ANY four-card badugi beats ANY three-card badugi",
          "It's a tie",
          "Player B — three cards are better",
        ],
        correctIndex: 1,
        explanation: "In Badugi a complete four-card badugi always beats a three-card hand, regardless of the actual card values.",
      },
    ],
  },

  "poker-3-09": {
    intro: "Mixed games like HORSE and the 8-Game rotate through different poker variants. The skill isn't one game — it's knowing exactly which game you're in and adapting instantly.",
    spots: [
      {
        id: "p3-09-s1", label: "What HORSE Stands For",
        situation: "You sit down at a HORSE table where the game changes each orbit.",
        prompt: "Which set of games does HORSE rotate through?",
        options: [
          "Hold'em, Omaha Hi-Lo, Razz, Seven-Card Stud, Stud Eight-or-better",
          "Hold'em, Omaha, Razz, Roulette, Stud",
          "Five games of Hold'em variants only",
          "Hold'em, Omaha, Razz, Snap, Euchre",
        ],
        correctIndex: 0,
        explanation: "HORSE = Hold'em, Omaha 8, Razz, Stud, Stud 8 — five rotating variants, each demanding its own strategy.",
      },
      {
        id: "p3-09-s2", label: "Know Your Game",
        situation: "The round has rotated to Razz, but a player keeps trying to make the highest hand.",
        prompt: "Why is that a costly mistake?",
        options: [
          "Razz is a LOW game — the lowest hand wins, so chasing high loses",
          "Razz rewards the highest hand",
          "Razz uses community cards",
          "Razz is the same as Hold'em",
        ],
        correctIndex: 0,
        explanation: "Mixed-game edge starts with tracking the current variant; playing Razz like a high game is a fundamental error.",
      },
      {
        id: "p3-09-s3", label: "Hi-Lo Inside a Mix",
        situation: "The rotation lands on Stud Eight-or-better (Stud 8) within the mix.",
        prompt: "What should you aim for to win the most in this round?",
        options: [
          "Only high hands",
          "Hands that can SCOOP — win both the high and the qualifying low",
          "Only low hands",
          "Folding every hand",
        ],
        correctIndex: 1,
        explanation: "Stud 8 is a split-pot game, so the most profitable hands are those that can scoop both halves.",
      },
      {
        id: "p3-09-s4", label: "Why Mixed Games Reward Skill",
        situation: "A strong all-around player and a Hold'em-only specialist both sit in an 8-Game.",
        prompt: "Who has the edge across the full rotation?",
        options: [
          "The Hold'em specialist, always",
          "The all-around player — breadth across every variant compounds over the rotation",
          "Neither — it's pure luck",
          "Whoever sits on the button first",
        ],
        correctIndex: 1,
        explanation: "Mixed games reward broad skill: specialists leak chips in their weak games, so the well-rounded player profits over the rotation.",
      },
    ],
  },

  "poker-3-10": {
    intro: "Mastering variants is also about smart game selection. Pick games where your edge is biggest, lean on skills that transfer, and respect that variance differs game to game.",
    spots: [
      {
        id: "p3-10-s1", label: "Game Selection",
        situation: "You can join two tables of equal stakes: one full of weak, loose players, one full of tough pros.",
        prompt: "Which table maximizes your win rate?",
        options: [
          "The table of weak players — seek the softest game",
          "The table of pros — to prove yourself",
          "It makes no difference",
          "Whichever has the most players",
        ],
        correctIndex: 0,
        explanation: "Game selection is a top profit lever: your edge comes from opponents' mistakes, so choose the softest game available.",
      },
      {
        id: "p3-10-s2", label: "Transferable Skills",
        situation: "You're a solid Hold'em player thinking about learning PLO and Omaha 8.",
        prompt: "Which skills carry over to the new variants?",
        options: [
          "None — every game is totally separate",
          "Core skills like position, pot odds, hand reading and bankroll discipline transfer across all poker",
          "Only the rules of Hold'em transfer",
          "Only bluffing transfers",
        ],
        correctIndex: 1,
        explanation: "Fundamentals — position, odds, reading ranges, discipline — transfer across every poker variant; only the specific rules change.",
      },
      {
        id: "p3-10-s3", label: "Variance Differs",
        situation: "You move from Limit Hold'em to Pot-Limit Omaha with the same bankroll.",
        prompt: "How should you adjust?",
        options: [
          "Nothing — variance is identical",
          "PLO has higher variance (big draws, close equities), so use a larger bankroll cushion",
          "Play even bigger to recover faster",
          "PLO has lower variance than Limit Hold'em",
        ],
        correctIndex: 1,
        explanation: "Big-bet, draw-heavy games like PLO swing harder than limit games, so a bigger bankroll buffer is needed to survive the variance.",
      },
      {
        id: "p3-10-s4", label: "Mastering a Variant",
        situation: "You want to become a long-term winner in a chosen new game.",
        prompt: "What's the soundest path to mastery?",
        options: [
          "Jump straight into the biggest game you can afford",
          "Study the variant's specific rules and strategy, start at low stakes, and review your play",
          "Rely on luck and play more hands",
          "Only play when you feel hot",
        ],
        correctIndex: 1,
        explanation: "Deliberate study, starting small to manage variance, and reviewing your decisions is how skill in any variant is genuinely built.",
      },
    ],
  },
};
