import type { ScenarioConfig } from "./types";

// "Play the Hand" Decision-Trainer scenarios for the ADVANCED Texas Hold'em epoch.
// Each spot is a deterministic, skill-based decision — the correct line is the
// +EV play taught in that stage, never a luck-of-the-draw outcome. correctIndex
// and explanation are stripped server-side before reaching the client.
export const poker2Scenarios: Record<string, ScenarioConfig> = {
  "poker-2-01": {
    intro: "Winning starts before the flop. Open the right hands from the right seats — ranges widen as you move toward the button.",
    spots: [
      {
        id: "p2-01-s1", label: "UTG Open",
        situation: "Folded to you under the gun at a 9-handed table. Everyone is deep-stacked.",
        hand: ["A♠", "J♦"],
        prompt: "What's the standard raise-first-in play with offsuit A-J from early position?",
        options: [
          "Fold — A-Jo is below a tight UTG opening range",
          "Raise — it's an Ace, always open it",
          "Limp to keep the pot small",
          "Raise to 5x to isolate",
        ],
        correctIndex: 0,
        explanation: "A-J offsuit is dominated by the range that continues against an UTG raise, so it's a fold from the first seat at a full table.",
      },
      {
        id: "p2-01-s2", label: "Button Open",
        situation: "Folded to you on the button. Only the two blinds are left to act behind you.",
        hand: ["9♠", "7♠"],
        prompt: "What's the correct raise-first-in play here?",
        options: [
          "Raise — the button opening range is very wide and 9-7s plays great in position",
          "Fold — suited connectors are too weak",
          "Limp behind to disguise it",
          "Fold and wait for a premium",
        ],
        correctIndex: 0,
        explanation: "On the button you can profitably open roughly the top 45-50% of hands, and a suited connector with position is a clear raise.",
      },
      {
        id: "p2-01-s3", label: "Small Blind Decision",
        situation: "Folded to you in the small blind. The big blind is a competent regular.",
        hand: ["K♣", "8♦"],
        prompt: "How should you play K-8 offsuit heads-up from the small blind?",
        options: [
          "Raise or fold — never limp into a single big blind out of position",
          "Limp — you're getting a discount on the call",
          "Limp-call any raise",
          "Always fold any unpaired hand",
        ],
        correctIndex: 0,
        explanation: "Out of position in the blind-vs-blind battle you want a raise-or-fold strategy; limping forfeits initiative and lets the BB realize equity cheaply.",
      },
      {
        id: "p2-01-s4", label: "Hijack Marginal",
        situation: "Folded to you in the hijack (two off the button) with a middling broadway hand.",
        hand: ["Q♥", "T♦"],
        prompt: "What's the standard play with Q-T offsuit from the hijack?",
        options: [
          "Raise — Q-To is comfortably inside a hijack opening range",
          "Fold — it's only Queen-high",
          "Limp to see a cheap flop",
          "Min-raise to invite callers",
        ],
        correctIndex: 0,
        explanation: "By the hijack the opening range has widened enough that Q-T offsuit is a routine raise-first-in.",
      },
    ],
  },

  "poker-2-02": {
    intro: "The 3-bet and 4-bet war decides big pots. Build a range of value hands and bluffs — and know when to release the bottom of it.",
    spots: [
      {
        id: "p2-02-s1", label: "Value 3-Bet",
        situation: "A solid player opens from the cutoff and you're on the button with a premium hand.",
        hand: ["Q♠", "Q♦"],
        prompt: "What's the strongest play with pocket Queens in position?",
        options: [
          "3-bet for value — build the pot with a dominating hand in position",
          "Flat call to keep their bluffs in",
          "Fold to avoid a 4-bet",
          "Cold-call and check-raise the flop",
        ],
        correctIndex: 0,
        explanation: "QQ is far ahead of a cutoff opening range, so 3-betting for value to grow the pot in position is the most profitable line.",
      },
      {
        id: "p2-02-s2", label: "The Bluff 3-Bet",
        situation: "A late-position regular opens. You hold a hand that blocks their strong continues and plays well postflop.",
        hand: ["A♠", "5♠"],
        prompt: "Why is A-5 suited a great candidate to 3-bet as a bluff?",
        options: [
          "The Ace blocks their AA/AK/AQ and the suited wheel hand has good equity when called",
          "It's the nuts preflop",
          "Because suited hands can never be 4-bet",
          "You should only 3-bet your very best hands",
        ],
        correctIndex: 0,
        explanation: "A-5s is an ideal light 3-bet: the Ace blocker reduces their value combos, and the hand retains flush/wheel equity when called.",
      },
      {
        id: "p2-02-s3", label: "Facing the 4-Bet",
        situation: "You 3-bet with a suited bluff, and the original raiser 4-bets. You're getting a marginal price and you're out of position.",
        hand: ["K♥", "9♥"],
        prompt: "What's the disciplined play with the bottom of your 3-bet bluffing range?",
        options: [
          "Fold — K-9s is below the threshold to continue against a 4-bet",
          "5-bet jam to apply max pressure",
          "Call and try to flop big",
          "Call because it's suited",
        ],
        correctIndex: 0,
        explanation: "When 4-bet, you keep the bluffs with the best blockers/equity and fold the rest; K-9s without an Ace blocker is a clean fold.",
      },
      {
        id: "p2-02-s4", label: "Trap or Jam",
        situation: "You open, a deep aggressive player 3-bets, and you wake up with the best hand. Stacks are 100bb.",
        hand: ["A♣", "A♥"],
        prompt: "What's the standard play with Aces facing a 3-bet at 100bb?",
        options: [
          "4-bet for value — get money in vs a wide 3-bettor and build the pot",
          "Flat call to slow-play out of position",
          "Fold to disguise your range",
          "Min-4-bet to look weak",
        ],
        correctIndex: 0,
        explanation: "Against a 3-bet, 4-betting Aces for value at 100bb maximizes value and avoids playing a bloated pot with no initiative.",
      },
    ],
  },

  "poker-2-03": {
    intro: "The c-bet is a range tool, not an autopilot. Bet where your range is stronger; check and barrel where the board demands it.",
    spots: [
      {
        id: "p2-03-s1", label: "Range-Advantage C-Bet",
        situation: "You raised preflop and got one caller. The flop hits the top of your range hard.",
        hand: ["A♦", "K♣"],
        board: ["A♠", "K♦", "4♣"],
        pot: "$60",
        prompt: "On this Ace-King-high board, what's the best continuation-bet approach?",
        options: [
          "C-bet — you have huge range and nut advantage on a board that favors the raiser",
          "Check — you don't want to scare them",
          "Check to trap with two pair",
          "Bet pot every time regardless of board",
        ],
        correctIndex: 0,
        explanation: "On a high, dry board that smashes the preflop raiser's range, c-betting (often a smaller size, high frequency) prints value and denies equity.",
      },
      {
        id: "p2-03-s2", label: "Give Up the Bluff",
        situation: "You raised with a bluffy hand and the flop misses you and favors the caller's range.",
        hand: ["A♥", "Q♥"],
        board: ["8♠", "7♦", "6♣"],
        pot: "$70",
        prompt: "On this low connected board, what's the disciplined play with two overcards and no draw?",
        options: [
          "Check — this board favors the caller, so give up rather than c-bet into their range",
          "C-bet large as a bluff every time",
          "Overbet to represent a set",
          "Bet small and barrel all streets",
        ],
        correctIndex: 0,
        explanation: "Low, connected boards favor the preflop caller; firing a c-bet with no equity into their range is a burn, so check and give up.",
      },
      {
        id: "p2-03-s3", label: "Double Barrel",
        situation: "You c-bet a flush draw on the flop and got called. The turn is a great card to keep applying pressure.",
        hand: ["K♠", "Q♠"],
        board: ["J♠", "7♦", "3♣", "A♠"],
        pot: "$120",
        prompt: "The turn Ace completes your nut flush draw into the nut flush — what's the play?",
        options: [
          "Bet — you now hold the nut flush, so barrel for value (and the Ace also favors your range)",
          "Check to disguise the flush",
          "Check-fold the turn",
          "Check-call only",
        ],
        correctIndex: 0,
        explanation: "Hitting the nut flush turns your semi-bluff into a value hand; betting the turn extracts from worse made hands and weaker draws.",
      },
      {
        id: "p2-03-s4", label: "Texture Read",
        situation: "You raised and got one caller. You must decide a c-bet sizing based on board texture.",
        board: ["Q♣", "J♦", "T♠"],
        pot: "$60",
        prompt: "On this very wet, connected Q-J-T board, how does the texture affect your c-bet?",
        options: [
          "C-bet less often and more polarized — this dynamic board smashes the caller's range too",
          "C-bet your whole range for a small size",
          "Always overbet to deny equity",
          "Texture never changes c-bet strategy",
        ],
        correctIndex: 0,
        explanation: "Wet, connected boards reduce the raiser's range advantage, so you c-bet a tighter, more polarized range rather than firing your whole range.",
      },
    ],
  },

  "poker-2-04": {
    intro: "Advanced players count combinations and use blockers. The cards you hold change how many hands your opponent can have.",
    spots: [
      {
        id: "p2-04-s1", label: "Count the Combos",
        situation: "You're estimating how many ways an opponent can hold a specific pocket pair when no blockers are present.",
        prompt: "How many combinations of a specific pocket pair (e.g. exactly KK) exist with no cards removed?",
        options: [
          "6",
          "16",
          "4",
          "12",
        ],
        correctIndex: 0,
        explanation: "Any specific pocket pair has 6 combinations (4 cards choose 2); unpaired hands have 16, or 12 offsuit + 4 suited.",
      },
      {
        id: "p2-04-s2", label: "Blocker to Bluff",
        situation: "The board is four to a flush on the river and you're deciding whether to bluff-jam.",
        hand: ["A♠", "7♦"],
        board: ["K♠", "9♠", "4♠", "2♥", "Q♠"],
        pot: "$200",
        prompt: "Why does holding the A♠ make this a great spot to bluff?",
        options: [
          "It blocks the nut flush, so opponents can't have the A-high flush and must fold more",
          "It guarantees you win the pot",
          "Aces are always the nuts",
          "Blockers only matter preflop",
        ],
        correctIndex: 0,
        explanation: "The bare A♠ removes the nut flush from your opponent's range, making a bluff far more likely to fold out their strongest hands.",
      },
      {
        id: "p2-04-s3", label: "Blocker to Fold",
        situation: "You face a big river shove and hold a bluff-catcher. You consider your own cards as blockers.",
        hand: ["T♣", "T♦"],
        board: ["A♠", "K♦", "Q♣", "5♥", "2♠"],
        pot: "$240", toCall: "$160",
        prompt: "Your tens block no value hands and you beat only missed draws — what does combo logic say?",
        options: [
          "Fold — you unblock all their value (AK, AQ, KQ, sets) and the price is bad",
          "Call — pocket tens are always strong",
          "Raise as a bluff",
          "Call because you have a pair",
        ],
        correctIndex: 0,
        explanation: "TT blocks none of their straights/two-pairs/sets, so against a polarized shove you're a clear fold — the blocker math says you beat almost nothing.",
      },
      {
        id: "p2-04-s4", label: "Equity vs a Range",
        situation: "On the flop you hold a strong draw against an opponent's perceived range of top pairs and overpairs.",
        hand: ["J♠", "T♠"],
        board: ["Q♠", "9♦", "2♠"],
        pot: "$80",
        prompt: "With an open-ended straight flush draw vs their made-hand range, how should you view your equity?",
        options: [
          "You're often a small favorite or near coin-flip — play aggressively for fold equity plus equity",
          "You have no equity until you make the hand",
          "You should fold any draw to a bet",
          "Your equity doesn't matter, only made hands win",
        ],
        correctIndex: 0,
        explanation: "A combo draw with ~15 outs has roughly 50%+ equity against one-pair hands, so it's a powerhouse to bet/raise rather than a weak draw.",
      },
    ],
  },

  "poker-2-05": {
    intro: "Strong draws aren't passive. Bet and raise them — you win when they fold AND when you hit. Two ways to win beats one.",
    spots: [
      {
        id: "p2-05-s1", label: "Raise the Draw",
        situation: "You hold the nut flush draw plus a gutshot on the flop, and the preflop raiser c-bets into you.",
        hand: ["A♠", "K♠"],
        board: ["Q♠", "T♠", "3♦"],
        pot: "$50", toCall: "$30",
        prompt: "What's the most profitable line with this big combo draw facing a bet?",
        options: [
          "Raise — semi-bluff for fold equity on top of your large pot equity",
          "Just call and hope to hit",
          "Fold the draw to the bet",
          "Call and check-fold the turn",
        ],
        correctIndex: 0,
        explanation: "A nut-flush-draw-plus-gutshot has so much equity that raising as a semi-bluff is +EV: you can win immediately or improve to the nuts.",
      },
      {
        id: "p2-05-s2", label: "Why Semi-Bluff",
        situation: "You're choosing between betting a draw and checking it.",
        prompt: "What's the core advantage of a semi-bluff over a pure check-call with a draw?",
        options: [
          "You get two ways to win: opponents fold now, or you complete your draw later",
          "It guarantees you'll hit the draw",
          "Checking always makes more money",
          "Semi-bluffs only work against pros",
        ],
        correctIndex: 0,
        explanation: "The whole point of a semi-bluff is the dual threat — fold equity now plus the chance to make the best hand — which a passive call forgoes.",
      },
      {
        id: "p2-05-s3", label: "Sizing the Semi-Bluff",
        situation: "You're semi-bluffing a strong draw on the turn and want maximum pressure and fold equity.",
        hand: ["9♥", "8♥"],
        board: ["7♥", "6♣", "2♥", "K♦"],
        pot: "$120",
        prompt: "With an open-ender plus flush draw and big fold equity, how should you size to set up a river jam?",
        options: [
          "Bet large (near pot) to build the pot and threaten a river shove",
          "Bet the minimum to keep it cheap",
          "Check it back to control the pot",
          "Bet tiny so they always call",
        ],
        correctIndex: 0,
        explanation: "With a monster draw you want a big turn bet that maximizes fold equity and sets up a credible river all-in (the leverage of a big semi-bluff).",
      },
      {
        id: "p2-05-s4", label: "Draw Without Fold Equity",
        situation: "You have a weak draw on the river — but the river has already come and missed you, against a calling station.",
        hand: ["J♦", "T♦"],
        board: ["A♠", "9♣", "4♥", "K♦", "2♠"],
        pot: "$100", toCall: "$60",
        prompt: "Your draw missed and you have jack-high vs a player who never folds — what's correct?",
        options: [
          "Check-fold / give up — there's no fold equity and no showdown value to bluff a station",
          "Bluff jam every time",
          "Bet small as a blocker bet",
          "Call to see a card",
        ],
        correctIndex: 0,
        explanation: "Semi-bluffing requires fold equity or remaining outs; a missed draw with no equity left against a station should simply give up.",
      },
    ],
  },

  "poker-2-06": {
    intro: "More players, more caution. Multiway pots demand tighter value, fewer bluffs, and disciplined pot control with medium hands.",
    spots: [
      {
        id: "p2-06-s1", label: "Tighten Up",
        situation: "Two players have already called a raise in front of you, and you have a speculative hand.",
        hand: ["A♦", "9♦"],
        prompt: "How does a multiway pot change the value of a marginal hand like A-9s?",
        options: [
          "Tighten — multiway, top-pair-weak-kicker hands lose value, so play more cautiously",
          "It plays exactly the same as heads-up",
          "Raise bigger to thin the field always",
          "Multiway pots favor bluffing more",
        ],
        correctIndex: 0,
        explanation: "Against several opponents the chance someone holds a stronger hand rises sharply, so domination-prone hands like A-9s should be played more carefully.",
      },
      {
        id: "p2-06-s2", label: "Bluff Less",
        situation: "It's a three-way pot on the flop and you completely missed with a bluffy hand.",
        board: ["K♠", "8♦", "5♣"],
        pot: "$90",
        prompt: "Why should you bluff far less in this multiway flop?",
        options: [
          "More players means more hands that can call, so c-bet bluffs get through far less often",
          "Bluffing is illegal multiway",
          "You should bluff more to fold everyone",
          "Multiway pots have no effect on bluffs",
        ],
        correctIndex: 0,
        explanation: "With two opponents to get through, a bluff needs both to fold, so bluffing frequency must drop and you lean toward value-only betting.",
      },
      {
        id: "p2-06-s3", label: "Pot Control",
        situation: "Four-handed pot. You flop a medium-strength hand and you're in middle position with players still to act.",
        hand: ["A♣", "J♦"],
        board: ["J♠", "8♥", "4♣"],
        pot: "$100",
        prompt: "With top pair decent kicker multiway, what's the best way to keep the pot manageable?",
        options: [
          "Check / keep the pot small — a medium hand multiway doesn't want to bloat the pot",
          "Bet big to charge draws on every street",
          "Overbet the flop for protection",
          "Check-raise all in",
        ],
        correctIndex: 0,
        explanation: "Medium-strength hands play best in small pots multiway; checking for pot control avoids building a big pot where you're often beaten.",
      },
      {
        id: "p2-06-s4", label: "Value the Nuts",
        situation: "Five-way pot and you flop the absolute nuts on a dynamic board.",
        hand: ["7♦", "6♦"],
        board: ["8♦", "5♣", "4♦"],
        pot: "$150",
        prompt: "You flopped a straight (and a flush draw redraw) in a big multiway pot — what's correct?",
        options: [
          "Bet — with the nuts on a wet board and many opponents, bet to build the pot and protect",
          "Slow-play to trap everyone",
          "Check because it's multiway",
          "Check-fold to avoid variance",
        ],
        correctIndex: 0,
        explanation: "The 'bluff less multiway' rule is about weak hands — with the nuts on a draw-heavy board you bet for value and protection against the many draws.",
      },
    ],
  },

  "poker-2-07": {
    intro: "Sizing is a language. Small bets merge thin value, big bets and overbets polarize into nuts-or-air. Match the size to the message.",
    spots: [
      {
        id: "p2-07-s1", label: "Small for Range",
        situation: "You have a big range advantage on a dry flop and want to bet your whole range.",
        board: ["A♣", "7♦", "2♠"],
        pot: "$50",
        prompt: "On this dry, Ace-high board you can c-bet your entire range — what size fits best?",
        options: [
          "A small bet (~25-33% pot) — high frequency, low cost, denies equity across your range",
          "An overbet to polarize",
          "A pot-sized bet always",
          "Check your whole range",
        ],
        correctIndex: 0,
        explanation: "On a dry board where you hold the range advantage, a small high-frequency c-bet lets you bet everything cheaply while denying equity.",
      },
      {
        id: "p2-07-s2", label: "The Overbet",
        situation: "The river card completes your value range and the board is polarizing. You have the nuts.",
        hand: ["K♠", "Q♠"],
        board: ["A♠", "J♠", "9♣", "4♦", "T♠"],
        pot: "$180",
        prompt: "You hold the nut flush on a scary river — when is an overbet (>pot) correct here?",
        options: [
          "When your range is polarized to nuts-or-bluffs and they have many bluff-catchers — overbet for max value",
          "Never — overbets are reckless",
          "Only when you're bluffing",
          "Only in tournaments",
        ],
        correctIndex: 0,
        explanation: "Overbets shine with a polarized range against an opponent capped to bluff-catchers; the nut flush here can charge a premium for max value.",
      },
      {
        id: "p2-07-s3", label: "Polarized vs Merged",
        situation: "You're choosing a betting range and size on the river.",
        prompt: "What's the difference between a polarized and a merged betting range?",
        options: [
          "Polarized = nuts or bluffs (big size); merged = thin value + medium hands (small size)",
          "They're the same thing",
          "Merged means only bluffs",
          "Polarized means only medium hands",
        ],
        correctIndex: 0,
        explanation: "A polarized range (strong size) is nuts-or-air; a merged range (smaller size) bets thinner value hands that want calls from worse — sizing signals which.",
      },
      {
        id: "p2-07-s4", label: "Thin Value Size",
        situation: "On the river you have a medium-strength hand that beats some of their calling range but not the top of it.",
        hand: ["A♥", "T♣"],
        board: ["T♠", "8♦", "6♣", "3♥", "2♠"],
        pot: "$120",
        prompt: "You hold top pair decent kicker and want value from worse — what sizing extracts best?",
        options: [
          "A small-to-medium (merged) bet that worse pairs and draws can call",
          "An overbet to blow them off the pot",
          "A pot-sized polarized bet",
          "Check it back and give up value",
        ],
        correctIndex: 0,
        explanation: "Thin value wants a smaller, merged size so weaker pairs call; a big polarized bet only folds out the hands you beat.",
      },
    ],
  },

  "poker-2-08": {
    intro: "The numbers tell you the default; the player tells you the deviation. Profile your opponents and exploit each type correctly.",
    spots: [
      {
        id: "p2-08-s1", label: "Exploit the Nit",
        situation: "A very tight, passive player ('a nit') who only raises premium hands suddenly 3-bets you.",
        hand: ["A♦", "Q♣"],
        prompt: "How do you adjust to a nit's surprise 3-bet?",
        options: [
          "Over-fold — a nit's 3-bet is almost always a monster, so fold hands like A-Q",
          "4-bet bluff them aggressively",
          "Call and try to outplay them postflop",
          "Treat it like any regular's 3-bet",
        ],
        correctIndex: 0,
        explanation: "A nit's range is so tight that their aggression screams strength; folding strong-but-dominated hands like A-Q is the correct exploit.",
      },
      {
        id: "p2-08-s2", label: "Exploit the Station",
        situation: "A loose-passive calling station never folds top pair or any draw and rarely bluffs.",
        hand: ["K♠", "K♦"],
        board: ["K♣", "9♦", "5♠"],
        pot: "$80",
        prompt: "You flop top set against a calling station — how do you maximize?",
        options: [
          "Bet big for value on every street — they'll pay off with worse, so don't bluff, just value-bet",
          "Slow-play to trap them",
          "Check to induce a bluff",
          "Bet small so they don't fold",
        ],
        correctIndex: 0,
        explanation: "Against a station you stop bluffing and relentlessly value-bet large; they call too wide, so thin and thick value both print.",
      },
      {
        id: "p2-08-s3", label: "Counter the LAG",
        situation: "A loose-aggressive regular is 3-betting and barreling relentlessly, putting you to tough decisions.",
        hand: ["A♣", "J♣"],
        prompt: "What's a sound adjustment against a hyper-aggressive LAG?",
        options: [
          "Widen your calling/bluff-catching range and let them barrel into your strong hands",
          "Fold everything but Aces and Kings",
          "Match their aggression with random bluffs",
          "Stop playing pots in position with them",
        ],
        correctIndex: 0,
        explanation: "Because a LAG bluffs too much, you profitably loosen your calls and trap — letting their relentless betting pay off your made hands.",
      },
      {
        id: "p2-08-s4", label: "Position on the Whale",
        situation: "A rich recreational 'whale' who plays almost every hand and overvalues weak holdings just sat down.",
        prompt: "What's the single biggest adjustment to maximize value from the whale?",
        options: [
          "Try to play more pots in position against them and value-bet relentlessly",
          "Bluff them off every pot",
          "Avoid the whale to dodge variance",
          "Only play premium hands and fold the rest",
        ],
        correctIndex: 0,
        explanation: "Seat selection and position against a loose, paying whale lets you isolate them and extract maximum thin value — the most profitable adjustment in the game.",
      },
    ],
  },

  "poker-2-09": {
    intro: "At the final table, chips aren't dollars. ICM warps every decision near a pay jump — survival has real, mathematical value.",
    spots: [
      {
        id: "p2-09-s1", label: "ICM Fold",
        situation: "Final table, you're a medium stack on a pay jump. A short stack jams all-in and a big stack is still behind you.",
        hand: ["A♠", "Q♦"],
        prompt: "Why might you fold A-Q here that you'd snap-call in a cash game?",
        options: [
          "ICM — busting before a pay jump forfeits huge equity, so you fold many chip-EV calls",
          "A-Q is a weak hand",
          "You should always call all-ins at a final table",
          "ICM only matters for the chip leader",
        ],
        correctIndex: 0,
        explanation: "ICM makes chips lost worth more than chips won near a pay jump, so you tighten and pass marginal calls that would be fine for cash.",
      },
      {
        id: "p2-09-s2", label: "Big-Stack Pressure",
        situation: "You're the chip leader at the final table. The medium stacks are trying to ladder up the pay scale.",
        prompt: "How should the big stack use ICM to their advantage?",
        options: [
          "Apply pressure — open and 3-bet wider, because the medium stacks must fold to preserve their equity",
          "Sit tight and fold to avoid risk",
          "Only play premium hands",
          "Limp every pot to keep pots small",
        ],
        correctIndex: 0,
        explanation: "ICM pressure flows downhill: the big stack risks little (covered no one), so attacking the medium stacks who fear busting is highly profitable.",
      },
      {
        id: "p2-09-s3", label: "Short-Stack Shove",
        situation: "You're short with about 8 big blinds, folded to you in the cutoff at the final table.",
        hand: ["K♦", "T♠"],
        prompt: "What's the correct play with a short stack and a reasonable hand?",
        options: [
          "Open-shove all-in — at ~8bb you're in push/fold and K-T is well within a cutoff jamming range",
          "Min-raise and fold to a shove",
          "Limp to see a flop",
          "Fold and wait for Aces",
        ],
        correctIndex: 0,
        explanation: "At ~8bb there's no room to play postflop; open-jamming K-T from the cutoff is the standard push/fold play that maximizes fold equity and all-in value.",
      },
      {
        id: "p2-09-s4", label: "Bubble Discipline",
        situation: "You're on the money bubble with a comfortable stack. A big stack opens and you have a strong-but-not-premium hand.",
        hand: ["J♣", "J♥"],
        prompt: "How does ICM on the bubble shape your play with pocket Jacks vs the big stack?",
        options: [
          "Play more cautiously — avoid stacking off in a flip where busting on the bubble is catastrophic",
          "Always get it all-in preflop with JJ",
          "Fold JJ entirely",
          "Limp-call to keep the pot small",
        ],
        correctIndex: 0,
        explanation: "On the bubble against a covering stack, ICM says avoid coin-flips for your tournament life; JJ plays a smaller pot rather than a stack-off.",
      },
    ],
  },

  "poker-2-10": {
    intro: "Modern theory ties it together. Defend enough to stay unexploitable, respect range advantage, and run a real study routine.",
    spots: [
      {
        id: "p2-10-s1", label: "Don't Over-Fold",
        situation: "An opponent bets pot on the river. You hold a marginal bluff-catcher and feel like folding.",
        pot: "$100", toCall: "$100",
        prompt: "Against a pot-sized bet, roughly what minimum defense frequency keeps you unexploitable?",
        options: [
          "Defend about 50% — folding too much lets them profitably bluff any two cards",
          "Fold everything but the nuts",
          "Defend 100% of your range",
          "Defense frequency doesn't matter",
        ],
        correctIndex: 0,
        explanation: "Minimum defense frequency vs a pot bet is ~50% (1 - bet/(pot+bet)); over-folding hands you a printing press of profitable bluffs.",
      },
      {
        id: "p2-10-s2", label: "Pot Odds to Defend",
        situation: "Facing a half-pot river bet, you need to know how often to continue to avoid being exploited.",
        pot: "$100", toCall: "$50",
        prompt: "Against a half-pot bet, what's the approximate minimum defense frequency?",
        options: [
          "About 67% — smaller bets require defending a larger share of your range",
          "About 33%",
          "About 50%",
          "About 25%",
        ],
        correctIndex: 0,
        explanation: "MDF vs a half-pot bet is 1 - 0.5/1.5 ≈ 67%; the smaller the bet, the more of your range you must defend to stop cheap bluffs.",
      },
      {
        id: "p2-10-s3", label: "Range Advantage",
        situation: "You're the preflop aggressor on a flop that favors your range, and you're choosing a default strategy.",
        board: ["A♥", "K♣", "5♦"],
        pot: "$60",
        prompt: "How should range advantage guide your default c-bet strategy on an Ace-King flop?",
        options: [
          "Bet a high frequency with a small size — your range advantage lets you pressure cheaply",
          "Check your entire range",
          "Only bet your two-pair-plus hands",
          "Always overbet for value",
        ],
        correctIndex: 0,
        explanation: "When you hold the range and nut advantage, the balanced default is a high-frequency small c-bet that leverages your edge across your whole range.",
      },
      {
        id: "p2-10-s4", label: "Study Routine",
        situation: "You want to improve fastest between sessions and turn leaks into edges.",
        prompt: "What's the most effective modern study habit for a serious player?",
        options: [
          "Review your own marked hands and run them through a solver to find and fix recurring leaks",
          "Only play more volume and never review",
          "Memorize one preflop chart and never adjust",
          "Watch streams passively without taking notes",
        ],
        correctIndex: 0,
        explanation: "Deliberate review of your real hands against a solver targets your actual leaks, which improves results far faster than volume or passive watching alone.",
      },
    ],
  },
};
