import type { QuizConfig } from "./types";

export const quizStage01: QuizConfig = {
  questions: [
    {
      id: "q1",
      type: "🔐 Cipher Challenge",
      challenge: [
        "INTERCEPTED TRANSMISSION — CLASSIFIED",
        "─────────────────────────────────────",
        "",
        "  Khoor Djhqw. Wklv phvvdjh lv",
        "  fodvvlilhg. Rqob dxwkrulchg",
        "  shuvrqqho pd| ghfubsw wklv.",
        "",
        "Cipher type: Caesar  |  Key: ???",
        "Hint: Each letter shifted +3 positions",
        "",
        "Decoded: Hello Agent. This message is",
        "         classified. Only authorized",
        "         personnel may decrypt this.",
      ].join("\n"),
      text: "An enemy intercepted this transmission but couldn't read it. A spy used a Caesar cipher (shift +3) to protect the contents. Which CIA Triad principle does encryption like this directly implement?",
      options: [
        "Confidentiality — only authorized parties can read the data",
        "Integrity — the data has not been altered in transit",
        "Availability — the data is accessible when needed",
        "Non-repudiation — the sender cannot deny sending it",
      ],
      correctIndex: 0,
      explanation:
        "Encryption is the classic implementation of Confidentiality. The Caesar cipher (and modern equivalents like AES-256) ensures that even if an attacker intercepts the data, they cannot read it without the key. The message was 'available' and 'intact' — but unreadable to unauthorized eyes.",
    },
    {
      id: "q2",
      type: "🔍 Hash Tampering Analysis",
      challenge: [
        "FILE TRANSFER VERIFICATION REPORT",
        "──────────────────────────────────",
        "",
        "  File: patient_records_2024.db",
        "  Size: 14.2 MB",
        "",
        "  ORIGINAL checksum (sender):",
        "  sha256: a3f5c2d8e1b4f7a9c6d3e8f2b1a4c7d0",
        "         e9f6a3b8c5d2e7f4a1b6c3d8e5f2a9b4",
        "",
        "  RECEIVED checksum (our server):",
        "  sha256: a3f5c2d8e1b4f7a9c6d3e8f2b1a4c7d0",
        "         e9f6a3b8c5d2e700000000000000DEAD",
        "",
        "  ⚠ MISMATCH DETECTED",
      ].join("\n"),
      text: "A hospital transmitted patient records. The SHA-256 checksums don't match — the last 8 bytes differ. The file was silently modified in transit by a man-in-the-middle attacker. Which CIA principle was violated, and what is the attacker's technique called?",
      options: [
        "Integrity — a man-in-the-middle (MITM) attack tampered with the data",
        "Confidentiality — an attacker read the file contents during transfer",
        "Availability — the attacker blocked the file from being delivered",
        "Authentication — the sender's identity was not verified",
      ],
      correctIndex: 0,
      explanation:
        "Integrity ensures data is accurate and unaltered. Cryptographic hashes (SHA-256, MD5) are the primary integrity control — any modification, even a single bit, produces a completely different hash. This attack is a MITM (man-in-the-middle), and the technique is called 'tampering'. In this scenario, an attacker modified patient records mid-transfer — a potentially life-threatening integrity failure.",
    },
    {
      id: "q3",
      type: "📡 Network Log Analysis",
      challenge: [
        "LIVE NETWORK MONITOR — CRITICAL ALERT",
        "──────────────────────────────────────",
        "",
        " [09:14:01] SYN packets/sec:      412",
        " [09:14:02] SYN packets/sec:    8,204",
        " [09:14:03] SYN packets/sec:   94,817",
        " [09:14:04] SYN packets/sec:  210,443",
        " [09:14:05] Connection table:   100% full",
        " [09:14:05] New connections:    REFUSED",
        " [09:14:06] Service status:     UNREACHABLE",
        "",
        " Source IPs: 182 unique addresses (spoofed)",
        " Target: hospital-icu-monitor.internal:443",
        " !! LIFE-CRITICAL SYSTEM OFFLINE !!",
      ].join("\n"),
      text: "A hospital's ICU patient monitoring system was taken offline by a SYN flood. Attackers sent millions of half-open TCP connections, exhausting the server's connection table. No patient data was stolen or altered. Which CIA principle was violated, and what category of attack is this?",
      options: [
        "Availability — a volumetric DDoS (SYN flood) attack",
        "Confidentiality — attackers exfiltrated ICU patient data",
        "Integrity — attackers modified the ICU monitoring readings",
        "Availability — a ransomware encryption attack",
      ],
      correctIndex: 0,
      explanation:
        "Availability ensures systems are accessible when needed. A SYN flood exploits the TCP three-way handshake — the attacker sends SYN packets but never completes the ACK, leaving thousands of half-open connections until the server's table fills up and it stops accepting legitimate connections. This is a Distributed Denial-of-Service (DDoS) attack. Against life-critical hospital systems, an availability attack can be as dangerous as any data breach.",
    },
  ],
};
