import type { ScenarioConfig } from "./types";

// "Decision Trainer" scenarios for the Spades epoch. Each spot is a deterministic,
// skill-based decision — the correct line is the rules-correct or +value play taught
// in that stage, never luck. correctIndex and explanation are stripped server-side
// before reaching the client. Standard 4-player partnership Spades, game to 500.
export const spades1Scenarios: Record<string, ScenarioConfig> = {
  "spades-1-01": {
    intro: "Pull up a chair. Before any cards fly, make sure the shape of the game — four players, two teams, and one suit that always wins — is second nature.",
    spots: [
      {
        id: "spades-01-s1", label: "The Table",
        situation: "You've just sat down to a fresh game and the deck is being shuffled.",
        prompt: "How is a standard game of Spades set up?",
        options: [
          "Three teams of two",
          "Every player for themselves",
          "Four players in two partnerships, partners sitting across the table",
          "Two players head to head",
        ],
        correctIndex: 2,
        explanation: "Standard Spades is four players in two partnerships, with partners seated opposite each other.",
      },
      {
        id: "spades-01-s2", label: "Trump",
        situation: "It's your first hand and you're sorting your cards.",
        hand: ["A♠", "9♠", "K♥", "4♦"],
        prompt: "Which suit is trump this hand?",
        options: [
          "Spades — always, every hand",
          "Whichever suit is led first",
          "The suit chosen by bidding",
          "Hearts, because you hold the King",
        ],
        correctIndex: 0,
        explanation: "Spades is the permanent trump suit every hand; there is no auction to pick trump.",
      },
      {
        id: "spades-01-s3", label: "Your Score",
        situation: "You take 3 tricks and your partner takes 4.",
        prompt: "Whose tricks count toward your result?",
        options: [
          "Only the tricks you personally win",
          "Yours and your partner's, combined into one team total",
          "Every trick at the table",
          "Only the dealer's tricks",
        ],
        correctIndex: 1,
        explanation: "Spades is a partnership game — your tricks and your partner's combine into a single team score.",
      },
      {
        id: "spades-01-s4", label: "The Finish",
        situation: "Several hands in, your team is at 470 points.",
        prompt: "How does the game of Spades end?",
        options: [
          "After exactly five hands",
          "When one player takes all 13 tricks in a hand",
          "When someone bids nil",
          "When a team is first to reach 500 points",
        ],
        correctIndex: 3,
        explanation: "Teams keep playing hands until one side reaches the target score, traditionally 500.",
      },
    ],
  },

  "spades-1-02": {
    intro: "Every hand starts the same way: deal all 52, then remember the one rule that never changes — any spade beats any other suit. Get the deal and the fixed trump cold.",
    spots: [
      {
        id: "spades-02-s1", label: "The Deal",
        situation: "The dealer deals the whole deck out, one card at a time, clockwise.",
        prompt: "How many cards does each player receive?",
        options: ["11", "13", "7", "All 52"],
        correctIndex: 1,
        explanation: "The full 52-card deck is dealt evenly, so each of the four players gets 13 cards.",
      },
      {
        id: "spades-02-s2", label: "Low Trump",
        situation: "A heart is led and the trick already holds the Ace of hearts. You're void in hearts and play the 2 of spades.",
        hand: ["2♠"],
        board: ["A♥"],
        prompt: "Who wins this trick?",
        options: [
          "The A♥ — it's the higher card",
          "They tie and the trick is split",
          "The 2♠ — any spade beats any non-spade",
          "Whoever led the heart",
        ],
        correctIndex: 2,
        explanation: "Spades are trump, so even the lowest spade outranks the highest card of another suit.",
      },
      {
        id: "spades-02-s3", label: "Follow Suit",
        situation: "A diamond is led and your hand still contains diamonds.",
        hand: ["K♦", "8♦", "Q♠", "3♣"],
        board: ["7♦"],
        prompt: "What are you required to do?",
        options: [
          "Follow suit — play a diamond",
          "Trump in with the Q♠",
          "Discard the 3♣",
          "Play whatever card you like",
        ],
        correctIndex: 0,
        explanation: "If you hold the led suit you must follow it — you cannot trump or discard while you can follow.",
      },
      {
        id: "spades-02-s4", label: "Choosing Trump",
        situation: "A new hand is about to start.",
        prompt: "How is the trump suit chosen this hand?",
        options: [
          "The players bid for it",
          "The dealer names it",
          "The first card led sets it",
          "It isn't chosen — spades are always trump",
        ],
        correctIndex: 3,
        explanation: "Trump is fixed as spades every hand; there is no selection or auction.",
      },
    ],
  },

  "spades-1-03": {
    intro: "Most of Spades is decided before a card is played. Count the tricks your hand can really win, then combine with your partner into one team contract.",
    spots: [
      {
        id: "spades-03-s1", label: "Count Your Tricks",
        situation: "It's your turn to bid. You weigh your near-sure winners — high spades and side aces.",
        hand: ["A♠", "K♠", "Q♠", "A♥", "K♦", "9♦", "7♦", "8♣", "5♣", "4♣", "6♥", "3♥", "2♥"],
        prompt: "What's a sensible bid for this hand?",
        options: [
          "0 (nil)",
          "About 4 or 5",
          "All 13",
          "Exactly 1",
        ],
        correctIndex: 1,
        explanation: "Three top spades plus the A♥ are near-certain, with the K♦ a likely fourth or fifth — about 4–5.",
      },
      {
        id: "spades-03-s2", label: "Team Contract",
        situation: "You bid 4 and, around the table, your partner bids 3.",
        prompt: "How many tricks must your team win?",
        options: [
          "Exactly 4",
          "Exactly 3",
          "At least 7 — the bids combine",
          "At least 13",
        ],
        correctIndex: 2,
        explanation: "Partners' bids add together: 4 + 3 = 7 tricks needed as a team.",
      },
      {
        id: "spades-03-s3", label: "Made It",
        situation: "Your team bid 5 and takes its 5 tricks.",
        prompt: "How much does the made contract score?",
        options: [
          "5 points",
          "500 points",
          "Nothing until you hit 500",
          "50 points (10 per bid trick)",
        ],
        correctIndex: 3,
        explanation: "A made contract scores 10 points per bid trick, so a bid of 5 is worth 50.",
      },
      {
        id: "spades-03-s4", label: "The Set",
        situation: "Your team bid 8 but manages only 7 tricks.",
        prompt: "What happens?",
        options: [
          "You're 'set' and lose 80 points",
          "You score 70 points",
          "You score 80 points anyway",
          "Nothing changes",
        ],
        correctIndex: 0,
        explanation: "Missing the contract is a set: you lose 10 points per bid trick, here -80.",
      },
    ],
  },

  "spades-1-04": {
    intro: "Every trick runs on three rules: follow the led suit if you can, trump in if you can't, and never lead a spade until they're 'broken'. Drill the legal play.",
    spots: [
      {
        id: "spades-04-s1", label: "Must Follow",
        situation: "Hearts are led and you hold a heart.",
        hand: ["A♥", "9♥", "K♠", "4♣"],
        board: ["7♥"],
        prompt: "What must you do?",
        options: [
          "Play a heart — follow suit",
          "Trump with the K♠",
          "Discard the 4♣",
          "Lead a new suit",
        ],
        correctIndex: 0,
        explanation: "If you can follow the led suit you must — you can't trump or discard while holding it.",
      },
      {
        id: "spades-04-s2", label: "Trump In",
        situation: "A heart is led, the A♥ is already out, and you have no hearts at all.",
        hand: ["K♠", "5♠", "8♦", "3♣"],
        board: ["A♥"],
        prompt: "How can you win this trick?",
        options: [
          "You can't — just discard",
          "Play a spade to trump in — it beats every heart",
          "Play a higher heart",
          "You must pass your turn",
        ],
        correctIndex: 1,
        explanation: "Void in the led suit, you may trump with a spade, which beats any non-spade in the trick.",
      },
      {
        id: "spades-04-s3", label: "Can You Lead Spades?",
        situation: "No spade has been played yet this hand. It's your lead and you hold both spades and side cards.",
        hand: ["A♠", "Q♦", "9♦", "6♣"],
        prompt: "May you lead a spade?",
        options: [
          "Yes, any time you want",
          "Only on the last trick",
          "No — spades aren't 'broken' yet, so lead a side suit",
          "Yes, and you must lead your highest spade",
        ],
        correctIndex: 2,
        explanation: "You can't lead spades until they're broken — unless your hand is nothing but spades, which it isn't here.",
      },
      {
        id: "spades-04-s4", label: "Higher Spade Wins",
        situation: "A heart was led; an opponent already trumped it with the 4♠. You're void in hearts.",
        hand: ["J♠", "8♦", "2♣"],
        board: ["6♥", "4♠"],
        prompt: "How do you take this trick from them?",
        options: [
          "Discard the 8♦ — you can't win it",
          "Play the J♠ — a higher spade beats their 4♠",
          "Play the 2♣ to follow along",
          "Nothing beats the first spade played",
        ],
        correctIndex: 1,
        explanation: "When more than one spade is played, the highest spade wins — your J♠ tops their 4♠.",
      },
    ],
  },

  "spades-1-05": {
    intro: "The nil bid is the soul of Spades: promise ZERO tricks for a big bonus. Learn to spot a safe nil hand and to lose tricks on purpose.",
    spots: [
      {
        id: "spades-05-s1", label: "A Nil Hand",
        situation: "You're deciding whether to bid nil with this hand.",
        hand: ["3♠", "2♠", "9♦", "6♦", "4♦", "2♦", "8♣", "5♣", "3♣", "2♣", "7♥", "4♥", "2♥"],
        prompt: "Is this a good hand to bid nil?",
        options: [
          "Yes — all low cards, no Aces or Kings, only two low spades",
          "No — far too many spades to ever duck",
          "No — you must hold an Ace to bid nil",
          "Yes, but only as a blind nil",
        ],
        correctIndex: 0,
        explanation: "Low cards and only two small spades make this easy to duck under everything — an ideal nil hand.",
      },
      {
        id: "spades-05-s2", label: "Nil Payoff",
        situation: "You bid nil and successfully take zero tricks the whole hand.",
        prompt: "What is a made nil typically worth?",
        options: [
          "+10 points",
          "+100 points",
          "+200 points",
          "Nothing — nil is just for show",
        ],
        correctIndex: 1,
        explanation: "A made nil usually scores a +100 bonus on top of your partner's normal bid; breaking it loses 100.",
      },
      {
        id: "spades-05-s3", label: "Danger Card",
        situation: "You're playing a nil and scanning for the card most likely to win an unwanted trick.",
        hand: ["A♣", "5♣", "3♦", "2♦", "4♥", "3♥", "6♠", "2♠", "9♦", "7♦", "8♥", "5♥", "2♥"],
        prompt: "Which card most threatens your nil?",
        options: [
          "The 2♠",
          "The 3♦",
          "The A♣ — it can be forced to win when clubs are led",
          "The 2♥",
        ],
        correctIndex: 2,
        explanation: "A high card like the bare Ace is the classic nil-breaker — when its suit is led you may be forced to win.",
      },
      {
        id: "spades-05-s4", label: "Duck the Trick",
        situation: "On your nil, a club is led with the K♣ already played. You hold the A♣ and the 4♣.",
        hand: ["A♣", "4♣"],
        board: ["K♣"],
        prompt: "Which club do you play to stay safe?",
        options: [
          "The A♣ — get rid of it now",
          "The 4♣ — duck under and lose the trick",
          "Neither — you should trump it",
          "The A♣ to win and take control",
        ],
        correctIndex: 1,
        explanation: "You must follow with a club; the A♣ would win and break your nil, so duck with the 4♣.",
      },
    ],
  },

  "spades-1-06": {
    intro: "A blind nil is the boldest bid in the game: zero tricks declared BEFORE you look. Big reward, big risk — usually a comeback tool when you're far behind.",
    spots: [
      {
        id: "spades-06-s1", label: "When to Go Blind",
        situation: "Your team is trailing 480 to 290 late in the game.",
        prompt: "When is bidding blind nil usually the right gamble?",
        options: [
          "Every hand, to rack up bonuses",
          "When you're far behind and need a big swing to catch up",
          "When you're comfortably ahead",
          "Only on the very first hand of the game",
        ],
        correctIndex: 1,
        explanation: "Blind nil is a high-variance comeback play — worth the risk mainly when a normal plan can't close the gap.",
      },
      {
        id: "spades-06-s2", label: "The Stakes",
        situation: "You're weighing a blind nil against an ordinary nil.",
        prompt: "How does blind-nil scoring compare with a regular nil?",
        options: [
          "Exactly the same, ±100",
          "Smaller, only ±50",
          "Bigger — commonly ±200",
          "There's no penalty at all",
        ],
        correctIndex: 2,
        explanation: "Because you bid before seeing your cards, both the bonus and the penalty are larger, often ±200.",
      },
      {
        id: "spades-06-s3", label: "Bid First, Look After",
        situation: "Your team agrees to attempt the comeback bid.",
        prompt: "What makes a nil 'blind'?",
        options: [
          "You bid it before looking at your cards",
          "You bid it only after carefully studying your hand",
          "Your partner bids it for you",
          "You play the whole hand with cards face down",
        ],
        correctIndex: 0,
        explanation: "A blind nil is declared before you've seen your hand, which is exactly what makes it so risky.",
      },
      {
        id: "spades-06-s4", label: "The Card Pass",
        situation: "Your house rules allow help after a blind nil is declared.",
        prompt: "How do many rule sets aid the blind-nil bidder?",
        options: [
          "By revealing the opponents' hands",
          "By skipping the bidder's turns",
          "By doubling the bonus a second time",
          "By letting partners swap a couple of cards — you give danger, partner gives lows",
        ],
        correctIndex: 3,
        explanation: "An optional card pass lets you trade away your most dangerous cards for your partner's lowest ones.",
      },
    ],
  },

  "spades-1-07": {
    intro: "In most games more is better — not in Spades. Every trick past your bid is a 'bag', and 10 bags trigger a -100 penalty. Learn to bid up and dump extras.",
    spots: [
      {
        id: "spades-07-s1", label: "What's a Bag",
        situation: "Your team bid 5 and ends up taking 7 tricks.",
        prompt: "What are those two extra tricks called?",
        options: [
          "Bonuses worth 50 points each",
          "Bags (overtricks), worth just 1 point each",
          "A set",
          "A nil",
        ],
        correctIndex: 1,
        explanation: "Tricks above your bid are 'bags' worth only 1 point each — and they pile up against you.",
      },
      {
        id: "spades-07-s2", label: "The 10-Bag Cliff",
        situation: "Your running bag counter has just ticked up to 10.",
        prompt: "What happens?",
        options: [
          "You win the game outright",
          "Nothing — bags are free points",
          "You lose 100 points and the counter rolls back by 10",
          "You gain 100 points",
        ],
        correctIndex: 2,
        explanation: "Reaching 10 bags triggers a -100 penalty, and your bag count drops back by 10.",
      },
      {
        id: "spades-07-s3", label: "Dump the Extra",
        situation: "Your contract is already safely made and your team is sitting on 9 bags. A trick comes around that you could easily win or lose.",
        prompt: "What's the disciplined play?",
        options: [
          "Win every remaining trick you can",
          "Lose the trick on purpose to avoid the 10th bag",
          "Trump in to be sure you win it",
          "Bid nil mid-hand",
        ],
        correctIndex: 1,
        explanation: "On 9 bags one careless overtrick costs 100 points — dump tricks once your bid is locked.",
      },
      {
        id: "spades-07-s4", label: "Bid What You'll Take",
        situation: "Looking at your hand, you can see it will clearly win about 6 tricks no matter how you play.",
        prompt: "What's the smart bid?",
        options: [
          "Bid 6 — those tricks score 10 each instead of becoming bags",
          "Bid 2 to play it safe",
          "Bid nil",
          "Bid 13",
        ],
        correctIndex: 0,
        explanation: "If you'll take the tricks anyway, bid them so they score 10 each rather than piling up as 1-point bags.",
      },
    ],
  },

  "spades-1-08": {
    intro: "Spades is a team game, and nowhere more than when your partner bids nil. Your job is to win the tricks they can't afford to.",
    spots: [
      {
        id: "spades-08-s1", label: "Cover the Nil",
        situation: "Your partner is going for nil. A heart is led, partner safely plays the 8♥, and an opponent the 5♥. You hold the A♥.",
        hand: ["A♥", "K♣", "3♦"],
        board: ["8♥", "5♥"],
        prompt: "How do you protect your partner's nil?",
        options: [
          "Play the A♥ to win the trick yourself",
          "Throw the 3♦ and duck",
          "Let the opponent win it",
          "Play low and hope it's fine",
        ],
        correctIndex: 0,
        explanation: "Taking the trick yourself with the A♥ keeps it off your partner, protecting their nil.",
      },
      {
        id: "spades-08-s2", label: "Bid to Support",
        situation: "Your partner has just bid nil and it's your turn to bid.",
        prompt: "How should you bid your own hand?",
        options: [
          "Bid 0 as well to match them",
          "Bid a little higher so you can take strong tricks and cover them",
          "Refuse to bid",
          "Bid exactly 1, always",
        ],
        correctIndex: 1,
        explanation: "The covering partner bids up and plays to win tricks, so the nil player never has to take one.",
      },
      {
        id: "spades-08-s3", label: "Win Over the Threat",
        situation: "A spade is led and your nil partner could be stuck if the trick reaches them. You can take it with either the A♠ or the 10♠.",
        hand: ["A♠", "10♠", "6♦"],
        board: ["4♠"],
        prompt: "What's the safest way to take the trick off your partner?",
        options: [
          "Win with the 10♠ and hope it holds up",
          "Duck and let your partner take it",
          "Win with the A♠ — guarantee you, not partner, take the trick",
          "Discard the 6♦",
        ],
        correctIndex: 2,
        explanation: "When covering a nil, certainty matters most — the A♠ guarantees you take the trick away from your partner.",
      },
      {
        id: "spades-08-s4", label: "Don't Strand Partner",
        situation: "Your partner is playing a nil and you're choosing who should control the lead.",
        prompt: "Why should you, not your nil partner, take the lead?",
        options: [
          "Leading often forces you to win, which would break their nil",
          "Partners are not allowed to lead",
          "Leading scores extra bags",
          "The nil player is required to lead every trick",
        ],
        correctIndex: 0,
        explanation: "Whoever leads frequently ends up winning, so the covering partner takes the lead to keep the nil safe.",
      },
    ],
  },

  "spades-1-09": {
    intro: "Memory is a weapon. Track the spades as they fall, know when opponents are out of trump, and squeeze them short of their bid to 'set' them.",
    spots: [
      {
        id: "spades-09-s1", label: "Count the Spades",
        situation: "Several tricks in, you're keeping a mental tally of every spade played.",
        prompt: "Why do strong players track how many spades are gone?",
        options: [
          "To know when their own spades are winners and when opponents are out of trump",
          "Because the rules require an out-loud count",
          "To decide which suit becomes trump",
          "Spades stop mattering once they're led",
        ],
        correctIndex: 0,
        explanation: "Counting trump tells you when your spades will win and when opponents can no longer trump your side suits.",
      },
      {
        id: "spades-09-s2", label: "Setting Them",
        situation: "The opponents bid an aggressive 7 and you're planning your defense.",
        prompt: "What does it mean to 'set' the opponents?",
        options: [
          "Help them reach their bid",
          "Stop them making their bid, costing them 10 points per bid trick",
          "Bid nil against them",
          "Hand them your bags",
        ],
        correctIndex: 1,
        explanation: "Setting opponents means holding them below their bid, which costs them 10 points for every trick bid.",
      },
      {
        id: "spades-09-s3", label: "Force the Set",
        situation: "The opponents need exactly one more trick to make their bid. A side Ace of diamonds is led and you're void in diamonds.",
        hand: ["7♠", "5♣", "2♣"],
        board: ["A♦"],
        prompt: "How do you set them?",
        options: [
          "Discard and let them have the trick",
          "Trump in with the 7♠ to steal the trick they need",
          "Follow with the 4♦",
          "There's no legal way to stop them",
        ],
        correctIndex: 1,
        explanation: "You're void, so trumping the led Ace with the 7♠ snatches the exact trick they needed — a set.",
      },
      {
        id: "spades-09-s4", label: "Draw Their Trump",
        situation: "Spades are broken, you're on lead, and you hold the A♠, K♠, and Q♠ plus a long side suit.",
        prompt: "Why lead your high spades now?",
        options: [
          "To draw out the opponents' spades so your side suit runs later",
          "You aren't allowed to lead spades at all",
          "To deliberately create bags for yourself",
          "Only nil players are permitted to lead trump",
        ],
        correctIndex: 0,
        explanation: "Leading top spades pulls opponents' trump, after which your established side-suit cards win freely.",
      },
    ],
  },

  "spades-1-10": {
    intro: "Bring it together — accurate bidding, endgame memory, and a taste of the house variants that change the deal. This is the difference between a steady winner and the table.",
    spots: [
      {
        id: "spades-10-s1", label: "Accuracy Wins",
        situation: "You're thinking about your long-run approach across a whole game to 500.",
        prompt: "What matters most over the course of a game?",
        options: [
          "Bidding as high as possible every single hand",
          "Accurate bids — making contracts while avoiding both sets and bags",
          "Always bidding nil",
          "Taking every trick you possibly can",
        ],
        correctIndex: 1,
        explanation: "Disciplined, accurate bidding — neither overbidding into sets nor underbidding into bags — wins games.",
      },
      {
        id: "spades-10-s2", label: "Endgame Count",
        situation: "Only a few cards remain in everyone's hand and the hand is on the line.",
        prompt: "What's the key skill in the endgame?",
        options: [
          "Guessing more or less at random",
          "Always leading your lowest card",
          "Remembering which cards — especially spades — are gone, to place yours perfectly",
          "Bidding again partway through the hand",
        ],
        correctIndex: 2,
        explanation: "Late in a hand, memory of the spent cards (above all the spades) lets you play out the last tricks exactly.",
      },
      {
        id: "spades-10-s3", label: "Joker-Joker-Deuce Variant",
        situation: "Your group wants to try the popular 'Joker-Joker-Deuce-Deuce' house variant.",
        prompt: "What changes in that variant?",
        options: [
          "Two jokers are added as the highest trumps (and low cards removed to keep the deal even)",
          "Spades stop being trump",
          "Each player is dealt 26 cards",
          "Nil bids are banned",
        ],
        correctIndex: 0,
        explanation: "The Joker variant adds both jokers as the top trumps above the spades, dropping low cards to keep the deal even.",
      },
      {
        id: "spades-10-s4", label: "Mirror & Whiz",
        situation: "Another night, the table tries the 'Mirror' (and the related 'Whiz'/'Suicide') variants.",
        prompt: "In that family of variants, the bidding is...",
        options: [
          "Completely free, just like the standard game",
          "Constrained — e.g. Mirror forces your bid to equal your number of spades (or nil)",
          "Removed entirely; no one bids",
          "Always a blind nil",
        ],
        correctIndex: 1,
        explanation: "Mirror/Whiz-style variants restrict bidding — you must bid your spade count (or nil), not a free number.",
      },
    ],
  },
};
